Added a file to run before django shell
eJourn-al/eJournal pull request #1000
Opened 2020-09-04 06:46 UTC by mjvkeulen

## Description
Added a file which `make shell` will always run directly after being called. This saves us the pain of always importing VLE.models and other commonly used modules.

2020-09-04 07:20 UTC, mjvkeulen commented
To save the reviewers some trouble:

![image](https://user-images.githubusercontent.com/39912610/92210827-bc977d00-ee8f-11ea-9979-3d092111719b.png)

It is important the `PYTHONSTARTUP` env variable does not persist, else it would be called after the startup of other python files.

2020-09-04 07:46 UTC, Larspolo approved these changes

2020-09-06 15:31 UTC, engelhamer requested changes

2020-09-06 15:31 UTC, engelhamer commented on src/django/shell_startup.py
> +import test.factory as factory  # noqa: F401
Don't you think it is going to be confusing in practice that the `factory` import actually refers to the _test_ factory (with consequences as to what is being created).

2020-09-06 15:50 UTC, mjvkeulen commented on src/django/shell_startup.py
> +import test.factory as factory  # noqa: F401
You would have been welcome to change it to the full path or whatever suits your preferences, the current VLE.factory is slowly being phased out. If you want to test something in the shell, it is quite likely you use the test factories more often (especially since the preset db is created using these test factories).

2020-09-06 18:27 UTC, engelhamer approved these changes

2020-09-07 06:03 UTC, merged