Minor fixes in the build script used to deploy 1.4.0 to Sentry
eJourn-al/eJournal pull request #1007
Opened 2020-09-08 07:04 UTC by mjvkeulen

2020-09-08 07:21 UTC, Larspolo requested changes

2020-09-08 07:21 UTC, Larspolo commented on config/env_vars/base.yml
> +run_backups: false
Would prefer backups to still be made, this reduces the lost data when a deploy needs to be reverted. Only the copy to local machine can be off by default

2020-09-08 10:59 UTC, Larspolo approved these changes

2020-09-12 13:02 UTC, engelhamer approved these changes

2020-09-12 13:02 UTC, merged