Added group only notifications and JIR notifications
eJourn-al/eJournal pull request #1016
Opened 2020-09-15 12:02 UTC by Larspolo

## Description
![image](https://user-images.githubusercontent.com/11822478/93207642-8beef780-f75b-11ea-95f0-6f819e3fdbc2.png)
Added group only notifications and JIR notifications
Also users now don't get notifications from:
- courses they cannot see
- courses where they are not in the active lti course
- groups they are not in, if that preference is set
- when the preference is set to off (previously it would still create the notification, just not mail it)

## Summary of changes
- Fixes Z#1158
- group only notifications

2020-09-15 16:45 UTC, mjvkeulen commented on src/django/VLE/models.py
> +        groups = user.participation_set.filter(course__in=courses).values('groups')
user has a `groups` forward manager

2020-09-15 16:45 UTC, mjvkeulen commented on src/django/VLE/models.py
> +                for user in VLE.permissions.get_supervisors_of(self.target):
There is a dedicated permission for managing JIRs

2020-09-15 16:45 UTC, mjvkeulen commented on src/django/VLE/models.py
> +            Notification.objects.filter(jir=self).delete()
Should notificatons already sent not remains like others?

2020-09-15 16:45 UTC, mjvkeulen commented on src/django/VLE/models.py
> +    def email_preference(self):
Was this preference purely tied to email? Or will this likely be tied to other stuff later (e.g. notification tray).

2020-09-15 18:52 UTC, engelhamer requested changes

2020-09-15 18:52 UTC, engelhamer commented on src/django/VLE/models.py
> +                'content': '{journal} requested to import another journal.',
That is a bit too much info for me. I think the current setup is fine and consistent with the other notification content.

2020-09-15 18:52 UTC, engelhamer commented on src/django/VLE/models.py
> +        return self.assignment.get_own_group_users(self.user).filter(pk__in=self.journal.authors.values('user'))
Currently this would be a bit inconvenient for a course with only a `staff` group and students not in any group: for the assignment page's group filter, we exclude any groups that do not have journals in them.

Something similar could be done here as well: if there are no journals in the user's group, then include notifications for all journals?

2020-09-15 18:52 UTC, engelhamer commented on src/django/VLE/models.py
> +    def email_preference(self):
The notification tray will likely always show all, and optionally filter or something?

2020-09-15 18:52 UTC, engelhamer commented on src/django/VLE/models.py
> +    def email_preference(self):
So email is fine in that case.

2020-09-15 18:52 UTC, engelhamer commented on src/vue/src/components/profile/NotificationCard.vue
> +                <radio-button
For toggles between two states we usually display only one of the buttons (the active case). See e.g. `unlimited` vs `preset only` for the `TemplateEditor`. I would prefer that here as well for space reasons and simplicity for limited options.

2020-09-15 21:56 UTC, Larspolo commented on src/django/VLE/models.py
> +                'content': '{journal} requested to import another journal.',
More inline, and sending grades by email is not done

2020-09-15 21:58 UTC, Larspolo commented on src/django/VLE/models.py
> +        groups = user.participation_set.filter(course__in=courses).values('groups')
What do you mean?

2020-09-15 22:00 UTC, Larspolo commented on src/django/VLE/models.py
> +    def email_preference(self):
> Was this preference purely tied to email? Or will this likely be tied to other stuff later (e.g. notification tray).

Didnt know which way we would prefer it for the notification tray, so I names it now "email_preference" as it was only hitting email stuff. When adding a notification tray this needs to be discussed

2020-09-15 22:01 UTC, Larspolo commented on src/django/VLE/models.py
> +        return self.assignment.get_own_group_users(self.user).filter(pk__in=self.journal.authors.values('user'))
Should the "own group" behaviour in the ToDo task act the same?

2020-09-16 01:45 UTC, engelhamer commented on src/django/VLE/models.py
> +        return self.assignment.get_own_group_users(self.user).filter(pk__in=self.journal.authors.values('user'))
Own group is fine this way because it should bot draw as much focus every time. Hence why its not a button.

2020-09-16 07:29 UTC, mjvkeulen commented on src/django/VLE/models.py
> +        groups = user.participation_set.filter(course__in=courses).values('groups')
I got confused with the groups from the permissions mixin, resolving.

2020-09-16 07:31 UTC, mjvkeulen commented on src/django/VLE/models.py
> +        return self.assignment.get_own_group_users(self.user).filter(pk__in=self.journal.authors.values('user'))
Digest task or ToDo deck?

2020-09-16 07:35 UTC, mjvkeulen commented on src/django/VLE/models.py
> +        return self.assignment.get_own_group_users(self.user).filter(pk__in=self.journal.authors.values('user'))
> Currently this would be a bit inconvenient for a course with only a `staff` group and students not in any group: for the assignment page's group filter, we exclude any groups that do not have journals in them.
> 
> Something similar could be done here as well: if there are no journals in the user's group, then include notifications for all journals?

This would be explicitly triggered by the user enabling group only notifications right? It would indeed not work well for the situation you outlined, but I would simply expect users in that scenario not to opt in for group only notifications. I feel introducing an exception here is not required.

2020-09-16 07:42 UTC, mjvkeulen commented on src/django/test/test_notification.py
> +            g_journal.authors.add(factory.AssignmentParticipation(assignment=g_assignment))
A `journal` is always initiated with a single author by default (applies to group and nongroup journals alike). 
Keeping that in mind adding 4 additional authors to a group journal could be done as:

g_journal = factory.GroupJournal(assignment=g_assignment, author_limit=5, add_users=[user2, user3, user4, user5])

2020-09-17 18:30 UTC, mjvkeulen commented on src/django/VLE/models.py
> +    def is_in_group(self):
This does not return a boolean, possibly add a docstring?

2020-09-17 18:32 UTC, mjvkeulen commented on src/django/VLE/models.py
> +        if self.type in self.OWN_GROUP_TYPES and self.user.preferences.group_only_notifications \
I would move this to a function for clarity, then the comment can be a docstring

2020-09-17 18:35 UTC, mjvkeulen commented on src/django/VLE/models.py
> +                    if user.has_permission('can_manage_journal_import_requests', self.target.assignment):
Possibly move the nested if to a kwarg argument of get_supervisors_of ?

2020-09-18 09:44 UTC, Larspolo commented on src/django/VLE/models.py
> +        if self.type in self.OWN_GROUP_TYPES and self.user.preferences.group_only_notifications \
Was thinking about it as well, but couldnt come up with a good name, can you?

2020-09-18 10:02 UTC, Larspolo commented on src/django/VLE/models.py
> +    def is_in_group(self):
Added doctring, but now it also only returns the boolean

2020-09-18 12:00 UTC, mjvkeulen commented on src/django/VLE/models.py
> +            courses = self.courses.all()
What is it that self.courses refers to?

2020-09-18 12:08 UTC, mjvkeulen commented on src/django/VLE/models.py
> +    def get_own_group_users(self, user, courses=None, **kwargs):
get_users_in_own_groups? I got confused, and this would fix group no longer being singular.

2020-09-18 12:12 UTC, mjvkeulen commented on src/django/VLE/models.py
> +    def is_in_group(self):
has_authors_in_own_groups?

2020-09-18 12:14 UTC, mjvkeulen commented on src/django/VLE/models.py
> +    def has_users_in_own_group(self, *args, **kwargs):
This would then become has_users_in_own_groups

2020-09-18 12:19 UTC, mjvkeulen commented on src/django/VLE/models.py
> +        if self.type in self.OWN_GROUP_TYPES and self.user.preferences.group_only_notifications \
I find it tricky as well, possibly split up the logic?

- self.type in self.OWN_GROUP_TYPES and self.user.preferences.group_only_notifications -> `self.group_specific`
- self.assignment.has_users_in_own_groups(self.user) and not self.has_authors_in_own_groups() -> still tricky.

I suggested some other renames to make this click

2020-09-18 18:30 UTC, mjvkeulen approved these changes

2020-09-30 17:27 UTC, engelhamer commented on src/vue/src/components/profile/NotificationCard.vue
> +                <template v-if="$store.getters['preferences/saved'].group_only_notifications">
`v-if` can be moved to the button itself (no wrapper with single child needed)

2020-09-30 17:27 UTC, engelhamer commented on src/vue/src/components/assets/RadioButton.vue
> +            {{ option.text }}
This is now not needed anymore right?

2020-10-02 15:17 UTC, engelhamer approved these changes

2020-10-02 16:39 UTC, merged