Fixed bugs and improved speed for teacher entries
eJourn-al/eJournal pull request #1026
Opened 2020-09-23 19:06 UTC by Larspolo

## Description
Fixed bugs and improved speed for teacher entries

## Summary of changes
- deleting a teacher entry from list now removes correct journal
- when selecting more journal when same grade was disabled, it didnt get
the correct initial grade
- no more inconsistency between grade, published state, and journal
- speedup serializer by over 10x
- Increased teacher entry creation by 4x

2020-09-23 20:56 UTC, mjvkeulen commented on src/django/VLE/views/teacher_entry.py
> +            a = utils.optional_typed_params(
a?

2020-09-23 20:56 UTC, mjvkeulen commented on src/django/VLE/utils/import_utils.py
> +    for old_fc in files:
Is this preference or does this execute fewer queries?

2020-09-23 20:56 UTC, mjvkeulen commented on src/django/VLE/utils/import_utils.py
> +    ) for node, grade in itertools.zip_longest(nodes, grades)]
Fillvalue of None works well for grades, but could bite us for nodes. `zip_equal` introduced in #1008 could be of use?

2020-09-23 20:56 UTC, mjvkeulen commented on src/django/VLE/utils/import_utils.py
> +    for node, entry in itertools.zip_longest(nodes, entries):
Ditto, entries should never float so zip_longest is dangerous.

2020-09-23 20:56 UTC, mjvkeulen commented on src/django/VLE/views/teacher_entry.py
> +        self._copy_teacher_entry(teacher_entry, new_journals, request.user)
Should this be labeled as public? (not introduced in this PR, but what are our own guidelines).

2020-09-23 20:56 UTC, mjvkeulen commented on src/django/VLE/views/teacher_entry.py
> +            grade.entry.save()
How come the reverse relations have to be updated? Also can this not be done in one query?

2020-09-26 13:50 UTC, Larspolo commented on src/django/VLE/utils/import_utils.py
> +    for old_fc in files:
It skips the `content.save()` below if no files exist

2020-09-26 13:51 UTC, Larspolo commented on src/django/VLE/views/teacher_entry.py
> +            a = utils.optional_typed_params(
Old debug code, should be removed

2020-10-01 14:17 UTC, Larspolo commented on src/django/VLE/views/teacher_entry.py
> +            grade.entry.save()
> Also can this not be done in one query?

Didnt manage yet.

> How come the reverse relations have to be updated?

Because the latest grade need to be set to the entry. This is not automatically done because we have a grade history book

2020-10-01 17:56 UTC, engelhamer requested changes
Upon posting a teacher entry where no grade is set, teachers now do not see a 'needs marking' badge anymore.

2020-10-01 17:56 UTC, engelhamer commented on src/vue/src/components/assignment/PostTeacherEntry.vue
> +                } else if (!this.selectedJournals.some(journal => journal.id === journalFromUsername.id)) {
`journal.id` should be `journal.journal_id` with the change you just introduced. Now it is possible to add the same journal multiple times.

2020-10-01 18:19 UTC, engelhamer approved these changes
Moved previous comment into issue.

2020-10-01 20:02 UTC, Larspolo commented on src/django/VLE/serializers.py
> +    title = None
Can probably be removed

2020-10-02 09:48 UTC, Larspolo commented on src/django/VLE/serializers.py
> +    title = None
Could not, added comment

2020-10-02 10:01 UTC, merged