Added an admin panel for management tasks
eJourn-al/eJournal pull request #1028
Opened 2020-10-01 18:43 UTC by engelhamer

2020-10-24 11:04 UTC, Larspolo reviewed
I still see a lot of frontend changes as well

2020-10-24 11:04 UTC, Larspolo commented on src/vue/src/views/AdminPanel.vue
> +                    {
To be removed

2020-10-25 10:29 UTC, mjvkeulen commented on src/vue/src/components/admin/UserOverview.vue
> +                + 'This includes courses which they are the author of. This cannot be undone!')) {
I didn't even know this. Propose we change this to including course without remaining administrative users or similar?

2020-10-25 10:29 UTC, mjvkeulen commented on src/vue/src/components/admin/UserOverview.vue
> +                        this.getAllUsers()
Is this for updating the user list after a successful removal?

2020-10-25 10:29 UTC, mjvkeulen commented on src/vue/src/components/assets/CodeVersionAlert.vue
> +        eJournal received an update 🎉, click <b>here</b> to reload
The alert itself is clickable, not the `here` text. Could this not result in users specifically attempting to click the `here` text?

2020-10-25 10:29 UTC, mjvkeulen commented on src/vue/src/components/assets/NumberBadge.vue
> -.number-badge-container
Curious to see how these look now

2020-10-25 10:29 UTC, mjvkeulen commented on src/vue/src/sass/global.sass
> +    // background-image: url(/background.png)
tag

2020-10-25 10:29 UTC, mjvkeulen commented on src/vue/src/sass/partials/cards.sass
> +        // QUESTION: How about only doing this for course, assignment and journal cards?
Tagging open question, will come back to this.

2020-10-25 10:29 UTC, mjvkeulen commented on src/vue/src/sass/partials/columns.sass
> +        height: calc(100vh - 50px)
The 50px seems to be recurring often, time to move it to a variable?

2020-10-25 10:29 UTC, mjvkeulen commented on src/vue/src/views/AdminPanel.vue
> +// import courseAPI from '@/api/course.js'
tag

2020-10-26 20:45 UTC, engelhamer commented on src/django/VLE/views/admin.py
> +            return response.forbidden('You are not allowed to invite new users.')
Indeed an issue would be fine. This level of configurability is an additional feature.

2020-10-26 20:48 UTC, engelhamer commented on src/django/VLE/views/admin.py
> +                created_user = factory.make_user(username=user['username'], email=user['email'],
The `make_user` fuction uses the `set_unusable_password` function for inactive (yet to be activated) account like these.

2020-10-26 20:59 UTC, engelhamer commented on src/django/VLE/views/admin.py
> +                created_user = factory.make_user(username=user['username'], email=user['email'],
As of the newest changes this is updated to bulk create. We do have to consider the error catch now: do you know if the bulk create could fail still even if the `full_clean` is called on the individual users to be created?

2020-10-26 21:06 UTC, engelhamer commented on src/django/VLE/views/admin.py
> +            for user_id in created_user_ids:
Moved to background job. Do you think we should do additional crash handling there? This used to be fine becauses they were separate threads, but if something goes wrong now we should maybe receive a notification and keep running for the other users.

2020-10-26 21:32 UTC, engelhamer commented on src/vue/src/components/template/TemplateEdit.vue
> -                    class="delete-button"
The reason for moving away is that the 'semantic' name was invalid in may cases. E.g.: saving a grade that already existed was done using an `add-button` rather than a `change-button`. The opposite was the case for setting bonus points via the bulk import method.

An orange bulk import seems intuitive rather than a green one, whereas a green save button is intuitive rather than an orange one. This is why I prefered to get the color names instead of this 'semantic' name.

Also this is consitstent with the other color classes for e.g. `text-` and `background-`.

2020-10-26 21:34 UTC, engelhamer commented on src/django/VLE/views/admin.py
> +        if any([not user['username'] for user in users]):
The user can see this in the front end by the empty fields in that column. We do not have front-end field validation highlights, see [Z#1093](https://zube.io/ejourn-al/ejournal/c/1093).

2020-10-26 21:36 UTC, engelhamer commented on src/django/VLE/views/admin.py
> +        if any([not user['email'] for user in users]):
Afaik we do not currently use serializers for creation? Would prefer to tackle that in bulk for consistency: it should then always be reliable to use serializers for creation instead of having to check still for which models / serializers you can rely on this.

2020-10-26 21:40 UTC, engelhamer commented on src/django/VLE/views/admin.py
> +            return response.not_found('User to delete does not exist.')
There is in fact something going wrong.

2020-10-26 22:15 UTC, engelhamer commented on src/django/VLE/views/admin.py
> +    def remove_user(self, request, pk):
Improved structure to adhere CRUD and REST framework.

2020-10-26 22:16 UTC, engelhamer commented on src/vue/src/components/admin/UserOverview.vue
> +                + 'This includes courses which they are the author of. This cannot be undone!')) {
Actually it might not be true now that I come to check.

2020-10-26 22:17 UTC, engelhamer commented on src/vue/src/components/admin/UserOverview.vue
> +                        this.getAllUsers()
Yes, I would like to always keep this updated. Also when pagination is added, we cannot just perform the update in the front end manually (since we don't know what the next page will be),

2020-10-26 22:18 UTC, engelhamer commented on src/vue/src/components/assets/CodeVersionAlert.vue
> +        eJournal received an update 🎉, click <b>here</b> to reload
Then that is no problem. Click to refresh may  be interpreted as 'click anywhere', Not necessarily within this popup itself.

2020-10-26 22:19 UTC, engelhamer commented on src/vue/src/sass/partials/cards.sass
> +        // QUESTION: How about only doing this for course, assignment and journal cards?
Moved to UI changes PR.

2020-10-26 22:24 UTC, engelhamer commented on src/django/VLE/views/admin.py
> +class AdminView(viewsets.ViewSet):
That is indeed more sensible. All functions have been moved.

2020-10-26 22:27 UTC, engelhamer commented on src/vue/src/sass/partials/columns.sass
> +        height: calc(100vh - 50px)
That is the (new) header height. Indeed a variable might be alright, but we'll have to come up with some formula's to scale the elements along (since otherwise changing the 50px itself also required additional changes anyways).

2020-10-27 07:57 UTC, mjvkeulen commented on src/django/VLE/serializers.py
> +        read_only_fields = fields
This serializer does not make use of much of its possible functionality. The view could also simply return values_list(fields)

2020-10-27 08:09 UTC, mjvkeulen commented on src/vue/src/components/admin/UserOverview.vue
> +                        this.getAllUsers()
Possibly move it into the `then` block, the state should not change if the request fails.

2020-10-27 08:11 UTC, mjvkeulen commented on src/vue/src/components/assets/ResetWrapper.vue
> +        // TODO: this is broken
tag

2020-10-27 08:16 UTC, mjvkeulen commented on src/vue/src/sass/partials/columns.sass
> +        height: calc(100vh - 50px)
Valid point, however, without the formula's we will still have the clarity of a named variable.

2020-10-27 08:17 UTC, mjvkeulen commented on src/vue/src/views/AdminPanel.vue
> +
hspace

2020-10-27 08:32 UTC, mjvkeulen commented on src/django/VLE/factory.py
> +    if save:
Having a conditional save in a module dedicated to creating model instances is a bit counter-intuitive. 

I propose moving the validation block to a User class method.

2020-10-27 08:42 UTC, engelhamer commented on src/django/VLE/factory.py
> +    if save:
Not if it's used for bulk creation, and `False` by default?

2020-10-27 09:32 UTC, Larspolo commented on src/django/VLE/views/user.py
> +        if not (request.user.is_superuser):
brakets can be removed

2020-10-27 09:32 UTC, Larspolo commented on src/django/VLE/views/user.py
> +            User.objects.filter(pk__in=created_user_ids).delete()
created_user_ids will only be set at the end, and thus this wont delete anything if for loop crashes. Would suggest moving the `users_to_create` outside of the try scope, and use `[u.pk for u in users_to_create]`

2020-10-27 09:32 UTC, Larspolo commented on src/django/VLE/views/user.py
> +            send_invite_emails.delay(created_user_ids)
except already returns sth, else is not needed (now it is not consistent with the success return)

2020-10-27 09:32 UTC, Larspolo commented on src/vue/src/components/admin/EditInstance.vue
> +                .finally(() => {
Would also suggest a `then((instance) => { this.instance = instance }` in case the server did sth while updating (example: strip whitespace from name (maybe this should be added s well now I type it, or move to issue?)), it changes back to what the server responded

2020-10-27 09:32 UTC, Larspolo commented on src/django/VLE/views/admin.py
> +                created_user = factory.make_user(username=user['username'], email=user['email'],
I cannot say anything for sure about this

2020-10-27 09:58 UTC, Larspolo requested changes
![image](https://user-images.githubusercontent.com/11822478/97284986-fb1f3780-1841-11eb-832d-69133734a086.png)
When the options are opened, the bottom gets a couple pixel margin


![image](https://user-images.githubusercontent.com/11822478/97285491-91535d80-1842-11eb-8f67-b6caf2b744da.png)
Two error messages shown, would suggest only using the message that the backend sends

![image](https://user-images.githubusercontent.com/11822478/97285799-f313c780-1842-11eb-862f-55b28d98160d.png)
Would suggest clearing the error output also when new errors occure, now it can be outdated

![image](https://user-images.githubusercontent.com/11822478/97286015-4554e880-1843-11eb-864a-7851ebf795c4.png)
When there is whitespace, it gives a weird error, the whitespace is even imported from the excel file. So if there is a whitespace there, it can be really shitty debugging it

2020-10-27 09:58 UTC, Larspolo commented on src/vue/src/components/admin/UserOverview.vue
> +                .then(() => { this.$toasted.success(`Successfully made ${user.full_name} teacher.`) })
I personally like having response messages in the backend. Can be combined with the `responseSuccessToast: true` in frontend

2020-10-27 09:58 UTC, Larspolo commented on src/django/VLE/views/instance.py
> -
This is now inconsistent with the style, also the docstring apperently already was wrong: `data -- the new data for the journal` shoudl be `data -- the new data for the instance`

2020-10-27 16:01 UTC, engelhamer commented on src/vue/src/components/admin/UserOverview.vue
> +                        this.getAllUsers()
It could be that the request failed because some other admin already deleted the user. In that case we should update.

2020-10-27 16:03 UTC, engelhamer commented on src/django/VLE/serializers.py
> +        read_only_fields = fields
No? There are much fewer fields included here. E.g. lti id, verified email, test student status etc.

2020-10-27 16:06 UTC, engelhamer commented on src/django/VLE/views/user.py
> +            User.objects.filter(pk__in=created_user_ids).delete()
That's true, but users to create do not have a pk since they are not created yet?

2020-10-27 16:32 UTC, engelhamer commented on src/vue/src/components/admin/UserOverview.vue
> +                .then(() => { this.$toasted.success(`Successfully made ${user.full_name} teacher.`) })
This now uses the `User` update method (according to your request) which can be used to update a whole variety of things. I would not propose adding all of those as individual messages in the back end for readability.

2020-10-27 16:32 UTC, engelhamer commented on src/django/VLE/views/instance.py
> -
Went wrong while reverting the copy.

2020-10-27 16:44 UTC, engelhamer commented
> ![image](https://user-images.githubusercontent.com/11822478/97284986-fb1f3780-1841-11eb-832d-69133734a086.png)
> When the options are opened, the bottom gets a couple pixel margin
> 

Seems to be a Firefox-only bug. Have not been able to fix yet.

> ![image](https://user-images.githubusercontent.com/11822478/97285491-91535d80-1842-11eb-8f67-b6caf2b744da.png)
> Two error messages shown, would suggest only using the message that the backend sends

If the back end sends a message we show that. If the back end sends an object (error log) it is shown separately in the view itself and a separate error is shown front end only.

> ![image](https://user-images.githubusercontent.com/11822478/97286015-4554e880-1843-11eb-864a-7851ebf795c4.png)
> When there is whitespace, it gives a weird error, the whitespace is even imported from the excel file. So if there is a whitespace there, it can be really shitty debugging it

All strings are now trimmed. If a row is present with only falsy values after trimming, it is discarded,

2020-10-27 17:22 UTC, engelhamer commented on src/vue/src/sass/partials/columns.sass
> +        height: calc(100vh - 50px)
Added it in the breakpoints sass file. Kind of an awkward position, but global usage of sass vars is kind of finicky, couldn't make it accessible just from the global sass file.

2020-10-27 21:39 UTC, mjvkeulen commented on src/django/VLE/views/admin.py
> +                created_user = factory.make_user(username=user['username'], email=user['email'],
I believe full_clean also performs unique contraint checks, I think it will be reasonable to assume bulk create should work

2020-10-27 21:42 UTC, mjvkeulen commented on src/django/VLE/serializers.py
> +        read_only_fields = fields
I think you misunderstood, this serializer doesn't really add anything. If you just return
response.success(x: User.objects.filter(xxx).values_list('username', 'full_name', 'email', 'is_teacher', 'is_active', 'id')) we could just omit this serializer.

2020-10-27 21:50 UTC, mjvkeulen commented on src/django/VLE/factory.py
> +    if save:
I was dealing with this myself in other areas where we require speedups. We need to move toward separating validation, cleaning, and updating/creation, otherwise it's difficult to properly encapsulate application-level constraints or state guarantees. Forcing us to repeat logic in multiple places for each scenario which ignores the default model save (update, bulk_creation, etc).

Leave this solution as it is for now. We will need to agree on an approach but there will be other PR's more suited to this discussion.

2020-10-27 22:10 UTC, Larspolo commented on src/django/VLE/views/user.py
> +            User.objects.filter(pk__in=created_user_ids).delete()
Owww ofcourse,missed that. Good enough then

2020-10-28 13:04 UTC, mjvkeulen reviewed
Admin panel requires some user search functionality

2020-11-23 10:03 UTC, Larspolo requested changes
![image](https://user-images.githubusercontent.com/11822478/99948577-f33bb000-2d79-11eb-8d5c-6e250f3b63fa.png)


![image](https://user-images.githubusercontent.com/11822478/99948621-02226280-2d7a-11eb-9916-00d1663bfd8c.png)
Its possible to invite users with an empty username

Same goes for whitespace before a username. This will result in a user that will never be able to be logged in as we remove whitespace on login request

2020-11-25 07:50 UTC, mjvkeulen requested changes
Atm loading home as a teacher gives me a 403 "You are not allowed to get all courses."

2020-11-25 07:50 UTC, mjvkeulen commented on src/django/test/test_course.py
> +        assert len(get_resp) == 2, 'Teacher should get all courses they are the author of or ar participating in'
are

2020-11-25 07:50 UTC, mjvkeulen commented on src/django/test/test_course.py
> +            'Teacher should get all courses they are the author of or ar participating in'
ditto

2020-11-25 07:50 UTC, mjvkeulen commented on src/django/test/test_email.py
> +            'Current URL should be in developer support email'
Nice strict email content checks

2020-11-25 07:50 UTC, mjvkeulen commented on src/django/test/test_email.py
> +        assert all(mail.outbox[i].from_email == f'eJournal | Support<support@{settings.EMAIL_SENDER_DOMAIN}>' for i in
Since we are now also strict with checking for the correct sender name, it's time to move these to a setting's variable. Prob best to do so in a format where the specific email names are linked to their respective sender names.

2020-11-25 07:50 UTC, mjvkeulen commented on src/django/test/test_user.py
> +        ]
Using the user factory would improve maintainability.

```
users = [factory.Student.build() for _ in range(10)]
params = [{'full_name': u.full_name, 'username': u.username, 'email': u.email} for u in users]
```

2020-11-25 07:50 UTC, mjvkeulen commented on src/django/test/test_user.py
> +    def test_invite_users(self):
Good test, but quite long. Consider splitting or using nested functions? Possibly validation, creation, validation link etc?

2020-11-25 07:50 UTC, mjvkeulen commented on src/vue/src/components/admin/InviteUsers.vue
> +            return this.usersToInvite.filter(user => !(!user.full_name && !user.username && !user.email))
not not not not to or or or?

2020-11-25 07:50 UTC, mjvkeulen commented on src/vue/src/sass/partials/cards.sass
> +        // QUESTION: How about only doing this for course, assignment and journal cards?
Ok, prob best to remove the question here so it will be a new question on that branch.

2020-11-25 08:14 UTC, Larspolo commented
> Atm loading home as a teacher gives me a 403 "You are not allowed to get all courses."

See my comment on how to solve that

2020-11-26 20:26 UTC, engelhamer commented on src/django/VLE/views/user.py
> +        serializer = UserOverviewSerializer(User.objects.all().order_by('full_name'), context={'user': request.user},
`.values` does not return a dict. So then that would also have to be made here for each user.

2020-11-26 20:35 UTC, engelhamer commented on src/django/test/test_user.py
> +        ]
Why? That would still keep practically the same list comprehensions of dicts on the second line. Also now whitespace has been added.

2020-11-26 20:37 UTC, engelhamer commented on src/django/test/test_email.py
> +        assert all(mail.outbox[i].from_email == f'eJournal | Support<support@{settings.EMAIL_SENDER_DOMAIN}>' for i in
> Prob best to do so in a format where the specific email names are linked to their respective sender names

I do not understand what you mean by this?

2020-11-26 20:38 UTC, engelhamer commented on src/django/VLE/views/user.py
> +            capture_message('Something went wrong while inviting users: {}'.format(exception), level='error')
> > Atm loading home as a teacher gives me a 403 "You are not allowed to get all courses."
> 
> See my comment on how to solve that

That solution limited functionality. Consider e.g. the case where a superuser also has a course they teach.

2020-11-26 20:42 UTC, engelhamer commented
> > Atm loading home as a teacher gives me a 403 "You are not allowed to get all courses."
> 
> See my comment on how to solve that

That solution limited functionality. Consider e.g. the case where a superuser also has a course they teach.

2020-11-26 20:52 UTC, engelhamer commented on src/django/test/test_user.py
> +    def test_invite_users(self):
Fine by me

2020-11-27 07:09 UTC, mjvkeulen commented on src/django/test/test_email.py
> +        assert all(mail.outbox[i].from_email == f'eJournal | Support<support@{settings.EMAIL_SENDER_DOMAIN}>' for i in
Map the corresponding domain prefix to the desired 'from' sender name in the data structure you pick?

2020-11-27 07:11 UTC, mjvkeulen commented on src/django/test/test_user.py
> +        ]
The logic of how the desired fields should be formatted remains in one central place. The user factory.

2020-11-27 07:14 UTC, mjvkeulen commented on src/django/test/test_user.py
> +        ]
Why did you opt for adding white space to the base case over introducing whitespace where it is specifically tested? By introducing whitespace as the default the test loses some strength for non-white space cases.

2020-11-27 07:22 UTC, mjvkeulen commented on src/django/VLE/views/user.py
> +            User.objects.filter(pk__in=created_user_ids).delete()
The try-catch undo structure is redundant. The bulk_create occurs within a single transaction which will either be successful or not (if not state will be reverted to the beginning of the transaction).

2020-11-27 07:26 UTC, mjvkeulen commented on src/vue/src/sass/partials/columns.sass
> +        height: calc(100vh - 50px)
Since it is indeed not a breakpoint, how about a new .sass module? E.g. `dimensions.sass`? 

We can then make that module globally available in `vue.config.js` by adding it to the sass loader options configuration:
`@import "~sass/modules/dimensions.sass"`

2020-11-27 08:11 UTC, mjvkeulen commented on src/django/test/test_email.py
> +        assert all(mail.outbox[i].from_email == f'eJournal | Support<support@{settings.EMAIL_SENDER_DOMAIN}>' for i in
E.g. in `base.py` in the settings module.

```
@dataclass
class EmailToSender:
    label: str

    @property
    def email(self) -> str:
        return f'{self.label}@{EMAIL_SENDER_DOMAIN}'

    @property
    def sender(self) -> str:
        name = self.email.split('@')[0].capitalize()
        return f'eJournal | {name}'


class Emails:
    support = EmailToSender('support')
    info = support = EmailToSender('info')
    contact = support = EmailToSender('contact')
```

Which would allow a bit more clean access, e.g. `Emails.support.sender`. Or just go 

```
EMAIL_SENDER_NAME_MAP = {
    'support': {'email': f'support@{EMAIL_SENDER_DOMAIN}', 'sender': 'eJournal | Support'}
}
```

I just dislike the access pattern, e.g. `EMAIL_SENDER_NAME_MAP['support']['email']`

2020-11-27 13:33 UTC, engelhamer commented on src/django/test/test_email.py
> +        assert all(mail.outbox[i].from_email == f'eJournal | Support<support@{settings.EMAIL_SENDER_DOMAIN}>' for i in
I kind of think that this is overengineering as there is really only one file where we actually send mails?

2020-11-27 13:33 UTC, engelhamer commented on src/django/test/test_email.py
> +        assert all(mail.outbox[i].from_email == f'eJournal | Support<support@{settings.EMAIL_SENDER_DOMAIN}>' for i in
But feel free to add whatever you like.

2020-11-27 15:24 UTC, mjvkeulen commented on src/django/test/test_email.py
> +        assert all(mail.outbox[i].from_email == f'eJournal | Support<support@{settings.EMAIL_SENDER_DOMAIN}>' for i in
I don't care what structure you pick, but the sender names should be moved to a setting

2020-11-27 19:10 UTC, mjvkeulen commented on src/django/VLE/views/user.py
> +            User.objects.filter(pk__in=created_user_ids).delete()
You have already taken the steps to ensure the data is unique and available, how about just removing the try catch and error log?

How do you perceive an exception will occur?

2020-11-27 19:12 UTC, mjvkeulen commented
![image](https://user-images.githubusercontent.com/39912610/100478081-6f235880-30ea-11eb-9ae2-55270475954b.png)
Minor: possibly introduce a minimum width for the column headers?

2020-11-27 19:15 UTC, engelhamer commented
> ![image](https://user-images.githubusercontent.com/39912610/100478081-6f235880-30ea-11eb-9ae2-55270475954b.png)
> Minor: possibly introduce a minimum width for the column headers?
> 

So with overflow scroll?

2020-11-27 19:22 UTC, mjvkeulen requested changes

2020-11-27 19:22 UTC, mjvkeulen commented on src/django/VLE/views/user.py
> +            created_user_ids = [user.id for user in User.objects.bulk_create(users_to_create)]
Users created via this method end up without a preferences table, and as such can't use the platform (or even login).

I propose to define our own `bulk_create` method on the extended user manager (`UserManagerExtended`). Where within one checkpoint/transaction we bulk_create both the desired users and their corresponding preferences. 

Initialization of the user instances can be left as is (by the user factory, rewrite can be done another time). 
Validation is already cleanly handled and imo should remain outside of the manager logic.

2020-11-27 19:31 UTC, mjvkeulen commented
![image](https://user-images.githubusercontent.com/39912610/100479780-7dc03e80-30ef-11eb-8422-cafd374722b7.png)
Minor: I would expect even division of the tabs for all sizes?

2020-11-27 19:36 UTC, engelhamer commented
> ![image](https://user-images.githubusercontent.com/39912610/100479780-7dc03e80-30ef-11eb-8422-cafd374722b7.png)
> Minor: I would expect even division of the tabs for all sizes?

This is default bootstrap pill tab styling. Want to change that?

2020-11-27 21:15 UTC, Larspolo approved these changes
Think we already spoke about this, but I would really like class name changes to get their own PR. Now im reviewing "137"  where probably not even 20% of them are actually useful

2020-11-27 21:15 UTC, Larspolo commented on src/django/test/test_course.py
> +        api.get(self, 'courses', params={'get_all': True}, user=self.student, status=403)
Would prefer this to be tested now with the strings `"true"` and `"false"` to replicate the real deal

2020-11-28 08:05 UTC, mjvkeulen commented on src/django/VLE/tasks/email.py
> +        You have been invited to eJournal by {}. Please click the button below to activate your account.""" \
![image](https://user-images.githubusercontent.com/39912610/100496971-ad576100-3158-11eb-8278-fbeb940ed945.png)
I believe the chance this phrasing will clash is relatively high, e.g. for the UvA this would be:
`You have been invited to eJournal by eJournal - UvA`

How about only using the instance name?

2020-11-28 08:06 UTC, mjvkeulen commented on src/django/VLE/tasks/email.py
> +            subject='Complete your registration for eJournal at {}'.format(instance_name),
A similar clash here:
![image](https://user-images.githubusercontent.com/39912610/100497020-06bf9000-3159-11eb-84ef-bf22b17aa1aa.png)

2020-11-28 08:12 UTC, mjvkeulen commented on src/django/test/test_email.py
> +        assert all(mail.outbox[i].from_email == f'eJournal | Support<support@{settings.EMAIL_SENDER_DOMAIN}>' for i in
Let's use the new `EMAILS` variable here as well?

2020-11-28 08:54 UTC, engelhamer commented on src/django/VLE/tasks/email.py
> +        You have been invited to eJournal by {}. Please click the button below to activate your account.""" \
This is because you did not run preset db again (or at least I changed the default to 'Demo' iso 'eJournal'. For UvA it would need to be changed to 'UvA' iso 'eJournal - UvA' and on the landing page this has been changed accordingly.

2020-11-28 08:54 UTC, engelhamer commented on src/django/VLE/tasks/email.py
> +            subject='Complete your registration for eJournal at {}'.format(instance_name),
Same as other

2020-11-28 16:19 UTC, mjvkeulen commented on src/django/VLE/models.py
> +            Preferences.objects.bulk_create(preferences)
This would be quite suited (and faster, though not really relevant) as a list comprehension.

` Preferences.objects.bulk_create([Preferences(user=user) for user in users])`

2020-11-28 16:19 UTC, mjvkeulen approved these changes

2020-11-28 16:53 UTC, merged