Added the ability to add files as teacher in the node description
eJourn-al/eJournal pull request #1034
Opened 2020-10-11 14:05 UTC by Larspolo

## Description
Added the ability to add files as teacher in the node description
![image](https://user-images.githubusercontent.com/11822478/95680618-3f240280-0bdb-11eb-9f52-611e383ca461.png)
![image](https://user-images.githubusercontent.com/11822478/95680629-5236d280-0bdb-11eb-961b-8ca13dfed452.png)

## Summary of changes
- Fixes Z#1295

2020-10-12 07:17 UTC, mjvkeulen commented on src/django/VLE/migrations/0065_presetnode_files.py
> +            field=models.ManyToManyField(related_name='preset_node_files', to='VLE.FileContext'),
I am always torn on how to implement the many to one relation of our files. Is this your preferred method when a file is not embedded in RT? For example, some downsides of this method are:
- DB does not reflect the actual relations (M2M instead of many-to-one). This has the effect that some basic rules need to be enforced manually.
- Additional DB table for the (not truly needed) M2M relationships.
- We mix two methods, consistency drops.

I am also leaning towards this approach, but I am just curious about your input?

2020-10-12 07:21 UTC, mjvkeulen commented on src/django/VLE/models.py
> +        related_name='preset_node_files',
`fc.presetnode_set` vs `fc.preset_node_files`, since the result is a set of `PresetNodes` I would prefer the first.

2020-10-12 07:25 UTC, mjvkeulen commented on src/django/VLE/utils/file_handling.py
> +def establish_file(author, identifier, **kwargs):
Would you agree moving to kwargs is more error-prone to leaving out desired context?

2020-10-12 07:27 UTC, mjvkeulen commented on src/django/VLE/utils/generic_utils.py
> +            print(file_date)
debug

2020-10-12 07:29 UTC, mjvkeulen commented on src/django/VLE/utils/generic_utils.py
> +        preset_node.files.exclude(pk__in=[file['id'] for file in files]).delete()
We will still need to run similar logic for temp file cleanup, possibly move this to cleanup as well? Working towards a centralized place of logic for file cleanup and all that.

2020-10-12 08:18 UTC, Larspolo commented on src/django/VLE/utils/file_handling.py
> +def establish_file(author, identifier, **kwargs):
More modular, none of these kwargs are actually needed for this function, so why specify them? Now you only need to specify them in one place, I would say this makes it less error-prone actually, as now you cant forget to add it here as well

2020-10-12 08:42 UTC, Larspolo commented on src/django/VLE/models.py
> +        related_name='preset_node_files',
I did the same as the `comment_files` implementation

2020-10-12 11:30 UTC, Larspolo commented on src/django/VLE/migrations/0065_presetnode_files.py
> +            field=models.ManyToManyField(related_name='preset_node_files', to='VLE.FileContext'),
Same implementation as comment files, I do see that this might need to be improved, but how would you say to move that to a new issue and attack both of them at the same time?

2020-10-14 08:30 UTC, mjvkeulen commented on src/django/VLE/utils/file_handling.py
> +def establish_file(author, identifier, **kwargs):
I understand your argument if it was regarding a helper or private function. However, since this function is called directly (not private), by moving these arguments to kwargs it more likely to leave out context which is in fact, desired. I see it as having access to the expected arguments (e.g. in my IDE), when calling the function (sort of interface/header of what parameters are expected).

2020-10-14 08:39 UTC, mjvkeulen commented on src/django/VLE/models.py
> +        related_name='preset_node_files',
I still feel my point holds, but you raise a valid point regarding the similarity of the `comment` files naming scheme. 

Comments and PresetNodes, both have two types of files, either embedded in the text (description) or attached. Making this difference more explicit would have my vote. How about:

`comment.attached_files` and `fc.attached_comments`
`preset.attached_files` and `fc.attached_presets` 

Or some variation?

2020-10-14 12:19 UTC, Larspolo commented on src/django/VLE/models.py
> +        related_name='preset_node_files',
You can change the name if you want, just keep it consistent between the two

2020-10-14 12:23 UTC, Larspolo commented on src/django/VLE/utils/file_handling.py
> +def establish_file(author, identifier, **kwargs):
Updated to context to make it more clear what the kwargs are

2020-10-14 14:28 UTC, mjvkeulen commented on src/django/VLE/utils/file_handling.py
> +def establish_file(author, identifier, **kwargs):
Renaming `kwargs` to `context` does not make the actual context parameters more transparent?

2020-10-14 17:02 UTC, Larspolo commented on src/django/VLE/utils/file_handling.py
> +def establish_file(author, identifier, **kwargs):
Personally I find this more clear. A list of all different parameters you are mostly not gonna use  doesnt make it clear on what needs to be set I think, now its like "context, ah okay, I need to set context". But what I think counts more is that this is now modular, and reduces the amount of places that needs to be updated,if you want to add a new context place

2020-10-22 20:14 UTC, engelhamer commented
Hm, there appears to be some inconsistency going on here in terms of related names.. why is that?

2020-10-22 20:30 UTC, mjvkeulen commented on src/django/VLE/utils/generic_utils.py
> +        for file_date in attached_files:
typo

2020-10-22 20:33 UTC, mjvkeulen commented on src/django/VLE/utils/generic_utils.py
> +        preset_node.save()
Was this save required for something specific? Also saved on line 251.

2020-10-22 20:36 UTC, mjvkeulen approved these changes

2020-10-22 20:45 UTC, mjvkeulen requested changes
I forgot about the outstanding kwargs debate.

2020-11-01 17:06 UTC, mjvkeulen approved these changes

2020-11-13 16:55 UTC, engelhamer requested changes
Will fix what is required myself now.

2020-11-13 16:55 UTC, engelhamer commented on src/vue/src/components/assets/file_handling/FilesList.vue
> +                    <icon
Clicking this icon not only deletes the file, but also downloads it before deleting (which is undesirable).

2020-11-13 16:55 UTC, engelhamer commented on src/vue/src/components/assets/file_handling/ImageFileDisplay.vue
> +            class="controls unselectable"
Controls may not be specific enough. Be aware this may clash with some libs or something in the future.

2020-11-13 16:57 UTC, engelhamer approved these changes

2020-11-13 19:07 UTC, merged