Added automatic draft and restore of rich text
eJourn-al/eJournal pull request #1038
Opened 2020-10-16 12:04 UTC by mjvkeulen

Rich text content is now stored in local storage by default as a draft and remains there for 1 week. If a draft can be found for a rich text area, it is automatically restored.

Note that it is important the rich text editor receives a very specific id as it serves as the local storage key for draft storage.

- fixes #1279

2020-10-16 12:08 UTC, engelhamer commented
This is nice but maybe include the other fields of e.g. an Entry as well in this PR? Now it might be weird for users that their rich text content does appear after reloading the page, but not other fields.

2020-10-23 08:18 UTC, Larspolo requested changes
1. go to format editor
2. create new template
3. insert text in first field
4. wait 10 seconds
5. save assignment
6. navigate away
7. repeat 1 and 2
8. -> content is loaded in again, think this should be erased as it is a different new entry

Same goes for when creating a new assignment, or when placing a new comment (most common probably, see screenshot), or when creating a new presetnode in the format editor

![image](https://user-images.githubusercontent.com/11822478/96972869-60f48200-1517-11eb-8497-1f5576f7cdcc.png)

2020-10-23 08:18 UTC, Larspolo commented on src/vue/src/components/entry/EntryFields.vue
>                      :key="`rich-text-editor-field-${field.id > 0 ? field.id : field.location}`"
Should key and id be the same? When is which used?

2020-11-01 17:02 UTC, mjvkeulen commented on src/vue/src/components/entry/EntryFields.vue
>                      :key="`rich-text-editor-field-${field.id > 0 ? field.id : field.location}`"
key needs to be unique for that specific dom view, id needs to map the specific RT to storage.

2020-11-01 18:53 UTC, Larspolo commented on src/vue/src/components/entry/EntryFields.vue
>                      :key="`rich-text-editor-field-${field.id > 0 ? field.id : field.location}`"
So why not keep it the same?

2020-11-05 12:22 UTC, mjvkeulen commented on src/vue/src/components/entry/EntryFields.vue
>                      :key="`rich-text-editor-field-${field.id > 0 ? field.id : field.location}`"
Can do but why does that have your preference? (Either way is fine by me)

2020-11-06 14:55 UTC, Larspolo commented on src/vue/src/components/entry/EntryFields.vue
>                      :key="`rich-text-editor-field-${field.id > 0 ? field.id : field.location}`"
For consistency mostly

2020-11-13 17:01 UTC, engelhamer reviewed
In my opinion this is not very usable now, since e.g. comments re-appear illogically after a refresh (like Lars pointed out above). See my previous comment for it to be useful.

2021-04-03 11:17 UTC, mjvkeulen commented
Moving to another solution #688

2021-04-03 11:17 UTC, closed without merging