Improved the performance of editing an assignment
eJourn-al/eJournal pull request #1044
Opened 2020-10-31 08:35 UTC by mjvkeulen

2020-10-31 12:00 UTC, Larspolo requested changes

2020-10-31 23:23 UTC, mjvkeulen commented on src/django/VLE/models.py
> +        if unpublished and not old.can_unpublish():
Unpublished can only occur when we move the state from published to not. As such old is always available.

2020-10-31 23:27 UTC, mjvkeulen commented on src/django/VLE/views/format.py
> +def _update_assigned_groups(assignment, course_id, requested_group_ids):
Could do, but it's rather specific to how the group ids are supplied. Which in my opinion is heavily connected to the view. If it was a more generic set assigned groups function it would make more sense on the model itself. 

If you can come up with a name to reflect the expected behavior I will move it to the model.

2020-10-31 23:28 UTC, mjvkeulen commented on src/django/VLE/models.py
> +            ap.create_new_assignment_notification()
Quite aware, but the notification save holds a lot of logic.

2020-10-31 23:29 UTC, mjvkeulen commented on src/django/VLE/models.py
> +        Journal.objects.bulk_update(list(journals.keys()), ['needs_lti_link'])
Makes sense, and will do. Although I am quite sure this can also be done at the DB level. However, I couldn't make the query work.

2020-10-31 23:33 UTC, mjvkeulen commented on src/django/VLE/models.py
> +            ap = AssignmentParticipation.objects.create(assignment=self, user=user)
Can move the AP to bulk create, not much logic there.

Remind me, I believe a new AP creates a new assignment notification. So this should cause duplicates.

2020-11-01 09:28 UTC, mjvkeulen commented on src/django/VLE/models.py
> +        create = not new.pk
Create stems from the Django manager and serializer naming scheme

2020-11-01 10:23 UTC, mjvkeulen commented on src/django/VLE/models.py
> +            self.setup_journals()
Bit of a question of how you would like to couple the actions seems to make sense here.

2020-11-01 10:40 UTC, mjvkeulen commented on src/django/VLE/models.py
> +            ap = AssignmentParticipation.objects.create(assignment=self, user=user)
I remember why I didn't bulk create these, bulk creating journals requires quite a bit of effort.

# Bulk create APs
# Bulk create Journals (set all computed fields manually per instance)
# Bulk create preset nodes for those journals
# Bulk create notifications for deadlines (Progress and Presets)

Will require some implementation time, prob worthy of discussion

2020-11-01 12:05 UTC, mjvkeulen commented on src/django/VLE/models.py
> +        Journal.objects.bulk_update(list(journals.keys()), ['needs_lti_link'])
A journal instance has no access to either the assignment or the assignment participation and their respective users without performing queries. 

In the specific scenario here these are all fetched in one query, but not for one journal, for **all** journals about to be bulk updated. However, we are still working from the AP table, if you can improve the approach to work from the Journal table merging the logic with a `get_needs_lti_link` function could be clean. As it is now, the function would not share any logic for either approach (save vs (bulk) update).

2020-11-01 13:09 UTC, Larspolo commented on src/django/VLE/models.py
> +        create = not new.pk
Well, then update the name for the rest as well right? Now we have two naming schemes

2020-11-01 13:11 UTC, Larspolo commented on src/django/VLE/models.py
> +            self.setup_journals()
Missed this one to move to handle_publish

2020-11-01 13:11 UTC, Larspolo commented on src/django/VLE/models.py
> +            if new.conflicting_lti_link():
This can be in 1 if statement: `if active_lti_id_modified and new.conflicting_lti_link():`

2020-11-01 13:17 UTC, Larspolo commented on src/django/VLE/models.py
> +        Journal.objects.bulk_update(list(journals.keys()), ['needs_lti_link'])
> However, I couldn't make the query work.

Same. That's where the computed fields started

2020-11-01 13:25 UTC, Larspolo commented on src/django/VLE/views/format.py
> +def _update_assigned_groups(assignment, course_id, requested_group_ids):
The group ids are just a list right? Doesnt seem specific to me. Can even be called `group_ids` iso `requested_group_ids`

2020-11-01 13:46 UTC, mjvkeulen commented on src/django/VLE/views/format.py
> +def _update_assigned_groups(assignment, course_id, requested_group_ids):
Group ids is not a list of the new state of assigned groups, it is only a desired update from the perspective of a specific course.

2020-11-01 13:47 UTC, mjvkeulen commented on src/django/VLE/models.py
> +        create = not new.pk
I meant to express we already use multiple naming schemes?

2020-11-01 14:30 UTC, Larspolo commented on src/django/VLE/views/format.py
> +def _update_assigned_groups(assignment, course_id, requested_group_ids):
Maybe the function can be extended with also supporting the possibility of not giving a course ID, and only when supplied it gets limited to that set. I think then its funcitoning as expected for a model function

2020-11-01 19:18 UTC, Larspolo approved these changes

2020-11-01 20:11 UTC, engelhamer approved these changes

2020-11-01 20:14 UTC, Larspolo approved these changes

2020-11-01 20:14 UTC, merged