Max function length and complexity
eJourn-al/eJournal pull request #1045
Opened 2020-11-05 11:45 UTC by mjvkeulen

We had most of the required tools enabled already. 

How would you all like to proceed?

2020-11-05 11:51 UTC, Larspolo commented on src/vue/src/views/FormatEdit.vue
> +        /* eslint-enable complexity */
Would suggest to not do this, as this later hides these functions. I would opt for one of the following:
- reduce the complexity of these two functions to set a lower minimum
- increase the minimum to the complexity of these functions

After this its fine by me to just add this PR and later reduce the numbers to more sensible stuff

2020-11-05 15:18 UTC, mjvkeulen commented on src/vue/src/views/FormatEdit.vue
> +        /* eslint-enable complexity */
> After this its fine by me to just add this PR and later reduce the numbers to more sensible stuff

I am fine with this as well, would you be ok with leaving that one function as an exception? Its cyclomatic complexity is 60, which is quite out of line with the rest of our code so I figured better to just make the exception once so we could keep the number 3x lower without rewriting anything.

2020-11-05 16:15 UTC, Larspolo commented on src/vue/src/views/FormatEdit.vue
> +        /* eslint-enable complexity */
Nah, Ill change the function myself then to already get this reduction going. The goal of this PR is to reduce complexity right? Not hide high complexity functions

2020-11-05 17:18 UTC, Larspolo approved these changes

2020-11-16 16:47 UTC, engelhamer requested changes

2020-11-16 16:47 UTC, engelhamer commented on setup.cfg
> +max-function-length = 210
Why these numbers? To accept the status quo and prevent worse stuff from happening? That would not really seem like a sound method right?

2020-11-16 16:47 UTC, engelhamer commented on src/vue/src/views/FormatEdit.vue
> +            presetErrors: [
The construction is alright, but it is not really sensible to place these errors here as they are not used anywhere but in the dedicated funtion below. I do not think that moving this to the component data achieves any of the goals (i.e. readability, maintainability etc.) for which this PR is opened.

2020-11-16 16:47 UTC, engelhamer commented on src/vue/src/views/FormatEdit.vue
> +            // Returns false if order is incorrect or one of the dates is null
Returns true if any of the dates is null?

2020-11-16 16:47 UTC, engelhamer commented on src/vue/src/views/FormatEdit.vue
> +            // Returns false if order is incorrect or one of the dates is null
Comment may not be needed at all.

2020-11-16 16:47 UTC, engelhamer commented on src/vue/src/views/FormatEdit.vue
> +                if (error.happened) {
I'd prefer `occurred` instead (more colloquial to errors).

2020-11-16 16:47 UTC, engelhamer commented on src/vue/src/views/FormatEdit.vue
> +            presetErrors: [
Same holds for the `templatesIds` and `lastTarget`.

2020-11-16 18:31 UTC, mjvkeulen commented on setup.cfg
> +max-function-length = 210
This is our current upper limit. What do you propose?

2020-11-16 19:08 UTC, engelhamer commented on setup.cfg
> +max-function-length = 210
Well I do not have a strong preference for applying a specific limit, but just picking the max lines we currently have does not have added value right?

2020-11-16 19:42 UTC, mjvkeulen commented on setup.cfg
> +max-function-length = 210
It sets an upper limit, something we can reduce over time. 

I could also reduce this limit by creating a couple of exceptions for current high line/complexity cases. So we could use the lower limit as a more practical guideline without introducing a lot of refactoring work. I originally did this for one function (60CC) so we could lower the CC to 22. @Larspolo provided feedback that was not his preferred approach.

2020-11-16 20:18 UTC, engelhamer commented on setup.cfg
> +max-function-length = 210
Okay! Reducing over time seems valid. Shall we create an issue for that?

2020-11-20 16:18 UTC, Larspolo commented on src/vue/src/views/FormatEdit.vue
> +            presetErrors: [
Moving it inside the function means it gets re-initialized every time the function is run. I would prefer this option over inside the function. But I also see your point, do you have another idea on where to put it outside of the function?

2020-11-20 16:28 UTC, engelhamer commented on src/vue/src/views/FormatEdit.vue
> +            presetErrors: [
Given that this is just some JS client stuff, I don't think that will matter in terms of performance?

2020-11-20 16:32 UTC, Larspolo commented on src/vue/src/views/FormatEdit.vue
> +            presetErrors: [
Its more that I dont see moving it insight of the function being a better option then leaving it in de component data. Both seem like bad practices, and then I will go for the one where the linter works & is better on performance

2020-11-20 16:52 UTC, engelhamer commented on src/vue/src/views/FormatEdit.vue
> +            presetErrors: [
The linter is in place to make things more maintainable or readable. This option achieves neither: rather the contrary since you have to scroll elsewhere to read these errors, they are not used anywhere, and they are stored globally..

2020-11-26 13:38 UTC, Larspolo commented on src/vue/src/views/FormatEdit.vue
> +            presetErrors: [
Only when you are actually in the format editor its loaded. You don't see improvements on maitainability and readability with this approach compared to the old one? For me it was a bit of a mess, whereas now its all in a single list viewable with functions that indicate what is actually being checked

2020-11-26 16:16 UTC, engelhamer commented on src/vue/src/views/FormatEdit.vue
> +            presetErrors: [
That single list would otherwise be in a much more sensible location, namely in the only function where it is used. The only thing that this does is introduce more scrolling?

2020-11-26 16:16 UTC, engelhamer commented on src/vue/src/views/FormatEdit.vue
> +            presetErrors: [
Just copy the list to the top of the function itself then.

2020-11-26 17:07 UTC, Larspolo commented on src/vue/src/views/FormatEdit.vue
> +            presetErrors: [
done

2020-11-26 20:54 UTC, engelhamer approved these changes

2020-11-27 21:46 UTC, merged