Improved load times for most requests via serialization
eJourn-al/eJournal pull request #1047
Opened 2020-11-09 21:23 UTC by mjvkeulen

Node view (timeline serialization) speedup resulted in a more thorough approach to serialization speeds.

2020-11-10 12:42 UTC, Larspolo reviewed
General question just to have it all clear:

When do you use the following:
- Just the serializer with the query inside
- Use setup_eager_loading first
- Do sth like `{field: getattr(user, field) for field in UserSerializer.Meta.user_fields}`

Think I know, but then this question (or here it becomes clear that I dont know):
can we make it that the serializers themself reflect this logic -> rewrite the userserializer to just get the methods in a dict for example, then we will use it correctly automatically

2020-11-10 12:42 UTC, Larspolo commented on src/django/VLE/serializers.py
> +        journals = self.context.get('journals', False)
This is falsy by default (`None`), imo this can be left out here. as well as other places where `None` will also suffice like:
```
    def get_usernames(self, journal):
        if self.context.get('can_view_all_journals', False):
            return journal.usernames
        return None
```

2020-11-10 12:42 UTC, Larspolo commented on src/django/VLE/serializers.py
> +            # NOTE: This is no longer valid if journals from different assignments are serialized at the same time
Think I would not like this, can we just not set assignment in those cases? Would like to see the assignment set in the context on all places where possible. Places where no single assignment is know, should not then get a random assignment as permission check. We could change this to loop over all assignments of the journals and if for 1 assignment the user doesnt have the permissions -> False for all

2020-11-10 12:42 UTC, Larspolo commented on src/django/VLE/serializers.py
> +            return node.unlock_date.strftime('%Y-%m-%dT%H:%M')  # QUESTION: Why does this format deviate?
QUESTION: why do the others include seconds as well? We only support minutes right?

2020-11-10 12:42 UTC, Larspolo commented on src/django/VLE/serializers.py
> +        # 'jir__source__assignment__courses',
Think both are done as I would do too, JIR is too uncommon

2020-11-10 12:42 UTC, Larspolo commented on src/django/VLE/serializers.py
> +                            # second one can_view_course check per entry
Maybe we should just leave it at the assignment name (with PK?), its not even the real course anyway right? Could even generate a 500 error if there is no active course to the user

2020-11-10 15:02 UTC, mjvkeulen commented on src/django/VLE/serializers.py
> +        journals = self.context.get('journals', False)
A good place to tag this, the line below u see I omit the default.

```
journals = self.context.get('journals', False)
course = self.context.get('course')
```

From the context, the expected type is not always obvious.

`context['journals']` is just used as a boolean (opposed to a list of journals), which I made clear by the default.
`context['course']` is actually a course instance. 

For me working with the code it's more clear with the default, I think I broke something due to this at some point.

I am generally in favor of omitting function defaults, they just clutter and increase reading complexity (most of the time). 

However such defaults are not always obvious, e.g. a serializer is flagged as `read_only=True` by default when a queryset or many=True is passed as kwarg, unless a custom list serializer is implemented which can handle create or update operations. This is only obvious if the reader has some knowledge about the serializer class.

We have an outstanding issue regarding type hinting, and I am sure I was not fully consistent about providing a default everywhere. So I don't really know where to go with this, it depends I guess? 

For the line you tagged specifically the default would have saved me a bug during coding.

2020-11-10 15:05 UTC, mjvkeulen commented on src/django/VLE/serializers.py
> +            return node.unlock_date.strftime('%Y-%m-%dT%H:%M')  # QUESTION: Why does this format deviate?
@engelhamer ? I believe most dates follow the format set on the `Field` class: ALLOWED_DATETIME_FORMAT

2020-11-10 15:09 UTC, Larspolo commented on src/django/VLE/serializers.py
> +        journals = self.context.get('journals', False)
> which I made clear by the default.

It now indeed is a bit weird and unclear, the default helps, but doesnt solve the core problem I think.

Would prefer an option where it is clear that the name is a boolean: `also_get_journals`. Then no default value is needed, and we dont later on overwrite this variable by the actual journals. Would this solve the problem also?

2020-11-10 15:09 UTC, mjvkeulen commented on src/django/VLE/serializers.py
> +            return node.unlock_date.strftime('%Y-%m-%dT%H:%M')  # QUESTION: Why does this format deviate?
(`'%Y-%m-%dT%H:%M:%S'`)

2020-11-10 15:10 UTC, mjvkeulen commented on src/django/VLE/serializers.py
> +        # 'jir__source__assignment__courses',
You mean do not prefetch filecontext_set aswell?

2020-11-10 15:37 UTC, mjvkeulen commented on src/django/VLE/timeline.py
> +            EntrySerializer.setup_eager_loading(Entry.objects.filter(node=node)).first(),
Good catch, [0] should be get() where possible else first(). I refactored this later and missed this one.

2020-11-10 15:38 UTC, mjvkeulen commented on src/django/VLE/models.py
> +        ordering = ['location']
It does mean ORDER_BY is always applied, not free. We could definitely add this to models for which it makes a lot of sense.

2020-11-10 16:16 UTC, Larspolo commented on src/django/VLE/serializers.py
> +        # 'jir__source__assignment__courses',
No I ment I agree with your current configuration, fetching fielcontext, not fetching JIR courses

2020-11-10 16:18 UTC, Larspolo commented on src/django/VLE/models.py
> +        ordering = ['location']
True, lets not always add it to all, maybe we should add a `sort_default()` function to all models to keep a consistent ordering only when asked for

2020-11-11 13:09 UTC, mjvkeulen commented on src/django/VLE/models.py
> +    def get_student_deadline(self, journal):
They operate on a single instance (which makes it a good candidate for a model function), and this allows one to select the function for unit testing a bit more straight forward as well.

2020-11-11 13:35 UTC, mjvkeulen commented on src/django/VLE/models.py
> +        courses = self.courses.all()
> When do you use the following:
 
> * Just the serializer with the query inside

If there is no query manipulation required (select_related / prefetching). We have many _leaf_ level serializers, serializers that do not nest any other serializers (e.g. `InstanceSerializer`). So for these, it makes sense. Some of these do not even have any method fields / permission checks, and are basically just model to dict functions. For these simple serializers, if speed is of concern, just using query.values(...) to json (by response) is much faster and is also a valid option. Here is an excellent article on the topic: https://hakibenita.com/django-rest-framework-slow

> * Use setup_eager_loading first

Most likely calling a serializer that contains multiple nested serializers, e.g. `EntrySerializer`. The serializer represents more than a single DB table (entry also serializes its content (fields / files), author, template etc), all of these nested representations will cost multiple additional queries (for each of the primary table rows), so best we get in front of these by calling eager loading.

> * Do sth like `{field: getattr(user, field) for field in UserSerializer.Meta.user_fields}`

So this would leaf nodes which are fetched in sufficient bulk that it makes sense, e.g. list all users. Or it could be that we want the table to be serialized with fewer/different fields than existing serializers (creating a serializer class is sometimes silly compared to just .values('pk', 'name').

> Think I know, but then this question (or here it becomes clear that I dont know):
> can we make it that the serializers themself reflect this logic -> rewrite the userserializer to just get the methods in a dict for example, then we will use it correctly automatically
I am not too sure what you mean here, we could **add** a serializer which is just a function converting a user query set to the desired fields, in this fashion, we would lock down what fields are serialized for the faster calls. But this is also less flexible (we want an additional field in a different view method, new function? or just add it to .values() there).

2020-11-11 13:36 UTC, mjvkeulen commented
> When do you use the following:
 
> * Just the serializer with the query inside

If there is no query manipulation required (select_related / prefetching). We have many _leaf_ level serializers, serializers that do not nest any other serializers (e.g. `InstanceSerializer`). So for these, it makes sense. Some of these do not even have any method fields / permission checks, and are basically just model to dict functions. For these simple serializers, if speed is of concern, just using query.values(...) to json (by response) is much faster and is also a valid option. Here is an excellent article on the topic: https://hakibenita.com/django-rest-framework-slow

> * Use setup_eager_loading first

Most likely calling a serializer that contains multiple nested serializers, e.g. `EntrySerializer`. The serializer represents more than a single DB table (entry also serializes its content (fields / files), author, template etc), all of these nested representations will cost multiple additional queries (for each of the primary table rows), so best we get in front of these by calling eager loading.

> * Do sth like `{field: getattr(user, field) for field in UserSerializer.Meta.user_fields}`

So this would leaf nodes which are fetched in sufficient bulk that it makes sense, e.g. list all users. Or it could be that we want the table to be serialized with fewer/different fields than existing serializers (creating a serializer class is sometimes silly compared to just .values('pk', 'name').

> Think I know, but then this question (or here it becomes clear that I dont know):
> can we make it that the serializers themself reflect this logic -> rewrite the userserializer to just get the methods in a dict for example, then we will use it correctly automatically

I am not too sure what you mean here, we could **add** a serializer which is just a function converting a user query set to the desired fields, in this fashion, we would lock down what fields are serialized for the faster calls. But this is also less flexible (we want an additional field in a different view method, new function? or just add it to .values() there).

2020-11-11 21:28 UTC, mjvkeulen commented on src/django/VLE/models.py
> +        ordering = ['location']
I can see that being a useful addition to the models respective querysets.

2020-11-11 21:29 UTC, mjvkeulen commented on src/django/VLE/timeline.py
> +        and journal.authors.filter(user=author).exists() \
I can't see why it should be there. If you see a scenario I will gladly write a test for it?

2020-11-12 17:03 UTC, mjvkeulen commented on src/django/VLE/timeline.py
> +            EntrySerializer.setup_eager_loading(Entry.objects.filter(node=node)).first(),
So this was this intentional, a deadline might not yet hold an Entry.

2020-11-12 17:04 UTC, mjvkeulen commented on src/django/VLE/models.py
> +        courses = self.courses.all()
Doesn't matter if prefetched, .all() does not modify the query so the prefetch is used.

2020-11-12 17:05 UTC, mjvkeulen commented on src/django/VLE/serializers.py
> +        if name in instance._prefetched_objects_cache:
You will have to point out the other locations, depending on the number of nests / logic I sometimes prefer it for readability or ease of expansion (like dangling commas for git diffs). I don't see a reason here so I will update it.

2020-11-12 17:15 UTC, mjvkeulen commented on src/django/VLE/serializers.py
> +        journals = self.context.get('journals', False)
I updated the journals flag to `serialize_journals`

2020-11-12 17:16 UTC, mjvkeulen commented on src/django/VLE/serializers.py
> +        # 'jir__source__assignment__courses',
Moving the question to a NOTE, and removing the other question.

2020-11-12 17:20 UTC, mjvkeulen commented on src/django/VLE/serializers.py
> +                            # second one can_view_course check per entry
Since we decided against the prefetch of the `jir__source__assignment__courses`, the question is moot, and we should just stick with the get active course.

2020-11-12 17:40 UTC, mjvkeulen commented on src/django/VLE/serializers.py
> +            # NOTE: This is no longer valid if journals from different assignments are serialized at the same time
Atm, we do not serialize journals across assignments. If that were to change, I would be in favor of tackling it then. 

I don't think the else False for all is a final solution. So let's leave it for when we know the scenario and what would be required?

2020-11-13 08:14 UTC, Larspolo commented on src/django/VLE/models.py
> +        ordering = ['location']
Created issue

2020-11-13 08:24 UTC, Larspolo commented on src/django/VLE/timeline.py
> +        and journal.authors.filter(user=author).exists() \
Owww wow. I found what the problem was. It was with the param "author".

`author not in journal.authors.all()` assumes author is an AP -> will almost always return false

`journal.authors.filter(user=author).exists()` correctly assumes author is a user -> will only return true when author is in journal

This ment that untill now users with "can_have_journal" and that were allowed to view other students journal, would have seen an add-button in the timeline of other students journals

You could still write a test for it so it doesnt occure in the future, but this bug fixed now after 8 months

2020-11-13 08:26 UTC, Larspolo commented on src/django/VLE/timeline.py
> +            EntrySerializer.setup_eager_loading(Entry.objects.filter(node=node)).first(),
Then both `.first()`? Would probably doesnt matter much

2020-11-13 08:29 UTC, Larspolo commented on src/django/VLE/serializers.py
> +        if name in instance._prefetched_objects_cache:
The one I pointed out earlier, not in this PR

2020-11-13 08:34 UTC, Larspolo commented on src/django/VLE/serializers.py
> +            # NOTE: This is no longer valid if journals from different assignments are serialized at the same time
Added sentry message for now if this happens. Quite dangerous if it will happen without us noticing

```
                if self.instance.count() > 1:
                    capture_message(
                        'Journal serializer is used across assignments. This is may lead to permission issues',
                        level='warning'
                    )
```

2020-11-13 17:45 UTC, mjvkeulen commented on src/django/VLE/timeline.py
> +            EntrySerializer.setup_eager_loading(Entry.objects.filter(node=node)).first(),
What do you mean both? First is not prefered since it is both order by and limit 1

2020-11-13 19:17 UTC, engelhamer commented on src/django/VLE/serializers.py
> +            return node.unlock_date.strftime('%Y-%m-%dT%H:%M')  # QUESTION: Why does this format deviate?
This is to mitigate issues with date time pickers: Flatpickr uses this format and if you give it something else it will (annoyingly) change the original value a bit.

2020-11-13 19:33 UTC, engelhamer reviewed
Review not finished yet.

2020-11-13 19:33 UTC, engelhamer commented on src/django/VLE/models.py
> +                # Sum published grades to check if PROGRESS node is fullfiled
Bonus points should also be included in this sum, so start with that as the initial value for t_grade. (grade_sum as a more semantic name?)

2020-11-13 19:33 UTC, engelhamer commented on src/django/VLE/models.py
> +                # Sum published grades to check if PROGRESS node is fullfiled
Also maybe add a test for this.

2020-11-13 19:33 UTC, engelhamer commented on src/django/VLE/models.py
> +            # QUESTION: This effectively makes it impossible to join a journal with participants from a different course
This is undesirable and unpredictable for teachers right? I would prefer this to be possible.

2020-11-13 19:33 UTC, engelhamer commented on src/django/VLE/models.py
> +            raise VLEProgrammingError('Unsafe used of journal author property')
`use`

2020-11-13 19:33 UTC, engelhamer commented on src/django/VLE/serializers.py
> +            # QUESTION: full_name is not permission guarded compared to username and profile picture.
I think that anyone who can retrieve this serializer may also see the corresponding profile picture (for which only a `can_view` check is used below, which could indeed be removed in my opinion). The username on the other hand should not be visible for all. Take for example a group journal where students should not be able to see usernames (student IDs) of their fellow students. This would leak info that is not freely available elsewhere (e,g, on the LMS).

2020-11-13 21:44 UTC, mjvkeulen commented on src/django/VLE/serializers.py
> +            return node.unlock_date.strftime('%Y-%m-%dT%H:%M')  # QUESTION: Why does this format deviate?
So why do we have two formats @engelhamer

2020-11-13 21:52 UTC, mjvkeulen commented on src/django/VLE/models.py
> +                # Sum published grades to check if PROGRESS node is fullfiled
Code is quite old, I have not touched the logic apart from speedup here. Renamed t_grade variable as requested.

2020-11-13 21:53 UTC, mjvkeulen commented on src/django/VLE/serializers.py
> +            # QUESTION: full_name is not permission guarded compared to username and profile picture.
Removed check from profile picture, username is still guarded. Removed question.

2020-11-13 22:08 UTC, engelhamer commented on src/django/VLE/models.py
> +                # Sum published grades to check if PROGRESS node is fullfiled
But besides the name change bonus points should be included in the check too.

2020-11-13 22:09 UTC, mjvkeulen commented on src/django/VLE/models.py
> +                # Sum published grades to check if PROGRESS node is fullfiled
Ye it makes sense to change this with a test, will do when fresh

2020-11-13 22:16 UTC, mjvkeulen commented on src/django/VLE/models.py
> +            # QUESTION: This effectively makes it impossible to join a journal with participants from a different course
This is why that question exists, but why was this logic in place? When DO we want to serialize journals from the perspective of a signal course within an assignment?

2020-11-13 22:31 UTC, engelhamer commented on src/django/VLE/models.py
> +            # QUESTION: This effectively makes it impossible to join a journal with participants from a different course
Well that was not in the question: it wasn't even a question at all 😅

2020-11-13 22:46 UTC, mjvkeulen commented on src/django/VLE/serializers.py
> +            # NOTE: This is no longer valid if journals from different assignments are serialized at the same time
Added

2020-11-14 08:02 UTC, mjvkeulen commented on src/django/VLE/models.py
> +            # QUESTION: This effectively makes it impossible to join a journal with participants from a different course
Questions are simply a way to flag lines to get a discussion going during the review process. Whether that's in the form of a point of interest or question..

We currently serialize journals from the AssignmentSerializer (and children) with this filter applied if a `course` is provided as context. When do we want to filter an assignment's journals based on a specific course?  We currently also ignore that the user might be a participant in more than one of the assignments courses.

- We use `AssignmentSerializer` for the teacher journal overview (including group assignments)
- We use `Journal list` for the student journal overview (group assignment)

I moved the current Journal list filter to the queryset right below this filter for comparison. It is clear these are not even consistent (see `for_course` vs `for_course2`), a good reminder why centralizing such logic (on the respective model's QuerySet) is good practice.

Once the questions/discussion settle we can merge these filters.

2020-11-14 11:53 UTC, mjvkeulen commented on src/django/VLE/models.py
> +                # Sum published grades to check if PROGRESS node is fullfiled
Done

2020-11-14 19:08 UTC, Larspolo commented on src/django/VLE/models.py
> +        if self.is_entry:
This property doesnt exist right?

2020-11-15 21:15 UTC, mjvkeulen commented on src/django/VLE/models.py
> +        if self.is_entry:
It's defined on line 1892?

2020-11-19 20:17 UTC, engelhamer requested changes

2020-11-19 20:17 UTC, engelhamer commented on src/django/VLE/models.py
> +            # QUESTION: This effectively makes it impossible to join a journal with participants from a different course
What do you propose?

2020-11-19 20:17 UTC, engelhamer commented on src/django/VLE/serializers.py
> +    return default, False
Why always directly return this default value as part of a tuple? It is not used above.

2020-11-19 20:17 UTC, engelhamer commented on src/django/VLE/serializers.py
> +        read_only_fields = ('id', 'has_teacher_entries')
Why not `course_count`? Or `stats`?

2020-11-19 20:17 UTC, engelhamer commented on src/django/VLE/serializers.py
> +        # QUESTION: Could the permission context be safely set for a queryset of assignments as well?
What do you expect can go wrong? I would like a bit more info.

2020-11-19 20:17 UTC, engelhamer commented on src/django/VLE/serializers.py
> +            return node.unlock_date.strftime('%Y-%m-%dT%H:%M')  # QUESTION: Why does this format deviate?
Ah I don't think there's a valid reason for that. It can be changed but be sure to check the flatpickr components that use this.

2020-11-19 20:17 UTC, engelhamer commented on src/django/VLE/models.py
> +            # TODO: This (by accident) also catches node__entry__grade__isnull=True, make explicit
TODO left.

2020-11-19 20:17 UTC, engelhamer commented on src/django/VLE/models.py
> +            # QUESTION: Again significance of grade__grade__isnull=True?
I think this can be replaced by `grade__isnull=True`. We do not accept grades with empty input, but this was a potential (hacky) method to re-allow editing of entries a while ago. May be left from that feature.

2020-11-19 22:00 UTC, mjvkeulen commented on src/django/VLE/serializers.py
> +        read_only_fields = ('id', 'has_teacher_entries')
I guess this is just leftover.

Serializers should be read-only where possible for speed (will not initialize validation rules for said fields).

- Method fields are read-only by design (stats).
- Id is a ReadOnlyField unless overridden.
 
So these could be removed without affecting anything, which I will do since you asked. I don't see much point in also changing this for the `read_only_fields` definitions. It's just making the default obvious (in regards to `id`).

2020-11-19 22:03 UTC, mjvkeulen commented on src/django/VLE/serializers.py
> +        # QUESTION: Could the permission context be safely set for a queryset of assignments as well?
If we serialize assignments only from the perspective of a single course, the permission checks could be cached for the first assignment queryset instance. If not, a permission cache should be created for each unique course.

2020-11-19 22:04 UTC, mjvkeulen commented on src/django/VLE/models.py
> +            # TODO: This (by accident) also catches node__entry__grade__isnull=True, make explicit
So can I remove null=True from our Grade model?

2020-11-19 22:05 UTC, mjvkeulen commented on src/django/VLE/models.py
> +            # QUESTION: Again significance of grade__grade__isnull=True?
Ok, will update the DB to reflect this rule.

2020-11-19 22:06 UTC, mjvkeulen commented on src/django/VLE/serializers.py
> +    return default, False
That is by design if the attribute is not present in the instance cache the default is returned as value?

2020-11-20 07:49 UTC, mjvkeulen commented on src/django/VLE/models.py
> +            # QUESTION: This effectively makes it impossible to join a journal with participants from a different course
Merged the for_course filters, moved the for_course questions to an issue.

2020-11-20 15:44 UTC, engelhamer commented on src/django/VLE/serializers.py
> +    return default, False
Ah sorry, misread this part.

2020-11-20 15:53 UTC, engelhamer commented on src/django/VLE/serializers.py
> +            return node.unlock_date.strftime(VLE.models.Field.ALLOWED_DATETIME_FORMAT)
Maybe move the `ALLOWED_DATETIME_FORMAT` to a higher level (not within the `Field` model) as this usage is not related to fields at all.

2020-11-20 15:59 UTC, Larspolo approved these changes
Can save enough say that the same values are serialized. Only change I could find what that the UserSerializer not the role serialized when no course is supplied where it would preciously supply `role: None`. Checked frontend and found no issues with that change there

2020-11-21 10:26 UTC, engelhamer approved these changes

2020-11-21 10:27 UTC, merged