Changed commands folder to submodule
eJourn-al/eJournal pull request #1053
Opened 2020-11-23 19:16 UTC by Larspolo

## Description
This moves it to a private submodule which allows for easier non-app related commands

https://github.com/eJourn-al/eJournal-commands

2020-11-26 16:18 UTC, engelhamer approved these changes

2020-11-26 16:19 UTC, engelhamer commented
Travis does not like this yet.

2020-12-17 07:32 UTC, mjvkeulen requested changes
- Another/parallel job to run our linting
- Github actions run in parallel by default (apparently up to 20 jobs for open source/free tier?). We could speed up our tests by dividing the test files over multiple actions. Here is an example project which automates this process (even the merging of the coverage reports) 
https://github.com/jerry-git/pytest-split-gh-actions-demo/blob/master/.github/workflows/test.yml
Which seems quite doable on a low time budget?

2020-12-17 12:55 UTC, mjvkeulen commented on Makefile
> +	&& pytest ${TOTEST} src/django/test/ --store-durations
I think this is a left over for the upload? Or should this be continually updated?

2020-12-17 12:57 UTC, Larspolo commented on Makefile
> +	&& pytest ${TOTEST} src/django/test/ --store-durations
Would like it to be continually updated. Every time someone adds a test, it will then be automatically added to test test durations

2020-12-17 13:01 UTC, mjvkeulen commented on Makefile
> +	&& pytest ${TOTEST} src/django/test/ --store-durations
Does this slowdown running tests locally significantly? 

This also means an additional file to commit on each make test run right? (Not sure if we would like git changes to be polluted with this file on each PR / commit)

2020-12-17 13:02 UTC, mjvkeulen commented on Makefile
> +	&& pytest ${TOTEST} src/django/test/ --store-durations
I would be in favor of periodically uploading a new version, just so we keep git changes a bit cleaner. From the split test doc: if any test is missing from the duration.json file, it is assumed to be of average execution time. This seems fine for us with a periodical commit that updates this file?

2020-12-17 14:44 UTC, Larspolo commented on Makefile
> +	&& pytest ${TOTEST} src/django/test/ --store-durations
Good point, moved the auto update to seperate command, andcreated an issue

2020-12-19 12:11 UTC, mjvkeulen reviewed
Great to have CI working again! Seems like we got quite a decent speed going again too.

Just some remarks remaining regarding the build.yml file, which is the shiny new addition of course. 

Ideally the environment used during CI matches our local and production environment closely. 
Would it be possible to tweak the makefile commands for testing front and back (tests + lints) so we use the same commands for both CI and local env?

2020-12-19 12:11 UTC, mjvkeulen commented on .github/workflows/build.yml
> +      - name: Set up Python 3.6.9
Occurs 3 times, good candidate to be reused with an anchor? Assuming this works as valid yaml?

2020-12-19 12:11 UTC, mjvkeulen commented on .github/workflows/build.yml
> +          useLockFile: false
How does this work? Should our node env also be cached?

2020-12-19 12:11 UTC, mjvkeulen commented on .github/workflows/build.yml
> +jobs:
I could not find much about splitting jobs across different yaml files, do you know if that's possible?

2020-12-21 14:53 UTC, Larspolo commented on .github/workflows/build.yml
> +          useLockFile: false
`useLockFile: false` is saying that we do not have a lock file, and to use the package.json instead

Might be posisble, but as is is fast enough. Although if you want you can try to make it cashed as well, should be useful once we start adding front end testing as well

2020-12-21 14:54 UTC, Larspolo commented on .github/workflows/build.yml
> +      - name: Set up Python 3.6.9
Im not too familliar with yaml, count be possible, but what I tried didnt work

2020-12-21 14:54 UTC, Larspolo commented on .github/workflows/build.yml
> +      - name: Run tests
Thats all the tests we have though

2020-12-21 15:23 UTC, mjvkeulen commented on .github/workflows/build.yml
> +      - name: Run tests
Fair enough, calling lints tests is unfair.

2020-12-21 15:47 UTC, mjvkeulen commented on .github/workflows/build.yml
> +      - name: Set up Python 3.6.9
I looked and atm github actions simply doesn't support anchors. There are composite actions, so we could split the jobs file but it looks like slightly too much effort for the gain.

2020-12-21 15:49 UTC, mjvkeulen commented on .github/workflows/build.yml
> +          useLockFile: false
So using the composite action `bahmutov/npm-install@v1.4.5` already sorts out cache for us.

2020-12-21 15:51 UTC, mjvkeulen commented on .github/workflows/build.yml
> +jobs:
Composite actions

2020-12-22 11:47 UTC, engelhamer commented on .test_durations
> +[
Why does this file have to be commited?

2020-12-22 11:56 UTC, Larspolo commented on .test_durations
> +[
To better schedule the tests into parallel actions. Say 1 test takes 10 minutes, then a single action would be created specifically for that test

2020-12-22 13:48 UTC, mjvkeulen approved these changes

2020-12-22 13:59 UTC, merged