Release 1.5 fixes
eJourn-al/eJournal pull request #1056
Opened 2020-11-29 13:34 UTC by mjvkeulen

Pre 1.5 release fixes

- Fixes #1379

2020-11-29 16:29 UTC, Larspolo requested changes

2020-11-29 16:29 UTC, Larspolo commented on src/django/VLE/views/journal.py
> +            stored_name=self._get_name(name, amount, assignment),
This doesnt work now, see https://zube.io/ejourn-al/ejournal/c/1394

2020-11-30 10:23 UTC, Larspolo commented on src/vue/src/views/Home.vue
> +            return display
Now you dont know whether it is the end or start date of the course. Elsewhere this is fixed by doing `if (course.startdate || course.enddate) { display += ' - ' }`

2020-11-30 11:28 UTC, mjvkeulen commented on src/vue/src/views/Home.vue
> +            return display
I don't see the fix? We don't have a clear distinction between start and end if only one date is shown elsewhere afaik?

2020-11-30 12:52 UTC, Larspolo commented on src/vue/src/views/Home.vue
> +            return display
`src/vue/src/utils/generic_utils.js:27`

2020-11-30 14:21 UTC, mjvkeulen commented on src/vue/src/views/Home.vue
> +            return display
Having a single place for this logic has my preference as well, I don't see how `courseWithDatesDisplay` as is would solve this issue. 

`- date`
`date -` 
both of these are not really practical indications of either start or stop.

I think we need a proper solution?

2020-11-30 17:27 UTC, Larspolo commented on src/vue/src/views/Home.vue
> +            return display
Something better is preferred, but until then reusing existing functions is also preferred

2020-11-30 18:28 UTC, mjvkeulen commented on src/vue/src/views/Home.vue
> +            return display
Go for it, the function you refer to will need to be split. Currently it returns both the course name and date as a single string for use in multiselects.

Still curious how you will make a distinction between start and end date of only ons is available.

2020-11-30 19:35 UTC, Larspolo commented on src/vue/src/views/Home.vue
> +            return display
Before the "-" -> start date
After the "-" -> end date

2020-12-01 09:29 UTC, engelhamer commented
![image](https://user-images.githubusercontent.com/39912581/100721747-05dc6780-33c0-11eb-965a-412a20553d5c.png)

2020-12-01 09:49 UTC, engelhamer approved these changes

2020-12-01 15:39 UTC, Larspolo approved these changes

2020-12-01 20:57 UTC, merged