Added pagination to the user overview
eJourn-al/eJournal pull request #1064
Opened 2020-12-09 14:23 UTC by mjvkeulen

Pagination can be configured via URL query parameters:
- `page` (int): the window of the query set to serialize.
- `page_size` (int): size of the window.
- `order_by` (str): order by argument, can be descending (-).
- `filter` (str): filter to apply to the query, for the user table this performs a case insensitive search for the columns  `full_name`, `username`, and `email`.

Changing pages is compatible with the set filter and order.

An upper limit to the desired  `page_size` can be configured via `max_page_size`, this can be done globally (`PAGE_SIZE`), or per view, as is done in this PR (see views/user.py).

![image](https://user-images.githubusercontent.com/39912610/101640964-72dfa500-3a31-11eb-8131-e3c304196890.png)

![image](https://user-images.githubusercontent.com/39912610/101641031-88ed6580-3a31-11eb-90c6-ee41aae79f95.png)

2020-12-09 16:17 UTC, engelhamer requested changes

2020-12-09 16:17 UTC, engelhamer commented on src/vue/src/components/admin/UserOverview.vue
> +                    label: '',
This column should not be sortable: clicking in the red square causes a 500 error.

![click](https://user-images.githubusercontent.com/39912581/101655731-36687500-3a42-11eb-996a-7174dcbe8194.png)

2020-12-09 16:17 UTC, engelhamer commented on src/vue/src/components/admin/UserOverview.vue
> +            console.log(context)
Debug print left?

2020-12-22 11:52 UTC, engelhamer approved these changes

2020-12-22 14:31 UTC, Larspolo approved these changes
Would prefer the table only showing the load icon after halve a second, this reduces the flash, but its not much used, and already a way better version then currently, so still approving

2020-12-22 15:23 UTC, merged