Fixed various small issues
eJourn-al/eJournal pull request #1075
Opened 2020-12-23 14:09 UTC by mjvkeulen

- Fixes Z#1383
- Fixes Z#1387
- Fixes Z#1389
- Fixes Z#1403
- Fixes Z#1414
- Fixes Z#1418
- Fixes Z#1095

2020-12-23 17:31 UTC, Larspolo commented
> Submodule commands updated from f2f2b8 to f7d314

Should not be included in this PR

2020-12-23 18:41 UTC, Larspolo commented
Good PR, all works well. Just some other issues that were inline with this PR:

- JIR modal also does not display the assignment due dates, idk if that is meant

- Would be nice if other stuff also (slowly) made use of the new validation input (like the points possible)

- Teacher specific notification settings are still visible for students (same other way around teachers having student notification settings)

2020-12-23 18:41 UTC, Larspolo approved these changes

2020-12-26 20:05 UTC, engelhamer requested changes
The Youtube embed is not consistent throughout front and back end implementations. This could cause weird errors in the current form.

2020-12-26 20:05 UTC, engelhamer commented on src/django/VLE/validators.py
> +    r = r"^((?:https?:)?\/\/)?((?:www|m)\.)?((?:youtube\.com|youtu.be))(\/(?:[\w\-]+\?v=|embed\/|v\/)?)([\w\-]+)(\S+)?$"
This regex yields different results from the front end (js) one. For example `https://www.youtube.com/channel/UCDZkgJZDyUnqwB070OyP72g` is valid from this check, but invalid front end. The latter makes sense, since this is a channel URL rather than a video.

2020-12-26 20:05 UTC, engelhamer commented on src/django/test/test_utils.py
> +        valid_youtube_video_urls = [
These tests are not all video URLs and while they do all pass the back end regex, they do not all pass the front end regex. There should not be an inconsistency between these.

2020-12-26 20:05 UTC, engelhamer commented on src/vue/src/utils/validation.js
> +            const re = /^(?:https?:\/\/)?(?:m\.|www\.)?(?:youtu\.be\/|youtube\.com\/(?:embed\/|v\/|watch\?v=|watch\?.+&v=))((\w|-){11})(?:\S+)?$/ // eslint-disable-line
This regex is different than the one used to extract and display the video at https://github.com/eJourn-al/eJournal/blob/e05e3be0a9845a348f08c72ca1e7c5cb62c837f0/src/vue/src/components/entry/EntryFields.vue#L208 . Should be consistent all throughout.

2020-12-26 21:17 UTC, Larspolo commented on src/django/test/test_utils.py
> +            'https://www.youtube.com/channel/UCDZkgJZDyUnqwB070OyP72g',
Guess same for the watch, use our promotion video

2020-12-29 10:55 UTC, Larspolo commented on src/django/test/test_utils.py
>              'youtube.com/n17B_uFF4cA',
These are not valid YT links. Same goes for `https://youtube.com/iwGFalTRHDA`. Bit weird to then include them in the test

2021-01-07 13:14 UTC, engelhamer approved these changes

2021-01-07 13:15 UTC, merged