Added variety of tests to parts that needed some
eJourn-al/eJournal pull request #1079
Opened 2021-01-06 16:53 UTC by Larspolo

## Description
Added variety of tests to parts that needed some

2021-01-07 07:16 UTC, mjvkeulen commented on src/django/VLE/utils/entry_utils.py
> +                # If its required, it already returns after the `check_fields` right?
Provided `validate_entry_content` is always called before `create_entry_content`, `VLEMissingRequiredField` should always be raised already and this block never reached.

2021-01-07 07:18 UTC, mjvkeulen commented on src/django/test/factory/params.py
> +            node = preset.node_set.filter(journal=journal).first()
This is because of the one to one issue in the factory right? Possible change this to .get() iso first() for clarity.

2021-01-07 07:20 UTC, mjvkeulen commented on src/django/test/factory/params.py
> +        author = kwargs.pop('author', random.choice(journal.authors.all()).user)
So in python function args are always evaluated. So even if an author is present in kwargs we will query the journal authors.

2021-01-07 07:22 UTC, mjvkeulen commented on src/django/test/test_entry.py
> +        # Entries cannot be published after lockdate
Publishing entries?

2021-01-07 07:27 UTC, mjvkeulen commented on src/django/test/test_entry.py
> +        # Template of that is not bound to node, should not be useable, even from the same assignment
`of that is not`

It should not be possible to create a deadline entry using a template other than the preset's template?

2021-01-07 07:32 UTC, mjvkeulen commented on src/django/test/test_entry.py
> +        assert 'EntryDeadline' in resp, 'Node must be progress node if "node_id" is supplied'
I don't quite follow this block. 

We try to create an entry for a progress node. 

> 'Node must be progress node if "node_id" is supplied'

The node is now a progress node right?

2021-01-07 07:33 UTC, mjvkeulen commented on src/django/test/test_entry.py
> +        factory.Template(format=factory.Assignment().format)
Possible to reuse the assignment?

2021-01-07 07:37 UTC, mjvkeulen commented on src/django/test/test_file_handling.py
> +        api.get(self, 'files/access_id', params={'pk': file.access_id}, user=other_teacher)
Possibly sprinkle some comments on why the individual cases differ and what the expected outcome is.

2021-01-07 07:39 UTC, mjvkeulen commented on src/django/test/test_file_handling.py
> +        api.get(self, 'files/access_id', params={'pk': file.access_id}, user=other_teacher)
Makes me think of another param to api.get, msg -> use as assert msg when status does not match?

2021-01-07 07:40 UTC, mjvkeulen commented on src/django/test/test_gradepassback.py
> +        journal = factory.Journal()
Possible to use the setup assignment?

2021-01-07 07:41 UTC, mjvkeulen commented on src/django/test/test_gradepassback.py
> +        author = journal.authors.first()
We have a shorthand for this (which is also 1 query less), `journal.author`

2021-01-07 07:42 UTC, mjvkeulen commented on src/django/test/test_gradepassback.py
> +            'When author has no greade url, it should say so'
typo, clear comments to these tests tho ^^

2021-01-07 07:42 UTC, mjvkeulen requested changes
Good stuff, some of these tests cover essential business logic. Silly they were not tested!

2021-01-07 14:05 UTC, Larspolo commented on src/django/test/test_gradepassback.py
> +        journal = factory.Journal()
Its nowhere else needed though. This needs to be a non LTI journal specifically, the rest tests with LTI

2021-01-07 14:09 UTC, Larspolo commented on src/django/test/test_file_handling.py
> +        api.get(self, 'files/access_id', params={'pk': file.access_id}, user=other_teacher)
Currently doesn't exists right? Will do it in comments instead for now

2021-01-07 14:11 UTC, Larspolo commented on src/django/test/test_gradepassback.py
> +        author = journal.authors.first()
`journal.author` gets the user (which is generally wanted), but now we want the AP

2021-01-07 14:16 UTC, Larspolo commented on src/django/test/test_entry.py
> +        assert 'EntryDeadline' in resp, 'Node must be progress node if "node_id" is supplied'
Updated to "You should not be able to create a note in a PROGRESS node"

2021-01-07 14:19 UTC, Larspolo commented on src/django/test/factory/params.py
> +            node = preset.node_set.filter(journal=journal).first()
Yes, did it

2021-01-08 08:30 UTC, mjvkeulen commented on src/django/test/test_gradepassback.py
> +        author = journal.authors.first()
You know how often I make this mixup, damn our phrasing sometimes.

2021-01-08 08:34 UTC, mjvkeulen approved these changes

2021-01-10 12:21 UTC, engelhamer approved these changes

2021-01-10 12:24 UTC, merged