Add categories to templates, template and preset node views, assignment editor rework, import file bugfix
eJourn-al/eJournal pull request #1081
Opened 2021-01-29 13:39 UTC by mjvkeulen

- Categories can now be added via template edit
- Format editor reworked. Each component now has a display and edit mode. Each instance holds its own draft.
- Dedicated views to the models `PresetNode` and `Template`, each with their own validation front and backend.
- Files are now properly copied on import/copy, before removing a file from the source (e.g. in rich-text) would also delete the file for the target. 

## Summary of changes
- Fixes Z#1477
- Fixes Z#1454
- Fixes Z#1443
- Fixes Z#55
- Fixes Z#90 (remaining issue better encapsulated in #1482)

## Questions
- What still needs to be done to satisfy Z#95?

2021-01-29 16:56 UTC, Larspolo requested changes
Checked the backend code, and clicked through the frontend. Still frontend code to go, but I already like the addition of the store modules.

2021-01-29 16:56 UTC, Larspolo commented on src/django/VLE/serializers.py
> +    ]
[NIT/Q]
```
            queryset=PresetNodeSerializer.setup_eager_loading(
                VLE.models.PresetNode.objects.order_by('due_date')
            ),
```
the order by is now no longer necessary right?

2021-01-29 16:56 UTC, Larspolo commented on src/vue/src/components/assignment_editor/timeline_controlled/assignment/AssignmentEdit.vue
> +                return
[NIT] Somewhere an indication into which are still to be saved would make this PR even better. If not for now, I would defenitly see this as a future improvement

2021-01-29 16:56 UTC, Larspolo commented on src/django/VLE/tasks/beats/cleanup.py
> +    ass_fcs_without_reference = ass_fcs_without_reference.exclude(pk__in=fc_ids_attached_to_preset_nodes)
Nice comments! Did this mean that before this change attached files to preset nodes would have been deleted?

2021-01-29 16:56 UTC, Larspolo commented on src/django/VLE/utils/file_handling.py
> +def copy_and_replace_rt_files(rich_text, user, assignment=None, category=None):
This function name feels a bit too brought for what it does. Currently only supports assignment / categories right?

Would either change the name, or widen the scope. Maybe import_utils.py:182 (inside `import_content`) could make use of it as well (and possibly add for non rt files then as well

2021-01-29 16:56 UTC, Larspolo commented on src/django/VLE/utils/generic_utils.py
> +    if type == bool and value == 'false':
Nice function :)

[NIT] In `get_lti_params_from_jwt` we do ` == 'true'` for boolean fields. That could also make use of this

2021-01-29 16:56 UTC, Larspolo commented on src/django/VLE/utils/import_utils.py
> +    Category.objects.bulk_update(categories_with_copied_rt_description, ['description'])
[Q] would this be useful to all be put inside a `with transation`?

2021-01-29 16:56 UTC, Larspolo commented on src/django/VLE/utils/import_utils.py
> +    ]
[Q] can this be done in a `bulk_create`?

2021-01-29 16:56 UTC, Larspolo commented on src/django/VLE/views/assignment.py
> +    # Worth spending some time looking into the advantages / disadvantages?
The shorter we lock, the sooner its available elsewhere right? Maybe we could start the transaction only after the permission check, but I still like the addition of it here over nothing

2021-01-29 16:56 UTC, Larspolo commented on src/django/VLE/serializers.py
>              # Not used / missing: active_lti_id, lti_id_set, assigned_groups, format
[NIT] I'm not sure when it was added, but this comment seem to now not be up to date, as format is now also added.
[Q] Why is this added? Should it be added to the read_only fields?

2021-01-29 16:56 UTC, Larspolo commented on src/django/VLE/serializers.py
> +            'lti_id',
[Q] Should `id` also be included in this list? Or is it by default? Or is it needed from importing assignment?

2021-01-29 16:56 UTC, Larspolo commented on src/django/VLE/views/assignment.py
> +        # Requires assignment with accurate pk
[Q] This funciton could also make use of a atomic transation thing right?

2021-01-29 16:56 UTC, Larspolo commented on src/django/VLE/views/format.py
> -"""
Nice :D

2021-01-29 16:56 UTC, Larspolo commented on src/django/test/factory/assignment.py
> +        kwargs['course_id'] = assignment.courses.first().pk
[NIT] could possibly change to sth like `        kwargs['course_id'] = kwargs.get('course_id', assignment.courses.first().pk)`

2021-01-29 16:56 UTC, Larspolo commented on src/django/VLE/views/preset_node.py
> +        return response.success({
I was able to change the progress node's out of order:
![image](https://user-images.githubusercontent.com/11822478/106303409-6241f300-625a-11eb-9462-c5ad5146c05c.png)
This was not possible before and gave a validation error

2021-01-30 08:09 UTC, mjvkeulen commented on src/vue/src/components/assignment_editor/timeline_controlled/assignment/AssignmentStartReadMode.vue
> +<template>
This is caused by a switch component changing subcomponents via `v-if`. I will have to look into a solution, I think this approach is applied quite commonly by us, but I agree it is quite visible here.

2021-01-30 09:08 UTC, mjvkeulen commented on src/vue/src/components/assignment_editor/timeline_controlled/assignment/AssignmentEdit.vue
> +        save () {
Point one and two fixed, not sure how to address point 3. This is simply the router actually navigating to a different page. Would you like to see a different type of transition?

2021-01-30 09:10 UTC, mjvkeulen commented on src/vue/src/components/category/CategoryEdit.vue
> +        },
What is the exact order to reproduce this? If I simply change the templates of a category, or the categories of a template and save I cannot reproduce this?

2021-01-30 09:11 UTC, mjvkeulen commented on src/vue/src/components/category/CategoryEdit.vue
>              />
Atm, I have been consistent in using our display components as true as possible to the normal views. Do you disagree with this design choice? Or just break it in this one instance?

2021-01-30 09:12 UTC, mjvkeulen commented on src/vue/src/components/template/TemplateEditSettings.vue
> +            <!-- Question: @ Lars, hide this as well or hide nothing? -->
I am not in favor either way, so atm we have you on the one side and Engel on the other.

2021-01-30 09:15 UTC, mjvkeulen commented on src/vue/src/components/assignment_editor/timeline_controlled/preset_node/PresetNodeEdit.vue
> +            />
Ah tricky, updating the template actually creates a new one (due to the archiving process). I would have to think about a clever solution since we cannot even rely on name as identifiers atm.

2021-01-30 09:25 UTC, mjvkeulen commented on src/vue/src/components/assignment_editor/timeline_controlled/preset_node/PresetNodeEdit.vue
> +                />
Good catch, was some bad ordering of some filters (and clearly bad tests). 

What should the display be for attached files of a deadline preset node? Added a TODO for this point.

2021-01-30 09:26 UTC, mjvkeulen commented on src/vue/src/components/assignment_editor/timeline_controlled/preset_node/PresetNodeEdit.vue
> +                </template>
I dont mind either way, removing the if

2021-01-30 09:26 UTC, mjvkeulen commented on src/vue/src/components/assignment_editor/timeline_controlled/preset_node/PresetNodeEdit.vue
> +                </template>
Tag the right line tho! :p

2021-01-30 09:28 UTC, mjvkeulen commented on src/vue/src/store/modules/assignmentEditor.js
> +        const originalTemplate = templates.find(elem => elem.id === template.id)
Cancel edit should only occur on objects already created (and thus part of modules category/template etc). Thus hopefully the original should always be found. 

Weird error, hopefully, we get a better trace at some point?

2021-01-30 09:34 UTC, mjvkeulen commented on src/vue/src/views/Course.vue
> +                name: 'AssignmentEditor',
Good catch, easy fix but also have to move the assignmentAPI create function to the respective module to update local state. Will do that in a couple hours.

2021-01-30 16:01 UTC, Larspolo commented on src/vue/src/components/assignment_editor/timeline_controlled/assignment/AssignmentStartReadMode.vue
> +<template>
Maybe its also a css transition that is being applied? Thats what I was thinking. It is not on the other card

2021-01-31 16:07 UTC, Larspolo commented on src/vue/src/components/assignment_editor/timeline_controlled/assignment/AssignmentEdit.vue
> +        save () {
I would expect it to not have a transition at all, or at least a transition that doesn't display the breadcrumb etc twice

2021-01-31 16:09 UTC, Larspolo commented on src/vue/src/components/category/CategoryEdit.vue
>              />
I totally agree with the design choice, but in this specific instance I would expand to also view the component as it would be viewed when clicking the "(i)"  icon

2021-01-31 16:11 UTC, Larspolo commented on src/vue/src/components/category/CategoryEdit.vue
> +        },
1. Go to a category
2. Click edit
3. Select a template that was not selected before
4. Click save
5. Click anywhere on the breadcrumb
6. View the (unexpected) prompt

2021-01-31 16:12 UTC, Larspolo commented on src/vue/src/components/template/TemplateEditSettings.vue
> +            <!-- Question: @ Lars, hide this as well or hide nothing? -->
Lets put the final say to @engelhamer then

2021-01-31 16:15 UTC, Larspolo commented on src/vue/src/components/assignment_editor/timeline_controlled/preset_node/PresetNodeEdit.vue
> +                />
Think as is works fine. This is also the same as a student would view it

![image](https://user-images.githubusercontent.com/11822478/106390285-e83f7480-63e7-11eb-9e29-4f815347f516.png)

2021-01-31 16:21 UTC, engelhamer commented on src/vue/src/components/assignment_editor/timeline_controlled/assignment/AssignmentStartReadMode.vue
> +<template>
I will check it out now

2021-01-31 16:48 UTC, engelhamer commented on src/django/VLE/models.py
> +            raise ValidationError('One or more deadlines are locked after the assignment locks.')
[NIT]: would like this to be rephrased to 'have a lock date after..' (i.e. use 'lock date' is 'locks' everywhere). This way we use the exact same term the user sees and mitigate unneeded confusion from having to realise that 'locks' refers to this.

2021-01-31 17:46 UTC, mjvkeulen commented on src/django/VLE/tasks/beats/cleanup.py
> +    ass_fcs_without_reference = ass_fcs_without_reference.exclude(pk__in=fc_ids_attached_to_preset_nodes)
Yes, the current bug is quite severe, if any files of a copied assignment / imported template are changed/removed in the original, they are also removed from the copied assignment/template.

2021-02-01 09:07 UTC, engelhamer reviewed
Until 04d124a

2021-02-01 09:07 UTC, engelhamer commented on src/vue/src/components/format/timeline_controlled/assignment/AssignmentEdit.vue
> +<template>
[NIT] Would `AssignmentDetailsEdit` not make more sense for a name? The whole format thing is actually assignment edit.

2021-02-01 09:07 UTC, engelhamer commented on src/vue/src/components/format/timeline_controlled/preset_node/PresetNodeEdit.vue
> +                <!-- QUESTION: User facing it might make more sense to use 'deadline' over 'preset'? -->
Yes, if not already done (reviewing earlier commit) then this is a nice change to still make.

2021-02-01 09:07 UTC, engelhamer commented on src/vue/src/components/template/TemplateEditSettings.vue
> +            <!-- Question: @ Lars, hide this as well or hide nothing? -->
I would like the category stuff to be hidden until a category is created, to make it easier for new users to get started and not be intimidated by all options as much. This is also in line with some informal user feedback we have had in the past.

2021-02-01 09:07 UTC, engelhamer commented on src/vue/src/components/template/TemplateImport.vue
> -                <category-display
I can imagine scenarios where the categories would be nice to copy as well. Maybe if we support importing categories from another assignment this should be reconsidered (create an issue)?

2021-02-01 10:55 UTC, engelhamer commented on src/vue/src/components/assignment_editor/timeline_controlled/preset_node/PresetNodeEdit.vue
> +            />
You have a template chain, which should be able to fix this issue?

2021-02-01 11:32 UTC, engelhamer reviewed
All code only

2021-02-01 11:32 UTC, engelhamer commented on src/vue/src/components/category/CategoryEdit.vue
>              />
That is true, but this 'view' of a category on it's own (so not part of the list for selecting it within an entry) is not viewable for students at all. I think it would not hurt also including the selected templates as well (since it now looks abit 'empty', right?).

2021-02-01 11:32 UTC, engelhamer commented on src/vue/src/views/FormatEdit.vue
> +                // this.$intro().start()
Comment just to ensure this is re-enabled later.

2021-02-01 11:32 UTC, engelhamer commented on src/vue/src/components/assignment_editor/AssignmentEditorBreadCrumb.vue
> +<template>
I think that moving this to two nested components harms readability of the assignment editor. Why do you prefer this rather than keeping it in the same file? This method:
- introduces more lines than needed (overhed `template` tags, `export default` etc.)
- Requires you to click through to an additional file rather than where it is used
- Results in way more files, and this particular example has only 3 logical lines really?

2021-02-01 15:40 UTC, Larspolo commented on src/vue/src/components/assignment/AssignmentDetailsDates.vue
> +        },
[NIT] Woudl prefer removing this function, and flipping the parameters, this makes it for me more readable as you only have to look at the order of parameters, and not also first at the function name

2021-02-01 15:40 UTC, Larspolo commented on src/vue/src/components/assignment/AssignmentDetailsDates.vue
> +                || new Date(this.assignment.unlock_date) > additionalConfig.minDate)) {
[NIT] I think here you can also make use of the `firstBeforeSecond` function right?

2021-02-01 15:40 UTC, Larspolo commented on src/vue/src/components/assignment_editor/AssignmentEditorBreadCrumb.vue
> +<template>
A positive I see is that if we were to make further changes to the breadcrumb specific, then it will be handled in its specific file.
Another downside I see is that creating components may impact performance. That said, I don't think this single one makes much of a difference

Could go either way for me

2021-02-01 15:40 UTC, Larspolo commented on src/vue/src/components/assignment_editor/timeline_controlled/SelectedTimelineComponentSwitch.vue
> +    <div>
[NIT][ Is this div needed?

2021-02-01 15:40 UTC, Larspolo commented on src/vue/src/components/assignment_editor/timeline_controlled/assignment/AssignmentEndReadMode.vue
> +                Edit
[NIT] I would think that this edit button might cause confusion on what is being edited

2021-02-01 15:40 UTC, Larspolo commented on src/vue/src/components/assignment_editor/timeline_controlled/preset_node/PresetNodeEdit.vue
> +                    {{ (edit) ? 'Save' : 'Add Preset' }}
[NIT] brackets shouldnt be necessary right?

2021-02-01 15:40 UTC, Larspolo commented on src/vue/src/components/assignment_editor/timeline_controlled/preset_node/PresetNodeEdit.vue
> +                    <!-- QUESTION: User facing it might make more sense to use 'deadline' over 'preset'? -->
Totally agree

2021-02-01 15:40 UTC, Larspolo commented on src/vue/src/components/entry/Entry.vue
>              </template>
I can no longer create entries

![image](https://user-images.githubusercontent.com/11822478/106478011-1042dc80-64a9-11eb-8cb5-f1240a5176d8.png)

2021-02-01 15:40 UTC, Larspolo commented on src/vue/src/components/assignment_editor/timeline_controlled/preset_node/PresetNodeReadMode.vue
> +        <!-- TODO Category: This does not display any attached files -->
Huh, this is quite the bug, no student can currently see the attached files. only in progress nodes

2021-02-01 15:40 UTC, Larspolo commented on src/vue/src/store/modules/assignmentEditor.js
> +                template: '',
[Q] why si template '' and not null?

2021-02-01 15:40 UTC, Larspolo commented on src/vue/src/store/modules/assignmentEditor.js
> +                name: 'Entry',
[NIT] Maybe we should leave this empty. Seems only logical

2021-02-01 15:40 UTC, Larspolo commented on src/vue/src/store/modules/assignment.js
> +    update (context, { id, data, connArgs = auth.DEFAULT_CONN_ARGS }) { // eslint-disable-line
[NNIT]] could specify which rule you are disabeling so other stuff doesnt also become more ugly

2021-02-01 15:40 UTC, Larspolo commented on src/vue/src/store/modules/assignment.js
> +        return fn()
[Q] Can this now just be return `auth.update`? Would prefer that. Dont think it can use cache anyway

2021-02-01 15:40 UTC, Larspolo commented on src/vue/src/router/index.js
> +            store.commit('category/CLEAR_FILTERED_CATEGORIES')
[Q] Why is this not included in `            store.commit('assignmentEditor/RESET')`?

2021-02-01 15:40 UTC, Larspolo commented on src/vue/src/helpers/global_mixins.js
> +                return !invalid
[NIT] would prefer to swap the variable name in the foreach to valid and returning false when sth is invalid

2021-02-01 15:40 UTC, Larspolo commented on keep_testing.sh
>      stty size | perl -ale 'print "-"x$F[1]'
Although not touched in this PR, Preset DB doesn't work (anymore)

2021-02-01 20:02 UTC, engelhamer commented on src/vue/src/components/assignment_editor/timeline_controlled/assignment/AssignmentStartReadMode.vue
> +<template>
Was quite a fun bug: caused by the load wrapper. Moved it to a more appropriate position now.

2021-02-01 20:02 UTC, engelhamer commented on src/vue/src/components/assignment_editor/timeline_controlled/assignment/AssignmentEdit.vue
> +        save () {
Point 3 was the same reason as the other fade thing with assignment details (load wrapper). Fixed now.

2021-02-02 07:46 UTC, mjvkeulen commented on src/vue/src/components/category/CategoryEdit.vue
> +        },
Whereas I don't think I had this issue, I did find some propagation issues where drafts were stale. Could you confirm this is resolved? These are steps I took to resolve/test it manually, if you find something, mind adding the route to this list? Will save us time when extending the frontend checklist.

# Test AssignmentEditor

Global rules:

- Selecting a component shows a central view in "read-mode"
- Only "create new" buttons start in edit mode by default
- "create mode" views do not show a "delete button" and their edit button is shown as "preview" (when applicable)
- Can only enter "edit mode" from read mode via edit button
- Can only save from edit mode
- Deleting a currently active component -> Go to the default view (assignment details)
- When navigating away from a component that holds changes (made in edit mode) without saving, reselecting the component
should now start in edit mode, showing the unsaved changes.
- Making any changes should only trigger the visual dirty flag for that component, e.g. updating a template's categories
should not trigger dirty on the respective categories.

## Draft M2M propagation

### Template perspective

#### Single draft manipulations
- Select template -> Edit -> Add category -> Save -> Observe template added to category and category to template; nothing dirty
- Select template -> DELETE any associated category directly via menu -> Observe draft is updated without dirty set; template component view remains active

#### Double draft manipulation
- Select template -> Edit -> Add 1 to name -> Select category -> Edit -> Add previous template -> Save -> Revisit template ->
- Remove 1 from name -> Observe no longer dirty -> Save -> Observe both template and category are not dirty.

### Category perspective

#### Single draft manipulations
- Select category -> Edit -> Add template -> Save -> Nothing is dirty -> Select added template -> Observe category is added; Template is not dirty
- Select category -> DELETE any associated template directly via menu -> Observe draft is updated without dirty set; category component view remains active

#### Double draft manipulation
- Select category -> Edit -> Add 1 to name -> Select template -> Edit -> Add previous category -> Save -> Revisit category ->
Remove 1 from name -> Observe no longer dirty -> Save -> Observe both template and category are not dirty

### TODO/Order
- Create a new assignment (without categories)
    - Observe: Timeline filter hidden; Categories menu collapsed (Create New Category is not visible); Template edit "fixed categories" option hidden
    - Add 1 category -> All above becomes visible
- Tests for timeline filter as one edits the assignment

2021-02-02 07:47 UTC, mjvkeulen commented on src/vue/src/components/category/CategoryEdit.vue
>              />
I added the requested information, including a tooltip that the visual tag of the category is how most of the users will see the category.

![image](https://user-images.githubusercontent.com/39912610/106568234-4e84de00-6533-11eb-9bd0-0015f52befd8.png)

2021-02-02 08:33 UTC, mjvkeulen commented on src/vue/src/components/assignment_editor/timeline_controlled/preset_node/PresetNodeEdit.vue
> +            />
The issue purely issues with syncing state across different objects frontend. This is slightly complicated as a template update can in fact create a new template (old archived, new version is created). Which needs to be synced with both the categories data and preset node forced templates.

Since most was kept sync already, this should be fixed in 457168fe6711b735ac4cc7cb34742bbcb4676127

2021-02-02 08:33 UTC, mjvkeulen commented on src/vue/src/components/assignment_editor/timeline_controlled/preset_node/PresetNodeEdit.vue
> +                />
So was this resolved?

2021-02-02 08:36 UTC, mjvkeulen commented on src/vue/src/components/assignment_editor/timeline_controlled/preset_node/PresetNodeEdit.vue
> +                />
> What should the display be for attached files of a deadline preset node? Added a TODO for this point.

Still not sure what to do here, entry preview does not include attached files, your screenie only shows a progress goal, what should the read mode be of an entry deadline?

2021-02-02 08:37 UTC, mjvkeulen commented on src/vue/src/components/template/TemplateEditSettings.vue
> +            <!-- Question: @ Lars, hide this as well or hide nothing? -->
I assume this is resolved then @Larspolo and remove the question

2021-02-02 08:41 UTC, mjvkeulen commented on src/django/VLE/models.py
> +            raise ValidationError('One or more deadlines are locked after the assignment locks.')
How would you like to see your proposal applied to the following example? (Which I think reads quite naturally as is)
`Deadline locks before the assignment is due`

2021-02-02 08:42 UTC, mjvkeulen commented on src/django/VLE/models.py
> +            raise ValidationError('Unknown preset node type.')
Kinda sad it is basically circular imports blocking us from a gradual refactor right?

2021-02-02 08:45 UTC, mjvkeulen commented on src/django/VLE/serializers.py
> +    ]
You are right, I also think adding ordering to template (by 'name') means we can remove it anywhere where the default manager is used.

2021-02-02 08:48 UTC, mjvkeulen commented on src/vue/src/components/assignment_editor/timeline_controlled/assignment/AssignmentEdit.vue
> +                return
Is this regarding https://zube.io/ejourn-al/ejournal/c/1482 (Highlight validation errors in the timeline), or something other?

For example, I could make the mixin `validateData` (global_mixins.js), also set all validation states to false on validation (whereas they could possibly still be null instead (indicating neither pass or fail)).

2021-02-02 08:54 UTC, mjvkeulen commented on src/django/VLE/utils/file_handling.py
> +def copy_and_replace_rt_files(rich_text, user, assignment=None, category=None):
So currently it is used for `Assignment`, `Template`/`Field`, `PresetNode` and `Category`,

copy_rt_files_and_update_rt_references as new name? 

Content has both RT files and single content file fields, making it less suited to use this function (as it not just RT files).

2021-02-02 09:02 UTC, Larspolo commented on src/vue/src/components/assignment_editor/timeline_controlled/preset_node/PresetNodeEdit.vue
> +                />
I noticed later as well yeah. I think you could add the files component after the preset node description

2021-02-02 09:05 UTC, Larspolo commented on src/vue/src/components/assignment_editor/timeline_controlled/assignment/AssignmentEdit.vue
> +                return
No, thisis about some components that have a draft open to have an indication rhat they are open. We discussed rhis also in the scrum meeting

2021-02-02 09:09 UTC, Larspolo commented on src/django/VLE/utils/file_handling.py
> +def copy_and_replace_rt_files(rich_text, user, assignment=None, category=None):
copy_rt_files_and_update_rt_references wouldn't fix it. `copy_assignment_related_rt_files`? Because it doesn't work for course files, entry files, comment files, which also have rt

2021-02-02 09:27 UTC, mjvkeulen commented on src/django/VLE/utils/import_utils.py
> +    Category.objects.bulk_update(categories_with_copied_rt_description, ['description'])
This is related to the question I posed in assignment.py:

> There are a lot of steps which change assignment data, wrap the method in an atomic decorator?
This seems like it would be almost the desired default behavior for most of our logic
Worth spending some time looking into the advantages/disadvantages?

I believe it makes sense to wrap the entire `copy` assignment in a transaction block, it does not make sense to have half of a copied assignment ever. However, I still do not fully grasp the impact of the transaction block itself.

For example, if you use a transaction block and only execute read operations, nothing will be locked. If you do perform updates, I believe the full row is locked (not just the column of the updated fields), and I do not know if this lock lasts until the end of the entire transaction (I believe not, just until the end of the update), but I am not entirely sure. How this works is postgres (not Django) specific, and would require some research before I am fully comfortable using it in such large functions.

2021-02-02 09:28 UTC, mjvkeulen commented on src/django/VLE/utils/import_utils.py
> +    ]
I believe so, but that would also mean we hold all files open in memory, not sure if that is preferred? (memory and fd wise)

2021-02-02 09:31 UTC, mjvkeulen commented on src/django/VLE/views/assignment.py
> +    # Worth spending some time looking into the advantages / disadvantages?
So regarding the more general issue:

Do we want to invest some time into researching how postgres handles transactions by default? 
Do we want to make use of more transactions in the backend?

Move to issue?

2021-02-02 09:34 UTC, mjvkeulen commented on src/django/VLE/serializers.py
> +            'lti_id',
Id is read-only by default, I removed all ids from the read-only list in a refactor a couple of months ago.

2021-02-02 10:51 UTC, mjvkeulen commented on src/django/VLE/serializers.py
>              # Not used / missing: active_lti_id, lti_id_set, assigned_groups, format
So I am able to update an assignment's format via the serializer with this setting, so good catch (provided we have _floating_ format somehwere). 

I don't believe we require the format (pk) to be serialized to begin with, will simply remove format.

2021-02-02 10:53 UTC, mjvkeulen commented on src/django/VLE/views/assignment.py
> +        # Requires assignment with accurate pk
Yes, let's aggregate this discussion into an issue.

2021-02-02 12:49 UTC, mjvkeulen commented on src/django/VLE/views/preset_node.py
> +        return response.success({
Should be fixed backend in: 3ea2d6ddb7cfd5e3851235f6289ca5e33ecd4e6f
Frontend in: 029300694f30ef9cb88ead4a1c2b357a0e6e3097

2021-02-02 12:49 UTC, mjvkeulen commented on src/django/VLE/models.py
> +        # NOTE: First requires solution for live data
What would you like to see? Issue?

2021-02-02 12:55 UTC, mjvkeulen commented on src/django/VLE/utils/import_utils.py
> +    Category.objects.bulk_update(categories_with_copied_rt_description, ['description'])
Lets move the discussion here: https://zube.io/ejourn-al/ejournal/c/1486

2021-02-02 13:04 UTC, mjvkeulen commented on src/vue/src/components/template/TemplateImport.vue
> -                <category-display
Think we have this issue (if that covers it) https://zube.io/ejourn-al/ejournal/c/1466

2021-02-02 13:46 UTC, mjvkeulen commented on src/vue/src/components/assignment_editor/AssignmentEditorBreadCrumb.vue
> +<template>
I prefer compartmentalizing logic where possible, this is also how I started the `FormatEdit.vue` refactor. At the start `FormatEdit.vue` itself was 600 lines, including intro text scattered throughout even duplicated for the breadcrumb (as it appears twice). With the old breadcrumb taking up 15ish lines twice, whereas the current `AssignmentEditor.vue` template is 55 lines total.

This explains my initial approach, but now that the dust has settled does the assignment breadcrumb component hamper clarity / performs a false abstraction?

I don't believe so, at least not for the arguments u make here. What the assignment editor looks like functionally, is helped by the abstraction. You don't care about how the breadcrumb is structured / what styling is needed when looking at the assignment editor top down.

Later on, you make a valid point about a tour step being hidden, as it is now placed in a nested component. I believe this does show that the abstraction is leaky. Since we can't have multiple tour steps on the same component, I will flatten the structure to address this issue.

2021-02-02 14:02 UTC, mjvkeulen commented on src/vue/src/views/AssignmentEditor.vue
> -    <load-wrapper :loading="loading">
@engelhamer is this not desired behaviour? Wrapping all of the content in a single load wrapper prevents the need to sprinkle additional guards throughout the template. Improves readability, making the logic slightly simpler to follow?

2021-02-02 14:06 UTC, mjvkeulen commented on keep_testing.sh
>      stty size | perl -ale 'print "-"x$F[1]'
Are you sure? Preset DB requires an updated faker version

2021-02-02 14:08 UTC, mjvkeulen commented on src/django/VLE/views/assignment.py
> +    # Worth spending some time looking into the advantages / disadvantages?
https://zube.io/ejourn-al/ejournal/c/1486

2021-02-02 14:12 UTC, mjvkeulen commented on src/vue/src/components/assignment_editor/timeline_controlled/SelectedTimelineComponentSwitch.vue
> +    <div>
yes

2021-02-02 14:15 UTC, mjvkeulen commented on src/vue/src/components/assignment_editor/timeline_controlled/assignment/AssignmentEndReadMode.vue
> +                Edit
In read mode, you can see the end dates, e.g. lock date. Clicking edit will give you the opportunity to edit this.

2021-02-02 14:26 UTC, mjvkeulen commented on src/vue/src/store/modules/assignmentEditor.js
> +                template: '',
I don't know, I think this was extracted during the rework, template can prob be null

2021-02-02 14:38 UTC, mjvkeulen commented on src/vue/src/store/modules/assignmentEditor.js
> +                template: '',
![image](https://user-images.githubusercontent.com/39912610/106615288-9542fa00-656c-11eb-8c09-61798525eed6.png)

Makes use of `''` to show the default text, and `null` to show the nonselectable option.

2021-02-02 14:44 UTC, mjvkeulen commented on src/vue/src/store/modules/assignment.js
> +    update (context, { id, data, connArgs = auth.DEFAULT_CONN_ARGS }) { // eslint-disable-line
Would you prefer:
`line-of-logic` // eslint-disable-line object-curly-newline, max-len
`line-of-logic` // eslint-disable-line

Keep in mind line of logic can be lengthy

2021-02-02 14:46 UTC, mjvkeulen commented on src/vue/src/store/modules/assignment.js
> +        return fn()
All of the noncached functions can drop the `fn` wrapper. 

However, adding a cache, for example to prevent multiple clicks triggering multiple updates, requires a diff of two lines atm.

2021-02-02 14:48 UTC, mjvkeulen commented on src/vue/src/router/index.js
> +            store.commit('category/CLEAR_FILTERED_CATEGORIES')
The list of filtered categories transcends the assignment editor (filter active in any other view, e.g. journal)

2021-02-02 14:50 UTC, mjvkeulen commented on src/vue/src/helpers/global_mixins.js
> +                return !invalid
Imo an "invalid" check works well with the nature of a for `some` loop.

2021-02-02 16:14 UTC, Larspolo commented on src/vue/src/views/AssignmentEditor.vue
> +respective template setting "<i>Fixed Categories / Custom Categories</i>".
```
It is also possible to allow students to add other existing categories to an entry. This can be turned on via the respective template setting "<i>Fixed Categories / Custom Categories</i>".
```

2021-02-02 16:18 UTC, Larspolo commented on src/vue/src/views/AssignmentEditor.vue
> +    color: $theme-orange
![image](https://user-images.githubusercontent.com/11822478/106628914-92e79c80-657a-11eb-836e-460b7b9ca15e.png)
Dirty indicator is not for new stuff. Could be added / create an issue for it

2021-02-02 16:20 UTC, mjvkeulen commented on src/vue/src/views/AssignmentEditor.vue
> +    color: $theme-orange
Would be quite simple to add if you would like, not sure how to visually display it tho. E.g. what should the "dirty" state of the timeline add node look like?

2021-02-02 16:21 UTC, Larspolo commented on src/vue/src/components/template/TemplateMenuItem.vue
> +            :class="{ dirty: isTemplateDirty(template) }"
There is a bug with this indicator:
1. Click on template 1
2. Click edit,but do not edit anything
3. Click on template 2
4. Click edit
5. Edit sth and save
template 1 now has a dirty indicator, while it is not dirty

2021-02-02 16:22 UTC, mjvkeulen commented on src/vue/src/views/AssignmentEditor.vue
> +    color: $theme-orange
The new <X> undefined looks like it needs a fix tho

2021-02-02 16:25 UTC, mjvkeulen commented on src/vue/src/components/template/TemplateMenuItem.vue
> +            :class="{ dirty: isTemplateDirty(template) }"
Can not reproduce? :/

2021-02-02 16:26 UTC, Larspolo commented on src/vue/src/components/category/CategoryEdit.vue
> +        },
> Could you confirm this is resolved?

Can confirm the problem is solved, however, a new (I think closely related) problem occures now:

1. Edit template name that contains at least 1 category (also save)
2. Edit category name that is related to that template (also save)
3. View that the template now becomes dirty, this should not be the case

2021-02-02 16:28 UTC, Larspolo commented on src/vue/src/components/category/CategoryEdit.vue
> +        },
Select template -> Edit -> Add 1 to name -> Save -> Select related category -> Edit -> Add 1 to name -> Save -> Observe template becomes dirty

2021-02-02 16:49 UTC, Larspolo commented on src/vue/src/components/assignment_editor/timeline_controlled/preset_node/PresetNodeEditSelectAndPreviewTemplate.vue
> +                        {{ (showTemplatePreview) ? 'Hide Preview' : 'Show Preview' }}
Preview button can now be (re)moved as it shows more then just the template. Maybe like the template creation a preview btn top right? Otherwise a removal is also fine imo

2021-02-02 16:52 UTC, Larspolo commented on src/vue/src/components/assignment_editor/timeline_controlled/preset_node/PresetNodeEdit.vue
> +            />
Managed to reproduce it once, but can no longer, small enough issue RN for me to leave it be

2021-02-02 17:07 UTC, Larspolo commented on src/vue/src/store/modules/assignment.js
> +    update (context, { id, data, connArgs = auth.DEFAULT_CONN_ARGS }) { // eslint-disable-line
First one, if its too long, you can do `// eslint-disable-next-line object-curly-newline, max-len`

2021-02-02 19:01 UTC, mjvkeulen commented on src/vue/src/components/category/CategoryEdit.vue
> +        },
> Edit template name that contains at least 1 category (also save)
Edit category name that is related to that template (also save)
View that the template now becomes dirty, this should not be the case

Could not reproduce this following the given steps.

2021-02-02 19:04 UTC, mjvkeulen commented on src/vue/src/components/category/CategoryEdit.vue
> +        },
> Select template X -> Edit -> Add 1 to name -> Save -> Select related category -> Edit -> Add 1 to name -> Save -> Observe template X becomes dirty

This happens only if an entry deadline exists which makes use of the template. Not sure why, will look into this.

2021-02-02 20:36 UTC, engelhamer commented on src/vue/src/views/AssignmentEditor.vue
> -    <load-wrapper :loading="loading">
I think that this is desired behaviour: the load wrapper itself is a transition which fades-out the content on changing conditions. This should be used for portions of the app that require longer loading than others, but is not desired for whole router-pushed components because of the bug we saw.

2021-02-02 20:37 UTC, engelhamer commented on src/django/VLE/models.py
> +            raise ValidationError('One or more deadlines are locked after the assignment locks.')
`Deadline has a lock date before the assignment due date`

2021-02-02 20:38 UTC, engelhamer commented on src/django/VLE/models.py
> +        # NOTE: First requires solution for live data
If you are not going to resolve this now an issue would be nice right?

2021-02-02 20:39 UTC, engelhamer commented on src/vue/src/components/template/TemplateImport.vue
> -                <category-display
I think it can be expanded to also support copying template categories then 👍

2021-02-02 23:48 UTC, engelhamer commented
![image](https://user-images.githubusercontent.com/39912581/106673569-140e5600-65b2-11eb-826d-77eeb7e26fbd.png)

Creating a new LTI assignment fails due to a date error.

2021-02-03 10:10 UTC, mjvkeulen commented
> Creating a new LTI assignment fails due to a date error.

Fixed in fac353c9dd713cdbbe69feddd97e836ba25e19f5 (showing a wider problem, also resulting in ea1ad1bee3d2cb7fd5bfe5b34bd1edede361993e)

2021-02-03 19:15 UTC, engelhamer commented
![image](https://user-images.githubusercontent.com/39912581/106796887-3eb4e900-665c-11eb-9e15-c2660ff1b22e.png)

Clicking 'add deadline' gives a back end error rather than the validation label. Only when the 'due date' input is clicked the validation line is shown, and clicking 'add deadline' then does give the right user-friendly error.

![image](https://user-images.githubusercontent.com/39912581/106797127-83d91b00-665c-11eb-86d3-eb1b86849839.png)

2021-02-03 19:17 UTC, engelhamer commented on src/vue/src/components/template/TemplateMenuItem.vue
> +            :class="{ dirty: isTemplateDirty(template) }"
I can't reproduce either (chrome)

2021-02-03 21:56 UTC, engelhamer commented
![image](https://user-images.githubusercontent.com/39912581/106814623-fa811300-6672-11eb-8588-098869d108f1.png)

There are no placeholders for an empty description or template list in the category display

2021-02-03 22:36 UTC, Larspolo approved these changes

2021-02-04 07:21 UTC, mjvkeulen commented on src/vue/src/views/AssignmentEditor.vue
> +    content: '\2022'
I like the dot!

2021-02-04 07:22 UTC, mjvkeulen commented on src/vue/src/views/AssignmentEditor.vue
> +    text-shadow: 0 0 6px rgba(232,167,35,0.5), 0 0 6px rgba(232,167,35,0.8)
Q) Are we sure about the shadow?

2021-02-04 07:29 UTC, mjvkeulen commented on src/vue/src/components/assignment/AssignmentDetails.vue
> -                    <template #append>
It seems to render fine without, but is this not the desired slot?

2021-02-04 07:36 UTC, mjvkeulen commented on src/vue/src/components/template/TemplateEditSettings.vue
> +            <!-- TODO CATEGORY: Invert the notion of 'fixed categories' in the back end? This seems more natural. -->
Should be simple as the term is unique, what is a clear term for free form categories?

2021-02-04 07:36 UTC, mjvkeulen commented on src/vue/src/components/template/TemplateEditSettings.vue
> +            <category-select
Can't wait till we flatten some of our UI

![image](https://user-images.githubusercontent.com/39912610/106860013-1c56b600-66c4-11eb-873e-5762a31c7d25.png)

2021-02-04 07:54 UTC, mjvkeulen commented on src/vue/src/components/template/TemplateEditSettings.vue
> +    <b-card class="no-hover">
Q) I thought we were moving away from the card in card layouts?

2021-02-04 07:54 UTC, mjvkeulen commented on src/vue/src/components/template/TemplateEditSettings.vue
> +        When disabled, this template can still be used for deadlines you add to the timeline.
Definitely looks better than the previous layout. 

We should consolidate our text with options menus into a reusable component. For example, it makes sense if the profile page uses the same component where applicable for a more uniform style:

![image](https://user-images.githubusercontent.com/39912610/106861386-faf6c980-66c5-11eb-8b7b-f7db0ed98aa3.png)

![image](https://user-images.githubusercontent.com/39912610/106861469-16fa6b00-66c6-11eb-9ae6-fe7cc6fecdd5.png)

2021-02-04 07:54 UTC, mjvkeulen commented on src/vue/src/components/template/TemplateEditSettings.vue
> -                    <b-button
Q) When do we prefer toggle buttons (True and False both visible), over a button which shows the current state:

![image](https://user-images.githubusercontent.com/39912610/106861733-735d8a80-66c6-11eb-902c-9f52bcdd6833.png)

The template edit menu now holds both.

2021-02-04 08:00 UTC, mjvkeulen commented on src/vue/src/components/assignment_editor/timeline_controlled/preset_node/PresetNodeEditSelectAndPreviewTemplate.vue
> +                {{ (templates.length === 0) ? 'Create a new template' : 'Or create a new template' }}
So currently we have:

1. + Create New Template
2. Enter desired template configuration
3. + Add Template
4. Template is saved and shown in read mode.

You would prefer to forgo the read mode, and take the user back to the state after step 1?

2021-02-04 08:08 UTC, engelhamer commented on src/vue/src/components/assignment_editor/timeline_controlled/preset_node/PresetNodeEditSelectAndPreviewTemplate.vue
> +                {{ (templates.length === 0) ? 'Create a new template' : 'Or create a new template' }}
I think yes, because they created the template in that context. There is also a preview button there so the view mode can be easily achieved

2021-02-04 08:09 UTC, engelhamer commented on src/vue/src/views/AssignmentEditor.vue
> +    text-shadow: 0 0 6px rgba(232,167,35,0.5), 0 0 6px rgba(232,167,35,0.8)
I think it attracts the attention a bit more like this

2021-02-04 08:10 UTC, engelhamer commented on src/vue/src/components/assignment/AssignmentDetails.vue
> -                    <template #append>
I think that the slot makes sense for e.g. email verification (enter email, then press verify button in slot to verify it). However, the publish toggle of the assignment is not an action that uses the input field (name) here.

2021-02-04 08:10 UTC, engelhamer commented on src/vue/src/components/template/TemplateEditSettings.vue
> +            <!-- TODO CATEGORY: Invert the notion of 'fixed categories' in the back end? This seems more natural. -->
`allow_custom_categories`?

2021-02-04 08:11 UTC, engelhamer commented on src/vue/src/components/template/TemplateEditSettings.vue
> +    <b-card class="no-hover">
In the next update, but for now I like the consistency between them.

2021-02-04 08:29 UTC, engelhamer commented on src/vue/src/components/template/TemplateEditSettings.vue
> -                    <b-button
This screenshot is a toggle button (only see the active state, click to toggle it). I think this is useful for when the button contains text, because it otherwise becomes too large. If there are multiple  options for which icons only would suffice (so true/false) we can show both.

2021-02-04 14:57 UTC, mjvkeulen commented on src/vue/src/components/template/TemplateEditSettings.vue
> +    <b-card class="no-hover">
I understand the separation, but I am not sure it always works:

![image](https://user-images.githubusercontent.com/39912610/106908714-d6b7de80-66ff-11eb-9301-911bcce717f5.png)

The card (for one field especially) breaks the uniformity of the editor. A simple solution would be to simply use form-groups with labels, and to remove the card:

![image](https://user-images.githubusercontent.com/39912610/106910491-90fc1580-6701-11eb-9264-c5e1baccdb94.png)

I feel this is more consistent

2021-02-04 15:40 UTC, mjvkeulen commented on src/vue/src/components/assignment_editor/timeline_controlled/preset_node/PresetNodeEditSelectAndPreviewTemplate.vue
> +                {{ (templates.length === 0) ? 'Create a new template' : 'Or create a new template' }}
I misunderstood the question, but this commit introduces what you are after: https://github.com/eJourn-al/eJournal/pull/1081/commits/357f1ae698ce5245a349372ee4d1431031357e73

The user is returned to editing the deadline if he chose to create a template during that workflow.

2021-02-04 15:48 UTC, mjvkeulen commented on src/django/VLE/models.py
> +        # NOTE: First requires solution for live data
Z#1489

2021-02-04 16:10 UTC, mjvkeulen commented on src/django/test/factory/assignment.py
> +        kwargs['course_id'] = assignment.courses.first().pk
[NFN] Not used atm, and your proposal would always execute a query (even when the id is provided).

2021-02-04 16:16 UTC, mjvkeulen commented on src/vue/src/components/template/TemplateEditSettings.vue
> +            <!-- TODO CATEGORY: Invert the notion of 'fixed categories' in the back end? This seems more natural. -->
Could work, fixed_categories is enabled by default. Might be an indication the name is fine for how we use it?

2021-02-04 16:24 UTC, engelhamer commented on src/vue/src/components/template/TemplateEditSettings.vue
> +    <b-card class="no-hover">
Fine by me! More consistent indeed. We can update that for the other instances in the UI branch but change this one now

2021-02-04 16:26 UTC, engelhamer commented on src/vue/src/components/template/TemplateEditSettings.vue
> +    <b-card class="no-hover">
Only thing that looks odd to me is the placement of the button below the label, for ibputs that makes sense but a right floating element not so much in my opinion

2021-02-04 16:28 UTC, engelhamer commented on src/vue/src/components/template/TemplateEditSettings.vue
> +            <!-- TODO CATEGORY: Invert the notion of 'fixed categories' in the back end? This seems more natural. -->
We also have e.g. `allow_custom_journal_name` and `allow_custom_journal_image` both off by default right?

2021-02-04 22:11 UTC, mjvkeulen commented on src/vue/src/components/category/CategoryEdit.vue
> +            <b-form-row class="mb-2">
NIT, work with multi-form or better define rule if not last child default multi-form spacing?

2021-02-04 22:13 UTC, mjvkeulen commented on src/vue/src/components/category/CategoryEdit.vue
> +                <b-col cols="auto">
Q) Is column separation required if the input is of fixed width?

2021-02-04 22:17 UTC, engelhamer commented on src/vue/src/components/category/CategoryEdit.vue
> +            <b-form-row class="mb-2">
`multi-form` in effect is identical to `mb-2` and the latter is a default bootstrap class. In the UI branch I removed all so Ingot used to this.

2021-02-04 22:18 UTC, engelhamer commented on src/vue/src/components/category/CategoryEdit.vue
> +                <b-col cols="auto">
Yes, since the default behaviour is equal division of width

2021-02-05 07:15 UTC, mjvkeulen commented on src/vue/src/components/category/CategoryEdit.vue
> +            <b-form-row class="mb-2">
Moved it to a not last-child rule

2021-02-05 08:43 UTC, mjvkeulen commented on src/vue/src/components/template/TemplateEditSettings.vue
> +    <b-card class="no-hover">
I stashed this solution as I don't like how the floating buttons interact with the next input row on wide devices (the buttons are twice the height of our text, adding additional margin-bottom when the text fits on a single line)

2021-02-05 13:35 UTC, merged