Added a default template entry grade setting
eJourn-al/eJournal pull request #1093
Opened 2021-02-10 10:11 UTC by mjvkeulen

Added a template setting which can be used to speed up the grading process.

![image](https://user-images.githubusercontent.com/39912610/107495482-6e9a4a00-6b90-11eb-8ca6-ff006175575b.png)

![image](https://user-images.githubusercontent.com/39912610/107495382-4dd1f480-6b90-11eb-9df6-8d1a723d2a11.png)

![image](https://user-images.githubusercontent.com/39912610/107495319-3c88e800-6b90-11eb-9185-bf93fc2ebc94.png)

- Fixes Z#1469

2021-02-19 11:01 UTC, Larspolo approved these changes
Mostly would like to see the autofocus fixed, rest is working nice, and also looks good!

2021-02-19 11:01 UTC, Larspolo commented on src/vue/src/components/template/TemplateEditSettings.vue
> +            autofocus
I would not make this auto focused. If anything, make the title auto focused (or maaybe the first unfilled spot) This looks especially weird when creating a new template

2021-02-19 11:07 UTC, mjvkeulen commented on src/django/VLE/migrations/0080_default_template_grade.py
> +            field=models.FloatField(blank=True, null=True),
This only applies to char/text fields, where null can be represented by None or ''

2021-02-19 11:12 UTC, Larspolo commented on src/django/VLE/migrations/0080_default_template_grade.py
> +            field=models.FloatField(blank=True, null=True),
Then what does `''` do for float fields?

2021-02-19 12:24 UTC, mjvkeulen commented on src/django/VLE/migrations/0080_default_template_grade.py
> +            field=models.FloatField(blank=True, null=True),
What do you mean? `''` is an invalid data type for a float field?

2021-02-19 16:47 UTC, Larspolo commented on src/django/VLE/migrations/0080_default_template_grade.py
> +            field=models.FloatField(blank=True, null=True),
What does blank do for a float field? I thought `blank == ''`

2021-02-19 19:51 UTC, mjvkeulen commented on src/django/VLE/migrations/0080_default_template_grade.py
> +            field=models.FloatField(blank=True, null=True),
blank is Django's term for allowing a value that represents null. 

So null=True allows null values in the DB, but without blank=True will yield validation errors on data clean, e.g. serialize.is_valid when passed None values.

2021-02-28 20:16 UTC, engelhamer requested changes
Looks good, minor tweak needed.

2021-03-01 13:53 UTC, engelhamer approved these changes

2021-03-03 09:09 UTC, merged