Upgraded the user interface to a modern flat design
eJourn-al/eJournal pull request #1096
Opened 2021-02-13 02:19 UTC by engelhamer

## Description
Will be updated.

## Summary of changes
- Fixes #
- Fixes #
- ...

2021-04-27 06:45 UTC, mjvkeulen requested changes
Really looking forward to the UI release

Some minor revisions

2021-04-27 06:45 UTC, mjvkeulen commented on src/vue/src/components/timeline/Timeline.vue
> +                        @input="filterByCategory"
I believe this is a merge mistake?

2021-04-27 06:45 UTC, mjvkeulen commented on src/vue/src/main.js
> +            ][id % 5]
Q) Is the 5 over the list length on purpose?

2021-04-27 06:45 UTC, mjvkeulen commented on src/vue/src/sass/global.sass
> +    // background-color: #f9f9f9
tag

2021-04-27 06:45 UTC, mjvkeulen commented on src/vue/src/sass/global.sass
> +.border-1
Q) There are quite some border and radius classes here, would this help: https://getbootstrap.com/docs/4.0/utilities/borders/ ?

2021-04-27 06:45 UTC, mjvkeulen commented on src/vue/src/sass/partials/cards.sass
> +    border-radius: 10px
Q) Could we extract some of these 10s and 9s or is there no shared logic behind them?

2021-04-27 06:45 UTC, mjvkeulen commented on src/vue/src/sass/partials/text.sass
> +@import url('https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,400;0,700;1,400;1,700&display=swap')
I did not see this update elsewhere, e.g. in the text editor or some of our static html pages

2021-04-27 06:45 UTC, mjvkeulen commented on src/vue/src/views/Assignment.vue
> +            </div>
Just tagging one more of those shared no results found blocks

2021-04-27 06:45 UTC, mjvkeulen commented on src/vue/src/views/AssignmentEditor.vue
> +            </b-card>
Good candidate for its own component?

2021-04-27 06:45 UTC, mjvkeulen commented on src/vue/src/views/AssignmentEditor.vue
> +                })
Tagging (again?), I will move this to the module API to purge the deleted assignment from the local cache

2021-04-27 06:45 UTC, mjvkeulen commented on src/vue/src/views/CourseEdit.vue
> +                <b-tab v-if="$hasPermission('can_edit_course_details')">
I like the tabs approach!

Q) We don't have a safe to leave guard in place, for tab or route switching. I believe we did not have this in place before the ui updates either? Issue worthy?

2021-04-27 06:45 UTC, mjvkeulen commented on src/vue/src/views/Home.vue
> +            <b-table-simple
Q) Was there a reason for not using the default b-table? This comes with quite some advantages:
- Far less html (no need for stuff like `tr` and `th`, or for-loops in template)
- Some logic like alternating background for each row is built-in
- Provider function built in: uniform approach to "loading" state

I mean this list view is just 2 columns with a row for each course right?

2021-04-27 06:45 UTC, mjvkeulen commented on src/vue/vue.config.js
> +                    options[0].fileBlacklist.push(new RegExp(`.*${chunkName}.+?.js$`))
Q) I believe this is supposed to be the literal character match for period?

2021-04-27 14:20 UTC, engelhamer commented on src/vue/src/App.vue
> +    max-width: 1500px
The variable would be called `maxAppWidth` or something, and only be used here. Now it is 3 lines below the `#app` id in a css line that expresses its semantic exactly. I think it's fine like this.

2021-04-27 14:22 UTC, engelhamer commented on src/vue/public/favicon/site.webmanifest
> -            "src": "/favicon/android-chrome-36x36.png?v=3",
We now have the same favicon setup as on www.ejournal.app. This was auto-generated by some website.

2021-04-27 14:23 UTC, engelhamer commented on src/vue/src/FeedbackSection.vue
> +                this.$toasted.error('Please enter your message')
Yes, issue exists on Zube.

2021-04-27 14:24 UTC, engelhamer commented on src/vue/src/components/assets/BreadCrumb.vue
> +    hr
It is within the `breadcrumb-container` class, which is only used in the breadcrumb. Not generic.

2021-04-27 14:25 UTC, engelhamer commented on src/vue/src/components/assets/DeadlineDateDisplay.vue
> +    },
Only used in this file. I like having it here immediately rather than having to switch files..

2021-04-27 14:26 UTC, engelhamer commented on src/vue/src/components/assets/DeadlineDeck.vue
> +                class="text-grey small float-right unselectable cursor-pointer"
This is not just info, but a clickable text. Some different contexts require minor variations on this setup, and I have found that using these generic classess to express what you're after is very quick and easy.

2021-04-27 14:27 UTC, engelhamer commented on src/vue/src/components/assets/DeadlineDeck.vue
> +            &:nth-of-type(even)
This is purely for this deadline deck and thus not relevant for other instances. For tables we have `tables.sass` and the default bootstrap striped styling.

2021-04-27 14:28 UTC, engelhamer commented on src/vue/src/components/assets/ImageCropper.vue
> +            class="mt-2"
This is out-of-the-box bootstrap, which I prefer to use as much as possible. Don't you think a more uniform approach is actually beneficial?

2021-04-27 14:29 UTC, engelhamer commented on src/vue/src/components/assets/file_handling/FilesList.vue
> +    .pdf-viewer, img
That is right. I put it here such that both the PDF viewer and images in the files list will always be treated equally. Duplicating this same sass in their respective components would be harder to maintain.

2021-04-27 14:30 UTC, engelhamer commented on src/vue/src/components/assignment/JournalCard.vue
> +    <!-- TODO UI: :class="$root.getBorderClass(journal.id)" -->
Not yet decided on this: what do you think we should do with it?

2021-04-27 14:33 UTC, engelhamer commented on src/vue/src/components/assignment/ManageTeacherEntriesModal.vue
> +                </small>
Don't think it is worth the time at this point.

2021-04-27 14:34 UTC, engelhamer commented on src/vue/src/components/assignment/ManageTeacherEntriesModal.vue
> +                </small>
Maybe make an issue to update to form groups for each of these. Also: note that this messes with `v-if-else` constructions sometimes, which have to be rewritten.

2021-04-27 14:57 UTC, engelhamer commented on src/vue/src/components/assignment_editor/timeline_controlled/assignment/AssignmentDetailsEdit.vue
> +                class="red-button float-right"
`ml-auto` causes content below which is left-aligned to clear for this button on the far right. In this case it is not relevant since there is no other content in the header, but in other cases this is undesirable.

Also: `h2` headings like the one in this header are (inline) blocks, which are convenient to push following content that floats left to the next line, whilst allowing other stuff (like these buttons) to float on the right without much more styling.

2021-04-27 14:58 UTC, engelhamer commented on src/vue/src/components/assignment_editor/timeline_controlled/preset_node/PresetNodeTypeSelection.vue
> +                    Requires students to post an entry using a specified template.
That holds for both selection options, and has already been added to the info text in the timeline next to the add button. 'New deadline'.

2021-04-27 15:06 UTC, engelhamer commented on src/vue/src/components/course/CourseDetailEditor.vue
> +            return this.originalData !== null && JSON.stringify(this.course, this.replacer) !== this.originalData
Both ways are acceptable. This one also considers ordering (though that is not required here). Not worth rewriting also the parts where new db content is retrieved etc. IMO.

2021-04-27 15:07 UTC, engelhamer commented on src/vue/src/components/course/CourseMembersEditor.vue
>          </div>
Would require two slots, all just to replace this sequence of classes. Not beneficial in my opinion.

I don't like having to click through so many files especially for very short components like these.

2021-04-27 15:08 UTC, engelhamer commented on src/vue/src/components/course/CreateCourseModal.vue
>              :vModel="form.lti_id"
![image](https://user-images.githubusercontent.com/39912581/116265135-2a741a00-a77b-11eb-9fc4-44aadf437dd9.png)

Thanks for the contribution!

2021-04-27 15:09 UTC, engelhamer commented on src/vue/src/components/course/CreateCourseModal.vue
> +        },
Called from outside.

2021-04-27 15:12 UTC, engelhamer commented on src/vue/src/components/course/CreateCourseModal.vue
> +        },
This is required since the component is in another file. When calling `this.refs['createCourseRef'].hide()` from another file, it is required that the component has such function (even if it just passes it on to the `b-modal` instance that is there as the only element).

Another downside of nesting components too much.

2021-04-27 15:12 UTC, engelhamer commented on src/vue/src/components/entry/EntryNonStudent.vue
> +                        scale="0.8"
When it is within a `small` text environment.

2021-04-27 15:12 UTC, engelhamer commented on src/vue/src/components/entry/EntryNonStudent.vue
> +                        scale="0.8"
Or e.g. a div with that class

2021-04-27 15:15 UTC, engelhamer commented on src/vue/src/components/journal/EditJournalModal.vue
> +        },
No, since these modals are not just opened and closed from a button but by scripts.

2021-04-27 15:16 UTC, engelhamer commented on src/vue/src/components/journal/JournalDetails.vue
> +        <!-- Use -->
You know, Use!

2021-04-27 15:17 UTC, engelhamer commented on src/vue/src/components/journal/JournalDetails.vue
> +                @click="showModal('editJournalModal')"
No, since it should also happen on non-click events (such as saving the new settings).

2021-04-27 15:19 UTC, engelhamer commented on src/vue/src/components/journal/JournalImportModal.vue
> +            </div>
In appearance, yes. In text, no.

Consider a component. It would looke like this:
![image](https://user-images.githubusercontent.com/39912581/116267448-b63a7600-a77c-11eb-8d41-2e9982640dfa.png)

Lines saved: 1
Layers of abstraction added: 1

Not worth imo.

2021-04-27 15:20 UTC, engelhamer commented on src/vue/src/components/journal/JournalStudent.vue
> +                        This preset is locked. You cannot submit an entry at the moment.
Updated.

2021-04-27 15:23 UTC, engelhamer commented on src/vue/src/components/lti/LtiCreateLinkAssignment.vue
> +// Todo: rename file to modal (Webpack does not resolve this change for some reason)
![image](https://user-images.githubusercontent.com/39912581/116267996-2cd77380-a77d-11eb-8cd7-9edb8179ea8e.png)

Still doesn't work: you can see that it exists in the sidebar, but it does not compile. Without `Modal` in the name it works fine.

Any idea?

2021-04-27 15:29 UTC, engelhamer commented on src/vue/src/components/template/TemplateEditSettings.vue
> +            </small>
Yes.

2021-04-27 15:33 UTC, engelhamer commented on src/vue/src/main.js
> +            ][id % 5]
Not used atm. This was written for the assignment page with all student journal borders.

Keep this (and remove the magic number) or discard? I'd do the latter for now.

2021-04-27 15:37 UTC, engelhamer commented on src/vue/src/sass/partials/cards.sass
> +    border-radius: 10px
Cards have a 10px border, other things that are round mostly 5 (buttons etc).

2021-04-27 15:41 UTC, engelhamer commented on src/vue/src/views/AssignmentEditor.vue
> +            </b-card>
Seems fine to move indeed. Can be done at the same time of the store purge change?

2021-04-27 15:41 UTC, engelhamer commented on src/vue/src/views/AssignmentEditor.vue
> +                })
👍

2021-04-27 15:41 UTC, engelhamer commented on src/vue/src/views/CourseEdit.vue
> +                <b-tab v-if="$hasPermission('can_edit_course_details')">
Not used often, but good to make issue indeed.

2021-04-27 15:44 UTC, engelhamer commented on src/vue/src/views/Home.vue
> +            <b-table-simple
But they do not support the extent of customization required for e.g. the router link as title (to allow middle mouse button click to open in new tab), clickable row for regular navigation, badge display, etc.

Mostly just plain text.

2021-04-27 15:46 UTC, engelhamer commented on src/vue/vue.config.js
> +                    options[0].fileBlacklist.push(new RegExp(`.*${chunkName}.+?.js$`))
ESLint marked it as an unnecessary escape char. How should this be formatted within the string to maintain the regex capabilities? Escape the slash?

2021-04-27 20:05 UTC, mjvkeulen commented on src/vue/src/views/Home.vue
> +            <b-table-simple
They offer slots for each column with the row values available?

2021-04-27 20:08 UTC, mjvkeulen commented on src/vue/public/favicon/site.webmanifest
> -            "src": "/favicon/android-chrome-36x36.png?v=3",
I meant I see some variants here like 32x32 which are added as files in this PR: src/vue/public/favicon/favicon-32x32.png, but these are not listed here?

2021-04-27 20:08 UTC, mjvkeulen commented on src/vue/public/favicon/site.webmanifest
> -            "src": "/favicon/android-chrome-36x36.png?v=3",
Ah these are listed in index.html

2021-04-28 09:02 UTC, mjvkeulen commented on src/vue/src/components/journal/JournalImportModal.vue
> +        </info-component>
Some debugging code?

2021-04-28 09:53 UTC, mjvkeulen commented on src/vue/src/components/assets/ImageCropper.vue
> +            class="mt-2"
I don't see how using a bootstrap shorthand for margin-top-x brings uniformity, that is my point exactly.

I would expect uniformity to come from defining a dimension variable which dictates form spacing. 

This variable is then used where applicable, or ideally in high level css such a form group and not last child etc. 

I consider moving mt-2 over some dimension variable a step backwards, would you agree?

2021-04-28 09:56 UTC, mjvkeulen commented on src/vue/src/components/assignment/JournalCard.vue
> +    <!-- TODO UI: :class="$root.getBorderClass(journal.id)" -->
How did you feel about the left hand side only border @Larspolo proposed?

2021-04-28 09:57 UTC, mjvkeulen commented on src/vue/src/components/assets/file_handling/FilesList.vue
> +    .pdf-viewer, img
If you make a change in FileList.vue, that is quite hard to reason on. This context is not available. I am not sure this benefits maintainability in that sense

2021-04-28 10:02 UTC, mjvkeulen commented on src/vue/src/components/course/CreateCourseModal.vue
>              :vModel="form.lti_id"
Haha that's not fair, you are showing an automated linter commit :(

2021-04-28 10:14 UTC, mjvkeulen commented on src/vue/src/components/journal/EditJournalModal.vue
> +        },
That should form no obstacle: we can also emit an event for the modal to close (`$emit('bv::hide::modal', id)`). 

This allows you to adhere to the parent-child relationship and prevents the need for functions in the child which are not called in the same file.

2021-04-28 10:23 UTC, mjvkeulen commented on src/vue/src/components/journal/JournalImportModal.vue
> +            </div>
I thought the idea was that no results in list view are so similar a simple component like this would work:

![image](https://user-images.githubusercontent.com/39912610/116388633-509dc680-a81c-11eb-9ab7-383844f802c6.png)

Reducing the repetition, uniform styling (`p-4 text-center background-light-grey round-border`) etc?

2021-04-28 10:28 UTC, mjvkeulen commented on src/vue/src/components/lti/LtiCreateLinkAssignment.vue
> +// Todo: rename file to modal (Webpack does not resolve this change for some reason)
Fixed it here: https://github.com/eJourn-al/eJournal/pull/1096/commits/5cb71d7ce4c58f7ef57436b45ac9d96ad9f1f396

For some reason the capital L made the difference

2021-04-28 10:37 UTC, mjvkeulen commented on src/vue/src/components/course/CreateCourseModal.vue
> +        },
I think this is more of a fault in design patterns which can be fixed see the other comment.

2021-04-29 20:39 UTC, engelhamer commented on src/vue/src/components/assignment/JournalCard.vue
> +    <!-- TODO UI: :class="$root.getBorderClass(journal.id)" -->
Too colourful..

2021-04-29 20:40 UTC, engelhamer commented on src/vue/src/components/course/CourseMembersEditor.vue
>          </div>
Made the component, will be here soon.

2021-04-30 15:21 UTC, Larspolo approved these changes

2021-05-01 10:39 UTC, engelhamer commented on src/vue/src/components/assets/ImageCropper.vue
> +            class="mt-2"
No I would not. I prefer to use the bootstrap class over some additional class. It is more versatile and ensures that the fields and other content are equidistant both left-right and top-bottom.

2021-05-01 10:41 UTC, engelhamer commented on src/vue/src/components/course/CreateCourseModal.vue
> +        },
I think that this is really not worth the time at this moment since the current solution works fine.

2021-05-01 10:42 UTC, engelhamer commented on src/vue/src/components/journal/EditJournalModal.vue
> +        },
Bootstrap does not recommend this.

![image](https://user-images.githubusercontent.com/39912581/116780108-ae2f4e80-aa7a-11eb-9ca2-210f409d5ad8.png)

2021-05-01 10:44 UTC, engelhamer commented on src/vue/src/components/course/CreateCourseModal.vue
> +        },
Please reply to the other conversation since it is not useful having so many about the same issue.

2021-05-01 10:47 UTC, mjvkeulen commented on src/vue/src/components/journal/EditJournalModal.vue
> +        },
This example does not hold, you do not have access to the modal reference. Instead, you access a child method from the parent which in turn calls a reference to the modal.

The child method never being called in the component itself breaks the encapsulation. I believe it is for such scenario's you can emit something from the parent instead.

2021-05-01 11:03 UTC, mjvkeulen commented on src/vue/src/store/modules/timeline.js
> +        startInEdit: false,
I don't believe the timeline module is an ideal candidate to store entry state

2021-05-01 11:05 UTC, engelhamer commented on src/vue/src/components/journal/EditJournalModal.vue
> +        },
What do you think the actual bootstrap code looks like? That is also a component which offers these methods without them being called in the component itself right? Since our component here is just a wrapper, I only find it sensible to offer the same methods. Just like we do with the `ThemeSelect` component (as wrapper around the `vue-multiselect`).

2021-05-01 11:31 UTC, mjvkeulen commented on src/vue/src/components/journal/EditJournalModal.vue
> +        },
> What do you think the actual bootstrap code looks like? That is also a component which offers these methods without them being called in the component itself right?

There a lot of such practices which hold for an external library: you do not know how the user will interact with your component so you simply offer some APIs. That does not hold for us, we know how our components are used?

Our `ThemeSelect` component does not hold any functions which are called from a parent right?

2021-05-01 16:14 UTC, mjvkeulen commented on src/vue/src/components/assets/ImageCropper.vue
> +            class="mt-2"
We are trying to lock down set behaviour: ensure uniform spacing between form elements. Versatility is not desired for this, it is actually problematic: imagine wanting to increase the spacing between form elements by 5 pixels. 

Because we now switch to a more "versatile" approach, this minor tweak requires manually checking all `mt-2` occurrences to decide whether these are used for form distance or for some other reason.

Similarly, `mt-2` carries no further meaning beyond some margins defined by bootstrap. So when making a change to a form (or some related component), it is not immediately obvious which class (or variable) should be used.

2021-05-01 16:22 UTC, engelhamer commented
The same holds for multi-form since it was also used on non-form elements
such as cards, buttons outside forms and the like.

Op za 1 mei 2021 18:14 schreef mjvkeulen ***@***.***>:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In src/vue/src/components/assets/ImageCropper.vue
> <https://github.com/eJourn-al/eJournal/pull/1096#discussion_r624530818>:
>
> > -            class="multi-form"
> +            class="mt-2"
>
> We are trying to lock down set behaviour: ensure uniform spacing between
> form elements. Versatility is not desired for this, it is actually
> problematic: imagine wanting to increase the spacing between form elements
> by 5 pixels.
>
> Because we now switch to a more "versatile" approach, this minor tweak
> requires manually checking all mt-2 occurrences to decide whether these
> are used for form distance or for some other reason.
>
> Similarly, mt-2 carries no further meaning beyond some margins defined by
> bootstrap. So when making a change to a form (or some related component),
> it is not immediately obvious which class (or variable) should be used.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/eJourn-al/eJournal/pull/1096#discussion_r624530818>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJQQJBMSQOBAXIYMTZP3NOLTLQSHJANCNFSM4XRU5WAA>
> .
>

2021-05-01 21:34 UTC, mjvkeulen approved these changes

2021-05-01 21:35 UTC, merged