Speedup publishing all grades
eJourn-al/eJournal pull request #1102
Opened 2021-02-25 14:15 UTC by Larspolo

## Description
Moved Entry & Grade to to (newer) way using the save & bulk create functions. This is among others for to improve the speed up publishing al grades

## Summary of changes
- Fixes Z#1355
- Fixes Z#1562

2021-02-25 15:58 UTC, mjvkeulen requested changes
Much needed addition, hopefully the metrics will look a bit better soon.

I am missing a test which shows that the grading speedup was effective. A simple approach would be to show that the number of queries when publishing grades is (mostly) linear to the number of entries graded (including for group journals?).

2021-02-25 15:58 UTC, mjvkeulen commented on src/django/VLE/models.py
> +        for entry in entries:
[NIT]: Since we hold the list of updated grades (and their respective entries), we could work in reverse.

for grade in Grade.objects.filter(pk__in=[grade.pk for grade in grades]).select_related('entry')

And bulk update the entries from here (less complex)

2021-02-25 15:58 UTC, mjvkeulen commented on src/django/VLE/models.py
> +    def from_assignment(self, assignment):
[NIT]: Would for_x make more sense? As in, give me all grades for this assignment / journal.

2021-02-25 15:58 UTC, mjvkeulen commented on src/django/VLE/tasks/notifications.py
> +        published=True,  # Only generate notificaitons for published grades
[NIT]: notifications

2021-02-25 15:58 UTC, mjvkeulen commented on src/django/VLE/tasks/notifications.py
> +        for author in grade.entry.node.journal.authors.all():
[NIT]: for user in User.objects.filter(assignmentparticipation__journal__node__entry__grade=grade) (or I think you have to select related on all intermediate model accesses)

2021-02-25 15:58 UTC, mjvkeulen commented on src/django/VLE/models.py
> +    def only_unpublished(self):
[NIT]: unpublished?

2021-02-27 19:17 UTC, Larspolo commented on src/django/VLE/factory.py
> +    params = {}
Now the default stays to whatever the default of the save function is

2021-02-27 19:19 UTC, Larspolo commented on src/django/VLE/lti_grade_passback.py
> -from VLE.models import Counter
Circular dependencies.

Grading is imported in models now
In grading you use lti grade passback

[NIT] I think the [Q] prefix would be a better option for this

2021-02-27 19:19 UTC, Larspolo commented on src/django/VLE/models.py
> +        if is_new:
The longer you are in the transaction, the longer it is locked

2021-02-27 19:27 UTC, Larspolo commented on src/django/VLE/models.py
> +    def from_assignment(self, assignment):
Could, I find "give me all grades from this assignment / journal." about the same

2021-02-27 19:38 UTC, Larspolo commented on src/django/VLE/models.py
> +    def only_unpublished(self):
?

2021-02-27 20:19 UTC, Larspolo commented on src/django/VLE/tasks/notifications.py
> +        for author in grade.entry.node.journal.authors.all():
I tried to select all related, didnt work for authors, thats why thats not selected.

I also tried the suggestion, doesnt work, dunno why, but didnt check further

2021-02-27 20:20 UTC, Larspolo commented on src/django/VLE/models.py
> +    def bulk_create(self, grades, *args, send_grade_notifications=True, **kwargs):
Good one, moved it all inside except for notifications generation

2021-02-27 20:21 UTC, Larspolo commented on src/django/VLE/models.py
> +    def only_unpublished(self):
Gonna steal this thread to say that adding a test was useful. Found a select related that further reduced the query set

2021-03-01 09:07 UTC, mjvkeulen commented on src/django/VLE/models.py
> +        if is_new:
If new what could be locked? Also, logic wise there is a single call to offload to celery, execution time is minimal. (Was not a nit)

2021-03-01 09:09 UTC, mjvkeulen commented on src/django/VLE/models.py
> +    def only_unpublished(self):
Weird, I don't see any content either. But if I edit the comment the original content is visible:

[NIT]: `unpublished`?

2021-03-09 11:50 UTC, Larspolo commented on src/django/VLE/models.py
> +        if is_new:
[ONTOPIC] Fixed

[OFFTOPIC] Is this really more than a NIT though? Neither are wrong & both solutions have a reasoning behind it . This is mostly personal preference

2021-03-09 12:01 UTC, Larspolo commented on src/django/VLE/models.py
> +    def only_unpublished(self):
`only_unpublished` sounded more clear that it is a filter function

`Grade.objects.from_assignment(assignment).only_unpublished()`

vs

`Grade.objects.from_assignment(assignment).unpublished()`

2021-03-15 17:11 UTC, mjvkeulen reviewed
Could you slightly expand the added data in the test?

2021-03-15 17:11 UTC, mjvkeulen commented on src/django/test/test_assignment.py
> +        for _ in range(10):
Q) Why 10?

2021-03-15 17:11 UTC, mjvkeulen commented on src/django/test/test_assignment.py
> +        with assert_num_queries_less_than(len(queries_for_publishing_one_grade) + 1, verbose=True):
Q) Why + 1?

2021-03-15 17:11 UTC, mjvkeulen commented on src/django/test/test_assignment.py
> +            factory.Grade(published=False, entry__node__journal=journal)
Could you introduce an additional group journal here (with unpublished grades and more than one more member)

2021-03-19 14:09 UTC, engelhamer approved these changes

2021-03-19 14:09 UTC, engelhamer commented on src/django/test/test_assignment.py
> +        with assert_num_queries_less_than(len(queries_for_publishing_one_grade) + 1, verbose=True):
To also allow exactly the amount of queries for publishing one grade, using `assert_num_queries_less_than`?

2021-03-23 07:01 UTC, mjvkeulen commented on src/django/test/test_assignment.py
> +        with assert_num_queries_less_than(len(queries_for_publishing_one_grade) + 1, verbose=True):
`self.assertNumQueries` is a better fit for an exact match.

2021-04-25 15:38 UTC, Larspolo commented on src/django/test/test_assignment.py
> +        for _ in range(10):
Artbitrary

2021-04-25 15:42 UTC, Larspolo commented on src/django/test/test_assignment.py
> +            factory.Grade(published=False, entry__node__journal=journal)
Not group journal necessarily right? Added another grade from another journal

2021-04-25 20:31 UTC, mjvkeulen commented on src/django/test/test_assignment.py
> +            factory.Grade(published=False, entry__node__journal=journal)
A group journal with more than one author would test the scaling of the query bests. If this works then great your speedup rocks! 

If not I am fine with delaying fixing it seeing the popularity of group journals.

2021-04-26 11:28 UTC, mjvkeulen approved these changes

2021-05-02 16:20 UTC, mjvkeulen requested changes
Just pending model split merge

2021-06-18 14:48 UTC, mjvkeulen approved these changes

2021-06-18 14:48 UTC, mjvkeulen commented on src/django/VLE/views/grade.py
> -        grade = factory.make_grade(entry, request.user.pk, grade, published)
I like that we are removing the factory creation slowly

2021-06-19 10:20 UTC, Larspolo commented on src/django/VLE/tasks/notifications.py
> +        published=True,  # Only generate notifications for published grades
It is only called during creation, so that is not for archived grades

2021-06-19 10:26 UTC, Larspolo commented on src/django/VLE/models/entry.py
> +                Notification.objects.filter(entry=self, type=Notification.NEW_ENTRY).delete()
Added it

2021-06-19 10:27 UTC, Larspolo commented on src/django/VLE/models/grade.py
> +            VLE.models.Entry.objects.bulk_update(entries, ['grade_id'])
Sadly `.update` didnt seem to work with annotations

2021-06-19 10:51 UTC, mjvkeulen commented on src/django/VLE/models/grade.py
> +            VLE.models.Entry.objects.bulk_update(entries, ['grade_id'])
Do you remember the error, because this is not intended behaviour

2021-06-19 11:05 UTC, merged