Added preview of group journal student names when joining
eJourn-al/eJournal pull request #1113
Opened 2021-03-12 13:46 UTC by mjvkeulen

- Fixes Z#1572

2021-03-17 20:59 UTC, engelhamer requested changes

2021-03-17 20:59 UTC, engelhamer commented on src/django/VLE/views/journal.py
> +        if not (can_view_journal or is_assignment_participant):
This allows any member of a course (even without the `can_view_all_journals` permission to obtain the names of all people in the course (via enumerating journal `pk`s). I don't really like that change, and instead we should probably check whether this is a group assignment (only if that is the case we may allow this, but just for those users who can have a journal themselves or can view all journals).

2021-03-18 06:55 UTC, mjvkeulen commented on src/django/VLE/views/journal.py
> +        if not (can_view_journal or is_assignment_participant):
I don't believe that being able to see the names of other students in your assignment as a student is too forthcoming with information.

A reasonable example of this in practice is Canvas, where once given access to a course you can navigate to "people" and see a list of the course members.

2021-03-19 14:12 UTC, engelhamer commented on src/django/VLE/views/journal.py
> +        if not (can_view_journal or is_assignment_participant):
Yes, but that holds only for students. There are also examples of course designers which should not be able to see students at all.

There is no benefit or other reason to change this functionality right? Why not keep the more secure state?

2021-03-23 13:07 UTC, mjvkeulen commented on src/django/VLE/views/journal.py
> +        if not (can_view_journal or is_assignment_participant):
> Why not keep the more secure state?

We need to be less restrictive to allow students to see the members of a journal of which they are NOT (yet) a part of. 
can_view(journal) governs access to more than simply the current journal member's names.

We cannot tie this permission to `can_have_journal` as this API is used by both students and educators.

2021-03-23 13:31 UTC, engelhamer commented on src/django/VLE/views/journal.py
> +        if not (can_view_journal or is_assignment_participant):
Indeed we need to be less restrictive, but _only for group assignments_. Hence I stated in my initial comment:

> instead we should probably check whether this is a group assignment (only if that is the case we may allow this, but just for those users who can have a journal themselves or can view all journals)

2021-03-28 17:59 UTC, Larspolo requested changes

2021-03-28 17:59 UTC, Larspolo commented on src/vue/src/components/assignment/JournalCard.vue
> -            v-if="assignment.is_group_assignment && $hasPermission('can_manage_journals')"
I dont think this should be removed. At least it needs to stay a group assignment

2021-03-28 17:59 UTC, Larspolo commented on src/vue/src/components/assignment/JournalCard.vue
> -            v-if="assignment.is_group_assignment && $hasPermission('can_manage_journals')"
![image](https://user-images.githubusercontent.com/11822478/112762364-91c56f80-8fff-11eb-9172-bfa1503ed633.png)

Example of a non group assignment

2021-03-28 17:59 UTC, Larspolo commented on src/vue/src/components/journal/JournalMembers.vue
> +                        if (this.$route.name === 'Journal') {
[Q] when is this triggered?

2021-03-28 18:27 UTC, engelhamer approved these changes

2021-03-28 18:27 UTC, engelhamer commented on src/vue/src/components/journal/JournalMembers.vue
> +                        if (this.$route.name === 'Journal') {
When quitting a journal as a student, right?

2021-03-28 18:28 UTC, engelhamer commented on src/vue/src/components/assignment/JournalCard.vue
> -            v-if="assignment.is_group_assignment && $hasPermission('can_manage_journals')"
Indeed has to be resolved

2021-03-29 11:38 UTC, Larspolo commented on src/vue/src/components/journal/JournalMembers.vue
> +                        if (this.$route.name === 'Journal') {
*when is this NOT triggered

2021-03-30 08:06 UTC, mjvkeulen commented on src/vue/src/components/journal/JournalMembers.vue
> +                        if (this.$route.name === 'Journal') {
never

2021-03-30 09:38 UTC, Larspolo approved these changes

2021-03-30 15:12 UTC, merged