Refactored timeline UI selection to pass nodes instead of indices
eJourn-al/eJournal pull request #1117
Opened 2021-03-19 13:19 UTC by mjvkeulen

Pave the way for future timeline related issues such as

- Z#1561
- Z#1238

2021-03-19 15:52 UTC, engelhamer commented on src/vue/src/components/journal/JournalStudent.vue
> +            addNodeSymbol: 'timeline/addNodeSymbol', // Add node is serialized by the backend
Shall we add it front end like the start and end nodes? Or maybe only use the FAB anymore?

2021-03-19 15:52 UTC, engelhamer commented on src/vue/src/components/journal/JournalStudent.vue
> +            addNodeSymbol: 'timeline/addNodeSymbol', // Add node is serialized by the backend
This could be a good moment to include it in the refactor anyways?

2021-03-19 15:52 UTC, engelhamer commented on src/vue/src/components/timeline/TimelineNodeCircle.vue
> +            const idKey = (this.workingWithPresetNodes) ? 'id' : 'nID'
Why do we keep this distinction between `id` and `nID` anyways? Maybe it is worth changing that instead of using the `workingWithPresetNodes` prop?

2021-03-23 06:54 UTC, mjvkeulen commented on src/vue/src/components/journal/JournalStudent.vue
> +            addNodeSymbol: 'timeline/addNodeSymbol', // Add node is serialized by the backend
We could move to only using the FAB, this would take out the logic we have for the positioning of the add node. 

The add node is added backend, I believe this was for 2 reasons:
- Ensure the add node has access to the relevant templates. We now have access to the assignment/template store anyway, this would be simple to switch.
- The positioning of the add node is handled (and tested) backend. This is valid, especially due to the tests, but if we just move over to the FAB, this logic is no longer required.

@Larspolo opinion?

2021-03-23 07:23 UTC, mjvkeulen commented on src/vue/src/components/timeline/TimelineNodeCircle.vue
> +            const idKey = (this.workingWithPresetNodes) ? 'id' : 'nID'
Sure, probably keep `nID` as query param?

2021-03-23 07:54 UTC, mjvkeulen commented on src/vue/src/components/journal/JournalStudent.vue
> +            addNodeSymbol: 'timeline/addNodeSymbol', // Add node is serialized by the backend
What would do with the assignment editor? Having just a FAB there might be ambiguous?

2021-03-23 11:07 UTC, Larspolo commented on src/vue/src/components/journal/JournalStudent.vue
> +            addNodeSymbol: 'timeline/addNodeSymbol', // Add node is serialized by the backend
> Or maybe only use the FAB anymore?

I like it in the timeline, created the feeling of adding something to the timeline iso just submitting another thing. Same behavior for submitting unlimited & deadline entries

> The positioning of the add node is handled (and tested) backend.

Some frontend tests for this would sure be nice, as testing this manually is annoying

2021-03-23 11:09 UTC, Larspolo commented on src/vue/src/components/timeline/TimelineNodeCircle.vue
> +            const idKey = (this.workingWithPresetNodes) ? 'id' : 'nID'
Yeah, queryparam should be kept for also LTI. At least keep supporting nID as current submissions will still use that param.

I also tested if LTI still works, and it does :ok_hand:

2021-03-23 11:24 UTC, Larspolo commented on src/vue/src/components/entry/Entry.vue
> +        clearDraft () {
Cancle button does not clear draft atm, this means that the edited content still persists, when it shouldnt
1.
![image](https://user-images.githubusercontent.com/11822478/112138996-7e1aa300-8bd2-11eb-8108-329d15a1359a.png)
2.
![image](https://user-images.githubusercontent.com/11822478/112139014-84108400-8bd2-11eb-84e2-2ad589a1134f.png)
3.
Click Cancel and see (BUG):
![image](https://user-images.githubusercontent.com/11822478/112139037-8d99ec00-8bd2-11eb-88f1-597d4ff9e448.png)
4.
navigate forth and back to another node does not give a warning:
![image](https://user-images.githubusercontent.com/11822478/112139080-a0acbc00-8bd2-11eb-998e-c3bf33842523.png)

2021-03-23 11:45 UTC, Larspolo requested changes

2021-03-23 11:45 UTC, Larspolo commented on src/vue/src/components/entry/Entry.vue
>              // created is provided.
Title should be taken into account in the content. It currently isn't (neither for current deploy).

Either fix this now, or we should create an issue for it. Probably same for categories

2021-03-23 11:45 UTC, Larspolo commented on src/vue/src/components/entry/EntryNonStudent.vue
> +                        this.grade.published = entry.grade.published
[NIT] Would `this.grade = entry.grade` also work?

2021-03-23 11:45 UTC, Larspolo commented on src/vue/src/components/journal/JournalStudent.vue
> +            addNodeSymbol: 'timeline/addNodeSymbol', // Add node is serialized by the backend
Relevant issue:
https://zube.io/ejourn-al/ejournal/c/1140

2021-03-23 11:45 UTC, Larspolo commented on src/vue/src/store/modules/assignmentEditor.js
> -        selectedTimelineElementIndex: -1, /* See timeline.vue for mapping (due for refactor). */
Nice :)

2021-03-23 12:48 UTC, mjvkeulen commented on src/vue/src/components/entry/Entry.vue
>              // created is provided.
We have an outstanding issue for this already

2021-03-23 12:53 UTC, mjvkeulen commented on src/vue/src/components/entry/Entry.vue
> +        clearDraft () {
I believe we have an [issue](https://zube.io/ejourn-al/ejournal/c/1759) for the lacking navigation guard.

2021-03-23 12:59 UTC, mjvkeulen commented on src/vue/src/components/entry/Entry.vue
> +        clearDraft () {
The nonJournal naviagation guard (safeToLeave), is addressed in this PR, where previously the pending grade was not reset on component destroy but via a watcher on node change.

The clear draft guard logic is missing checks, but that is the status quo nor the point of this PR.

2021-03-23 13:37 UTC, engelhamer commented on src/vue/src/components/timeline/TimelineNodeCircle.vue
> +        workingWithPresetNodes () {
This property is not used anywhere in this component, right? Why do we need to add it here?

2021-03-23 13:39 UTC, engelhamer commented on src/vue/src/components/entry/Entry.vue
> +        clearDraft () {
Then make an issue for the cancel button @Larspolo?

2021-03-23 17:59 UTC, mjvkeulen commented on src/vue/src/components/timeline/TimelineNodeCircle.vue
> +        workingWithPresetNodes () {
Left over, will remove

2021-03-23 18:02 UTC, mjvkeulen commented on src/vue/src/components/timeline/TimelineNodeCircle.vue
> +        workingWithPresetNodes () {
I think you are on old commit or smth?

2021-03-23 20:06 UTC, Larspolo commented on src/vue/src/components/entry/Entry.vue
> +        clearDraft () {
I think thats introduced in this PR, as this function should also reset title to '' or null?

2021-03-25 07:16 UTC, mjvkeulen commented on src/vue/src/components/entry/Entry.vue
> +        clearDraft () {
Behaviour is identical to production (sadly), probably best to create an issue as this PR does not address this?

2021-03-27 09:52 UTC, Larspolo approved these changes

2021-03-30 08:13 UTC, engelhamer approved these changes

2021-03-30 13:48 UTC, merged