Added a filter for past deadlines
eJourn-al/eJournal pull request #1118
Opened 2021-03-21 13:15 UTC by mjvkeulen

![image](https://user-images.githubusercontent.com/39912610/111906170-931af900-8a4f-11eb-8b01-8eae7c70aa48.png)
![image](https://user-images.githubusercontent.com/39912610/111906181-a62dc900-8a4f-11eb-83e8-572975afd9b7.png)

The options menu probably requires some additional styling in combination with the upcoming UI rework.

- Fixes Z#1238

2021-04-12 10:50 UTC, Larspolo requested changes

2021-04-12 10:50 UTC, Larspolo commented on src/vue/src/components/timeline/Timeline.vue
> +                node.type === 'd'
Why is this not also considering passed progress goals / filled entries? Now I can (as a teacher):
1. go to journal 1 without the OLD entry filled
2. hide passed deadlines,
3. navigate to journal 2 with the OLD entry filled
4. Notice that the OLD progress node is hidden
5. Notice that I now can no longer unhide the hidden deadlines

![image](https://user-images.githubusercontent.com/11822478/114382070-390fde00-9b8c-11eb-8e3e-d04c6473acb6.png)

Would personally like to now be able to filter the "OLD" nodes

2021-04-12 10:50 UTC, Larspolo commented on src/vue/src/components/timeline/Timeline.vue
> +                </div>
Maybe sth for @engelhamer , but I find the styling of this a bit odd. Would expect it to left align with the "Timeline" heading. Also the shadow / border is now not alligned with other cards we have elsewhere

![image](https://user-images.githubusercontent.com/11822478/114382189-62306e80-9b8c-11eb-9e37-77acf03357ee.png)

![image](https://user-images.githubusercontent.com/11822478/114382200-665c8c00-9b8c-11eb-86be-1195c5167cfb.png)

2021-04-12 10:50 UTC, Larspolo commented on src/vue/src/components/timeline/Timeline.vue
> +        filterNodes () {
Would like some comment somewhere about what exactly gets filtered. Also maybe we need a difference between teachers & students.

Student -> hide progress nodes & filled entries
Teacher -> hide progress nodes & unfilled entries?

2021-04-23 12:48 UTC, mjvkeulen commented on src/vue/src/components/timeline/Timeline.vue
> +        filterNodes () {
I don't think we need to differentiate between student and teachers. Lets use the example of the JIR for someone redoing a year, a teacher would still like to be able to filter all the missed deadlines (which are irrelevant as the student imported them).

Can add a comment, but I would prefer making it obvious from the code instead.

2021-04-23 12:55 UTC, mjvkeulen commented on src/vue/src/components/timeline/Timeline.vue
> +                </div>
I believe this is addressed in the UI branch, the checkbox as is will fit quite well in the upcoming look.

2021-04-23 15:18 UTC, Larspolo commented on src/vue/src/components/timeline/Timeline.vue
> +        filterNodes () {
ATM I dont find it clear, having to look over multiple functions with many if's in each, but if you could make it more clear, I'm also fine with that. Think that having a comment somewhere on what to test when rewriting (parts of) this code would be usefull

2021-04-24 14:21 UTC, engelhamer approved these changes

2021-04-24 14:22 UTC, engelhamer commented on src/vue/src/components/timeline/Timeline.vue
> +        filterNodes () {
> Student -> hide progress nodes & filled entries

I would never want to filter posted entries (except for with the category filter). What do you meean by this?

2021-04-25 15:11 UTC, Larspolo approved these changes

2021-04-25 15:42 UTC, merged