Added drafts for student entries
eJourn-al/eJournal pull request #1122
Opened 2021-04-01 19:22 UTC by Larspolo

## Description
Added drafts for student entries
CREATION:
![image](https://user-images.githubusercontent.com/11822478/113343514-33b2c800-9330-11eb-92c7-2043e1e29406.png)

DISPLAY:
![image](https://user-images.githubusercontent.com/11822478/113343497-2dbce700-9330-11eb-900d-8ad5aae90144.png)

EDITING:
![image](https://user-images.githubusercontent.com/11822478/113343532-3a413f80-9330-11eb-8816-8b770c22b9db.png)

TIMELINE:
![image](https://user-images.githubusercontent.com/11822478/113343566-488f5b80-9330-11eb-87f4-d3ec73e28bcb.png)

## Summary of changes
- Fixes Z#62

2021-04-01 21:46 UTC, mjvkeulen requested changes
Nice swift PR!

- How does a user go about explicitly clearing or restoring a draft?
- Drafts should be autosaved saved so users can profit from this nice feature when they encounter an error or simply make a mistake by closing a tab or something

2021-04-01 21:46 UTC, mjvkeulen commented on src/django/VLE/factory.py
> +def make_entry(template, author, node, category_ids=None, title=None, is_draft=None):
It would be more straightforward to default `is_draft` to False (matching the DB default). None is not valid input and need not be considered as a value?

2021-04-01 21:46 UTC, mjvkeulen commented on src/django/VLE/models.py
> +        if not author or not self.authors.filter(user=author).exists():
Q) Why does the presence of author function as a check to exclude entry drafts? Should be adopted in the docstring, or a more sensible argument passed?

2021-04-01 21:46 UTC, mjvkeulen commented on src/django/VLE/models.py
> +        print(draft_before, self.is_draft)
Left over

2021-04-01 21:46 UTC, mjvkeulen commented on src/django/VLE/models.py
> +            draft_before = Entry.objects.get(pk=self.pk).is_draft
draft_before as a variable name to me implies a reference to an entry instance itself, possibly was_draft/is_draft instead?

2021-04-01 21:46 UTC, mjvkeulen commented on src/django/VLE/timeline.py
> +    if needs_add_node:
Q) How come the journal.assignment.is_locked() check can be omitted?

2021-04-01 21:46 UTC, mjvkeulen commented on src/django/VLE/views/entry.py
> +        node_id, category_ids, title, is_draft = utils.optional_typed_params(
Would it not make more sense to make is_draft a required param? An entry is either a draft or not, the backend can then always simply use the provided flag.

2021-04-01 21:46 UTC, mjvkeulen commented on src/django/VLE/views/entry.py
> +        if not entry.is_draft or not is_draft:
Q) Why does patch care about the current draft state of the entry? Does not only the requested state dictate whether validation should run?

2021-04-01 21:46 UTC, mjvkeulen commented on src/django/VLE/views/entry.py
> +        # Entries should not be able to be posted
Q) I don't quite follow the comment in regards to the code block?

2021-04-01 21:46 UTC, mjvkeulen commented on src/django/VLE/views/entry.py
> +            entry.is_draft = False
Making is_draft a required param would streamline such logic as well.

2021-04-01 21:46 UTC, mjvkeulen commented on src/django/VLE/views/journal_import_request.py
> +            source_entries = Entry.objects.filter(node__journal=jir.source, is_draft=False)
Would it make sense to let the default Entry manager exclude drafts? I believe this would make working with draft less error prone, as one has to always explicitly reason about working with draft entries or not, similar to how we work with journals?

2021-04-02 09:23 UTC, Larspolo commented on src/django/VLE/timeline.py
> +    if needs_add_node:
Moved to inside the can_add function

2021-04-02 09:24 UTC, Larspolo commented on src/django/VLE/views/entry.py
> +        node_id, category_ids, title, is_draft = utils.optional_typed_params(
Defaulted to nothing to easily implement it with existing tests and teacher entry creation/updating

2021-04-02 09:25 UTC, Larspolo commented on src/django/VLE/views/entry.py
> +        if not entry.is_draft or not is_draft:
is_draft param could be set to true when the entry is already not a draft anymore. This would omit the call, but in actual fact, it would still need to be validated because it is posted entry

2021-04-02 09:36 UTC, Larspolo commented on src/django/VLE/views/journal_import_request.py
> +            source_entries = Entry.objects.filter(node__journal=jir.source, is_draft=False)
Going to the case of excluding teacher journals. That is a way stronger case of them being excluded. Entry drafts imo should act like just any other entry, except for cases as needs_marking, notifications and JIR.

Also excluding it in the default manager, still exposes it to sth like Node.objects.filter(entry...) which is also used  often. 

I think even when by default excluded, we will still need to think about weather or not we want to include drafts

2021-04-02 09:45 UTC, Larspolo commented
> How does a user go about explicitly clearing or restoring a draft?

Its all the same as clearing or restoring any other entry

2021-04-02 09:47 UTC, Larspolo commented on src/django/VLE/factory.py
> +def make_entry(template, author, node, category_ids=None, title=None, is_draft=None):
Could, but `optional_params` would set it to None nonetheless. This would then still require more work

2021-04-02 09:49 UTC, Larspolo commented on src/django/VLE/models.py
> +        if not author or not self.authors.filter(user=author).exists():
Adopted in the docstring, its used to check "can_see_drafted_entries"

2021-04-02 13:44 UTC, mjvkeulen commented
>> How does a user go about explicitly clearing or restoring a draft?

> Its all the same as clearing or restoring any other entry

When a user saves a draft and then later wants to reset, I don't believe this is possible right now? Edit -> cancel would still restore to the latest draft state stored remotely as far as I understand it?

2021-04-02 13:46 UTC, mjvkeulen commented on src/django/VLE/views/entry.py
> +        node_id, category_ids, title, is_draft = utils.optional_typed_params(
is_draft should not be optional when posting an entry, a user always intentionally posts an entry as ready for submission or explicitly as a draft. This should be reflected here.

2021-04-02 13:47 UTC, mjvkeulen commented on src/django/VLE/views/entry.py
> +        node_id, category_ids, title, is_draft = utils.optional_typed_params(
The benefit is that we also don't have to deal with None as a possible value. 

I hope fixing this in the tests should be as straightforward as adding one field to the entry params factory.

2021-04-02 13:51 UTC, mjvkeulen commented on src/django/VLE/models.py
> +        if not author or not self.authors.filter(user=author).exists():
The can_see_drafted_entries makes a lot of sense. 

Possibly move this out of this function as it does not align with getting sorted nodes? A solution would be to apply the exclude on the return value directly and keep this function pure.

2021-04-02 13:58 UTC, mjvkeulen commented on src/django/VLE/views/entry.py
> +        if not entry.is_draft or not is_draft:
So this is an interesting situation, did you block a user from saving a new draft when editing an already posted entry?

When a student now edits an entry that has already been created, then saves its edit as a draft. What does the teacher see? Is this combination not possible?

2021-04-02 15:16 UTC, Larspolo commented
> When a user saves a draft and then later wants to reset, I don't believe this is possible right now? Edit -> cancel would still restore to the latest draft state stored remotely as far as I understand it?

With the delete button bottom left. Is a name change to "discard draft" wanted?

2021-04-02 15:27 UTC, Larspolo commented on src/django/VLE/views/entry.py
> +        if not entry.is_draft or not is_draft:
> did you block a user from saving a new draft when editing an already posted entry?

No, only entries that are already un-drafted (aka posted) cannot be re-drafted

2021-04-02 15:29 UTC, Larspolo commented on src/django/VLE/views/entry.py
> +        node_id, category_ids, title, is_draft = utils.optional_typed_params(
Fixed by allowing `optional_typed_params` to also take defaults as a thrid value, now it never is `None`. I like the API not needing a draft value, where it will be undrafted by default

2021-04-02 15:40 UTC, Larspolo commented on src/django/VLE/models.py
> +        if not author or not self.authors.filter(user=author).exists():
> Can we encapsulate that in the manager/queryset?

I dont see where / how exactly. Moved it to a separate function.

2021-04-23 13:17 UTC, mjvkeulen commented
To summarize critique and earlier discussions:

- _Entry drafts should be auto-saved_: this will help users who encounter an error / close the tab by accident etc.
We agreed to implement this at a later date.

- _It is not possible to create a draft as an improvement to an already submitted entry_. E.g. a teacher marks an entry for improvement, a student can no longer use the draft functionality to improve his/her submission.
I believe we agreed to implement this at a later date?

- _The action of saving a draft should not take the user out of edit mode_. It is likely they might want to save now, but continue editing their work.
Under discussion

- Builds on point 2: _Users should be presented with a (subtle) indication that their draft is saved_ (it is now safe to leave the page without posting the entry)
![image](https://user-images.githubusercontent.com/39912610/115875422-7ce4cc00-a445-11eb-91c5-d89551a5e41a.png)
Under discussion

- _Discarding a draft should be explicitly communicated as such_. Currently, we still phrase discarding as a successful deletion. E.g. "Are you sure that you want to delete this entry?" and "Entry successfully deleted".

2021-04-23 13:44 UTC, mjvkeulen commented on src/django/VLE/views/entry.py
> +        node_id, category_ids, title, is_draft = utils.optional_typed_params(
I believe we disagree on this, and we now have a bit more complexity (but also more flexibility) with optional params with configurable defaults.

I am fine with resolving as is.

2021-04-23 15:24 UTC, Larspolo commented
I'm fine with implementing / discussing these points (preferably not over text), but atm it feels a lot like we are postponing a useful feature for students only because we want it more useful.

2021-04-29 17:57 UTC, engelhamer approved these changes

2021-04-29 17:57 UTC, engelhamer commented on src/django/VLE/models.py
> +        if not self.can_see_drafted_entries(user):
If `user` is not set the `can_see_drafted_entries` call also returns `False`, so the negation makes it so that drafts are included if no user is set. This contradicts the docstring, and I think it would be better to adhere to the situation described there.

2021-04-29 17:57 UTC, engelhamer commented on src/django/VLE/models.py
> +            was_draft = True
Also marks edited non-draft entries as `was_draft`.

i.e. create an entry, post it (no draft), edit it -> `was_draft` true.

2021-04-30 11:38 UTC, mjvkeulen commented
Discarding draft still triggers progress will not be saved if you leave warning

2021-04-30 11:39 UTC, mjvkeulen commented
It is possible to create a draft for an empty entry

2021-04-30 11:47 UTC, mjvkeulen commented on src/vue/src/components/entry/Entry.vue
> +                (!this.node || !this.node.entry || this.$_isEqual(this.newEntryContent, this.node.entry.content))
The entry title is not part of the entry content, so it is now possible to navigate away without warning after entering a title.

2021-04-30 16:02 UTC, mjvkeulen approved these changes

2021-04-30 16:16 UTC, merged