Added support for Kaltura via video embed
eJourn-al/eJournal pull request #1131
Opened 2021-04-23 09:12 UTC by mjvkeulen

A video field is added with all hosts enabled by default.

If Kaltura is an allowed host, the video input becomes a text area. This is to convey that more than a simple video link is expected:
![image](https://user-images.githubusercontent.com/39912610/115848107-cfad8c00-a423-11eb-8355-e885bbd56cac.png)
![image](https://user-images.githubusercontent.com/39912610/115848196-e8b63d00-a423-11eb-9289-fa520a9ad9fb.png)

Otherwise, the input remains a single line input as a simple video link is expected
![image](https://user-images.githubusercontent.com/39912610/115848556-49de1080-a424-11eb-808c-c693f7f7c7e2.png)
![image](https://user-images.githubusercontent.com/39912610/115848597-52364b80-a424-11eb-97de-a499c1957cb3.png)

If any validation errors occur during input the user is presented with an information icon which opens a modal for instructions:
![image](https://user-images.githubusercontent.com/39912610/115848926-accfa780-a424-11eb-8f73-e82480b78cd8.png)
![image](https://user-images.githubusercontent.com/39912610/115848972-b9540000-a424-11eb-9e7f-76bd51120623.png)

- Fixes Z#1480

2021-04-23 16:16 UTC, Larspolo requested changes
Looks good, just a few minor things, open for discussion

2021-04-23 16:16 UTC, Larspolo commented on src/django/test/test_utils.py
> +            '<iframe src="https://api.eu.kaltura.com/<anything_but_space_goes>" <any tags are allowed but not captured',
Although the current solution works, I would feel more save if we would remove/disallow any non iframe tag as well. Just in case we later on change sth / forget sth

2021-04-23 16:16 UTC, Larspolo commented on src/vue/src/components/entry/EntryVideoFieldDisplay.vue
> +                    return `https://www.youtube.com/embed/${youtubeId}?rel=0&amp;showinfo=0`
[Q] Why is "https://www.youtube.com/embed/" etc not also returned in the `parseYouTubeVideoID` function? If for no real reason, I would prefer to not have to add that here as well

2021-04-23 16:16 UTC, Larspolo commented on src/vue/src/components/entry/EntryVideoFieldInput.vue
> +<template>
Nice tutorial :)

2021-04-23 16:16 UTC, Larspolo commented on src/vue/src/components/entry/EntryVideoFieldInput.vue
> +                return 'Unknown video host selected, please contact us'
Would remove ", please contact us" in the placeholder tbh, doesnt really do much. Maybe "Your teacher has selected an invalid video host, if this issue persists, contact your teacher." as a warning somewhere

2021-04-24 06:33 UTC, mjvkeulen commented on src/django/test/factory/content.py
> +            return 'https://www.youtube.com/watch?v=lJMNA7UcpxE'
I will do so

2021-04-24 06:39 UTC, mjvkeulen commented on src/django/test/test_utils.py
> +            '<iframe src="https://api.eu.kaltura.com/<anything_but_space_goes>" <any tags are allowed but not captured',
The additional tags are part of the Kaltura embed code. As in, these will always be pasted by the user as part of the embed code. 

The regex specifically captures only the **src** attribute. However, it is important the regex only accepts the iframe embed code, because a default video link to a Kaltura resource link misses certain params which would allow the media to be played from another origin.

2021-04-24 06:41 UTC, mjvkeulen commented on src/vue/src/components/entry/EntryVideoFieldDisplay.vue
> +                    return `https://www.youtube.com/embed/${youtubeId}?rel=0&amp;showinfo=0`
I don't feel strongly about this, the function (as we have it currently), explicitly captures the video id from a valid YouTube url. What is wrong with the existing approach?

2021-04-24 06:59 UTC, mjvkeulen commented on src/django/test/factory/field.py
> +        return f'{Field.YOUTUBE},{Field.KALTURA}'
I could see the benefit of changing the DB field type to JSON or ARRAY.

2021-04-24 09:27 UTC, Larspolo commented on src/vue/src/components/entry/EntryVideoFieldDisplay.vue
> +                    return `https://www.youtube.com/embed/${youtubeId}?rel=0&amp;showinfo=0`
Because `parseYouTubeVideoID` does return the entire URL, mostly just consistency, not required

2021-04-24 09:29 UTC, Larspolo commented on src/django/test/test_utils.py
> +            '<iframe src="https://api.eu.kaltura.com/<anything_but_space_goes>" <any tags are allowed but not captured',
Would storing only the src part work as well? After it is stripped from the iframe tag

2021-04-24 09:53 UTC, mjvkeulen commented on src/django/test/test_utils.py
> +            '<iframe src="https://api.eu.kaltura.com/<anything_but_space_goes>" <any tags are allowed but not captured',
We could but I don't know exactly which of all these params (I experimented and the flashvars were relevant :() are required, so we would still have one ugly as link.

The regex is used to confirm that the user pastes the entire embed code (iframe and all), would you then use a different regex front and back?

If we use the same regex to parse the source from the embed code to strip, as we use to display the source anyway, there is no actual security gain.

2021-04-24 10:40 UTC, Larspolo approved these changes

2021-04-24 13:46 UTC, engelhamer commented on src/django/test/test_utils.py
> +            '<iframe src="https://api.eu.kaltura.com/<anything_but_space_goes>" <any tags are allowed but not captured',
Storing only source would make editing the entry confusing: the input is not the original embed paste anymore.

2021-04-24 13:46 UTC, engelhamer commented on src/vue/src/components/entry/EntryVideoFieldInput.vue
> +        <b-form-textarea
Would like to see a preview of the kaltura video maybe? Now it is a bit hard to tell what I am really embedding.

2021-04-24 13:47 UTC, engelhamer commented on src/vue/src/components/entry/EntryVideoFieldInput.vue
> +                        <li>Navigate to your Kaltura environment.</li>
Also because Kaltura is semi-whitelabel (no logo or name on the page, custom url, ..)

2021-04-24 13:52 UTC, engelhamer requested changes

2021-04-24 13:52 UTC, engelhamer commented on src/vue/src/components/template/TemplateField.vue
> +                <theme-select
I would like to see some text here also when something is selected. See e.g. the group filter on the assignment page.

2021-04-24 13:52 UTC, engelhamer commented on src/vue/src/components/template/TemplateField.vue
> +                <theme-select
Currently it's empty, and with both options selected by default the user may not know what this dropdown is for until they click on it.

2021-04-25 10:06 UTC, mjvkeulen commented on src/vue/src/components/entry/EntryVideoFieldInput.vue
> +            <icon
Field headings are optional, I moved the icon to the append slot of the input

2021-04-25 14:52 UTC, Larspolo commented on src/django/test/test_utils.py
> +            '<iframe src="https://api.eu.kaltura.com/<anything_but_space_goes>" <any tags are allowed but not captured',
True, but when editing, we could also re-add the <iframe> tags

2021-04-25 15:41 UTC, engelhamer commented on src/vue/src/components/entry/EntryVideoFieldInput.vue
> +        <b-form-textarea
@mjvkeulen how about this?

2021-04-25 20:13 UTC, mjvkeulen commented on src/vue/src/components/entry/EntryVideoFieldInput.vue
> +        <b-form-textarea
I am not sure here, a decent preview takes up quite some space. Our current process doesn't provide a preview either, and the addition of Kaltura as a supported video host does not change this. 

Possibly something to move to an issue if you feel strongly?

2021-04-25 20:14 UTC, engelhamer approved these changes

2021-04-25 20:15 UTC, engelhamer commented on src/vue/src/components/entry/EntryVideoFieldInput.vue
> +        <b-form-textarea
Okay, then maybr an issue for 'video embed preview'

2021-04-25 20:29 UTC, engelhamer approved these changes

2021-04-25 20:48 UTC, merged