Changed edit entry layout to display optional flag iso required
eJourn-al/eJournal pull request #1142
Opened 2021-05-04 11:42 UTC by Larspolo

## Description
OLD:
![image](https://user-images.githubusercontent.com/11822478/116998455-8b04d900-acde-11eb-9e4a-ea3753ce15aa.png)

NEW:
![image](https://user-images.githubusercontent.com/11822478/116998350-60b31b80-acde-11eb-9bb9-a3f06cba20bd.png)

- Fixes Z#1906

2021-05-07 13:03 UTC, engelhamer requested changes
I would propose using the same approach as the `required` css styling here, so with selectors and `:after`

2021-05-07 20:01 UTC, Larspolo commented
Done

2021-05-09 14:29 UTC, engelhamer commented
How about the other fields (why have a star for e.g. password forms etc, but optional here)?

Z#1906 is not fixed, since fields without a title are still not indicated as required or optional.

2021-05-09 18:22 UTC, Larspolo commented
I did not go over every input field we have, thag can be done as well, but was not the goal of this PR. 

This PR originated from the many users that fill it in even when not needed

There are two types of forms. One where all fields are expected to be optional unless stated otherwise, and one where all fields are ezpected to be required unless stated otherwise.  Entry fields are clearly taken as everything is required by the userbase. On the otherhand we have an assignment creation where the teacher ezcepts to not have to fill everything in, here a required star is imo more favourable

2021-05-09 18:32 UTC, Larspolo commented
> Z#1906 is not fixed, since fields without a title are still not indicated as required or optional.

It does, see the screenshot below (top to bottom inc title: optional, required, required, optional):
![image](https://user-images.githubusercontent.com/11822478/117583110-ae2bf000-b105-11eb-8a68-9d4e550d4a50.png)

2021-05-23 22:25 UTC, mjvkeulen commented on src/vue/src/sass/partials/text.sass
> +    &.optional::after
Move to class or duplicate and add to the .form-group (&.optional, &[optional]) block so we can use this with form groups as well.

Would this also allow you to remove some of the `<span class="field-heading optional">` blocks?

2021-05-25 11:31 UTC, Larspolo commented on src/vue/src/sass/partials/text.sass
> +    &.optional::after
I added it in the sass, but idk how/where that would reduce the span

2021-05-29 11:36 UTC, mjvkeulen approved these changes

2021-06-15 10:15 UTC, engelhamer approved these changes

2021-06-15 10:42 UTC, merged