Added auto-save for entry drafts
eJourn-al/eJournal pull request #1144
Opened 2021-05-06 15:58 UTC by Larspolo

## Description
Added the ability for students to auto save

## Summary of changes
- Fixes Z#1810

2021-05-06 19:29 UTC, mjvkeulen requested changes
Looking forward to this one!

Currently crashes when creating an entry for a deadline (does not even show entry component).

2021-05-06 19:29 UTC, mjvkeulen commented on src/django/test/factory/user.py
> +    full_name = factory.Faker('name')
Q) What was the difference?

2021-05-06 19:29 UTC, mjvkeulen commented on src/django/VLE/models.py
> +    auto_save_drafts = models.BooleanField(
I believe the user should not be confronted with a choice here, no need to add any complexity when auto-saving is just ideal behaviour for the user. 

If you insist on making this a setting: I propose moving this to the profile settings so the user not confronted with this option when posting an entry each time.

2021-05-06 19:29 UTC, mjvkeulen commented on src/vue/src/components/entry/Entry.vue
> +    },
You can combine this into a single watcher for three variables (unless deep conflicts with this somehow).

2021-05-06 19:29 UTC, mjvkeulen commented on src/vue/src/components/entry/Entry.vue
> +            deep: true,
Title is not a nested object so deep can be omitted

2021-05-06 19:29 UTC, mjvkeulen commented on src/vue/src/components/entry/Entry.vue
> +
How does the linter not detect this.

2021-05-06 19:29 UTC, mjvkeulen commented on src/vue/src/components/entry/Entry.vue
> +                    || this.title !== ''
Are you sure this still works for a preset entry where the template allows a custom title, but the teacher did specify a default display name?

2021-05-06 19:38 UTC, mjvkeulen commented on src/vue/src/components/entry/Entry.vue
> +                    this.autoSaveMessage = 'Saving...'
I think this is not visible as it is cleared on the next keypress. You should play around with the ordering here or clear the autoSaveMessage in a finally block of func

2021-05-06 19:52 UTC, Larspolo commented on src/django/test/factory/user.py
> +    full_name = factory.Faker('name')
non binary didnt work. Figured this was the quickest fix

2021-05-06 19:57 UTC, Larspolo commented on src/vue/src/components/entry/Entry.vue
> +                    this.autoSaveMessage = 'Saving...'
Thats on purpose. Wanted to not have a long "Saving...", Only when actually saving

2021-05-07 08:24 UTC, Larspolo commented on src/django/VLE/models.py
> +    auto_save_drafts = models.BooleanField(
Its not much of a confrontation, and some users have less internet and/or PC specs, think for those its nice to quickly turn it off

2021-05-07 08:25 UTC, Larspolo commented on src/vue/src/components/entry/Entry.vue
> +    },
How?

2021-05-07 08:31 UTC, Larspolo commented on src/vue/src/components/entry/Entry.vue
> +                    || this.title !== ''
Kinda, now it the student does not automatically start filling in the title, the teacher's title gets put into that field. On creation the title starts empty anyway. This could be changed, but that is kept default. Unless you want to check `this.title !== '' && this.title !== this.node.display_name` for the specific cases where the student copy pastes the original title and doesnt want to auto save the draft

2021-05-07 09:41 UTC, mjvkeulen commented on src/vue/src/components/entry/Entry.vue
> +    },
https://stackoverflow.com/questions/42737034/vue-js-watch-multiple-properties-with-single-handler

Again I don't know how deep will factor into this

2021-05-07 09:44 UTC, mjvkeulen commented on src/vue/src/components/entry/Entry.vue
> +                    this.autoSaveMessage = 'Saving...'
But currently, it does not show when actually saving afaik. That would require the autosave message to be cleared in the .then of the request itself?

2021-05-07 09:47 UTC, mjvkeulen commented on src/vue/src/components/entry/Entry.vue
> +                    this.autoSaveMessage = 'Saving...'
That makes sense

2021-05-07 10:02 UTC, Larspolo commented on src/vue/src/components/entry/Entry.vue
> +    },
The clean option is Vue 3 only. I think for the Vue 2, having a computed variable is not ideal either. Are you sure you want that solution?

2021-05-07 10:45 UTC, mjvkeulen commented on src/vue/src/components/entry/Entry.vue
> +    },
If this would become:

computed: newEntry (or autoSaveOnUpdate if we keep the pref)
watch
    newEntry: do stuff 

That seems fine with me, but it's not as clean as the Vue3 solution

2021-05-07 10:48 UTC, mjvkeulen commented on src/vue/src/components/entry/Entry.vue
> +                    : 'Entry successfully posted.' })
I believe if it's an autosave call the user should not see a toast. Again following the idea that auto-saving should be the default and as nondisruptive as possible

2021-05-07 10:52 UTC, mjvkeulen commented on src/vue/src/components/entry/Entry.vue
> +                        :class="{ 'input-disabled': !allowPreview }"
[NIT]: Add a little tooltip for why preview is disabled, eg. "Saving draft" or something similar.

2021-05-07 11:23 UTC, mjvkeulen commented on src/vue/src/components/entry/Entry.vue
> +    },
Lets leave it as a nit then!

2021-05-07 11:28 UTC, Larspolo commented on src/vue/src/components/entry/Entry.vue
> +                    : 'Entry successfully posted.' })
There is a lot of visual change: comment section is added, preview button is added, node is added to timeline.

This created the behaviour of not knowing what happened when I tested this with an end user. Thats why I added the toast, for when users do act suppriced, they have a toast to display them what happened. After this there are no toasts, because the visual change is also minimal (only the "saving..." / "saved" text)

2021-05-07 20:26 UTC, Larspolo commented on src/vue/src/components/entry/Entry.vue
> +                        :class="{ 'input-disabled': !allowPreview }"
When I attempted this, the tooltip kept showing when it was enabled again, so maybe if you know the fix we can add it, but else Im gonna leave it for now

2021-05-08 15:21 UTC, mjvkeulen commented on src/vue/src/components/entry/Comments.vue
> +        },
NIT: eID -> Entry object

2021-05-08 15:21 UTC, mjvkeulen commented on src/vue/src/components/entry/Entry.vue
> +                        :class="{ 'input-disabled': requestInFlight || create }"
Q) This reads as preview disabled when creating?

2021-05-08 15:21 UTC, mjvkeulen commented on src/vue/src/components/entry/Entry.vue
> +                }, this.create ? 1000 : 1000)
Left over from refactor (silly linter tbh)

2021-05-08 15:21 UTC, mjvkeulen commented on src/vue/src/components/template/TemplateCard.vue
> +            overflow: hidden
Prob have to cleanup/extract some of this css?

2021-05-08 15:21 UTC, mjvkeulen commented on src/vue/src/components/template/TemplateSelection.vue
> +    <div v-if="templates.length > 1">
NIT: I believe the div is not needed due to the v-if / else construct here

2021-05-09 14:11 UTC, engelhamer commented on src/vue/src/components/entry/Entry.vue
> +                            text: 'Submit',
Then change the button option letters too.

2021-05-09 14:12 UTC, engelhamer commented on src/vue/src/components/entry/Entry.vue
> +                            text: 'Submit',
However, we do say 'posting entries' everywhere

2021-05-09 14:13 UTC, engelhamer commented on src/vue/src/components/entry/Entry.vue
> +                        :class="{ 'input-disabled': requestInFlight || create }"
That's right and fine behaviour in my opinion.

2021-05-09 14:13 UTC, engelhamer commented on src/vue/src/components/template/TemplateCard.vue
> +            overflow: hidden
Doing that

2021-05-09 14:14 UTC, engelhamer commented on src/vue/src/components/template/TemplateSelection.vue
> +    <div v-if="templates.length > 1">
Template root cannot be a `template` tag and `v-if` cannot be combined with `v-for`, so I think this solution is the supposed setup.

2021-05-16 13:13 UTC, engelhamer approved these changes

2021-05-18 08:25 UTC, mjvkeulen approved these changes

2021-05-18 08:25 UTC, mjvkeulen commented on src/vue/src/components/assets/TextEditor.vue
> +        </b-card>
NIT: Makes sense to move this block into its own component. I can see us tweaking this to more closely resemble the RT editor in the future.

2021-05-18 08:25 UTC, mjvkeulen commented on src/vue/src/components/timeline/TimelineNodeCircle.vue
> +    left: -2px
NIT: Magic number fiesta

2021-05-21 18:13 UTC, engelhamer approved these changes

2021-05-21 18:47 UTC, mjvkeulen commented on src/vue/src/sass/partials/cards.sass
> +            top: -30px
Comment / variable?

2021-05-21 21:40 UTC, merged