Improved manage course groups experience
eJourn-al/eJournal pull request #1145
Opened 2021-05-11 15:47 UTC by mjvkeulen

- Increase the speed at which groups and their members load
- Added search functionality to both groups and if needed, members of the groups themselves
- Improved the edit course groups UI (more in line with the new UI, was due for an update)

![image](https://user-images.githubusercontent.com/39912610/117845484-e0159180-b280-11eb-8efa-c25d5ef15bfc.png)
![image](https://user-images.githubusercontent.com/39912610/117845211-a2186d80-b280-11eb-813f-0ff22aad54ec.png)
![image](https://user-images.githubusercontent.com/39912610/117845402-cbd19480-b280-11eb-9425-0010b5500bfb.png)

# Fixes
- Z#1918
- Z#1917

2021-05-11 17:31 UTC, Larspolo requested changes
Looking good!

2021-05-11 17:31 UTC, Larspolo commented on src/vue/src/components/course/CourseGroupEditor.vue
> +                'actions'
The filter icons look like they are for the field title on the left. Would prefer it to not be floated to the right, but instead directly after the title, especially with the large fields
![image](https://user-images.githubusercontent.com/11822478/117856788-5a97de80-b28c-11eb-987a-2b57e0928710.png)

2021-05-11 17:31 UTC, Larspolo commented on src/django/VLE/views/group.py
> +        })
This call could also be put into the list, with optional param being "get_members", and when it is true, we change the serializer. Less duplicate code & extend the functionality of this call.

2021-05-11 17:31 UTC, Larspolo commented on src/django/test/test_group.py
> +            assert len(group_data['members']) == len(group_usernames)
Missing assert messages

2021-05-11 17:31 UTC, Larspolo commented on src/django/test/test_group.py
> +            assert len(data) == 4, '4 groups exist and are serialized'
Missing the "why", why should 4 groups exist and be serialized? Why did you want to test this specifically?

2021-05-11 17:31 UTC, Larspolo commented on src/vue/src/components/course/CourseGroupEditor.vue
> +                    @click.native="row.toggleDetails"
I lose the overview too quick right now. I think this is caused by any of the following:
- There is no clear border between groups, this makes it unclear when one ends and the other starts
- There are borders within an opened groups, which for me act like thats where a new group starts
- There can be multiple opened groups at the same time, which cause for confusion for which you are editing in currently

I propose (any of) the following:
- Allow for only opened group
- Add a more visual separator between an opened groups and others (think: shadow, thicker border, and/or background colour change)

For reference:
![image](https://user-images.githubusercontent.com/11822478/117858222-f1b16600-b28d-11eb-89eb-5e3003992a77.png)

2021-05-11 17:31 UTC, Larspolo commented on src/vue/src/components/course/CourseGroupEditor.vue
> +        <b-table
[Q] Why is this table not iterating between white and gray background, and the inner one is?

2021-05-11 17:31 UTC, Larspolo commented on src/vue/src/components/group/GroupMemberEdit.vue
> +                'action',
[NIT] This action field is missaligned with the outer actions field. Not sure if intended or not, if not, I would prefer aligned action fields
![image](https://user-images.githubusercontent.com/11822478/117859097-e0b52480-b28e-11eb-98a5-04c15c43e9c8.png)

2021-05-11 17:31 UTC, Larspolo commented on src/vue/src/components/group/GroupMemberEdit.vue
> +                    this.group.members = this.group.members.filter((elem) => elem.id !== member.id)
Think `this.group = response.group` would be preferred, just in case something also also changed in the backend. This would then properly set those changes. Same goes for the other calls

2021-05-11 19:53 UTC, mjvkeulen commented on src/vue/src/components/course/CourseGroupEditor.vue
> +                'actions'
This is default bootstrap, I am not sure if this should be changed

2021-05-11 19:58 UTC, mjvkeulen commented on src/django/test/test_group.py
> +            assert len(group_data['members']) == len(group_usernames)
These are two checks where the assert msg is:  Data matches DB state. But adding them nonetheless

2021-05-11 20:01 UTC, mjvkeulen commented on src/vue/src/components/course/CourseGroupEditor.vue
> +        <b-table
Found this more confusing than helpful because of the nested table

2021-05-11 20:02 UTC, mjvkeulen commented on src/vue/src/components/group/GroupMemberEdit.vue
> +                'action',
These are nested tables, which should not align as these are not the same columns, or even part of the same table really. (also note column header spelling)

2021-05-12 10:13 UTC, Larspolo commented on src/vue/src/components/course/CourseGroupEditor.vue
> +                'actions'
I still found it confusing, think then others will find as well. What does @engelhamer think about it?

2021-05-12 10:23 UTC, Larspolo commented on src/vue/src/components/course/CourseGroupEditor.vue
> +                    @click.native="row.toggleDetails"
What do you propose?

> these are only expanded after explicit user interaction?

The difference here is that it is properly used when opening multiple groups, however, if the UI then becomes unclear because of proper use, we have a UI problem, not a "well dont do this then" problem. If the solution to unclear UI would be to close other groups, then I suggest doing that automatically. Its not often that a users wants to edit two groups at the same time anyway

2021-05-12 10:23 UTC, Larspolo commented on src/vue/src/components/group/GroupMemberEdit.vue
> +                'action',
Figured, I would still expect it to be at the same location, but this is fine by me then

2021-05-12 10:23 UTC, Larspolo commented on src/vue/src/components/group/GroupMemberEdit.vue
> +                    this.group.members = this.group.members.filter((elem) => elem.id !== member.id)
Sure, can be resolved, leaving it open for Engel to read

2021-05-12 12:52 UTC, mjvkeulen commented on src/vue/src/components/course/CourseGroupEditor.vue
> +                    @click.native="row.toggleDetails"
> Its not often that a users wants to edit two groups at the same time anyway

Searching for a user and looking at which groups they are a part of (including which other group members) seems like a good reason to allow multiple groups to display their members at the same time.

2021-05-12 19:04 UTC, Larspolo commented on src/vue/src/components/course/CourseGroupEditor.vue
> +                    @click.native="row.toggleDetails"
Fair, but then I would like to have a better divide, after opening up multiple, I quickly lose the overview

2021-05-13 07:00 UTC, mjvkeulen commented on src/vue/src/components/course/CourseGroupEditor.vue
> +                    @click.native="row.toggleDetails"
![image](https://user-images.githubusercontent.com/39912610/118090263-a3a17d00-b3c9-11eb-85f2-6128fbe1cdb2.png)

2021-05-20 12:41 UTC, Larspolo approved these changes

2021-06-19 12:45 UTC, engelhamer approved these changes

2021-06-19 12:45 UTC, engelhamer commented on src/vue/src/components/course/CourseGroupEditor.vue
> +                'actions'
Not bothered by it.

2021-06-19 12:45 UTC, engelhamer commented on src/vue/src/components/course/CourseGroupEditor.vue
> +                    @click.native="row.toggleDetails"
I like it.

2021-06-19 12:45 UTC, engelhamer commented on src/vue/src/components/group/GroupMemberEdit.vue
> +                'action',
Would still look  nicer if they were aligned. This is why I tend to use `b-table-simple`.

2021-06-19 13:02 UTC, merged