Improved email style compatibility
eJourn-al/eJournal pull request #1146
Opened 2021-05-11 18:06 UTC by engelhamer

## Description
Emails are now consistent with the rest of the design again. Also some issues related to display are now fixed.

Support:
![image](https://user-images.githubusercontent.com/39912581/117863285-e5c8a280-b293-11eb-98c4-b33592e50729.png)

Same, but in dark mode and other client (outlook):
![image](https://user-images.githubusercontent.com/39912581/117863382-ff69ea00-b293-11eb-8f45-a4d97f0061a8.png)

Digest:
![image](https://user-images.githubusercontent.com/39912581/117863504-20cad600-b294-11eb-96a1-10f56629905f.png)

Push notification:
![image](https://user-images.githubusercontent.com/39912581/117863166-c6ca1080-b293-11eb-91e9-388bfbb4c76a.png)

Email verification:
![image](https://user-images.githubusercontent.com/39912581/117863576-350ed300-b294-11eb-8e8f-f5bdd0ea92f6.png)

## Summary of changes
- Fixes Z#1322
- Fixes Z#1762
- Fixes Z#1911
- Email style is now consistent with new UI

2021-05-20 13:07 UTC, Larspolo commented on src/django/templates/email_templates/digest.html
> +{% endblock footer %}
Could be moved to a component as well

`{% block footer %}  {% include "default_footer.html" %} {% endblock footer %}` or sth

2021-05-20 13:07 UTC, Larspolo commented on src/vue/src/sass/global.sass
> +        .card-footer
Why is this here? Maybe left over from another branch?

2021-06-18 18:47 UTC, engelhamer commented on src/vue/src/sass/global.sass
> +        .card-footer
This is required for the bottom border of the login card. I was apparently removed somewhere, but is encountered through the emails with sign up link etc. That's why I changed it here.

2021-06-18 18:59 UTC, engelhamer commented
Email preview:
![image](https://user-images.githubusercontent.com/39912581/122605675-114f6180-d078-11eb-83c7-8e3b3d033650.png)

2021-06-19 12:51 UTC, Larspolo approved these changes

2021-06-21 10:46 UTC, mjvkeulen requested changes
Looking good! 

For me the only remaining item is the logo image, not all clients will render this by default and it's on quite a prominent spot.

If we simply use text instead we won't have to deal with this at all

2021-06-21 11:14 UTC, engelhamer commented
But then again that does not look as appealing and will be of a completely
different font?

Op ma 21 jun. 2021 12:46 schreef mjvkeulen ***@***.***>:

> ***@***.**** requested changes on this pull request.
>
> Looking good!
>
> For me the only remaining item is the logo image, not all clients will
> render this by default and it's on quite a prominent spot.
>
> If we simply use text instead we won't have to deal with this at all
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/eJourn-al/eJournal/pull/1146#pullrequestreview-688283282>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJQQJBNDXBWEHOC43RGGBR3TT4J7ZANCNFSM44WNZWSA>
> .
>

2021-06-21 13:00 UTC, mjvkeulen commented
To me, that's preferable to our outlook users (mostly teachers) receiving a
notification with a broken image link in a prominent location (logo /
header).

On Mon, 21 Jun 2021 at 13:14, Engel Hamer ***@***.***> wrote:

> But then again that does not look as appealing and will be of a completely
> different font?
>
> Op ma 21 jun. 2021 12:46 schreef mjvkeulen ***@***.***>:
>
> > ***@***.**** requested changes on this pull request.
> >
> > Looking good!
> >
> > For me the only remaining item is the logo image, not all clients will
> > render this by default and it's on quite a prominent spot.
> >
> > If we simply use text instead we won't have to deal with this at all
> >
> > —
> > You are receiving this because you were assigned.
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/eJourn-al/eJournal/pull/1146#pullrequestreview-688283282
> >,
> > or unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/AJQQJBNDXBWEHOC43RGGBR3TT4J7ZANCNFSM44WNZWSA
> >
> > .
> >
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/eJourn-al/eJournal/pull/1146#issuecomment-864949958>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJQQJIQX4HUXUWK3TBIZOJ3TT4NK3ANCNFSM44WNZWSA>
> .
>

2021-06-26 14:43 UTC, engelhamer commented
> To me, that's preferable to our outlook users (mostly teachers) receiving a notification with a broken image link in a prominent location (logo / header).

![image](https://user-images.githubusercontent.com/39912581/123516663-8553c000-d69d-11eb-8078-9a0ab67bcbbe.png)

This is the worst case. Most users will just see the normal logo. It is not obtrusive to me and very easy for those who experience it to fix by the click of a button.

All students on gmail will just see a fancy logo instead of the old text.

2021-07-06 21:00 UTC, mjvkeulen approved these changes

2021-09-07 08:10 UTC, merged