Added the ability for course coordinators to limit TA's to only viewing students from inside their group
eJourn-al/eJournal pull request #1148
Opened 2021-05-15 16:21 UTC by Larspolo

## Description
Added the ability for course coordinators to limit TA's to only viewing students from inside their group

Also, the 2 hours didn't go as planned. 5 hours now

## Summary of changes
- Fixes Z#1929

2021-05-18 11:22 UTC, mjvkeulen commented on src/django/VLE/models/participation.py
> +                groups__in=groups,
I believe this will yield a syntax error in Django 3+, groups=groups should work (also on Django 2 I believe)

2021-05-18 11:22 UTC, mjvkeulen commented on src/django/VLE/models/participation.py
> +        if courses is not -1:
Reuse NOT_SUPPLIED

2021-05-18 11:22 UTC, mjvkeulen commented on src/django/VLE/migrations/0087_role_can_view_journals_in_group.py
> +            name='can_view_journals_in_group',
Towards a user, it makes more sense to make the permissions can_view_journals_in_group and can_view_all_journals mutually exclusive. 

To highlight this distinction I would propose to rename the permission to `can_only_view_journals_in_group`

2021-05-18 11:22 UTC, mjvkeulen commented on src/django/VLE/models/user.py
> +
NIT: Prob add return false iso the implicit return None

2021-05-18 11:22 UTC, mjvkeulen commented on src/django/VLE/permissions.py
> +    # The nested many to many inside a SubQuery causes "IndexError: pop from empty list"
Hah I remember this one

2021-05-18 11:22 UTC, mjvkeulen commented on src/django/VLE/views/role.py
> +                # Could this also be a is_supervisor check?
If it is not used frontend, remove all conditional logic here and let us worry about it when we do need it.

2021-05-18 13:27 UTC, Larspolo commented on src/django/VLE/migrations/0087_role_can_view_journals_in_group.py
> +            name='can_view_journals_in_group',
How many hours is this change worth to you?

2021-05-18 13:38 UTC, mjvkeulen commented on src/django/VLE/migrations/0087_role_can_view_journals_in_group.py
> +            name='can_view_journals_in_group',
A few I guess? What is the expected result of giving a user both the permissions `can_view_journals_in_group` and `can_view_all_journals`?

2021-05-19 11:39 UTC, Larspolo commented on src/django/VLE/migrations/0087_role_can_view_journals_in_group.py
> +            name='can_view_journals_in_group',
My guess would be 2 to 3 hours

2021-05-20 13:11 UTC, Larspolo commented on src/django/VLE/models/user.py
> +
Which do you mean?

2021-05-23 22:29 UTC, mjvkeulen commented on src/django/VLE/models/user.py
> +
The block has no final return value

2021-06-17 12:37 UTC, Larspolo commented on src/django/VLE/models/user.py
> +            return True
Not introduced in this PR, and dont find it necessarily beter

2021-06-17 12:51 UTC, Larspolo commented on src/django/VLE/models/role.py
> +            self.can_view_journals_in_group = True
I still like it this way, feel like whenever someone can view all journal, this can simply be put to true, there is no other way it was intended

2021-06-17 12:56 UTC, Larspolo commented on src/django/VLE/permissions.py
> +    )
Good luck!

2021-06-17 12:56 UTC, Larspolo commented on src/django/VLE/views/assignment.py
> +        journals = Journal.objects.filter().viewable_for(request.user)
With the empty filter `viewable_for` becomes available to be used

2021-06-17 12:58 UTC, Larspolo commented on src/django/VLE/serializers.py
> +            assignment=assignment, authors__user__in=relevant_stat_users_own)
Probably the second

2021-06-17 12:58 UTC, Larspolo commented on src/django/VLE/views/assignment.py
> +                )
also probaly from refactory

2021-06-17 13:01 UTC, Larspolo commented on src/django/VLE/views/grade.py
> +            assignment=assignment, unpublished__gt=0).viewable_for(request.user).distinct()
Problem is that we cannot add it without a function call, because we do not have access to the user. But I am not opposed to having to type `viewable_for(...)` for every query. I would even like to see expanding this with `editable_by` and `deletable_by` etc. to reduce query counts, but that is for some other day.

2021-06-17 13:02 UTC, Larspolo commented on src/django/VLE/views/journal.py
> +        ).exists():
Cannot think of anything existing as of now

2021-06-17 13:06 UTC, Larspolo commented on src/django/VLE/views/journal.py
> +        request.user.check_can_view(journal)
join: no, the `can_view_journal` function only works for journal authors or teachers / observers

deletion: we could. Added.

2021-06-17 13:43 UTC, Larspolo commented on src/django/test/test_participation.py
> +        queries_per_additional_user = 6  # User serializer
Dont know anymore, changed it back, seemed to work local, lets see what CI thinks about it

2021-06-17 14:11 UTC, mjvkeulen commented on src/django/VLE/views/assignment.py
> +        journals = Journal.objects.filter().viewable_for(request.user)
As in: can you not simply do Journal.objects.viewable_for(request.user)?

2021-06-18 18:21 UTC, Larspolo commented on src/django/VLE/models/participation.py
> +            return self.none()
We want a queryset to be returned, the other returned a function

2021-06-19 13:01 UTC, engelhamer commented on src/django/VLE/views/journal.py
> +        request.user.check_can_view(journal)
I don't think it is needed to have this check at all here (because what really matters is the permission above, and nothing is shared?)

2021-06-19 13:01 UTC, engelhamer commented on src/django/VLE/views/journal.py
>          request.user.check_permission('can_edit_assignment', journal.assignment)
Shouldn't this be `can_manage_journals`?

2021-06-19 13:01 UTC, engelhamer commented on src/django/VLE/views/journal.py
> +        request.user.check_can_view(journal)
Same, see the permission check directly below. Why do you want this here? Same goes for assignment.

2021-06-19 13:01 UTC, engelhamer commented on src/django/VLE/views/journal_import_request.py
> +        request.user.check_can_view(journal_target)
Why?

2021-06-19 13:15 UTC, Larspolo commented on src/django/VLE/views/journal.py
> +        request.user.check_can_view(journal)
Without this TA's with this permission could kick users from other journals

2021-06-19 13:16 UTC, Larspolo commented on src/django/VLE/views/journal.py
> +        request.user.check_can_view(journal)
Without this TA's with this permission could kick users from other journals. Dont think that is preferred

2021-06-19 13:16 UTC, Larspolo commented on src/django/VLE/views/journal_import_request.py
> +        request.user.check_can_view(journal_target)
So that TA's can view JIR's from journals they cannot see

2021-06-19 13:25 UTC, engelhamer commented on src/django/VLE/views/journal.py
> +        request.user.check_can_view(journal)
But how do we decide which groups a group journal is in? If one of the members is in the group? What if they are kicked?

2021-06-19 15:33 UTC, Larspolo commented on src/django/VLE/views/journal.py
> +        request.user.check_can_view(journal)
Yeah, either
- a member of the journal,
- or in the assignment with the can_view_all_journals permission,
- or in the assignment with same groups as any of the authors and can_view_journals_in_own_group permission

2021-06-21 11:41 UTC, mjvkeulen commented on src/django/test/test_participation.py
> +            'By default the supervisors_only should return the teacher'
In line with your assert remarks @Larspolo shouldn't this actually check if the teacher of the course is returned? (course author)

2021-06-21 11:44 UTC, mjvkeulen commented on src/vue/src/components/assets/PdfDisplay.vue
> -            <pdf
Is this correct? Unexpected on this branch

2021-06-21 11:51 UTC, mjvkeulen commented on src/vue/src/components/course/UserRoleConfiguration.vue
> +                        <template v-if="disabledPermission(role, permission)">
![image](https://user-images.githubusercontent.com/39912610/122757107-86e54880-d297-11eb-82b3-d70905e1747d.png)

The tooltip itself is clear, but I would expect the style to be similar to how a teacher cannot remove can edit course roles/details:

![image](https://user-images.githubusercontent.com/39912610/122757212-abd9bb80-d297-11eb-9c27-30bda0e3df3f.png)

Selected checkbox which is disabled for input

2021-06-21 11:52 UTC, mjvkeulen commented on src/vue/src/main.js
> +            console.log(this.$hasPermission('can_view_journals_of_own_groups', 'assignment', assignment.id))
Left over

2021-06-21 11:55 UTC, mjvkeulen commented on src/vue/src/main.js
> -                    route.name = 'AssignmentEditor'
Q) What should the route name be if these user does not have `can_edit_assignment`? The behaviour is now slightly different but I can't recall why this was required in the first place.

2021-06-21 12:08 UTC, mjvkeulen commented on src/vue/src/views/Assignment.vue
>  <template>
When filtering groups on the assignment page I get the following error:

![image](https://user-images.githubusercontent.com/39912610/122759257-083dda80-d29a-11eb-9b4f-5d0074e42c59.png)

![image](https://user-images.githubusercontent.com/39912610/122759331-1a1f7d80-d29a-11eb-9671-3a85e155624c.png)


Group filter is also not updated because of it

2021-06-21 12:23 UTC, mjvkeulen requested changes
`edit_entry` in category.py is missing a journal specific check

2021-06-21 12:32 UTC, mjvkeulen commented on src/django/VLE/views/journal.py
> +        request.user.check_can_view(journal)
Does `request.user.check_can_view(journal.assignment)` not always yield True if `request.user.check_can_view(journal)` yields True? So the first check can be omitted?

2021-06-21 13:36 UTC, mjvkeulen commented on src/django/VLE/permissions.py
>  def can_edit(user, obj):
`_can_edit_entry` needs to filter journals based on viewable journals right?

2021-06-21 13:43 UTC, mjvkeulen commented on src/django/VLE/serializers.py
> +            assignment=assignment, authors__user__in=relevant_stat_users_own)
Q) Should TODOs not also be limited to those viewable specifically by the user?

2021-06-21 13:45 UTC, mjvkeulen commented on src/django/VLE/models/assignment.py
Q) Is this function  `get_all_users` of `models/assignment.py` not also impacted by the stricter filtering requirements introduced in this PR?

2021-06-21 13:50 UTC, mjvkeulen commented on src/django/VLE/models/user.py
> +        if Journal.objects.filter(authors__user__in=[self]).filter(authors__user__in=[user]).exists():
Q) Is the `__in` syntax required here?

2021-06-22 11:46 UTC, Larspolo commented on src/vue/src/components/course/UserRoleConfiguration.vue
> +                        <template v-if="disabledPermission(role, permission)">
How about changing the disabled teacher input to the newer style?

2021-06-22 11:48 UTC, Larspolo commented on src/vue/src/main.js
> -                    route.name = 'AssignmentEditor'
The navigation to home was to redirect users to the homepage if an external user send them a link to an assignment they were not part of. If we didnt redirect them, it showed weird stuff

2021-06-22 11:49 UTC, Larspolo commented on src/vue/src/views/Assignment.vue
>  <template>
(how) is this introduced in this PR?

2021-06-22 16:55 UTC, mjvkeulen commented on src/vue/src/views/Assignment.vue
>  <template>
Haven't looked, but not happening on develop :shrug:

2021-06-24 11:09 UTC, Larspolo commented on src/django/VLE/models/user.py
> +        if Journal.objects.filter(authors__user__in=[self]).filter(authors__user__in=[user]).exists():
Yes, tests fail if I change it to:
`Journal.objects.filter(authors__user=self).filter(authors__user=user).exists()`

2021-06-24 11:19 UTC, Larspolo commented on src/django/VLE/models/assignment.py
Missed that, added now

2021-06-24 11:39 UTC, Larspolo commented on src/django/VLE/permissions.py
>  def can_edit(user, obj):
Its kinda already done by checking if the user is inside the journal

2021-06-24 11:58 UTC, Larspolo commented on src/vue/src/components/course/UserRoleConfiguration.vue
> +                        <template v-if="disabledPermission(role, permission)">
Changed to my suggestion

2021-06-24 12:07 UTC, Larspolo commented on src/django/VLE/views/assignment.py
> +        journals = Journal.objects.filter().viewable_for(request.user)
No
```
>       journals = Journal.objects.viewable_by(request.user)
E       AttributeError: 'JournalManager' object has no attribute 'viewable_by'
```

2021-06-24 12:11 UTC, mjvkeulen commented on src/django/VLE/views/assignment.py
> +        journals = Journal.objects.filter().viewable_for(request.user)
Q) Would Journal.objects.all() also work as a starting point? (We just need a query set instance of Journal right)? Not that that's better than an empty filter

2021-06-25 08:22 UTC, mjvkeulen commented on src/django/VLE/views/grade.py
> +            assignment=assignment, unpublished__gt=0).viewable_for(request.user).distinct()
I think this touches on how there are too many alternative paths to check for a permission. Let's leave it as is for now and streamline our permissions once we introduce peer reviews (which will require object-level permissions, e.g. on a per `entry` basis).

2021-06-25 08:37 UTC, mjvkeulen commented on src/django/VLE/migrations/0093_role_can_view_journals_in_group.py
> +# Generated by Django 2.2.10 on 2021-05-14 16:41
Migration file name needs to also be updated to match the permission

2021-06-25 08:40 UTC, mjvkeulen commented on src/django/VLE/models/assignment_participation.py
> +            )
Wrap the subquery in an `Exists()` like we do in `annotate_has_unpublished_overall_assessment`, this allows us to work with a boolean as the annotation `can_view` would suggest.

2021-06-25 08:41 UTC, mjvkeulen commented on src/django/VLE/models/assignment_participation.py
> +        ).filter(can_view__isnull=False).annotate(can_view=F('pk')).distinct()
This can then just become can_view=True

2021-06-25 08:42 UTC, mjvkeulen commented on src/django/VLE/models/assignment_participation.py
> +        ).filter(can_view__isnull=False).annotate(can_view=F('pk')).distinct()
Q) Why is this required? `.annotate(can_view=F('pk'))`

2021-06-25 08:42 UTC, mjvkeulen commented on src/django/VLE/models/journal.py
> +        ).filter(can_view__isnull=False).annotate(can_view=F('pk')).distinct()
Similar thing here

2021-06-25 08:55 UTC, mjvkeulen commented on src/django/VLE/models/user.py
> +        if Journal.objects.filter(authors__user__in=[self]).filter(authors__user__in=[user]).exists():
This confused me so I double-checked.

Without the `__in` syntax, all tests passed!

What does worry me a bit (unrelated sort of), is that I first made the mistake of writing `authors__user=self` 2x instead of once, and all tests still passed!

2021-06-25 09:06 UTC, mjvkeulen commented on src/django/VLE/views/role.py
> +            # TODO: P Is this the right permission
So when is someone allowed to request the permissions of another user for a specific course.

@engelhamer?

2021-06-25 12:24 UTC, Larspolo commented on src/django/VLE/models/assignment_participation.py
> +        ).filter(can_view__isnull=False).annotate(can_view=F('pk')).distinct()
Removed again with the `Exists` option its no longer needed, but it was the same system as `allowed_journals` where multiple journals were returned

2021-06-26 06:29 UTC, mjvkeulen commented on src/vue/src/components/course/UserRoleConfiguration.vue
> +                        <template v-if="disabledPermission(role, permission)">
I preferred the old disabled checkbox (with tooltip), to me that is a bit more clear at first glance that this permission is enabled. However, this is nonblocking for me!

2021-06-26 06:32 UTC, mjvkeulen commented on src/django/VLE/models/role.py
> +            self.can_view_journals_in_group = True
So the only legitimate way someone can differ is by messing with the request/frontend themselves (now that this is enforced frontend (with tooltip and all)). This is why when someone does so I would expect an error not a silent change of the provide value (prone to confusion when refactoring something later on). 

Again nonblocking, but hopefully you agree with the argument ^^

2021-06-26 15:14 UTC, engelhamer commented on src/vue/src/components/course/UserRoleConfiguration.vue
> +                        <template v-if="disabledPermission(role, permission)">
I find this ambiguous: the grey info icon does not tell the user whether it is active or not without hovering.

2021-06-26 15:17 UTC, engelhamer commented on src/django/VLE/views/assignment.py
> +        journals = Journal.objects.filter().viewable_for(request.user)
Indeed `all()`

2021-06-26 15:47 UTC, engelhamer reviewed
For example the `can_manage_course_user_groups` is not very sensible in combination with this: it is possible to place users in another group, and then they are visible again. I think we should make this option only possible if a role has almost no management permissions such as this.

2021-06-26 15:47 UTC, engelhamer commented on src/django/VLE/views/role.py
> +            # TODO: P Is this the right permission
When they need to edit the permissions I guess? So the course edit > users tab.

2021-06-26 17:28 UTC, Larspolo commented on src/vue/src/components/course/UserRoleConfiguration.vue
> +                        <template v-if="disabledPermission(role, permission)">
The tooltip does

2021-06-26 20:51 UTC, mjvkeulen approved these changes

2021-06-26 21:03 UTC, engelhamer commented on src/vue/src/components/course/UserRoleConfiguration.vue
> +                        <template v-if="disabledPermission(role, permission)">
Consider extending this to the `can_have_journal_` combo: that value must be false for those who `can_view_all_journals`, and this would ideally be also displayed here. Then you would have the same symbol but for one it can mean `True` and for the other `False`>

2021-06-27 20:12 UTC, Larspolo commented on src/vue/src/components/course/UserRoleConfiguration.vue
> +                        <template v-if="disabledPermission(role, permission)">
I have no intensions of extending this to the `can_have_journal` combo

2021-06-27 20:16 UTC, engelhamer approved these changes

2021-07-04 14:50 UTC, merged