Fixed make setup
eJourn-al/eJournal pull request #1149
Opened 2021-05-16 13:29 UTC by mjvkeulen

Minor tweaks to get the build script running again

2021-05-16 13:30 UTC, engelhamer commented on Makefile
> +	sudo apt install nodejs npm -y
Npm should come with nodejs

2021-05-16 14:02 UTC, mjvkeulen commented on Makefile
> +	sudo apt install nodejs npm -y
I had to add this to make the setup script work on a clean install

2021-05-16 14:08 UTC, engelhamer commented on Makefile
> +	sudo apt install nodejs npm -y
Hm seems like a PPA may be the cause of differences here. Laat time I checked it was not needed. https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-ubuntu-18-04

Which version do you get from this install?

2021-05-16 15:23 UTC, Larspolo commented on Makefile
> +	sudo apt install nodejs npm -y
Ubuntu 20.04 could be the difference here

2021-05-17 08:09 UTC, mjvkeulen commented on Makefile
> +	sudo apt install nodejs npm -y
Setup for a fresh Ubuntu 20.04.2, npm version 7.13.0

2021-05-17 09:09 UTC, Larspolo commented on Makefile
> +	sudo apt install nodejs npm -y
Problem is that we github acitons stil required dataclasses, I still manually comment is out because of that

2021-05-17 09:32 UTC, mjvkeulen commented on Makefile
> +	sudo apt install nodejs npm -y
Cant we just move dataclasses to ci.txt?

2021-05-20 14:39 UTC, Larspolo commented on requirements/ci.txt
> +dataclasses==0.8 # Email sender config
Think this is Python version dependend, production still has an outdated version which should also be upgraded for it to not be needed there anymore

2021-06-12 13:04 UTC, Larspolo commented on requirements/ci.txt
> +dataclasses==0.8 # Email sender config
After #1150 is merged, this change is acceptable, but then it needs to be removed here as well

2021-06-15 11:25 UTC, Larspolo requested changes

2021-06-15 11:25 UTC, Larspolo commented on requirements/ci.txt
> +dataclasses==0.8 # Email sender config
@mjvkeulen this should now be removed as well

2021-06-15 11:32 UTC, engelhamer commented on requirements/ci.txt
> +dataclasses==0.8 # Email sender config
It is removed

2021-06-15 15:16 UTC, Larspolo approved these changes
`nodejs` is no longer a valid command after this. I think its changed to just `node`

2021-06-18 18:13 UTC, engelhamer approved these changes

2021-06-18 18:13 UTC, merged