Split assignment copy function to more comprehensable functions
eJourn-al/eJournal pull request #1159
Opened 2021-05-30 21:04 UTC by Larspolo

## Description
PR useful for copying existing formats to assignments. Although not full (e.g. frontend) support yet

2021-05-31 07:00 UTC, mjvkeulen approved these changes

2021-06-05 11:48 UTC, engelhamer commented on src/django/VLE/views/assignment.py
> +def create_a_to_be_copied_assignment(source, author, course):
Naming confusese me here. This copies the assignment already, and does not create a 'to be copied' assigmnent? The 'to be copied' assignment would be the source.

2021-06-05 11:48 UTC, engelhamer commented on src/django/VLE/views/assignment.py
>          assignment_source = Assignment.objects.get(pk=assignment_source_id)
Why is it needed to have this again here?

2021-06-05 12:22 UTC, Larspolo commented on src/django/VLE/views/assignment.py
> +def create_a_to_be_copied_assignment(source, author, course):
I indeed had trouble with the assignment name. The assignment gets copied partially, not yet the whole format
What do you suggest?

2021-06-12 13:00 UTC, Larspolo commented on src/django/VLE/views/assignment.py
>          assignment_source = Assignment.objects.get(pk=assignment_source_id)
Dont know, maybe @mjvkeulen knows

2021-06-12 13:01 UTC, Larspolo commented on src/django/VLE/views/assignment.py
> +def create_a_to_be_copied_assignment(source, author, course):
To reduce complexity (and overview) of the function. Especially with LTI mixed in as well, it was too unclear what was happening where, this was an attempt at clarifying it

2021-06-12 21:44 UTC, mjvkeulen commented on src/django/VLE/views/assignment.py
>          assignment_source = Assignment.objects.get(pk=assignment_source_id)
`assignment_source` is used as the template for `new_assignment`, some of its values are changed and is saved to become `new_assignment`. Whereas this process maintains the reference to the `assignment_source` its values are no longer correct (e.g. a new `pk` as its now effectively `new_assignment`).

2021-06-18 21:26 UTC, engelhamer requested changes

2021-06-18 21:26 UTC, engelhamer commented on src/django/VLE/views/assignment.py
>          assignment_source = Assignment.objects.get(pk=assignment_source_id)
Worth a comment as it is unclear.

2021-06-18 21:28 UTC, engelhamer approved these changes

2021-06-18 21:47 UTC, merged