Added rubrics and overall journal assessments
eJourn-al/eJournal pull request #1163
Opened 2021-06-05 07:43 UTC by mjvkeulen

TODO

2021-06-05 18:55 UTC, Larspolo commented on src/vue/src/components/journal/JournalNonStudent.vue
>          <template #right>
Missing this right one

2021-06-06 06:34 UTC, mjvkeulen commented on src/vue/src/components/journal/JournalNonStudent.vue
>          <template #right>
There is guaranteed content available for the slot when component is created

2021-06-11 13:02 UTC, Larspolo requested changes

2021-06-11 13:02 UTC, Larspolo commented on src/vue/src/components/journal/JournalEndCard.vue
> +        <load-wrapper :loading="loading">
This looks great, and is a good place to have the overall assessment. However, I do think some extra indication for both students and teachers would be nice to hint that the overall assessment is placed here

2021-06-11 13:04 UTC, mjvkeulen commented on src/vue/src/components/rubric/edit/LevelEdit.vue
> +                name="comments"
Clicking on the icon once yields this:

![image](https://user-images.githubusercontent.com/39912610/121690548-4848d480-cac6-11eb-992f-0470d9a584be.png)

So that is not sufficiently self-explanatory?

2021-06-11 13:08 UTC, mjvkeulen commented on src/vue/src/components/rubric/edit/RubricEdit.vue
> +                        name: 'Full marks',
Full marks for a single criterion are not related to the maximum number of points available for the assignment.

2021-06-11 13:25 UTC, mjvkeulen commented on src/vue/src/components/journal/JournalEndCard.vue
> +        <load-wrapper :loading="loading">
- Teacher publishes an overall assessment -> node is selected and assessment is displayed
- Student receives a notification, by default this is push, via the email button link the student is redirected to their journal, and the end node is selected displaying the overall assessment.

Both teacher and student are introduced to the location of the overall assessment quite naturally. What would you propose differently?

2021-06-11 13:55 UTC, mjvkeulen commented on src/vue/src/components/journal/JournalAssessment.vue
> +                        v-b-tooltip:hover="'Overall assessments trump any individual entry grades'"
This is a bit outdated, now the grade is reactive unless overwritten explicitly by the user. See the description

2021-06-11 13:59 UTC, Larspolo requested changes

2021-06-11 13:59 UTC, Larspolo commented on src/vue/src/components/rubric/CriterionRow.vue
> +                    :disabled="!grading || !criterionSubmission.level_id"
Would prefer it to switch to just text iso readonly. Especially for students this now looks a bit weird.

2021-06-11 13:59 UTC, Larspolo commented on src/vue/src/components/assessment/Assessment.vue
> +        <b-form-group label="Feedback">
[NIT] "Overall feedback" or "Extra feedback" might be a better title

2021-06-11 13:59 UTC, Larspolo commented on src/vue/src/components/journal/JournalAssessment.vue
> +        <b-modal
I think redirection this to the end node iso a modal would feel more natural. Even if it comes with the downside of modals being able to be wider.
The same width will be shown in the rubric editor, for student, and for teachers in the "end of assignment" node anyway.
We already have an issue open to improve the width restraint, which could imo be bumped after this PR

2021-06-11 13:59 UTC, Larspolo commented on src/vue/src/components/journal/JournalAssessment.vue
> +                    {{ assessment.is_draft ? nonDraft ? 'Restore' : 'Reset' : 'Delete' }}
[NIT] When it says "Restore", it shortly switches to "Reset" during loading, and only then changes to "Delete"

2021-06-11 13:59 UTC, Larspolo commented on src/vue/src/components/journal/JournalAssessment.vue
> +                    {{ assessment.is_draft ? nonDraft ? 'Restore' : 'Reset' : 'Delete' }}
[Q] when is "Reset" shown?

2021-06-11 13:59 UTC, Larspolo commented on src/vue/src/components/journal/JournalAssessment.vue
> +                    {{ assessment.is_draft ? nonDraft ? 'Restore' : 'Reset' : 'Delete' }}
[NIT] I still find this naming a bit confusing, but I also dont have the golden solution. How does changing "restore" to "Reset Draft" sound? Or "Remove pending changes"?

2021-06-11 13:59 UTC, Larspolo commented on src/vue/src/components/assessment/AssessmentGrades.vue
> +                return 'Back to default.'
[NIT] "Back to automatically determining grade."

2021-06-11 13:59 UTC, Larspolo commented on src/django/VLE/utils/generic_utils.py
> +            elif assessment:
Think you are missing something here. this now checks if the import is not None. Also add a test for this ;)

2021-06-11 13:59 UTC, Larspolo commented on src/django/VLE/utils/file_handling.py
> +def copy_rt_files(rich_text, user, assignment=None, category=None, assessment=None):
[NIT] Found the original name better. It cannot handle profile pictures or other non assignment related files if there are any

2021-06-11 13:59 UTC, Larspolo commented on src/django/VLE/utils/grading.py
> +    Assessment.objects.unpublished_assessment_for_journal(journal).update(is_published=True)
[NIT] really nit, but would expect this after the other grades are published

2021-06-11 13:59 UTC, Larspolo commented on src/django/VLE/utils/import_utils.py
> +    criteria = []  # [[C1, C2], [C3]]
left over code?

2021-06-11 13:59 UTC, Larspolo commented on src/django/VLE/views/assessment.py
> +        grading.task_journal_status_to_LMS.apply_async(args=[draft.journal.pk], countdown=settings.WEBSERVER_TIMEOUT)
This needs to go after the rest in case that crashes, we dont want the notifications to be send anyway

2021-06-11 13:59 UTC, Larspolo commented on src/django/test/factory/content.py
> +if not (os.path.exists(IMG_FILE_PATH)):
This check should include `for staging env` as well then?

2021-06-11 13:59 UTC, Larspolo commented on src/django/VLE/models/preferences.py
> +        default=PUSH,
[D(iscussion)] Do we wish to change the `new grade` to daily now? Because this is now more important

2021-06-11 13:59 UTC, Larspolo commented on src/django/VLE/models/rubric.py
> +def validate_fks(data, attr, expected_fk, instance_label):
[NIT] Feels like a utils functions to me (also unique name and locations (for templates)). Would like a docstring as well. When is this useful?

2021-06-11 13:59 UTC, Larspolo commented on src/django/VLE/models/rubric.py
> +                f'{instance_label} is unexpectedly linked to a different {attr}. `{actual_fk}` iso `{expected_fk}`.')
[NIT] if the user sees this error its a bit weird.

2021-06-11 13:59 UTC, Larspolo commented on src/django/VLE/settings/base.py
> +DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'
[Q] I cannot find this anywhere in the code, when is this useful?

2021-06-11 14:03 UTC, mjvkeulen commented on src/vue/src/components/rubric/edit/RubricEdit.vue
> +                        name: 'Full marks',
min (10, assignmentMax)

2021-06-11 14:04 UTC, mjvkeulen commented on src/vue/src/components/journal/JournalAssessment.vue
> +                        v-b-tooltip:hover="'Overall assessments trump any individual entry grades'"
will remove tooltip

2021-06-11 14:06 UTC, mjvkeulen commented on src/vue/src/components/journal/JournalEndCard.vue
> +        <load-wrapper :loading="loading">
Will change end of assignment title to assessment if present

2021-06-11 14:11 UTC, mjvkeulen commented on src/vue/src/components/rubric/CriterionRow.vue
> +                    :disabled="!grading || !criterionSubmission.level_id"
Will switch to text for both student and teacher in read mode

2021-06-11 14:19 UTC, mjvkeulen commented on src/vue/src/components/journal/JournalAssessment.vue
> +        <b-modal
Decided to move to zube issue in order to find a better solution

2021-06-11 14:24 UTC, mjvkeulen commented on src/vue/src/components/journal/JournalAssessment.vue
> +                        v-b-tooltip:hover="'Overall assessments trump any individual entry grades'"
Updated tooltip

2021-06-11 15:18 UTC, Larspolo requested changes
Dont mind all the test comments too much. I wanted to test if I could only review the test code based on the assert statements alone, managed pretty well

2021-06-11 15:18 UTC, Larspolo commented on src/django/test/test_assessment.py
> +            'A student should not see archived assessments unless specifically requested'
[Q] Is the student able to see archived assessments? How? Didnt see it frontend at least

2021-06-11 15:18 UTC, Larspolo commented on src/django/test/test_assessment.py
> +        assert self.assessment_draft.pk not in serialized_assessments_pks, 'A student not receive drafts'
A student should not receive drafted assessments

2021-06-11 15:18 UTC, Larspolo commented on src/django/test/test_assessment.py
> +            assert self.assessment_archived.pk in serialized_assessments_pks
Missing message

2021-06-11 15:18 UTC, Larspolo commented on src/django/test/test_assessment.py
> +        assert resp['assessment'], 'A created assessment is returned'
"When creating an assessment via de API, it should respond with the created assessment."

Although the statement above is more checking that then this statement is. This just checks if there is a response

2021-06-11 15:18 UTC, Larspolo commented on src/django/test/test_assessment.py
> +        assert self.assignment.author.full_name in resp['description']
"The author that already started their assessment should be given in the response"

2021-06-11 15:18 UTC, Larspolo commented on src/django/test/test_assessment.py
> +            'When starting a draft based via the assessment histroy, the source assessment should not be modified'
history*

2021-06-11 15:18 UTC, Larspolo commented on src/django/test/test_assignment.py
> +        )
"The source and target rubric should contain the same information after copy"

2021-06-11 15:18 UTC, Larspolo commented on src/django/test/test_assignment.py
> +        assert assignment_copy.rubrics.count() == source_assignment.rubrics.count()
"All rubrics should be copied during an assignment copy"

2021-06-11 15:18 UTC, Larspolo commented on src/django/test/test_notification.py
> +        assert '?assessment' in notification.url, \
Needs check that this doesnt exist on notifications that are not about assessment, but still contain journal

2021-06-11 15:18 UTC, Larspolo commented on src/django/test/test_rubric.py
> +        updated_data['criteria'][1]['levels'][1]['name'] = 'Some new name'
Would prefer these names to be different, just in case the name gets wrongly changed

2021-06-11 15:18 UTC, Larspolo commented on src/django/test/test_rubric.py
> +            'It is not possible to remove a criterion which is used in an assessment'
"The criterion should still exists when trying to remove it while it is in use"

2021-06-11 15:18 UTC, Larspolo commented on src/django/test/test_rubric.py
> +            'It is not possible to remove a level which is used in an assessment'
"The level should still exists when trying to remove it while it is in use"

2021-06-11 15:18 UTC, Larspolo commented on src/django/test/test_rubric.py
> +            'All rubrics are serialized where the used can edit the assignment'
This does not check if rubrics are returned multiple times. Would go for a length check as well

2021-06-11 19:01 UTC, mjvkeulen commented on src/vue/src/components/journal/JournalEndCard.vue
> +        <load-wrapper :loading="loading">
Also added show overall assessment to journal details

2021-06-11 19:17 UTC, mjvkeulen commented on src/vue/src/components/journal/JournalAssessment.vue
> +                    {{ assessment.is_draft ? nonDraft ? 'Restore' : 'Reset' : 'Delete' }}
When working on a draft and no older version is available (from the same working session, so excluding history)

2021-06-11 19:21 UTC, mjvkeulen commented on src/django/VLE/utils/generic_utils.py
> +            elif assessment:
What do you mean?

This works and is tested in `test_assessment_notification_content`

2021-06-11 19:22 UTC, mjvkeulen commented on src/django/VLE/utils/file_handling.py
> +def copy_rt_files(rich_text, user, assignment=None, category=None, assessment=None):
profile picture is not a `rich_text` file, this can be easily extended and works beyond specific assignment scope now

2021-06-11 19:41 UTC, mjvkeulen commented on src/django/VLE/views/assessment.py
> +        grading.task_journal_status_to_LMS.apply_async(args=[draft.journal.pk], countdown=settings.WEBSERVER_TIMEOUT)
I moved it, but this a downside of how we approach transactions.

Could just be 
```
transaction.on_commit(lambda: generate_new_assessment_notifications.delay(draft.pk))
transaction.on_commit(lambda: grading.task_journal_status_to_LMS.delay(draft.journal.pk))
```

But this would require us to inherit from `TransactionTestCase` for tests which uses stuff like `on_commit`. Which truncates all tables after a test, which might not be compatible with `setUpTestData(cls)`.

2021-06-11 19:43 UTC, mjvkeulen commented on src/django/test/factory/content.py
> +if not (os.path.exists(IMG_FILE_PATH)):
Could be added, it's a fallthrough check tho. If no file found look here, moved to elif to skip unneeded os path checks.

2021-06-11 19:46 UTC, mjvkeulen commented on src/django/VLE/models/preferences.py
> +        default=PUSH,
I would not change anything since you don't know which model will be used in advance.

2021-06-11 19:47 UTC, mjvkeulen commented on src/django/VLE/models/rubric.py
> +                f'{instance_label} is unexpectedly linked to a different {attr}. `{actual_fk}` iso `{expected_fk}`.')
Has to intentionally mess with data

2021-06-11 19:48 UTC, mjvkeulen commented on src/django/VLE/settings/base.py
> +DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'
Is migration setting from Django 2 to 3 (no behavioural change, just an explicit definition of what our pks are)

2021-06-11 19:50 UTC, mjvkeulen commented on src/django/VLE/views/grade.py
> +            Journal.all_objects  # Default manager has no access to `annotate_has_unpublished_overall_assessment`
Because our default manager is no created from `JournalQuerySet`

2021-06-11 19:52 UTC, mjvkeulen commented on src/django/test/test_assessment.py
> +            '''
No active assessment is generated for the journal, which is quite explicitly defined here no?

2021-06-11 19:52 UTC, mjvkeulen commented on src/django/test/test_assessment.py
> +            '''
Ditto here

2021-06-11 19:54 UTC, mjvkeulen commented on src/django/test/test_assessment.py
> +        assert assessment_history[0].update_date < assessment_history[1].update_date
These all check the same thing: `Assessment history returns all non draft assessments in order of oldest to newest`

These just validate it using python sort as well

2021-06-11 19:58 UTC, mjvkeulen commented on src/django/test/test_assessment.py
> +        # Only published assessments can be archived
I believe its correct: Only when an assessment is published can it be archived (both True)

2021-06-11 20:00 UTC, mjvkeulen commented on src/django/test/test_assessment.py
> +        assert criterion_submission
Kinda small seeing `first()` and being part of the init block (assert is still part of the init block)

2021-06-11 20:01 UTC, mjvkeulen commented on src/django/test/test_assessment.py
> +        assert not student.can_edit(rubric_submission), 'Student cannot edit the assessment'
This was intentional as its tied to the assessment

2021-06-11 20:01 UTC, mjvkeulen commented on src/django/test/test_assessment.py
> +        assert not student.can_edit(criterion_submission), 'Student cannot edit the assessment'
Likewise

2021-06-11 20:03 UTC, mjvkeulen commented on src/django/test/test_assessment.py
> +        assert teacher.can_edit(rubric_submission), 'Rubric submissions can only be edited for assessment drafts'
Sorry split the message?

2021-06-11 20:03 UTC, mjvkeulen commented on src/django/test/test_assessment.py
> +            'A student should not see archived assessments unless specifically requested'
If given the permission grade history

2021-06-11 20:07 UTC, mjvkeulen commented on src/django/test/test_assessment.py
> +            assert self.assessment_archived.pk in serialized_assessments_pks
The block has the comment: `The ability to see archived assessments is governed by `can_view_grade_history`` Will repeat it

2021-06-11 20:11 UTC, mjvkeulen commented on src/django/test/test_assessment.py
> +        assert resp['assessment'], 'A created assessment is returned'
That combination is fine no? We know the assessment is created and serialized since we got assessment the line above

2021-06-11 20:12 UTC, mjvkeulen commented on src/django/test/test_assessment.py
> +        assert resp['assessment'], 'A created assessment is returned'
I believe context prefix is good: `When creating an assessment via de API` but this generally puts mosts asserts over two lines. Do not forget the simplicity of the block: create is just called in a familar pattern. Or the name of the test `test_assessment_create`. 

These are all viable context

2021-06-11 20:13 UTC, mjvkeulen commented on src/django/test/test_assessment.py
> +        assert self.assignment.author.full_name in resp['description']
(Again the comment above the block could basically be repeated in the asserts)

2021-06-11 20:16 UTC, mjvkeulen commented on src/django/test/test_assignment.py
> +        assert assignment_copy.rubrics.count() == source_assignment.rubrics.count()
Also heavily implicated in the format of this assert tbh

2021-06-11 20:30 UTC, mjvkeulen commented on src/django/test/test_rubric.py
> +        updated_data['criteria'][1]['levels'][1]['name'] = 'Some new name'
Different names would not help here?

2021-06-12 09:34 UTC, Larspolo commented on src/vue/src/components/assessment/AssessmentGrades.vue
> +                    v-b-tooltip="gradeOverrideTooltip"
It would also be nice to have a visual indication that the grade is manually overwritten in the read mode. Some info icon with this tooltip would do.
![image](https://user-images.githubusercontent.com/11822478/121771822-155c1a80-cb72-11eb-9cee-887544abc5c0.png)

2021-06-12 09:42 UTC, mjvkeulen commented on src/vue/src/components/assessment/AssessmentGrades.vue
> +                    v-b-tooltip="gradeOverrideTooltip"
Done

2021-06-13 12:31 UTC, Larspolo commented on src/django/VLE/models/rubric.py
> +                        if level_data.get('criterion') > 0
@mjvkeulen This now doesnt throw a 500 anymore, but it throws a scilent 400 error (no toast):
![image](https://user-images.githubusercontent.com/11822478/121807337-0352a880-cc54-11eb-8565-9a129869652b.png)

NOTE: between step 1 and step 2 also save the rubric, and start editing it in step 2

2021-06-13 13:47 UTC, mjvkeulen commented on src/vue/src/components/rubric/edit/LevelEdit.vue
> +                name: `Less than ${afterLevel.name}`,
> Clicking the same "+" button twice, creates the error "Level name: Less than Full marks is not unique."

Would otherwise create the error "Name cannot be empty" (just showing that the error argument is not relevant to this discussion)

I am fine with an empty name, I like the less than prefix as it motivates you to work from high to low (similar to how the points are reduced)

2021-06-14 06:45 UTC, mjvkeulen commented on src/django/VLE/models/rubric.py
> +                        if level_data.get('criterion') > 0
Good catch, fixed with dedicated test

2021-06-15 11:30 UTC, Larspolo commented on src/django/VLE/serializers.py
> +        Prefetch('levels', queryset=VLE.models.Level.objects.order_by('location')),
[D] I think I would prefer the `order_by` to be based on `-points` so that the highest amount of points is always left. Can get really confusing if that would not be the case
![image](https://user-images.githubusercontent.com/11822478/122045316-dd590f80-cddd-11eb-9cf3-9a43f6719065.png)

2021-06-15 11:34 UTC, Larspolo commented on src/vue/src/components/rubric/edit/LevelEdit.vue
> +                name: `Less than ${afterLevel.name}`,
Changed it to NIT, to prevent this further halting the PR.

But to also react to you:
> just showing that the error argument is not relevant to this discussion

True, although I find "name cannot be empty" to be a clearer message to the user on what needs to be done. Especially because (at least in Firefox) it highlights the field that needs to be filled.

> similar to how the points are reduced

2021-06-19 19:10 UTC, engelhamer commented on src/vue/src/components/assessment/Assessment.vue
> +        <b-form-group label="Feedback">
I like the current better, actually I think 'overall' is a bit confusing and excessive in some instances already.

2021-06-19 19:10 UTC, engelhamer commented on src/vue/src/components/assessment/AssessmentGrades.vue
> +                return 'Back to default.'
Too long

2021-06-19 19:10 UTC, engelhamer commented on src/vue/src/components/assessment/AssessmentGrades.vue
> +$final-grade-font-size: 1.5em
Would prefer a heading here instead (for consistency).

2021-06-19 19:10 UTC, engelhamer commented on src/vue/src/components/assessment/AssessmentGrades.vue
> +    max-width: 100px
Why not use the `inline` class?

2021-06-19 19:10 UTC, engelhamer commented on src/vue/src/components/assessment/AssessmentGrades.vue
> +    max-width: 100px
Works with em and thus suits the input better probably

2021-06-19 19:10 UTC, engelhamer commented on src/vue/src/components/journal/JournalEndCard.vue
> +                    v-if="assessment && !loading"
Loading should be obsolete giving the load wrapper.

2021-06-19 19:10 UTC, engelhamer commented on src/vue/src/components/profile/NotificationSettings.vue
> +                    description: 'Receive an email when a journal receives an overall assessment.',
In the communication to students, I don't like the term 'overall assessment' as it sounds vague and is not used colloquially. A bit too formal. Do you think we can maybe merge the notification option with entry grades?

2021-06-19 19:10 UTC, engelhamer commented on src/vue/src/views/Assignment.vue
> +                            Sort by assessment
Confusing what the difference with entry is now:

how about
'Sort by marking needed' -> 'Sort by unmarked entries'
'Sort by assessment' -> 'Sort by assessment published'

2021-06-19 19:35 UTC, Larspolo commented on setup.cfg
> +max-function-length = 230
Yeah, not a favour of changing this even higher

2021-06-19 19:36 UTC, Larspolo commented on src/django/VLE/models/rubric.py
> +# QUESTION RUBRIC: Should we enforce max to min (left to right) on the levels of one criterion? So each sequential
Agree, also in another comment somewhere else

2021-06-19 19:39 UTC, Larspolo commented on src/vue/src/components/assessment/AssessmentGrades.vue
> +                return 'Back to default.'
The else case is way longer:
`return 'Override the default grade. Any future grade updates will no longer affect the final grade.'`

2021-06-19 19:40 UTC, Larspolo commented on src/django/test/test_assessment.py
> +        assert teacher.can_edit(assessment), 'Assigned teachers can always edit drafts'
Or test on the permission specific. And then check if both teachers and TAs have that permission by default

2021-06-20 07:31 UTC, mjvkeulen commented on src/vue/src/components/journal/JournalEndCard.vue
> +                    v-if="assessment && !loading"
No, this is something I brought up a couple of times before. The load wrapper does not guard against its content being admitted into the DOM before loading is finished. So initialization issues arise when relying on the load-wrapper for this task.

2021-06-20 07:36 UTC, mjvkeulen commented on src/django/VLE/models/notification.py
> +                'title': 'New overall assessment',
Did you have an alternative in mind?

2021-06-20 07:37 UTC, mjvkeulen commented on src/django/VLE/models/rubric.py
> +# QUESTION RUBRIC: Should we enforce max to min (left to right) on the levels of one criterion? So each sequential
It allows a (stubborn) teacher to work from min to max, or possibly insert a negative number of points (e.g. penalty) in between relevant levels.

This is why I opted to nudge towards max to min, but not to enforce it.

2021-06-20 07:39 UTC, mjvkeulen commented on src/django/VLE/models/rubric.py
> +    initial_feedback = models.TextField(
Default feedback for the selected level

2021-06-20 07:49 UTC, engelhamer commented on src/django/VLE/models/rubric.py
> +    initial_feedback = models.TextField(
I found this feature a bit confusing because that's really what the rubric contents are for

2021-06-20 07:50 UTC, engelhamer commented on src/vue/src/components/journal/JournalEndCard.vue
> +                    v-if="assessment && !loading"
That's weird since the load wrapper literally contains this exact `v-if` too? Hiw is this possible?

2021-06-20 07:52 UTC, mjvkeulen commented on src/vue/src/components/profile/NotificationSettings.vue
> +                    description: 'Receive an email when a journal receives an overall assessment.',
I thought as a student, would I respond differently if my portfolio has received a grade to an individual element, or if my portfolio has received an overall evaluation determining my final grade?

I figured I would care quite a bit more, sufficiently so that I might even configure my notification settings differently between the two types of notifications.

2021-06-20 07:54 UTC, mjvkeulen commented on src/vue/src/components/profile/NotificationSettings.vue
> +                    description: 'Receive an email when a journal receives an overall assessment.',
Regarding the exact phrasing, I am open to suggestions of course. 

I figured with '_overall assessment_', the meaning is quite clear at least. It is the overall assessment of your journal?

2021-06-20 07:56 UTC, mjvkeulen commented on src/vue/src/views/Assignment.vue
> +                            Sort by assessment
I went with 'Sort by unpublished assessments', as I think that is what you wanted and in line with 'Sort by unmarked entries'?

2021-06-20 07:58 UTC, mjvkeulen commented on src/django/VLE/models/rubric.py
> +    initial_feedback = models.TextField(
E.g. a teacher can configure a feedback snippet that is generally applicable when scoring that specific level of a rubric.

2021-06-20 08:03 UTC, mjvkeulen commented on src/vue/src/components/assessment/AssessmentGrades.vue
> +$final-grade-font-size: 1.5em
As in, use an HTML header element?

2021-06-20 08:07 UTC, mjvkeulen commented on src/django/VLE/serializers.py
> +        Prefetch('levels', queryset=VLE.models.Level.objects.order_by('location')),
Let's focus the discussion in the QUESTION thread. 

Just to add on the topic of `order_by '-points'`, we would still need location fields as we allow equal points for two or more levels within a criterion.

2021-06-20 08:08 UTC, mjvkeulen commented on src/django/VLE/models/notification.py
> +                'title': 'New overall assessment',
I figured this was in line with how we approach grades, when a grade is updated we also send a "New Grade" notification afaik.

2021-06-20 08:13 UTC, mjvkeulen commented on src/django/VLE/models/rubric.py
> +    initial_feedback = models.TextField(
I encountered this feature when checking out Brightspace's rubric system and thought it was a nice addition.

2021-06-20 14:02 UTC, Larspolo requested changes

2021-06-20 14:08 UTC, Larspolo commented on src/vue/src/components/rubric/edit/RubricEdit.vue
> +                        Add criterion
Addding a simple criteria to an existing rubric gives me the following 500 error:
![image](https://user-images.githubusercontent.com/11822478/122677236-ccdfd500-d1e1-11eb-8c81-76ad30243e2c.png)

2021-06-20 14:14 UTC, Larspolo commented on src/vue/src/components/rubric/edit/LevelEdit.vue
> +            <b-form-textarea
Would like to be able to resize this in the width as well tbh, that would allow me to read it better / edit the text better.

Or maybe we can wider the text area when clicking on it? So that it automatically is better for writing?

Or possibly also reducing the font size (which also better represents the readmode)?

2021-06-20 14:36 UTC, mjvkeulen commented on src/vue/src/components/rubric/edit/RubricEdit.vue
> +            transform: translateX(50%)
@engelhamer the rounded button is an improvement, but I would prefer if this remains aligned in the middle of a level cell

2021-06-20 14:40 UTC, mjvkeulen commented on src/vue/src/components/rubric/edit/RubricEdit.vue
> +            width: 20px
@engelhamer there is insufficient room for the button once in active state once clicked:

![image](https://user-images.githubusercontent.com/39912610/122678230-2a762080-d1e6-11eb-8fec-2aaa7748d4bb.png)

2021-06-20 14:44 UTC, mjvkeulen commented on src/vue/src/components/assessment/AssessmentGrades.vue
> +                <b>Final grade:</b>
Is it not still displayed for the final grade in read mode?

2021-06-20 14:57 UTC, mjvkeulen commented on src/vue/src/components/assessment/AssessmentGrades.vue
> +                <b>Final grade:</b>
Yes, but not in edit mode. Added to edit mode as well.

2021-06-20 14:59 UTC, mjvkeulen commented on src/vue/src/components/assessment/AssessmentGrades.vue
> +                <b>Final grade:</b>
I like the first suggestion

2021-06-20 15:20 UTC, mjvkeulen commented on src/vue/src/components/rubric/edit/RubricEdit.vue
> +                        Add criterion
Shit, but we do needs steps on how to reproduce this

2021-06-20 15:21 UTC, mjvkeulen commented on src/vue/src/components/journal/JournalDetails.vue
> +
Fixed

2021-06-20 15:21 UTC, mjvkeulen commented on src/vue/src/components/assessment/AssessmentGrades.vue
> +                    v-b-tooltip="'Grade is set manually by the assessor: Any future entry or bonus point updates will '
I am neutral towards this

2021-06-20 15:22 UTC, mjvkeulen commented on src/vue/src/components/assessment/AssessmentGrades.vue
> +                    :placeholder="defaultFinalGrade.toString()"
The old click to edit implementation was a bit more clear for this workflow, but might get repetitive when doing a full assignment.

2021-06-20 15:23 UTC, mjvkeulen commented on src/vue/src/components/rubric/edit/RubricEdit.vue
> +        />
I added it to the journal assessment, but not sure if I would like it here as well.

2021-06-20 15:26 UTC, mjvkeulen commented on src/vue/src/components/rubric/CriterionRow.vue
> +            background-color: #d1ecf1
Should we extract this or make this one of our theme colors?

2021-06-20 15:27 UTC, mjvkeulen commented on src/vue/src/components/rubric/CriterionRow.vue
> +        &.selected
How do you guys feel about the additional borders introduced by the level table horizontally?

![image](https://user-images.githubusercontent.com/39912610/122679839-bc812780-d1ec-11eb-851b-55297bedb09e.png)
![image](https://user-images.githubusercontent.com/39912610/122679848-c6a32600-d1ec-11eb-99df-30752f6c4884.png)

![image](https://user-images.githubusercontent.com/39912610/122679847-c60a8f80-d1ec-11eb-83c1-3a739799e84d.png)

2021-06-20 15:31 UTC, mjvkeulen commented on src/vue/src/components/assessment/AssessmentGrades.vue
> +        <b-tr class="background-light-grey">
This looks a bit funky if there is no content in between

![image](https://user-images.githubusercontent.com/39912610/122679950-4af5a900-d1ed-11eb-9832-e2e03acfdf87.png)

2021-06-20 15:56 UTC, engelhamer commented
Background-light-blue on the mark for assessment branch

Op zo 20 jun. 2021 17:26 schreef mjvkeulen ***@***.***>:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In src/vue/src/components/rubric/CriterionRow.vue
> <https://github.com/eJourn-al/eJournal/pull/1163#discussion_r654951239>:
>
> > +}
> +</script>
> +
> +<style lang="sass">
> ***@***.*** '~sass/partials/rubric.sass'
> +
> +table.criterion-levels
> +    padding: 0px
> +    border-collapse: separate
> +    tr:first-child td
> +        min-width: $rubric-min-cell-width
> +        border-radius: 10px
> +        .level-selected-check
> +            display: none
> +        &.selected
> +            background-color: #d1ecf1
>
> Should we extract this or make this one of our theme colors?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/eJourn-al/eJournal/pull/1163#pullrequestreview-687917647>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJQQJBIZACDHXTLF44POJIDTTYCCDANCNFSM46EG5WFA>
> .
>

2021-06-20 15:56 UTC, engelhamer commented on src/vue/src/components/assessment/AssessmentGrades.vue
> +                    :placeholder="defaultFinalGrade.toString()"
Canvas does it this way too.

2021-06-20 15:57 UTC, engelhamer commented on src/vue/src/components/assessment/AssessmentGrades.vue
> +                <b>Final grade:</b>
Bootstrap table has support for sticky columns, but I think they only stick to the left hand side

2021-06-20 15:59 UTC, engelhamer commented on src/vue/src/components/rubric/edit/RubricEdit.vue
> +            transform: translateX(50%)
It is confusing that when the cells are very large, the button also slides down to maintain in the middle.

2021-06-20 16:00 UTC, engelhamer commented on src/vue/src/components/rubric/edit/RubricEdit.vue
> +            width: 20px
Shall we try to ignore bootstrap accessibility stuff (the outline) here?

2021-06-20 16:01 UTC, engelhamer commented on src/vue/src/components/rubric/CriterionRow.vue
> +        &.selected
I don't really mind, actually I think the sligt padding looks better than if the line would touch the blue shaded area

2021-06-20 16:02 UTC, engelhamer commented on src/vue/src/components/assessment/AssessmentGrades.vue
> +        <b-tr class="background-light-grey">
We could remove the v-if and also show those rows for 0? Would make it nice and consistent across all uses 🙂

2021-06-20 16:02 UTC, engelhamer commented on src/vue/src/components/rubric/CriterionRow.vue
> +            background-color: #d1ecf1
Background-light-blue on mark for assessment branch

2021-06-20 16:10 UTC, Larspolo commented on src/vue/src/components/assessment/AssessmentGrades.vue
> +        <b-tr class="background-light-grey">
I agree with that suggestion

2021-06-20 16:13 UTC, Larspolo commented on src/vue/src/components/rubric/CriterionRow.vue
> +        &.selected
I dont mind it either

2021-06-20 16:18 UTC, Larspolo commented on src/vue/src/components/assessment/AssessmentGrades.vue
> +                    :placeholder="defaultFinalGrade.toString()"
Good enough for me, if also for @mjvkeulen he can resolve this threat

2021-06-20 16:20 UTC, Larspolo commented on src/vue/src/components/rubric/edit/RubricEdit.vue
> +                        Add criterion
```{"id":4,"assignment":1,"name":"Many levels","description":"Rubric description","criteria":[{"id":12,"name":"Overflow","description":"Would rock dream final production person. Seek forget Mrs deal. Think bad something treat end cultural.","location":0,"levels":[{"id":37,"name":"Level 31","description":"Indicate stock mind visit base. Technology involve partner. Ahead item what notice.","points":5,"initial_feedback":"Initial feedback snippet","location":0,"criterion":12,"is_in_use":false},{"id":38,"name":"Level 32","description":"Look traditional while level. Onto physical green blood him property. High though speak move.","points":5,"initial_feedback":"Initial feedback snippet","location":1,"criterion":12,"is_in_use":false},{"id":39,"name":"Level 33","description":"Behind money fish story be imagine attention respond. Reason quickly mind strategy very science.","points":5,"initial_feedback":"Initial feedback snippet","location":2,"criterion":12,"is_in_use":false},{"id":40,"name":"Level 34","description":"Art money door affect. Plan school nothing what sport. Catch themselves impact something hard adult blood.","points":5,"initial_feedback":"Initial feedback snippet","location":3,"criterion":12,"is_in_use":false},{"id":41,"name":"Level 35","description":"Fish all watch. Customer bank apply certain live system together. Little you foreign or.","points":5,"initial_feedback":"Initial feedback snippet","location":4,"criterion":12,"is_in_use":true},{"id":42,"name":"Level 36","description":"Summer not social voice energy left window. Enjoy near country sound.","points":5,"initial_feedback":"Initial feedback snippet","location":5,"criterion":12,"is_in_use":false},{"id":43,"name":"Level 37","description":"Group history follow then once reduce. Issue door lose.","points":5,"initial_feedback":"Initial feedback snippet","location":6,"criterion":12,"is_in_use":false}],"rubric":4,"is_in_use":true},{"id":-1,"name":"Criteria 2","description":"","long_description":"","rubric":4,"location":1,"levels":[{"name":"Full marks","points":10,"location":0,"id":-1},{"name":"No marks","points":0,"location":1,"id":-2}]}],"is_in_use":true}```
Maybe the raw data helps

2021-06-20 16:30 UTC, engelhamer commented on src/vue/src/components/journal/JournalAssessment.vue
> +                : null
Why do you want this to be `null` instead of 0? Is it displayed anywhere?

2021-06-20 16:32 UTC, engelhamer commented
Can give negative assessment:
![image](https://user-images.githubusercontent.com/39912581/122681667-cce9d000-d1f5-11eb-8f0f-24135eb69305.png)

2021-06-20 16:51 UTC, engelhamer commented
![scroll_rubric](https://user-images.githubusercontent.com/39912581/122682215-6d40f400-d1f8-11eb-9205-ecd44ca69864.gif)
Shall we also limit the max width for the cells? This lower table is extremely wide (don't think content is easy to write in this case).

2021-06-20 16:55 UTC, engelhamer commented on src/vue/src/views/Assignment.vue
> +                            Sort by assessment
Yes

2021-06-20 16:56 UTC, engelhamer commented on src/vue/src/components/profile/NotificationSettings.vue
> +                    description: 'Receive an email when a journal receives an overall assessment.',
Throughout my whole student career I have never asked peers about their 'overall assessment', but always about their grade. Even in cases where this was actually an 'overall assessment'.

2021-06-20 16:57 UTC, engelhamer commented on src/django/VLE/models/notification.py
> +                'title': 'New overall assessment',
It would be 'Assessment updated'. But OK for now.

2021-06-20 17:00 UTC, engelhamer commented on src/django/VLE/models/assessment.py
> +            'update_date',
Reverse this, such that the active assessment ends up at the top of the list? This is more convenient than having to scroll down to see the current one.

2021-06-20 19:51 UTC, mjvkeulen commented on src/vue/src/components/journal/JournalAssessment.vue
> +                : null
To me it makes sense that the value is null if no levels / points have been provided

2021-06-20 20:06 UTC, mjvkeulen commented on src/vue/src/components/rubric/edit/RubricEdit.vue
> +            transform: translateX(50%)
The center makes sense, as we are adding another whole level (of the same size as the current row). 

The button on top is as if its related specifically to the name field and not as pleasant on the eyes (not as symmetrical)

2021-06-20 20:09 UTC, mjvkeulen commented on src/django/VLE/models/assessment.py
> +            'update_date',
I believe the entry grade history is also old to new? 

Makes sense when evaluating a chronological list?

2021-06-21 14:44 UTC, mjvkeulen commented on src/vue/src/components/rubric/edit/LevelEdit.vue
> +            <b-form-textarea
Dynamically resizing table cell width sucks, I implemented option two: increase text area width if ever focused.

2021-06-22 09:22 UTC, Larspolo commented
The tutorial does not (yet) include the rubric part, think that might be really useful actually

2021-06-22 11:01 UTC, engelhamer commented on src/django/VLE/models/assessment.py
> +            'update_date',
But having to scroll is not nice.

When e.g. viewing news articles the top results are also most recent, though still in chronological order (just reversed).

2021-06-22 11:01 UTC, engelhamer approved these changes

2021-06-22 11:58 UTC, Larspolo commented on src/vue/src/components/rubric/edit/LevelEdit.vue
> +            <b-form-textarea
Much better! Although it now doesnt shrink when going out of the box, is this intended behaviour or not? Both are fine by me, but wanted your opinions on it too

2021-06-22 11:59 UTC, Larspolo commented on src/vue/src/components/rubric/edit/LevelEdit.vue
> +            <b-form-textarea
Also the criteria description could use this feature, that still stays the same for me

2021-06-22 12:01 UTC, Larspolo commented on src/django/VLE/models/assessment.py
> +            'update_date',
Would expect grade history to also be new to old btw

2021-06-22 12:06 UTC, engelhamer commented
Didn't notice, but would want it to shrink indeed. Definitely not desirable
that the table stays larger.

Op di 22 jun. 2021 13:59 schreef Lars ***@***.***>:

> *@Larspolo* commented on this pull request.
> ------------------------------
>
> In src/vue/src/components/rubric/edit/LevelEdit.vue
> <https://github.com/eJourn-al/eJournal/pull/1163#discussion_r656148706>:
>
> > @@ -0,0 +1,124 @@
> +<template>
> +    <div class="level-container">
> +        <b-form-group>
> +            <b-form-input
> +                v-model="level.name"
> +                placeholder="Name"
> +                type="text"
> +                trim
> +                required
> +            />
> +        </b-form-group>
> +
> +        <b-form-group>
> +            <b-form-textarea
>
> Much better! Although it now doesnt shrink when going out of the box, is
> this intended behaviour or not? Both are fine by me, but wanted your
> opinions on it too
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/eJourn-al/eJournal/pull/1163#discussion_r656148706>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJQQJBN3VWULAXKEV5LKJTLTUB3IPANCNFSM46EG5WFA>
> .
>

2021-06-22 13:30 UTC, Larspolo approved these changes

2021-06-22 13:54 UTC, merged