Added the ability to submit an entire journal for final assessment
eJourn-al/eJournal pull request #1173
Opened 2021-06-13 20:23 UTC by engelhamer

## Description
Added the ability to submit an entire journal for final assessment.

- Can be turned on via an assignment setting:
![image](https://user-images.githubusercontent.com/39912581/121820725-ac20f800-cc94-11eb-96b5-dfd7c3c972ec.png)
- Notifications and TODO's are muted while a journal is not ready for assessment.
- A student sees the following banner in the new 'assessment' panel:
![image](https://user-images.githubusercontent.com/39912581/121820797-face9200-cc94-11eb-955c-f0e1c60d6004.png)
- Once submitted (with a confirmation in case the 'freeze' option is on) the progress bar becomes visible to also make room for the assessment which follows:
![image](https://user-images.githubusercontent.com/39912581/121820825-133eac80-cc95-11eb-94bb-b182761d9841.png)
- Teachers always see the assessment related elements (and can also submit for students):
![image](https://user-images.githubusercontent.com/39912581/121820853-3e290080-cc95-11eb-8f78-0c69c02d5552.png)
- With the freeze option on, only teachers have the ability to cancel a submission:
![image](https://user-images.githubusercontent.com/39912581/121820873-61ec4680-cc95-11eb-974e-4538b5afd925.png)
- Can filter on only submitted journals on the assignment page:
![image](https://user-images.githubusercontent.com/39912581/121820949-db843480-cc95-11eb-8aad-430c9f5a3523.png)

## To do:
- Add tests
- Decide: what to do with drafts?
- Send notification when submitted?

## Summary of changes
- Fixes Z#1485
- Fixes Z#1970 (moved picture to breadcrumb)

2021-06-15 14:44 UTC, Larspolo requested changes

2021-06-15 14:44 UTC, Larspolo commented on src/vue/src/components/journal/JournalDetails.vue
> +                <b class="max-one-line">
I prefered it with the profile picture here as well. Maybe we can also include the profile pictures to the group journal member list

2021-06-15 14:44 UTC, Larspolo commented on src/vue/src/views/Assignment.vue
> +                        @click="setFilterSubmitted(!filterSubmitted)"
It is unclear what will happen when clicking on this button. With descending, the opposite is clear: ascending. But here all journals -> no journals?

2021-06-15 14:44 UTC, Larspolo commented on src/django/VLE/models/notification.py
> +                'content': '{journal} submitted for assessment.',
[NIT] Note that {journal} will often be just the full name (or group name), "full name submitted _their journal_ for assessment" would (I think) be more clear

2021-06-15 14:44 UTC, Larspolo commented on src/vue/src/components/journal/JournalAssessmentCard.vue
> +                Submit for assessment
I dont like how teachers can submit journals for assessment. Its imo really a student action. If we were to include teachers being able to submit for assessment, it should be clarified somewhere who submitted for assessment. At least then the student knows what happened and who to contact.

2021-06-15 14:44 UTC, Larspolo commented on src/vue/src/components/journal/JournalAssessmentCard.vue
> +                && !window.confirm('Are you sure you want to freeze all content and submit this journal?')) {
Also sth like "this action can only be reversed by a teacher" would be nice.

2021-06-15 14:44 UTC, Larspolo commented on src/vue/src/components/entry/Entry.vue
> +                    @finished-uploading-file="uploadingFiles --"
Some merge went wrong here I think. It should trigger the auto save, else the file uploads do not get saved unless text is changed elsewhere

2021-06-15 14:44 UTC, Larspolo commented on src/vue/src/components/assignment/AssignmentDetails.vue
> +            <!-- TODO: Move this block to assessment settings -> New sidebar or tab? -->
Imo also fine as is rn. In need of time, this could be moved to an issue for later

2021-06-15 14:44 UTC, Larspolo commented on src/vue/src/components/assignment/JournalCard.vue
> +            border-radius: 8px !important
Comment profile pictures are still round.

![image](https://user-images.githubusercontent.com/11822478/122070922-a3483780-cdf6-11eb-9a19-5f4ae5de7cb4.png)

2021-06-15 14:44 UTC, Larspolo commented on src/vue/src/components/assignment/JournalCard.vue
> +            border-radius: 8px !important
[NIT] I actually preferred the round look, but also don't care too much

2021-06-15 14:44 UTC, Larspolo commented on src/vue/src/components/assignment_editor/AssignmentEditorDangerZone.vue
> +            expanded: false,
Nice change!

2021-06-15 14:44 UTC, Larspolo commented on src/vue/src/components/category/CategoryMenuItem.vue
> +            :class="{ dirty: isCategoryDirty(category) }"
I prefer the dot outside of the colour, because with the colour being able to be anything, the dot can now get hidden. The dot is the same colour as the 4th colour being picked when adding categories manually

![image](https://user-images.githubusercontent.com/11822478/122071351-f91cdf80-cdf6-11eb-9444-f9206d096988.png)

2021-06-15 14:44 UTC, Larspolo commented on src/vue/src/components/journal/JournalAssessmentCard.vue
> +            This journal is not yet submitted for final assessment.
Would like an extra sentance like "Submitting the journal will notify the teacher that they should start assessing your journal"

2021-06-15 14:44 UTC, Larspolo commented on src/vue/src/components/journal/JournalMembers.vue
> +                            ': click to toggle' : ''}`"
[NIT] could be moved to a computed var for clarity (not introduced in this PR, thats why its NIT)

2021-06-15 14:44 UTC, Larspolo commented on src/vue/src/components/journal/JournalStartCard.vue
> +        </div> -->
This is not needed for this PR right? Would be nice as a zube issue

2021-06-15 14:44 UTC, Larspolo commented on src/vue/src/sass/partials/colors.sass
> +// Bootstrap alert background colors
[Q] why do we not use our theme colours? Or at least include them in theme colours ($theme-light-green or sth)

2021-06-15 15:06 UTC, Larspolo requested changes

2021-06-15 15:06 UTC, Larspolo commented on src/django/VLE/views/assignment.py
> +                (bool, 'remove_grade_upon_leaving_group'),
[NIT] We now actually have a default value that can be supplied here, the following would also work (and remove the `or False` check):
```
             utils.optional_typed_params(
                  ...
                 (bool, 'submit_for_assessment', False),
```

2021-06-15 15:06 UTC, Larspolo commented on src/django/VLE/views/entry.py
> +            return response.forbidden('This journal has been submitted for assessment. You cannot update it anymore')
Missing a "."

2021-06-15 15:06 UTC, Larspolo commented on src/django/VLE/views/entry.py
> +        if (journal.submitted_for_assessment or not assignment.submit_for_assessment) and not entry.is_draft:
[NIT] A function like "needs_submission" would be nice for clarity
```
def needs_submission(self):
    return self.assignment.submit_for_assessment and self.submitted_for_assessment
```
Then we can make this (and in other places) `if not journal.needs_submission() and not entry.is_draft`

2021-06-15 15:06 UTC, Larspolo commented on src/django/test/test_assignment.py
> +# from test.utils.performance import QueryContext
TODO (ofc)

2021-06-15 15:58 UTC, mjvkeulen requested changes
Not finished yet but had some pending comments which conflict with Lars his review so submitting a partial review

2021-06-15 21:18 UTC, Larspolo commented on src/django/VLE/views/journal.py
> +                ).delete()
Feels like this doesnt need a dedicated API call, as it still follows the REST API structure. In the end it is still "just" updating a journal value `submitted_for_assessment`. Problem is that this connects with different permissions, and causes notification triggers. Personally I think this is more about the permission system (and notificaiton system), than it is about the REST API structure. With a better use with serializers, I think we would get a long way as well.

Another simpler solution would be to move this part to a function.

2021-06-15 21:18 UTC, Larspolo commented on src/django/VLE/migrations/0087_submit_for_assessment.py
> +            name='freeze_submitted_for_assessment',
I agree

2021-06-15 21:18 UTC, Larspolo commented on src/vue/src/views/CourseEdit.vue
>                          />
Feels like, if even, something for not this week

2021-06-15 21:20 UTC, Larspolo commented on src/vue/src/views/CourseEdit.vue
> +                            class="shift-up-4"
Personally I found that those text area's already were a good step in directing the student (and teacher) on how this is done. Although i am not opposed to a tutorial for students, I would move this to another issue. If you do want it clearer, we could extent the text a bit as well

Example text message:
![image](https://user-images.githubusercontent.com/11822478/122124946-3fdafb80-ce30-11eb-94d5-42ebec2600ee.png)

2021-06-15 21:24 UTC, Larspolo commented on src/django/VLE/serializers.py
> +        # TODO SUBMIT FOR ASSESSMENT: Hide these as well?
Can see myself in that as well

2021-06-15 21:27 UTC, Larspolo commented on src/django/VLE/serializers.py
> +        return journal.needs_marking
Why then even have the annotations? Now they are no longer truthful. Furthermore, I think this would create extra query calls for each serialized journal, which will be a lot in the assignment overview page

2021-06-16 06:20 UTC, mjvkeulen commented on src/vue/src/components/journal/JournalAssessmentCard.vue
> +                Submit for assessment
Workflow wise it makes sense that a teacher can mark a journal as ready for assessment, this allows them to freeze the state of a journal at a time of their choosing. 

We can argue that the ability for a teacher to lock a journal should be possible via a different path (e.g. lock a selection via filter in the journal overview page / via groups etc). But until we have this functionality, it makes sense to allow some of this functionality via mark for assessment.

I propose we use this issue https://zube.io/ejourn-al/ejournal/c/1975 if we want to continue along this path.

2021-06-16 06:26 UTC, mjvkeulen commented on src/django/VLE/serializers.py
> +        return journal.needs_marking
> Why then even have the annotations? Now they are no longer truthful. This would mean we need this check everywhere else as well

This is what I meant with consistency, I am fine with moving this to logic onto the annotations themselves as well.

> I think this would create extra query calls for each serialized journal

If `assignment` is part of `select_related` this should be no issue.

2021-06-16 06:28 UTC, mjvkeulen commented on src/vue/src/components/assignment/AssignmentDetails.vue
> +            <!-- TODO: Move this block to assessment settings -> New sidebar or tab? -->
Merging comments: 

I like this proposal, would also allow us to create a save dedicated to the assessment-related settings.

Would allow for a dedicated assessment_model view and a bit of cleanup in the assignment patch function!

2021-06-16 06:31 UTC, mjvkeulen commented on src/django/VLE/factory.py
> +    freeze_submitted_for_assessment=False,
I generally still prefer explicit params, of course we have quite some params for this func, but that can also be solved in a different way. E.g. splitting the params passed to assignment, and moving some to `assessment_model`.

2021-06-16 06:34 UTC, mjvkeulen commented on src/django/VLE/serializers.py
> +        #     return None
Can this be resolved seeing the other threads @Larspolo?

2021-06-16 06:37 UTC, mjvkeulen commented on src/django/VLE/serializers.py
> +        if journal.assignment.submit_for_assessment and not journal.submitted_for_assessment:
@Larspolo let's resolve this focus the discussion in the other thread

2021-06-16 06:40 UTC, mjvkeulen commented on src/vue/src/views/CourseEdit.vue
> +                            class="shift-up-4"
Ideally, a teacher would not have to brief their students about marking their journal as ready for assessment at all when using the respective eJournal setting. 

Do you feel this is accomplished as is, from the perspective of a student?

2021-06-16 06:42 UTC, mjvkeulen commented on src/vue/src/views/CourseEdit.vue
>                          />
Requires an additional boolean setting, would qualify as an `if-minor` tag tbh

2021-06-16 06:54 UTC, mjvkeulen commented on src/vue/src/components/journal/JournalDetails.vue
> +                <b class="max-one-line">
I am also attached to the avatar of the journal user showing in the journal assignment details card. 

Was this primarily changed to make some room, or was there another reason?

2021-06-16 07:35 UTC, mjvkeulen requested changes
Did we have some preset DB additions to go alongside this PR?

2021-06-16 07:35 UTC, mjvkeulen commented on src/vue/src/components/assignment/AssignmentDetails.vue
> +                    Require students to explicitly submit their journal before assessment.
Q) Not specifically applicable here, but what motivated the terminology move from `mark` to `submit` for assessment?

2021-06-16 07:35 UTC, mjvkeulen commented on src/vue/src/components/assignment/AssignmentDetails.vue
> +                    The assignment lock date
The assignment lock date?

2021-06-16 07:35 UTC, mjvkeulen commented on src/vue/src/components/assignment/AssignmentDetails.vue
> +                    This will mute any notifications for teachers about intermediate journal submissions.
[NIT] Could the "for teachers" not be omitted?

2021-06-16 07:35 UTC, mjvkeulen commented on src/vue/src/components/assignment/AssignmentDetails.vue
> +            <div
![image](https://user-images.githubusercontent.com/39912610/122173592-2c588080-ce82-11eb-8e79-4eed81531cf2.png)

D) As this is a subsetting of submit_for_assessment, I would expect both settings to share the same border? Especially because we now have two groups of settings, assessment and group assignment

![image](https://user-images.githubusercontent.com/39912610/122173979-9ec96080-ce82-11eb-95db-24acde1ec33e.png)

2021-06-16 07:35 UTC, mjvkeulen commented on src/vue/src/components/journal/JournalAssessmentCard.vue
> +</style>
Left over

2021-06-16 07:35 UTC, mjvkeulen commented on src/vue/src/components/journal/JournalAssessmentCard.vue
> +<template>
Consolidating grading and assessment settings into a card like this seems like a good choice.

Q) Are we worried about how the "assessment" header could send a wrong message for ungraded assignments? For this scenario "Journal details" was a bit more of a neutral term.

2021-06-16 07:35 UTC, mjvkeulen commented on src/vue/src/components/journal/JournalNonStudent.vue
> +    border: 1px solid $text-color
This is shared between both journal components

2021-06-16 08:14 UTC, Larspolo commented on src/vue/src/components/journal/JournalAssessmentCard.vue
> +                Submit for assessment
Maybe we can simply change the button name to "lock journal"?

2021-06-16 08:15 UTC, Larspolo commented on src/vue/src/views/CourseEdit.vue
> +                            class="shift-up-4"
I almost did. Think with an extra sentance (like I said n another thread) would make it work

2021-06-18 15:11 UTC, mjvkeulen commented on src/vue/src/components/journal/JournalAssessmentCard.vue
> +                Submit for assessment
This might make sense from a teacher's perspective?

2021-06-18 15:17 UTC, mjvkeulen commented on src/vue/src/components/journal/JournalStudent.vue
> +                />
Would these changes not qualify for a dedicated PR?

2021-06-18 15:29 UTC, mjvkeulen commented on src/vue/src/components/journal/JournalAssessmentCard.vue
> +                        this.$toasted.success('Cancelled submission for assessment.')
Tagging pending Lars his proposal

2021-06-18 15:31 UTC, mjvkeulen commented on src/vue/src/sass/partials/columns.sass
> +        padding-left: 30px !important
Q) Is this some particular value that should be respected?

2021-06-18 15:34 UTC, engelhamer commented on src/vue/src/components/journal/JournalStudent.vue
> +                />
I changed the details card as well, thought this was a small change to fix a bug in the process.

2021-06-18 15:34 UTC, engelhamer commented on src/vue/src/sass/partials/columns.sass
> +        padding-left: 30px !important
Only in this file

2021-06-19 19:51 UTC, engelhamer commented on src/vue/src/components/journal/JournalDetails.vue
> +                <b class="max-one-line">
Mostly to make room and fix the issue quickly. Also: for 99% of the people this picture is identical, and thus does not matter as much?

2021-06-19 19:52 UTC, engelhamer commented on src/vue/src/views/Assignment.vue
> +                        @click="setFilterSubmitted(!filterSubmitted)"
There is no room for a much longer text: what would you like? Also it does not harm clicking it once to see what happens, I think that should be alright.

2021-06-19 19:54 UTC, engelhamer commented on src/vue/src/components/journal/JournalAssessmentCard.vue
> +                Submit for assessment
But then the student sees 'submitted for assessment' whereas the teacher may not know they caused this.

2021-06-19 19:57 UTC, engelhamer commented on src/vue/src/sass/partials/colors.sass
> +// Bootstrap alert background colors
These should only be used for these particular background color classes. The theme colors are too dark for readable black text in front, and also draw too much attention.

2021-06-19 20:00 UTC, engelhamer commented on src/vue/src/views/CourseEdit.vue
> +                            class="shift-up-4"
I think it is clear as is: there is a banner-like message with a background in a different color. Also, the teacher can tell their students if they want.

2021-06-19 20:01 UTC, engelhamer commented on src/django/VLE/migrations/0087_submit_for_assessment.py
> +            name='freeze_submitted_for_assessment',
It is not really, although 'lock' is more permanent (lock date passes means that really NOTHING AT ALL can be done anymore. Whereas this can be canceled easily.

2021-06-19 21:16 UTC, Larspolo commented on src/django/VLE/factory.py
> +    freeze_submitted_for_assessment=False,
So you dont like that Django automatically accepts any value in the `Model.objects.create()`? You would prefer manually having to add all the model variables to the create function?

2021-06-19 21:18 UTC, Larspolo commented on src/vue/src/components/journal/JournalAssessmentCard.vue
> +                Submit for assessment
They would still have the yellow/green message popup. Maybe we could add some text there if it would not already be clear

2021-06-19 21:19 UTC, Larspolo commented on src/vue/src/views/Assignment.vue
> +                        @click="setFilterSubmitted(!filterSubmitted)"
Checkbox with "Only submitted for assessment"?

2021-06-19 21:20 UTC, Larspolo commented on src/vue/src/components/journal/JournalDetails.vue
> +                <b class="max-one-line">
Good enough for me if it was a quick fix for an issue. I cannot remmeber what issue though, can you link it?

2021-06-26 14:44 UTC, engelhamer commented on src/vue/src/components/journal/JournalDetails.vue
> +                <b class="max-one-line">
https://zube.io/ejourn-al/ejournal/c/1970

2021-06-26 17:38 UTC, Larspolo commented on src/vue/src/components/journal/JournalStudent.vue
> +                />
I agree here with Maarten, this way you kinda "force" certain changes by including it in an important much bigger branch. A quick bugfix in between can also be done by committing, checkout to develop, create new branch, fix issue, push, create PR, and switch back

2021-06-28 06:19 UTC, mjvkeulen commented on src/vue/src/components/journal/JournalStudent.vue
> +                        @updated-journal="loadJournal"
When does the student journal view get updated?

2021-06-28 07:19 UTC, mjvkeulen commented on src/django/VLE/factory.py
Moving this to its own thread:

Did we have some preset DB additions to go alongside this PR?

2021-06-28 07:37 UTC, mjvkeulen commented on src/vue/src/components/journal/JournalAssessmentCard.vue
> +                || $hasPermission('can_grade')"
[NIT] Time to move these to computed proprties

2021-06-28 07:37 UTC, mjvkeulen commented on src/vue/src/components/journal/JournalAssessmentCard.vue
> +                    && ($hasPermission('can_manage_journals') || $hasPermission('can_have_journal'))"
The block above holds can_grade

2021-07-01 11:19 UTC, Larspolo commented on src/vue/src/components/assignment/JournalCard.vue
> +            border-radius: 8px !important
Not that I can see

2021-07-01 11:20 UTC, Larspolo commented on src/vue/src/components/assignment/AssignmentDetails.vue
> +                    Final submission for assessment
Changed to "Require submission for assessment". If this is still unclear, a suggestion would help

2021-07-01 11:21 UTC, Larspolo commented on src/vue/src/components/assignment/AssignmentDetails.vue
> +                    Require students to explicitly submit their journal before assessment.
sth for @engelhamer

2021-07-01 11:23 UTC, Larspolo commented on src/vue/src/components/assignment/AssignmentDetails.vue
> +            <div
Now we dont anymore. Does this feel alright now?
![image](https://user-images.githubusercontent.com/11822478/124116734-915dca00-da6f-11eb-80d6-a7bc5b781daf.png)

2021-07-01 11:25 UTC, Larspolo commented on src/vue/src/components/journal/JournalNonStudent.vue
> +    border: 1px solid $text-color
There is quite a lot shared. What do you suggest here? I feel like there are up and downsides to either approach

2021-07-01 11:26 UTC, Larspolo commented on src/vue/src/components/journal/JournalStudent.vue
> +                        @updated-journal="loadJournal"
When a student requests for assessment

2021-07-01 11:27 UTC, Larspolo commented on src/vue/src/components/journal/JournalAssessmentCard.vue
> +                    && ($hasPermission('can_manage_journals') || $hasPermission('can_have_journal'))"
Jup, this specific section does not need the `can_grade` permission

2021-07-01 12:27 UTC, Larspolo commented on src/vue/src/components/journal/JournalAssessmentCard.vue
> +<template>
We still have the "detials" card as well. For me this is no problem

2021-07-01 15:01 UTC, mjvkeulen commented on src/vue/src/components/assignment/JournalCard.vue
> +            border-radius: 8px !important
Ditto (but likewise NIT and not significant to me)

2021-07-01 15:02 UTC, mjvkeulen commented on src/vue/src/components/journal/JournalMembers.vue
> +                            ': click to toggle' : ''}`"
Not sure if this is a NIT, 4 lines in html with 3 ternaries ^^

2021-07-01 15:04 UTC, mjvkeulen commented on src/django/VLE/tasks/notifications.py
> +    for user in VLE.permissions.get_supervisors_of(journal):
Imo ideally the student gets a notifications that their journal was submitted for assessment by teacher X

2021-07-01 15:08 UTC, mjvkeulen commented on src/vue/src/components/assignment/AssignmentDetails.vue
> +            <div
Menu looks fine, comment holds but can be moved to NIT

2021-07-01 15:09 UTC, mjvkeulen commented on src/vue/src/components/journal/JournalNonStudent.vue
> +    border: 1px solid $text-color
I don't think I see the downside, is most (all?) not simply duplication?

2021-07-02 20:26 UTC, Larspolo commented on src/django/VLE/factory.py
Added

2021-07-02 20:41 UTC, Larspolo commented on src/vue/src/components/journal/JournalNonStudent.vue
> +    border: 1px solid $text-color
I was speaking about the whole component, there is a lot of changes between the two. Where do we put styling that is "only" used in two components?

2021-07-02 20:44 UTC, Larspolo commented on src/vue/src/components/assignment/AssignmentDetails.vue
> +            <div
https://zube.io/ejourn-al/ejournal/c/2036

2021-07-02 21:01 UTC, Larspolo commented on src/vue/src/components/journal/JournalMembers.vue
> +                            ': click to toggle' : ''}`"
I dont think we should ever require something to be fixed that is not introduced in the PR. But it is fixed anyway

2021-07-02 21:02 UTC, Larspolo commented on src/django/VLE/tasks/notifications.py
> +    for user in VLE.permissions.get_supervisors_of(journal):
Moving to issue? Might align more with the upcoming(?) "lock journal" issue

2021-07-02 21:05 UTC, Larspolo commented on src/vue/src/views/CourseEdit.vue
>                          />
Moved to an issue, if you want, you can create a PR

2021-07-02 21:08 UTC, Larspolo commented on src/django/VLE/migrations/0087_submit_for_assessment.py
> +            name='freeze_submitted_for_assessment',
That would be getting too long to even fit a simple variable assignment on a single line of 120 characters
```
            assessment_model.freeze_journals_once_submitted_for_assessment = freeze_journals_once_submitted_for_assessment
```
A shorter suggestion would be nicer

2021-07-03 06:36 UTC, mjvkeulen commented on src/vue/src/components/journal/JournalStudent.vue
> +                        @updated-journal="loadJournal"
This is the `JournalStudent` component, from your comment I infer that this can be omitted?

2021-07-03 06:38 UTC, mjvkeulen commented on src/vue/src/components/journal/JournalNonStudent.vue
> +    border: 1px solid $text-color
The journal-image stuff can go into `images.sass`, other shared css can go in `sass/partials/journal.sass` if there is no other common denominator.

2021-07-03 06:39 UTC, mjvkeulen commented on src/vue/src/components/journal/JournalStartCard.vue
> +        </div> -->
Tagging so the commented code is moved to the issue as well.

2021-07-03 06:43 UTC, mjvkeulen commented on src/vue/src/components/assignment/AssignmentDetails.vue
> +                    Final submission for assessment
Request(ing) assessment?

2021-07-03 06:58 UTC, mjvkeulen commented on src/vue/src/components/assignment_editor/timeline_controlled/assignment/AssessmentModelEdit.vue
> +                Require students to explicitly submit their journal before assessment.
Require students to mark their journal as ready to be assessed.

2021-07-03 06:58 UTC, mjvkeulen commented on src/vue/src/components/assignment_editor/timeline_controlled/assignment/AssessmentModelEdit.vue
> +                This will mute any notifications about intermediate journal submissions.
This will mute intermediate journal submission notifications.

2021-07-03 07:03 UTC, mjvkeulen commented on src/django/VLE/tasks/notifications.py
> +    for user in VLE.permissions.get_supervisors_of(journal):
This action significantly impacts a user: student has no idea why they no longer can make any edits to their journal. What/who caused this. 

Simply informing (notification) the user would go a long way to resolving this issue. I expect (bulk) lock journal functionality will not be here for a long time.

2021-07-03 07:10 UTC, mjvkeulen commented on src/django/VLE/factory.py
> +    freeze_submitted_for_assessment=False,
The parallel you chose fits well. 

The problem might be my IDE config:

![image](https://user-images.githubusercontent.com/39912610/124346325-7067b700-dbde-11eb-9b74-96084b015bea.png)

![image](https://user-images.githubusercontent.com/39912610/124346340-84131d80-dbde-11eb-9eed-cb733f85412b.png)

Where I prefer the second, apart from that I agree with your argument!

2021-07-03 07:14 UTC, mjvkeulen commented on src/vue/src/components/journal/JournalAssessmentCard.vue
> +                Submit for assessment
> But then the student sees 'submitted for assessment' whereas the teacher may not know they caused this.

To me this argument is sufficient to keep the terminology equal between student and teacher. 

> Maybe we could add some text there if it would not already be clear

Did you have an example of how we could compensate for this with some extra text?

2021-07-03 07:15 UTC, mjvkeulen commented on src/vue/src/views/Assignment.vue
> +                        @click="setFilterSubmitted(!filterSubmitted)"
Fine by me but omit "Only" imo

2021-07-03 07:17 UTC, mjvkeulen commented on src/vue/src/components/assignment/JournalCard.vue
> +            border-radius: 8px !important
Seeing how often this rule is used it is time for one.

```
$default-border-radius: 8px

%default-border
    border-radius: $default-border-radius
    ... (w/e else is shared)
```

2021-07-03 07:23 UTC, mjvkeulen commented on src/django/VLE/migrations/0087_submit_for_assessment.py
> +            name='freeze_submitted_for_assessment',
I disagree, a lock is designed to be unlocked as well. There is no more permanency to the terminology of `lock` than `frozen`. 

We should just use one of the two terms: I suggest lock as that is already embedded more deeply and requires less work.

2021-07-03 07:27 UTC, mjvkeulen commented on src/django/VLE/migrations/0087_submit_for_assessment.py
> +            name='freeze_submitted_for_assessment',
`lock_submitted_journals`

2021-07-03 07:41 UTC, mjvkeulen commented on src/vue/src/views/CourseEdit.vue
> +                            class="shift-up-4"
When a student first loads their journal they are presented with "Assignment details", the starting point (and node) of their journal. 

After reading the information provided here, a user should be able to understand what is expected of them. Hopefully the teacher adds a meaningful description, but any eJournal rules (such as mark for assessment), should be clearly explained here as well.

I could see this as a block below the assignment description where we explain some eJournal (assignment settings) related rules.

This also has the benefit that the read mode of assignment details more clearly reflects the assignment settings.

2021-07-03 07:47 UTC, mjvkeulen commented on src/vue/src/views/CourseEdit.vue
> +                            class="shift-up-4"
Created an issue for this: https://zube.io/ejourn-al/ejournal/c/2040 considering our deadline

2021-07-03 09:18 UTC, mjvkeulen commented on src/django/VLE/views/entry.py
> +        ):
This check also needs to be added to entry partial update

2021-07-03 09:24 UTC, mjvkeulen commented on src/django/VLE/views/entry.py
>              grading.task_journal_status_to_LMS.delay(journal.pk)
Tagging to ensure this conditional block is not skipped in the tests

2021-07-03 09:58 UTC, Larspolo commented on src/vue/src/components/journal/JournalAssessmentCard.vue
> +                Submit for assessment
No, I already found it pretty clear

2021-07-03 10:18 UTC, Larspolo commented on src/vue/src/components/assignment/AssignmentDetails.vue
> +                    Final submission for assessment
Note that this is the teacher's settings of whether students should submit before hand. Would "Require assessment request" work better?

2021-07-03 19:02 UTC, Larspolo commented on src/vue/src/components/assignment_editor/timeline_controlled/assignment/AssessmentModelEdit.vue
> +                Require students to explicitly submit their journal before assessment.
We didnt want to use "mark" anymore rigth? Does this suggestion still hold?

2021-07-03 20:18 UTC, Larspolo commented on src/django/VLE/views/entry.py
>              grading.task_journal_status_to_LMS.delay(journal.pk)
Tag is fine, but I think you overestimate the importance of testing this is. This is only about if the background task should run or not. Determining if the teacher should retrieve a TODO is done in the background task itself

2021-07-03 20:19 UTC, Larspolo commented on src/vue/src/components/journal/JournalStudent.vue
> +                        @updated-journal="loadJournal"
Removed it

2021-07-04 07:07 UTC, mjvkeulen commented on src/vue/src/components/assignment_editor/timeline_controlled/assignment/AssessmentModelEdit.vue
> +                Require students to explicitly submit their journal before assessment.
Doesn't hold anymore. 

I would still change `before` -> `to`. Submit before is quite formal.

2021-07-04 07:14 UTC, mjvkeulen commented on src/vue/src/components/assets/NumberBadge.vue
>  <template>
`Sort by unpublished assessments` no longer shows as a sort option for the `Assignment` view. Is this cause by some of the conditional assignment `stats` serialization?

2021-07-04 07:17 UTC, mjvkeulen commented on src/vue/src/components/assignment_editor/timeline_controlled/assignment/AssessmentModelEdit.vue
> +                    this.$toasted.success('Updated assessment settings.')
This is now the only component in the assignment editor which toasts on success

2021-07-04 07:18 UTC, mjvkeulen commented on src/vue/src/components/assignment_editor/timeline_controlled/assignment/AssessmentModelEdit.vue
> +                    this.$toasted.success('Updated assessment settings.')
Is this done because the journal end card read mode sucks?

2021-07-04 07:20 UTC, mjvkeulen commented on src/vue/src/views/Assignment.vue
> +                    <b-button
When filtering on only submitted for assessment the statistics card average points becomes empty, this should be zero similar to the other stats listed there.

![image](https://user-images.githubusercontent.com/39912610/124376770-e9334580-dca8-11eb-8f4d-5959dc038be4.png)

2021-07-04 07:22 UTC, mjvkeulen commented on src/vue/src/components/journal/JournalAssessmentCard.vue
> +            <b-button
Submit for assessment triggers a Internal Server Error: /journals/<jID>/ atm!

2021-07-04 07:23 UTC, mjvkeulen commented on src/vue/src/components/journal/JournalAssessmentCard.vue
> +            <b-button
Tests better be failing atm ^^

2021-07-04 07:24 UTC, mjvkeulen commented on src/vue/src/components/journal/JournalAssessmentCard.vue
> +            <b-button
`Permission can_manage_journals is not a general level permission.`

2021-07-04 07:26 UTC, mjvkeulen commented on src/vue/src/components/journal/JournalAssessmentCard.vue
> +            </template>
I would expect this block to be in another div with a more "danger-zone-esque" like background.

2021-07-04 07:30 UTC, mjvkeulen commented on src/vue/src/components/journal/JournalAssessmentCard.vue
> +        </b-card-body>
Students lost the ability to see the progress of their peers before they submit their journal (and possibly lock it). 

This makes no sense to me, I would expect this to be still visible I think? 

E.g. if a half of my peers have already submitted their journals and have received an assessment I would hope to see this here so I can be motivated to finish as well?

2021-07-04 11:54 UTC, Larspolo commented on src/vue/src/components/assignment_editor/timeline_controlled/assignment/AssessmentModelEdit.vue
> +                    this.$toasted.success('Updated assessment settings.')
Kinda yeah, because there is no other visual indication that the values actually changed

2021-07-04 11:55 UTC, Larspolo commented on src/vue/src/views/Assignment.vue
> +                    <b-button
https://zube.io/ejourn-al/ejournal/c/1526

2021-07-04 11:56 UTC, Larspolo commented on src/vue/src/components/journal/JournalAssessmentCard.vue
> +            <b-button
One of the three functions that I did not test yet ;)

2021-07-04 12:00 UTC, Larspolo commented on src/vue/src/components/journal/JournalAssessmentCard.vue
> +            </template>
I dont see how this can be nicely done. We have an alert already. Do you have a suggestion? I found the red background being too intrusive (its reversable, and nor requires immediate action):
![image](https://user-images.githubusercontent.com/11822478/124384090-19daa580-dcd0-11eb-8276-93b7a734d0be.png)

2021-07-04 12:02 UTC, Larspolo commented on src/vue/src/components/journal/JournalAssessmentCard.vue
> +        </b-card-body>
:shrug: I might agree. I think this was an intentional decision by @engelhamer

2021-07-04 13:43 UTC, mjvkeulen commented on src/vue/src/components/assignment_editor/timeline_controlled/assignment/AssessmentModelEdit.vue
> +                    this.$toasted.success('Updated assessment settings.')
Fine we have an outstanding issue which aims to address the view mode of the card, we can tackle it there and keep the toast till then.

2021-07-04 14:45 UTC, mjvkeulen approved these changes

2021-07-04 14:46 UTC, Larspolo approved these changes

2021-07-04 15:34 UTC, merged