Fixed an issue where pending comments would not be published when publishing a grade
eJourn-al/eJournal pull request #1175
Opened 2021-06-19 16:41 UTC by Larspolo

## Description
Fixed an issue where pending comments would not be published when publishing a grade

I suggest watching the files not in diff mode, because somehow that became a real mess

## Summary of changes
- Fixes [Z#1988](https://zube.io/ejourn-al/ejournal/c/1988)
- Fixes [Z#1985](https://zube.io/ejourn-al/ejournal/c/1985)

Not [Z#1987](https://zube.io/ejourn-al/ejournal/c/1987)

2021-06-21 13:07 UTC, mjvkeulen commented on src/django/test/test_import_utils.py
> +    def test_select_vle_coupling_based_on_jir_action(self):
Isnt the old name more appropriate seeing the function is defined as `_select_vle_coupling_based_on_jir_action`?

2021-06-21 13:42 UTC, Larspolo commented on src/django/test/test_import_utils.py
> +    def test_select_vle_coupling_based_on_jir_action(self):
Oww, missed that

2021-06-22 08:18 UTC, mjvkeulen requested changes
Great find, can't believe this was an issue!

On the two items addressed

#### Publishing pending comments
- Good test for creating a newly published grade
- Missing test for publishing all assignment grades / all journal grades. Both call `publish_grades`, so just testing that function in this regard would be sufficient. I believe publish all assignment grades already asserts `publish_grades` is called, not sure about publishing all journal grades.

#### Publishing grade should sent notification to the LMS (Z#1988)
- This seems addressed in the code but is missing an added test.

I took the liberty of rewriting `update_entries_to_most_recent_grade` into a single query and adding it to the entry queryset as `update_link_to_most_recent_grade` and added a unit test for it.

2021-06-22 09:18 UTC, mjvkeulen requested changes

2021-06-22 09:18 UTC, mjvkeulen commented on src/django/test/test_assignment.py
> +            factory.Comment(entry=grade.entry, published=False)
Q) Comments are created but no sequential check follows?

2021-06-22 09:18 UTC, mjvkeulen commented on src/django/test/test_assignment.py
> +            assert to_lms.called, \
Safer to use `assert_called_with` where possible

2021-06-22 09:18 UTC, mjvkeulen commented on src/django/test/test_journal.py
> +        assert publish_grades.called, \
Ditto

2021-06-22 11:13 UTC, Larspolo commented on src/django/test/test_assignment.py
> +            factory.Comment(entry=grade.entry, published=False)
Whoops, fixed now

2021-06-22 11:32 UTC, engelhamer approved these changes

2021-06-22 13:54 UTC, mjvkeulen approved these changes

2021-06-22 14:20 UTC, merged