Added the ability to display entry field descriptions as popover
eJourn-al/eJournal pull request #1197
Opened 2021-07-05 07:22 UTC by mjvkeulen

Fixes Z#2029

2021-07-06 11:42 UTC, engelhamer reviewed
I understand the need to view the description while grading, but do not think that a popover is the most accessible and appealing solution. How about:

2021-07-06 11:42 UTC, engelhamer commented on src/vue/src/components/entry/EntryFields.vue
> +                <icon
I don't really like the look of this icon when there is no title. Also in combination with the 'optional' tag there appears a lot of content whereas a teacher intentionally leaves a part untitled.

![image](https://user-images.githubusercontent.com/39912581/124594164-c6975d00-de5f-11eb-88e5-6f36e9c058fd.png)

The popover is very small (limited in width) and does not behave well with scrolling and a lot of content (which is sometimes the case in practice).

2021-07-06 12:38 UTC, mjvkeulen commented on src/vue/src/components/entry/EntryFields.vue
> +                <icon
> I don't really like the look of this icon when there is no title. Also in combination with the 'optional' tag there appears a lot of content whereas a teacher intentionally leaves a part untitled.

I agree it does not look pretty when there is a description but no title, however using a different icon will not address this.

I can move the display to an inline toggle, I could also fix the limited width and scrolling issue. 

I originally went for the popover solution as allows for a brief hover without disturbing where a teacher is in the document.  Personally, I feel this fits the workflow of a teacher most. Expanding the description shifts the entry and mixes the description with the answer.

2021-07-06 14:46 UTC, Larspolo requested changes
Looking good!

2021-07-06 14:46 UTC, Larspolo commented on src/vue/src/components/entry/EntryFields.vue
> +                    'required': field.required,
If we do decide to also use the required symbol, then this should also be used in the edit mode:
![image](https://user-images.githubusercontent.com/11822478/124619802-40881000-de79-11eb-8608-db64df522fbd.png)

2021-07-06 14:46 UTC, Larspolo commented on src/vue/src/sass/partials/popover.sass
> +        border-bottom: 1px solid $border-color
Headers are also bold

2021-07-06 14:46 UTC, Larspolo commented on src/vue/src/sass/partials/popover.sass
> +    border-radius: 10px
[NIT] Should we make this a variable ;)

2021-07-06 14:46 UTC, Larspolo commented on src/vue/src/components/entry/EntryFields.vue
> +                    :id="`field-${field.id}-description-info`"
This will cause duplicate key errors when switching nodes with same template. Thats why other keys also use the node id, e.g.: `node-${nodeID}-field-${field.id}`. I suggest also using that here (and line 54 then as well)

2021-07-06 14:47 UTC, Larspolo commented on src/vue/src/components/entry/EntryFields.vue
> +                <icon
The option "Truncating the text to fit a line, then showing 'more...' to toggle the full description" also sounds nice though. I see the shifting stuff, but with sizable descriptions, this option will also cause problems, as the description might go out of view

2021-07-09 11:37 UTC, mjvkeulen commented on src/vue/src/components/entry/EntryFields.vue
> +                <icon
Do we have something in place to truncate a sandboxed iframe's content?

2021-09-03 16:18 UTC, Larspolo commented on src/vue/src/components/entry/EntryFields.vue
> +                    'required': field.required,
@mjvkeulen this is still a thing

2021-09-06 12:59 UTC, engelhamer approved these changes

2021-09-07 14:49 UTC, mjvkeulen commented on src/vue/src/components/entry/EntryFields.vue
> +                    'required': field.required,
@engelhamer opinion?

2021-09-15 14:10 UTC, engelhamer commented on src/vue/src/components/entry/EntryFields.vue
> +                    'required': field.required,
I would prefer it to be EITHER star OR <optional> in one form. Not both.

2021-09-15 15:11 UTC, Larspolo approved these changes

2021-09-15 18:36 UTC, merged