Fixed an issue where locked nodes still displayed in edit mode
eJourn-al/eJournal pull request #1204
Opened 2021-07-07 14:06 UTC by Larspolo

## Description
Added "locked" icon, and changed draft message for locked drafts to exclude the "submit below" text
![image](https://user-images.githubusercontent.com/11822478/124773411-39c2d100-df3d-11eb-8a93-af442f89cec7.png)

## Summary of changes
- Fixes Z#1856
- Fixes Z#1971
- Did not fix https://zube.io/ejourn-al/ejournal/c/1881

2021-07-09 11:51 UTC, mjvkeulen requested changes
Error whilst attempting to create an entry for a deadline

![image](https://user-images.githubusercontent.com/39912610/125073798-c8119100-e0bc-11eb-9ab4-57b8de2f5830.png)

2021-09-03 07:42 UTC, mjvkeulen approved these changes

2021-09-06 13:44 UTC, engelhamer requested changes

2021-09-06 13:44 UTC, engelhamer commented on src/vue/src/components/entry/Entry.vue
> +                {{ node.entry.editable ? 'until you submit it below.' : 'and cannot be submitted (locked).' }}
`..anymore` ?

2021-09-06 13:44 UTC, engelhamer commented on src/vue/src/components/timeline/TimelineNodeCircle.vue
> +                return 'fill-grey'
I prefer grey icons to use the default behaviour below, since they are then white if the node is selected. Grey on dark blue can be tough on the eyes.

2021-09-07 07:45 UTC, Larspolo commented on src/vue/src/components/timeline/TimelineNodeCircle.vue
> +                return 'fill-grey'
Good one, fixed

2021-09-07 08:24 UTC, engelhamer requested changes

2021-09-07 08:24 UTC, engelhamer commented on src/vue/src/components/timeline/TimelineNodeCircle.vue
> +            // console.log((!entry || entry.is_draft))
Debug logs

2021-09-07 09:27 UTC, Larspolo commented on src/vue/src/components/timeline/TimelineNodeCircle.vue
> +            console.log(this.node)
```suggestion

```

2021-09-08 16:54 UTC, engelhamer approved these changes

2021-09-08 16:54 UTC, merged