Fixed an issue where the last edited and creation date of entries were wrong
eJourn-al/eJournal pull request #1211
Opened 2021-09-07 09:33 UTC by Larspolo

EJ-789 #close

2021-09-15 12:59 UTC, mjvkeulen requested changes

2021-09-15 12:59 UTC, mjvkeulen commented on src/django/VLE/models/entry.py
> +    first_posted = models.DateTimeField(
We use submit for our buttons that perform this action, how about `first_submitted`?

2021-09-15 12:59 UTC, mjvkeulen commented on src/django/VLE/models/entry.py
> +    last_edited = models.DateTimeField(
[NIT]: I wouldn't mind a docstring or comment explaining the differences between the date fields.

2021-09-15 12:59 UTC, mjvkeulen commented on src/django/VLE/models/entry.py
> +        # Entries should update last edited when it is switched from draft to no draft
I would still like to be able to determine when a student made the last edit to entries for drafts. So we would still be able to determine the activity for drafted entries.

I don't believe `update_date` suffices, when content is updated the entry is not saved again by definition.

I do agree that last_edit in the eyes of the teacher makes more sense as it's rewritten in this PR.

So does this mean we need another field that is always updated in the manner `last_edited` was before this PR? (After each entry create or update request).

2021-09-15 13:00 UTC, engelhamer approved these changes

2021-09-15 13:50 UTC, Larspolo commented on src/vue/src/components/entry/EntryNonStudent.vue
> +                        <!-- Last edited is only displayed if its edited later then three minutes after posting -->
Created issue

2021-09-15 13:54 UTC, Larspolo commented on src/vue/src/components/entry/EntryNonStudent.vue
> +                <!-- TODO: find out what this is again -->
Jup, grade creation date, not entry creation, so its all good

2021-09-15 13:55 UTC, mjvkeulen commented on src/django/VLE/models/entry.py
> +        # Entries should update last edited when it is switched from draft to no draft
Tracking when any entry was last edited (as before this PR), doesn't seem like some obscure use case?

2021-09-15 14:00 UTC, engelhamer commented
But this shouldn't matter for drafts? It's all the studentsm's business and
only becoems relevant from when the entry is submitted/posted.

Op wo 15 sep. 2021 15:56 schreef mjvkeulen ***@***.***>:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In src/django/VLE/models/entry.py
> <https://github.com/eJourn-al/eJournal/pull/1211#discussion_r709213664>:
>
> > @@ -273,18 +285,22 @@ def link_categories(self, category_ids):
>          ]
>          VLE.models.EntryCategoryLink.objects.bulk_create(entry_category_links)
>
> -    def should_send_new_entry_notification(self, is_new, was_draft):
> +    def should_update_last_edited(self, was_draft):
> +        # Entries should update last edited when it is switched from draft to no draft
>
> Tracking when any entry was last edited (as before this PR), doesn't seem
> like some obscure use case?
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/eJourn-al/eJournal/pull/1211#discussion_r709213664>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJQQJBNITKDHVBR25RJJZ73UCCQXXANCNFSM5DR7G37A>
> .
>

2021-09-15 14:05 UTC, Larspolo commented on src/django/VLE/models/entry.py
> +        # Entries should update last edited when it is switched from draft to no draft
The case for this specific feature was teacher focussed

2021-09-18 11:41 UTC, mjvkeulen requested changes
Entry model now has the following date fields::
- creation_date (draft start)
- update_date (awkward right now, should be updated whenever the entry title or content is - - updated (what last_edited is atm)
- first_submitted (I like this addition)
- last_edited (staat nu weer goed)

I would like to maintain the functionality of what last_edited does currently, this would allow us to gain insights into when the user was working on an entry last.

To achieve this I would leave `update_date` alone, as throughout our models this consistently displays when a model's concrete fields were updated last.

So I would suggest the addition of a new field? To accomplish this requires minimal work (3 occurrences where entry.last_edited is updated), and has to be done in this PR as the migration is tied to this change.

I will admit that the name might be slightly confusing, because update_date and last_edited both already exist.

2021-10-03 10:22 UTC, mjvkeulen requested changes

2021-10-03 10:22 UTC, mjvkeulen commented on src/django/VLE/migrations/0099_add_first_and_last_submitted.py
> +
Prob just fix for the linter (do we exclude these?)

2021-10-03 10:22 UTC, mjvkeulen commented on src/django/VLE/migrations/0099_add_first_and_last_submitted.py
> +    Entry.objects.filter(is_draft=False).update(
Q) What do we do with redrafts?

2021-10-03 10:22 UTC, mjvkeulen commented on src/django/VLE/models/entry.py
> +    # Last time the content was edited, does include draft edits, but not grade edits, used for analysis
Clear comments

2021-10-03 10:22 UTC, mjvkeulen commented on src/django/VLE/models/entry.py
> +        # Entries should update last edited when it is switched from draft to no draft
[NIT] Should this comment not be captured in the function name?

E.g. self.submitting_draft(self, was_draft) and then

if self.submitting_draft(was_draft):
    entry.last_submitted = now

2021-10-03 10:22 UTC, mjvkeulen commented on src/django/VLE/models/entry.py
> +    def should_set_first_submitted(self, was_draft):
[NIT] This would then be `first_submission` inline with the other comment

2021-10-03 10:22 UTC, mjvkeulen commented on src/django/test/test_entry.py
> +        assert not entry.last_submitted, 'Entry should not get a last_submitted when still in draft'
Did I miss it somewhere else or do we need to add a line to check whether last_edited is updated when an entry is updated (even when draft), but not when graded?

2021-10-03 10:22 UTC, mjvkeulen commented on src/vue/src/components/entry/Entry.vue
> +                        by {{ node.entry.author }}
Q) Not introduced in this PR, but is this handled in the serializer or is this wrong?

2021-10-03 10:49 UTC, Larspolo commented on src/django/VLE/migrations/0099_add_first_and_last_submitted.py
> +
We do exclude these, because auto generated stuff caused errors

https://ejournal.atlassian.net/browse/EJ-1105

2021-10-03 10:51 UTC, Larspolo commented on src/django/VLE/migrations/0099_add_first_and_last_submitted.py
> +    Entry.objects.filter(is_draft=False).update(
We dont have that distinction currently, hard to do anything with it. But from now on, we keep the first and last submittted for this reason

2021-10-03 10:52 UTC, Larspolo commented on src/django/VLE/models/entry.py
> +        # Entries should update last edited when it is switched from draft to no draft
I find this more clear. Could add a new function that is called inside `should_update_last_submitted`

2021-10-03 10:56 UTC, Larspolo commented on src/vue/src/components/entry/Entry.vue
> +                        by {{ node.entry.author }}
`author = serializers.CharField(source='author.full_name', default=VLE.models.User.UNKNOWN_STR)`

What would be wrong?

2021-10-03 10:56 UTC, Larspolo commented on src/django/test/test_entry.py
> +        assert not entry.last_submitted, 'Entry should not get a last_submitted when still in draft'
```

    def test_update_entry(self):
        entry = api.create(self, 'entries', params=self.valid_create_params, user=self.student)['entry']

        params = {
            'pk': entry['id'],
            'content': entry['content'].copy()
        }

        updated_entry = api.update(self, 'entries', params=params.copy(), user=self.student)['entry']
        assert entry['last_edited'] != updated_entry['last_edited'], \
            'Last edited should update when entry content changes'
```

2021-10-03 11:27 UTC, Larspolo commented on src/django/test/test_entry.py
> +        assert not entry.last_submitted, 'Entry should not get a last_submitted when still in draft'
Also added one more check for drafted entries

2021-10-04 13:45 UTC, mjvkeulen approved these changes

2021-10-04 13:46 UTC, merged