Added the ability for teachers to limit the usage of a specific template
eJourn-al/eJournal pull request #1219
Opened 2021-09-13 14:44 UTC by Larspolo

![image](https://user-images.githubusercontent.com/11822478/133104617-477d1c87-7dc1-4338-bc41-fc65bf3a93cb.png)

2021-09-13 21:23 UTC, mjvkeulen requested changes

2021-09-13 21:23 UTC, mjvkeulen commented on src/vue/src/components/template/TemplateEditSettings.vue
> +                    Specify the amount that students can freely use this template. 0 for unlimited usage.
amount -> number (we can count the number of times the template will be used).

The number of times that students can make use of this template. Note that this also includes any deadlines that make use of this template. Use 0 to indicate unlimited usage.

2021-09-13 21:23 UTC, mjvkeulen commented on src/vue/src/components/template/TemplateEditSettings.vue
> +                />
Q) Do we need another indication to represent unlimited use than 0? Might not be very intuitive for our non-technical users. Small text below the input with unlimited when 0 is set would be fine for example.

2021-09-13 21:23 UTC, mjvkeulen commented on src/vue/src/components/template/TemplateEditSettings.vue
> +                This can even be unlimited.
How about:
```
Allow students to freely create entries based on this template, or set an upper usage limit. 
When disabled, this template can only be used for deadlines you add to the timeline.
```

2021-09-13 21:23 UTC, mjvkeulen commented on src/django/test/test_entry.py
> +        Field.objects.all().update(required=False)
[NIT]: This would block switching the setup to the test module (as it would affect other state as well). Limiting the query to Field.objects.filter(template__format=journal1.assignment.format)

2021-09-14 07:24 UTC, Larspolo commented on src/django/test/test_entry.py
> +        template1.chain.max_uses = 2
`factory.errors.InvalidDeclarationError: Received deep context for unknown fields: {'chain__max_uses': 2} (known=['description', 'location', 'options', 'required', 'template', 'title', 'type'])`

2021-09-14 07:50 UTC, Larspolo commented on src/django/test/test_entry.py
> +            'Since template 1 is fully used, it should no longer be returned in get_add_node for the timeline'
![image](https://user-images.githubusercontent.com/11822478/133217599-9a179ed4-6aa5-4ca9-94b2-c0fac7224444.png)
Good one, think this is way better

2021-09-14 07:55 UTC, Larspolo commented on src/vue/src/components/template/TemplateEditSettings.vue
> +                />
I think the text on the left hand side is good enough as non-technical/new users will likely also read more of the text to understand it better

2021-09-14 12:14 UTC, mjvkeulen commented on src/django/test/test_entry.py
> +        template1.chain.max_uses = 2
Ah my bad, we flattened the chain creation structure by overloading `create`. 

factory.Journal(assignment__format__templates=[{'type': Field.TEXT, 'max_uses': 2}] would work!

2021-09-14 12:16 UTC, mjvkeulen commented on src/django/test/test_entry.py
> +        template1.chain.max_uses = 2
Doesn't work! factory.Template(max_uses=2) does, but format `templates` is not setup correctly.

2021-09-15 12:35 UTC, mjvkeulen requested changes

2021-09-15 12:35 UTC, mjvkeulen commented on src/django/VLE/migrations/0097_templatechain_max_uses.py
> +            field=models.PositiveIntegerField(default=0),
Make use of UNLIMITED iso 0

2021-09-15 12:35 UTC, mjvkeulen commented on src/django/VLE/models/journal.py
> +        )
And here I thought u loved floating commas

2021-09-15 12:35 UTC, mjvkeulen commented on src/django/VLE/models/journal.py
> +        )
[D]: get_available_templates(include_used_up....) is inherently confusing (to me). 

How about `get_templates` and `get_unavailable_templates` which calls `get_templates` and applies the exclude?

2021-09-15 12:35 UTC, mjvkeulen commented on src/django/VLE/views/entry.py
> +            if not journal.get_available_templates().filter(pk=template.pk).exists():
For example, if journal.get_unavaible_templates().filter(pk=..).exists() would now skip the negation

2021-09-15 12:35 UTC, mjvkeulen commented on src/vue/src/components/template/TemplateSelection.vue
> +            return row.item.max_uses > 0 && this.usedCount(row) >= row.item.max_uses
[NIT]
define unlimited on the js side as well (e.g. in data, or in utils/constants)
max_uses !== unlimited && ..

Just so later on this is obvious from the js side as well

2021-09-15 12:35 UTC, mjvkeulen commented on src/vue/src/components/template/TemplateSelection.vue
> +                    v-if="row.item.max_uses > 0"
[NIT] row.item.max_uses !== unlimited

2021-09-15 12:35 UTC, mjvkeulen commented on src/vue/src/components/template/TemplateEditSettings.vue
> +                </small>
The read mode of a template is missing an indication that it's configured for limited use. 
![image](https://user-images.githubusercontent.com/39912610/133433463-3d67377c-795c-4d86-85da-aaeebcddc017.png)

This is quite a crucial setting, so I would expect an indication before switching to edit mode. Possibly @engelhamer has an idea on how to visualize this?

What comes to my mind is a 0/x on the template menu in the assignment editor.

2021-09-15 12:35 UTC, mjvkeulen commented on src/vue/src/components/template/TemplateEditSettings.vue
> +                />
How about an infinite icon below/next to the input when 0 is the value? https://fontawesome.com/v5.15/icons?d=gallery&p=2&q=infinite

2021-09-15 12:38 UTC, Larspolo commented on src/django/VLE/migrations/0097_templatechain_max_uses.py
> +            field=models.PositiveIntegerField(default=0),
No, because then if it changes, we wont get a new migration, while we should have a new migration

2021-09-15 12:40 UTC, Larspolo commented on src/django/VLE/models/journal.py
> +        )
Feel like this is a NIT? Added it anyway, here was a lot of debugging, so thats also why its so spacious, easily being able to uncomment stuff

2021-09-15 12:41 UTC, mjvkeulen commented on src/vue/src/components/template/TemplateSelection.vue
> +                </small>
This takes up a bit more room than needed:
![image](https://user-images.githubusercontent.com/39912610/133435014-fc953bfe-dc02-4e98-a506-cbc1532afde0.png)

How about moving the <small> block inside the button block and separating the template name with a <br/>?

2021-09-15 12:42 UTC, Larspolo commented on src/django/VLE/models/journal.py
> +        )
Not really agreeing with the proposed structure.

Get templates could refer to also the archived or preset only templates or even only the used templates
Get available templates gets all available templates, do you wish to also include the used up templates, but other then that still available? Add that flag

Think its no big issue on both sides

2021-09-15 12:44 UTC, Larspolo commented on src/django/VLE/views/entry.py
> +            if not journal.get_available_templates().filter(pk=template.pk).exists():
It also adds it inside the function, this example doesnt convince me. Especially because we still need a `get_available_templates` function anyway

2021-09-15 12:47 UTC, engelhamer commented on src/django/VLE/migrations/0097_templatechain_max_uses.py
> +            field=models.PositiveIntegerField(default=0),
If what changes?

2021-09-15 12:48 UTC, engelhamer commented on src/django/VLE/models/journal.py
> +        )
Used up is confusibg to me. Would prefer smth like `limit_reached`

2021-09-15 13:07 UTC, Larspolo commented on src/vue/src/components/template/TemplateEditSettings.vue
> +                </small>
![image](https://user-images.githubusercontent.com/11822478/133438834-f6665843-be8b-40af-b659-6ba0381ea445.png)
Looks good like this

2021-09-15 13:07 UTC, Larspolo commented on src/vue/src/components/template/TemplateEditSettings.vue
> +                </small>
Like this look good to me:
![image](https://user-images.githubusercontent.com/11822478/133438894-15c2f6d1-ce21-4724-8a42-2fa0099f63ba.png)

2021-09-15 13:09 UTC, engelhamer commented on src/vue/src/components/template/TemplateEditSettings.vue
> +                />
Would prefer a button for infinity, filling in 0 is not intuitive. I believe there is another instance where something similar happens (so: just offer the button on the front end, but keep 0 in the back end).

2021-09-15 13:10 UTC, engelhamer commented on src/vue/src/components/template/TemplateEditSettings.vue
> +                </small>
I can look into this 👍

2021-09-15 13:19 UTC, engelhamer commented on src/vue/src/components/template/TemplateEditSettings.vue
> +                    Note this also includes any deadlines that make use of this template.
I don't like this: teachers would have to count the amount of times they add this template to a deadline manually? And it is not indicated while adding deadlines to the timeline that the number of uses is exceeded? What would intuitively happen if this is the case?

Would prefer the uses in preset deadlines to be independent of this setting.

2021-09-15 13:19 UTC, engelhamer commented on src/vue/src/components/template/TemplateEditSettings.vue
> +                </small>
@Larspolo: the 2 is a bit vague in this list in my opinion. Should we make it a table?

2021-09-15 13:19 UTC, engelhamer commented on src/vue/src/components/template/TemplateSelection.vue
> +        isUsedUp (row) {
Again, limit reached iso used up would sound more intuitive.

2021-09-15 13:22 UTC, Larspolo commented on src/vue/src/components/template/TemplateSelection.vue
> +                </small>
Inside the button makes it also higthlight when hovering, makes it float in the center compared to the template name, and doesnt reduce it by far.

I can also move it next to the button:
![image](https://user-images.githubusercontent.com/11822478/133441176-da615ce1-7766-47d2-919d-191b929474a7.png)

2021-09-15 13:27 UTC, Larspolo commented on src/vue/src/components/template/TemplateEditSettings.vue
> +                />
![image](https://user-images.githubusercontent.com/11822478/133441839-14590607-7113-4087-a2aa-91843cb50b15.png)
Tried something, but my preference is without anything. Maybe the indication in the template section helps for you too?

2021-09-15 13:27 UTC, Larspolo commented on src/django/test/test_entry.py
> +        template1.chain.max_uses = 2
Can close this I suppose?

2021-09-15 13:28 UTC, Larspolo commented on src/django/VLE/migrations/0097_templatechain_max_uses.py
> +            field=models.PositiveIntegerField(default=0),
The variable UNLIMITED

2021-09-15 13:28 UTC, Larspolo commented on src/django/VLE/models/journal.py
> +        )
Changed the naming schema

2021-09-15 13:34 UTC, Larspolo commented on src/vue/src/components/template/TemplateEditSettings.vue
> +                </small>
The 2 has a hover for more info

2021-09-15 14:29 UTC, engelhamer commented on src/vue/src/components/template/TemplateEditSettings.vue
> +                />
How about: leave empty to indicate unlimited usage?

2021-09-15 14:29 UTC, engelhamer commented on src/vue/src/components/template/TemplateEditSettings.vue
> +                />
The placeholder could then be infinity

2021-09-15 19:56 UTC, mjvkeulen commented on src/django/VLE/models/template.py
> +                max_uses=data.get('max_uses', 0),
Default to TemplateChain.UNLIMITED

2021-09-15 19:56 UTC, mjvkeulen commented on src/vue/src/components/template/TemplateEditSettings.vue
> +                    Click on the infinite icon (∞) to indicate unlimited usage.
to allow unlimited use.

2021-09-15 19:56 UTC, mjvkeulen commented on src/vue/src/components/template/TemplateEditSettings.vue
> +            UNLIMITED: templateGlobals.UNLIMITED,
Haha I hate this too, this is purely for the linter right? (Unused import, as its not detected between the <template> tags)

2021-09-15 19:56 UTC, mjvkeulen commented on src/vue/src/components/template/TemplateSelection.vue
> +            console.log(this.nodes)
Left over (is this not part of our linter?), I am sure it's a warning during the build stage.

2021-09-15 19:56 UTC, mjvkeulen commented on src/django/VLE/models/journal.py
> +        )
Resolved for me

2021-09-15 20:27 UTC, mjvkeulen requested changes
I really like the use of the infinity icon and the template menu max use indication!

I slightly tweaked the template select max use display and added a tooltip on hover when disabled.

![image](https://user-images.githubusercontent.com/39912610/133504602-94b3d6e7-107f-4645-bd04-8bbc94c3d382.png)

Feel free to revert e2412aea4106646184663b4774c74d184abc1af5 if you dont like it.

2021-09-15 20:27 UTC, mjvkeulen commented on src/vue/src/components/template/TemplateEditSettings.vue
> +                </b-button>
This can be merged as an [input group](https://bootstrap-vue.org/docs/components/input-group).

This will nicely group the infinity icon with the input field.

2021-09-15 20:27 UTC, mjvkeulen commented on src/vue/src/components/template/TemplateEditSettings.vue
> +                    min="1"
This requires a bit more work to get right: 0 is still valid as input.

2021-09-15 20:27 UTC, mjvkeulen commented on src/vue/src/components/template/TemplateEditSettings.vue
> +                    min="1"
A value of 0 should be validated backend and frontend.

0 is effectively preset only, this is confusing.
- do we want to remove this distinction?
- Toggle free use to false when saving a max use with a 0 value?

2021-09-15 20:41 UTC, Larspolo commented on src/vue/src/components/template/TemplateEditSettings.vue
> +                    min="1"
Guess if a teacher really wants it that way

2021-09-15 20:47 UTC, Larspolo commented on src/vue/src/components/template/TemplateEditSettings.vue
> +                    min="1"
Good if we postpone this to the PR with also the other validation checks?

2021-09-15 20:50 UTC, mjvkeulen commented on src/vue/src/components/template/TemplateEditSettings.vue
> +                    min="1"
As in just typing 0 will work

2021-09-16 06:07 UTC, mjvkeulen approved these changes

2021-09-16 06:45 UTC, merged