Added an analytics dashboard
eJourn-al/eJournal pull request #1231
Opened 2021-09-29 14:49 UTC by mjvkeulen

# Analytics

Analytics introduces a dedicated dashboard to monitor the progress of students within an assignment. The Analytics dashboard can be accessed on the **assignment** page in the _Analytics_ card under the button **all**.

![image](https://user-images.githubusercontent.com/39912610/135280492-dda70774-a6dc-4712-bd25-3d237dee7159.png)

At the top of the Analytics dashboard is an overview panel of the assignment:

![image](https://user-images.githubusercontent.com/39912610/135281348-e0e4d7ca-89cb-411c-8bd3-ae2ba0d1e1b4.png)

By default this shows some general statistics such as the total number of entries.

By clicking on the **Filters** button, you are presented with a wide range of filters and some statistics which directly relate to the selected filter configuration:

![image](https://user-images.githubusercontent.com/39912610/135281745-21551a45-3f24-42c4-90bc-cfdba8de80ce.png)

This allows for some relatively complex queries. For example: would you be only interested in which students of a specific group made use of a particular category? This is possible by combining the **Journal Filter** for _groups_ with the **Entry Filter** for _categories_.

It is also possible to gather more information about a specific deadline, on the lefthand side in the analytics dashboard you will find the hopefully familiar _timeline_. Simply select the deadline you are interested in. Please note it is only possible to select a single deadline at a time.

![image](https://user-images.githubusercontent.com/39912610/135289972-a3653100-7345-459e-9ca1-4c8e8707f177.png)

## Graphs

The analytics panel contains multiple graphs, each providing different insights into the progress of your students.

### Student activity

The student activity graph is a heatmap showing when your students were most active and/or most busy submitting entries.

![image](https://user-images.githubusercontent.com/39912610/135283280-4dc20caf-ca2d-44a8-aeb0-63eb37c41191.png)

Each block represents a specific day of the week, and the color represents how active students were that day. If you would like to know the exact number of activities that took place, just hover the blocks to see a tooltip that indicates the exact date and number of activities that took place.

![heatmap](https://user-images.githubusercontent.com/39912610/135283971-4011c1da-7307-4a00-bee2-a81bda3f6aee.gif)

The Analytics dashboard comes with some additional group assignment functionality, such as a direct overview of the number of students who are not yet part of a journal, and the ability to message this group directly.

### Student activity histogram

Would you prefer a histogram over a heatmap? 

![image](https://user-images.githubusercontent.com/39912610/135285001-cfe46860-7b5d-4b61-91e9-52319397041f.png)

It is possible to configure the bin size manually, for example you might be interested whether it makes sense to set a deadline on a Friday or a Sunday? You can set the bin size to _days_ instead of _months_.

![submission_on](https://user-images.githubusercontent.com/39912610/135286595-433c5938-1f6c-4fbd-818b-bd200f9ca8aa.gif)

Similarly, it is also possible to switch to a histogram of percentages or to include the submission status.

> Would you also like to display the entry draft status?
> Enable the **include drafts** settings in the **Global Filters** panel
>
> ![image](https://user-images.githubusercontent.com/39912610/135287293-b4a2309c-bbc9-45d2-afa9-366ca3df7da6.png)

### Grades

It is possible to view a grade histogram of all the _journals_ or _entries_.

![image](https://user-images.githubusercontent.com/39912610/135287904-3004080f-65a0-4480-918d-b20a376c7512.png)

When looking at the _journal_ grades the assignment goal will be visualized as a green vertical line.
It is possible to switch between the entry or journal view by clicking on the **Entries** or **Journal** tab. Again it is possible to configure the bin size or to work with a percentage of the total number of journals or entries, rather than the absolute quantities. 

> Note: when looking at the grades of entries, any possible overall assessment grades or bonus points are not taken into account as these apply to the journal as a whole.

### Deadline submissions

It is possible to more closely inspect a specific deadline. First, select the deadline in the _timeline_. A new chart will display which shows the distribution of submission statuses.

![deadlines_pie](https://user-images.githubusercontent.com/39912610/135291990-c3987cc7-606a-4d63-87b2-f84841703096.gif)

It is possible to directly contact a specific group. For example, you might want to email all the students who have not yet submitted an entry for a specific deadline.

> Tip: If any students have not joined a group journal yet, but they should have already submitted a deadline, these students will also be outlined on the bottom of the graph if you would like to contact this group!

2021-10-01 15:08 UTC, Larspolo reviewed
Just some frontend comments to get you through the weekend. Look nice though!

2021-10-01 15:08 UTC, Larspolo commented on src/vue/src/components/analytics/AnalyticsOverview.vue
> +                    :placeholder="filters.entryDeadline ? 'Active deadline filter' : 'Filter By Template'"
This is very minimal UI change, and I didn't know why I couldn't click it immediately (took me 3 to 5 seconds)

Could be "Cannot set template filter because deadline filter is active". Or hide it. Or gray out possibly?

![image](https://user-images.githubusercontent.com/11822478/135642536-fde3e745-2e8c-42ae-9d7a-2c905479dd6e.png)

2021-10-01 15:08 UTC, Larspolo commented on src/vue/src/components/analytics/JournalUserListModal.vue
> +            empty-filtered-text="No groups match the given search criteria."
Not exactly sure where it is, but the "No results for filter" text does not always appear. When typing "dsgf" in journal fullname/username filter, the "Deadline submissions" and "Grades" (journal tab only) do not show this text.

2021-10-01 15:08 UTC, Larspolo commented on src/vue/src/components/analytics/graphs/DeadlineSubmissionStatusPieChart.vue
> +        />
It is unclear to me that clicking on the piechart would result in this popup. Fine for now I think, but a different button (that can also be pressed with other filters in other graphs) would be preferred. Issue worthy?

2021-10-02 14:23 UTC, Larspolo commented on src/vue/src/components/assignment/StatisticsCard.vue
> +            All
Would expect the "All" be in the header of this menu. Sth like this:
![image](https://user-images.githubusercontent.com/11822478/135720626-15ea69ec-c928-4ece-a93e-ff9d8756e1ad.png)

2021-10-02 15:23 UTC, Larspolo requested changes

2021-10-02 15:23 UTC, Larspolo commented on src/django/test/factory/role.py
> +    can_send_bulk_email_notifications = True
According to the mirgration, this should also be in the TARoleFactory. [Q] Do we want that? Both permissions as well?

2021-10-02 15:23 UTC, Larspolo commented on src/django/test/test_analytics.py
> +    def test_get_entry_analytics(self):
Missing assert statements. _Why_ is this being tested?

2021-10-02 15:23 UTC, Larspolo commented on src/django/test/test_analytics.py
> +        assert not e['late_submission'], 'Deadline entry submitted before the deadline due date is late'
*on time

Also, you need to re-get the entry

Also also, if the check above would yield true, this can never be false (right?) (given that this due date is earlier then the assignment due date)

2021-10-02 15:23 UTC, Larspolo commented on src/django/test/test_assignment.py
> +        assert len(resp['users']) == 0, 'Students cannot use the API'
Would expect it to raise forbidden actually. Or only the APs where the student is in collaboration with (group journal), and at least returning their own data

2021-10-02 15:23 UTC, Larspolo commented on src/django/test/test_event.py
> +            'On login a login event is created corresponding to the user that logged in'
Missing the login via LTI check

2021-10-02 15:23 UTC, Larspolo commented on src/vue/src/components/analytics/graphs/SubmissionOnHistogram.vue
> +// import moment from 'moment'
left over

2021-10-02 15:23 UTC, Larspolo commented on src/vue/src/components/analytics/graphs/SubmissionOnHistogram.vue
> +            // return {
left over

2021-10-02 15:23 UTC, Larspolo commented on src/vue/src/components/analytics/graphs/SubmissionOnHistogram.vue
> +        // mapValuesToDatePairsArr (arr) {
left over

2021-10-02 15:23 UTC, Larspolo commented on src/vue/src/components/analytics/graphs/WeekDayHeatmap.vue
> +                        // colorScale: {
left over

2021-10-02 15:23 UTC, Larspolo commented on src/vue/src/components/analytics/graphs/WeekDayHeatmap.vue
> +        // maxMoment () {
left over

2021-10-02 15:23 UTC, Larspolo commented on src/vue/src/views/Analytics.vue
> +            // QUESTION ANALYTICS: Is the average journal entry grade desired? (Disregarding entry specific filters)
Dont think so

2021-10-03 07:14 UTC, mjvkeulen commented on src/vue/src/components/analytics/graphs/GradeHistograms.vue
> +                title="Entries"
This is intentional, the number of entries on the journal tab specifically applies to the journal filter.

Would you prefer to see a duplication of the entry filter number of the entry tab?

2021-10-03 07:58 UTC, mjvkeulen commented on src/vue/src/components/analytics/graphs/GradeHistograms.vue
> +                Grades
Annoying bug between b-tabs and apexchart. Fixed with hack

2021-10-03 08:34 UTC, mjvkeulen commented on src/vue/src/components/analytics/AnalyticsOverview.vue
> +                    :placeholder="filters.entryDeadline ? 'Active deadline filter' : 'Filter By Template'"
It is greyed out (disabled), compare it to filter by category. I believe this is default disabled styling across the app.

The text is also different, I can change it but `Cannot set template filter because deadline filter is active` is a bit lengthy.

2021-10-03 08:45 UTC, mjvkeulen commented on src/vue/src/components/analytics/JournalUserListModal.vue
> +            empty-filtered-text="No groups match the given search criteria."
I think you are confused about where this is taking place.

![image](https://user-images.githubusercontent.com/39912610/135746379-3c4e85ce-6ca6-4736-a38c-d8fc19acd509.png)

2021-10-03 08:47 UTC, mjvkeulen commented on src/vue/src/components/analytics/graphs/DeadlineSubmissionStatusPieChart.vue
> +        />
So you raise two seperate issues:

- It is not intuitive that the deadline submission chart is interactive
- The modal to communicate with students would be desired in other locations as well.

What do you suggest?

2021-10-03 08:51 UTC, mjvkeulen commented on src/django/VLE/models/entry.py
> +            id=F('pk'),
I don't quite follow, this is serialized as is and for some reason we use `id` frontend

2021-10-03 08:52 UTC, mjvkeulen commented on src/django/VLE/models/event.py
> +    def create_sent_bulk_email_event(self, user: User, n_emails: int) -> 'Event':
It is a way to handle definitions later on in the file (to prevent circular missing types)

2021-10-03 08:53 UTC, mjvkeulen commented on src/django/VLE/tasks/email.py
> +            capture_exception(e)
The default exception will have all this context quite high up in its stacktrace no?

2021-10-03 08:56 UTC, mjvkeulen commented on src/django/VLE/utils/responses.py
> +    def default(self, o):
The override paths are tested rest is well tested by lib already

2021-10-03 08:57 UTC, mjvkeulen commented on src/django/VLE/views/analytics.py
> +    request.user.check_permission('can_view_analytics', assignment)
I would expect this to be embedded in the permission check.

Also what statistics are available for an unpublished assignment? I don't believe we allow unpublish once started.

2021-10-03 08:59 UTC, mjvkeulen commented on src/django/VLE/views/analytics.py
> +    viewable_journals = Journal.all_objects.filter(
Because all the costly annotations are not needed?

Our structure of doing `allowed_journals` followed by a lot of additional annotations is a bit sucky for performance.

2021-10-03 09:03 UTC, mjvkeulen commented on src/django/VLE/views/assignment.py
> +    def participants(self, request):
So the url currently is /assignments/participants/ which is not bad tbh.

This is also in line with all the other actions in the assignment view, like `teacher_entries`, `participants_without_journal` etc. We can move this to a more broad issue to standardize the API or smth.

2021-10-03 09:26 UTC, mjvkeulen commented on src/django/VLE/views/assignment.py
> +        validated_user_data = (
I expected a list of flat user data, not AP data.

User serializer does not have journal as a field, and groups touch on `for_course` which I wanted to stay away from. 

Your point of keeping output consistent with serializers where possible stands, however. Not sure if I would move this to its own serializer, leave it as is or flatten the data frontend.

2021-10-03 09:28 UTC, mjvkeulen commented on src/django/VLE/views/email.py
> +    Event.objects.create_sent_bulk_email_event(user=request.user, n_emails=len(user_ids))
No external dependencies or complexity for something which has simple requirements to satisfy our needs.

2021-10-03 09:45 UTC, mjvkeulen commented on src/django/VLE/views/email.py
> +        AssignmentParticipation.objects
Is the combination of the permission check and viewable by not sufficient?

2021-10-03 09:45 UTC, mjvkeulen commented on src/django/test/factory/role.py
> +    can_send_bulk_email_notifications = True
I thought so

2021-10-03 09:48 UTC, mjvkeulen commented on src/django/test/test_analytics.py
> +    def test_get_entry_analytics(self):
I am not sure I agree, the asserts are sufficiently simple (does the serialized data key match with the expected serialized object value), that asserts messages repeating the code line do not contribute much

2021-10-03 09:56 UTC, mjvkeulen commented on src/vue/src/components/analytics/graphs/SubmissionOnHistogram.vue
> +// import moment from 'moment'
All the commented code can be used to transform the series into a time series instead of a discrete histogram with custom buckets.

Its just that I didn't like the looks of how the library then handles the x-axis labels.

2021-10-03 10:01 UTC, Larspolo commented on src/vue/src/components/analytics/graphs/GradeHistograms.vue
> +                title="Entries"
A tooltip would also suffice

2021-10-03 10:02 UTC, Larspolo commented on src/vue/src/components/analytics/AnalyticsOverview.vue
> +                    :placeholder="filters.entryDeadline ? 'Active deadline filter' : 'Filter By Template'"
Yeah, I think the whole app would improve with a better distinction

2021-10-03 10:04 UTC, Larspolo commented on src/vue/src/components/analytics/JournalUserListModal.vue
> +            empty-filtered-text="No groups match the given search criteria."
Yeah, the comment is not placed on the correct line, the explenation is about the analytics, not the email popup

2021-10-03 10:08 UTC, Larspolo commented on src/django/VLE/views/assignment.py
> +    def participants(self, request):
Yeah, we should make it an issue. But I dont like making it worse because elsewhere it is also done

2021-10-03 10:12 UTC, Larspolo commented on src/django/VLE/views/email.py
> +    Event.objects.create_sent_bulk_email_event(user=request.user, n_emails=len(user_ids))
What is our need? I would for example like to be able to add levels or categories

2021-10-03 10:13 UTC, Larspolo commented on src/django/VLE/views/analytics.py
> +    request.user.check_permission('can_view_analytics', assignment)
Its not, but I guess it works for now. Also assigned groups are not checked now

2021-10-03 10:14 UTC, Larspolo commented on src/django/VLE/views/email.py
> +        AssignmentParticipation.objects
Now you can send emails to users that cannot see the assignment yet, but you can see them

2021-10-03 10:25 UTC, Larspolo commented on src/vue/src/components/analytics/JournalUserListModal.vue
> +            empty-filtered-text="No groups match the given search criteria."
![image](https://user-images.githubusercontent.com/11822478/135749547-a41ace16-24bf-42e5-8e95-7d52e2aac035.png)
Screenshot for clarity

2021-10-03 10:26 UTC, Larspolo commented on src/vue/src/components/analytics/graphs/DeadlineSubmissionStatusPieChart.vue
> +        />
Dont have a good idea. But as a teacher I see this feature being easily overlooked. Or when they do find out once, then the next time not knowing how to do it

2021-10-03 10:27 UTC, Larspolo commented on src/django/VLE/tasks/email.py
> +            capture_exception(e)
But it may miss some context, but I noticed we dont do it elsewhere either, changed to a NIT

2021-10-03 10:30 UTC, Larspolo commented on src/django/VLE/utils/responses.py
> +    def default(self, o):
Why does it not use `return super().default(o)` for those cases? Codecov detects only the first statement as visited

2021-10-03 10:32 UTC, Larspolo commented on src/django/VLE/views/assignment.py
> +        validated_user_data = (
Would prefer then requesting the AP data, and then doing `ap.user.username`, so the structure is kept

2021-10-03 10:46 UTC, Larspolo commented on src/django/test/test_analytics.py
> +    def test_get_entry_analytics(self):
Well, not for every assert. But I would expect sth like:
- "When retrieving the entry analytics, all the entries within a single assignment should be returned"
- "Entries should be serialized with all the variables that are needed for analytics"
- "Preset node should be none for unlimited entries"

I also think you are more testing the annotate function. This can also be done separately to make it more clear. And then here only test if the correct entries get annotated

2021-10-03 10:54 UTC, mjvkeulen commented on src/django/VLE/views/assignment.py
> +        validated_user_data = (
I dislike requesting AP data, this should be User data imo.

2021-10-03 10:56 UTC, mjvkeulen commented on src/django/VLE/views/email.py
> +    Event.objects.create_sent_bulk_email_event(user=request.user, n_emails=len(user_ids))
Add it as a choices field once used?

2021-10-03 10:57 UTC, mjvkeulen commented on src/django/VLE/views/email.py
> +        AssignmentParticipation.objects
So if you are the legitimate supervisor of that user, you can send that user an email despite them not being able to see the assignment yet (via a manual API call at that)

2021-10-03 11:00 UTC, mjvkeulen commented on src/django/test/test_assignment.py
> +        assert len(resp['users']) == 0, 'Students cannot use the API'
An API not returning data for users which are not authorized seems fine by me as well, this also omits the repetition of a check which is already partly done via the query for the data itself.

2021-10-03 11:01 UTC, Larspolo commented on src/django/VLE/views/assignment.py
> +        validated_user_data = (
Could be a users api call then? `/users?assignment_id=x`

2021-10-03 11:02 UTC, Larspolo commented on src/django/VLE/views/email.py
> +    Event.objects.create_sent_bulk_email_event(user=request.user, n_emails=len(user_ids))
So then we are building our own logging module

2021-10-03 11:03 UTC, Larspolo commented on src/django/VLE/views/email.py
> +        AssignmentParticipation.objects
Yup, like we also do with the notificaiton system, only send notifications if the user can see the context

2021-10-03 11:23 UTC, mjvkeulen commented on src/vue/src/components/analytics/JournalUserListModal.vue
> +            empty-filtered-text="No groups match the given search criteria."
This is quite specific. Only for the deadline submission graph, and only when you filter journals down to 0. E.g. for an entry filter, this is shown:

![image](https://user-images.githubusercontent.com/39912610/135751475-05f89a81-e085-4edc-a4d5-aa165bac539f.png)

2021-10-03 11:32 UTC, mjvkeulen commented on src/vue/src/components/analytics/JournalUserListModal.vue
> +            empty-filtered-text="No groups match the given search criteria."
Should be addressed now

![image](https://user-images.githubusercontent.com/39912610/135751794-928088fd-b8da-4296-b3b1-935ff4ceb746.png)

2021-10-03 11:34 UTC, mjvkeulen commented on src/django/VLE/utils/responses.py
> +    def default(self, o):
Only the blocks for Date and DateTime are changed rest is default. This is something we already do in the serializers but rather weakly compared to this method.

2021-10-03 11:58 UTC, Larspolo commented on src/django/test/test_assignment.py
> +        assert len(resp['users']) == 0, 'Students cannot use the API'
Its different from the rest of the API. Why do this now? It may cause confusion

2021-10-04 08:23 UTC, mjvkeulen commented on src/django/VLE/views/email.py
> +    Event.objects.create_sent_bulk_email_event(user=request.user, n_emails=len(user_ids))
Note the "once used".

Even if you were to introduce a lib like structlog, we would still need to write similar logic to store it within the DB.

2021-10-04 08:25 UTC, mjvkeulen commented on src/django/VLE/views/email.py
> +        AssignmentParticipation.objects
This hardly applies to this example, the teacher decided to send this user an email and was verified that he has the right to do so. The rest is minor, and if you want to shield your example prob best to tack it onto the `('can_send_bulk_email_notifications', assignment)` check.

2021-10-04 08:26 UTC, mjvkeulen commented on src/django/VLE/views/email.py
> +        AssignmentParticipation.objects
I would even argue that if in this scenario the user cannot see the resource from some reason, it is better that they DO get an email so they might respond with WTF I can't even see the resource.

2021-10-04 08:31 UTC, mjvkeulen commented on src/django/test/test_assignment.py
> +        assert len(resp['users']) == 0, 'Students cannot use the API'
- Allows can_view to function both as a guard on the filter as on the result of the API
- I disagree this differs from the rest of the API, there are many places where the result is reduced or zero depending on your permission.

2021-10-04 10:40 UTC, Larspolo commented on src/vue/src/components/analytics/JournalUserListModal.vue
> +            empty-filtered-text="No groups match the given search criteria."
Not yet the "Grades" chart in the journal tab

![image](https://user-images.githubusercontent.com/11822478/135837573-c14f189f-4c4b-4ff0-a5cd-719beeb3992c.png)

2021-10-04 10:45 UTC, Larspolo commented on src/django/VLE/utils/responses.py
> +    def default(self, o):
Would this not suffice then?
```
    def default(self, o):
        # See "Date Time String Format" in the ECMA-262 specification.
        if isinstance(o, datetime.datetime):
            return o.strftime(settings.ALLOWED_DATETIME_FORMAT)
        elif isinstance(o, datetime.date):
            return o.strftime(settings.ALLOWED_DATE_FORMAT)
        else:
            return super().default(o)
```

2021-10-04 10:53 UTC, Larspolo commented on src/django/VLE/views/email.py
> +        AssignmentParticipation.objects
> prob best to tack it onto the ('can_send_bulk_email_notifications', assignment) check.

The `check_permission` function only checks for the permission itself, this is done all over the backend. Thats where the improved permissions PR is coming from

> I would even argue that if in this scenario the user cannot see the resource for some reason, it is better that they DO get an email so they might respond with WTF I can't even see the resource.

Good point that this is useful to point out. Would then even say that immediately informing the teacher is better then informing the student, that then has to inform the teacher. We could return a list of all users that are not able to view the assignment, and then display that to the teacher with a popup "Remove the users from the list | Send anyway"

2021-10-04 10:56 UTC, Larspolo commented on src/django/test/test_assignment.py
> +        assert len(resp['users']) == 0, 'Students cannot use the API'
> there are many places where the result is reduced or zero depending on your permission.

And no error message is giving? Which?

2021-10-05 09:06 UTC, mjvkeulen commented on src/django/VLE/views/email.py
> +        AssignmentParticipation.objects
I agree that embedding this nicely for the teacher would be better. 

But, leaving this as a responsibility for the student for now would work fine for now and we can make an issue to resolve this more cleanly when it does occur.

2021-10-05 09:09 UTC, mjvkeulen commented on src/django/test/test_assignment.py
> +        assert len(resp['users']) == 0, 'Students cannot use the API'
First place I looked: groups -> list -> can_only_view_users_of_own_groups -> group not part of own -> yields empty data. 

Works on the same principle where viewable_by guards the query.

2021-10-05 09:39 UTC, Larspolo commented on src/django/test/test_assignment.py
> +        assert len(resp['users']) == 0, 'Students cannot use the API'
Thats different. There you actually do get all the groups that they can see. If we go by that case, we should expect all the APs from the students' (group) journal as well

2021-10-12 07:08 UTC, engelhamer commented
Then toUsers can be omitted

Op di 12 okt. 2021 09:05 schreef mjvkeulen ***@***.***>:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In src/vue/src/api/email.js
> <https://github.com/eJourn-al/eJournal/pull/1231#discussion_r726819857>:
>
> > @@ -0,0 +1,7 @@
> +import auth from '@/api/auth.js'
> +
> +export default {
> +    sendEmailOnBehalfOfUserToUsers (data, connArgs = auth.DEFAULT_CONN_ARGS) {
>
> We send a lot of emails as a platform, such as notifications to users or
> w/e. Explicitly separating this route: we as a platform send a lot of
> emails on behalf of one user to other users makes a lot of sense
> naming-wise to me.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/eJourn-al/eJournal/pull/1231#discussion_r726819857>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJQQJBNL67JHMTGVLJFMR23UGPM2PANCNFSM5FACNPZQ>
> .
>

2021-11-05 09:53 UTC, Larspolo commented on src/vue/src/components/assignment/StatisticsCard.vue
> +                Analytics
[NIT] The title changed, but the filename is still the same

2021-11-13 16:16 UTC, engelhamer commented on src/django/VLE/views/email.py
> +    return response.success(description='Form succesfully received, we are working on notifying all users!')
```
    return response.success(description='Message sent!')
```
'Message sent' sounds much better and I really see no reason to keep this weird phrasing.

2021-11-13 16:50 UTC, engelhamer commented on src/vue/src/api/email.js
> +    sendEmailOnBehalfOfUserToUsers (data, connArgs = auth.DEFAULT_CONN_ARGS) {
No response from @mjvkeulen yet.

2021-11-13 16:51 UTC, engelhamer commented on src/vue/src/components/analytics/StatsDisplay.vue
> +        border-right: 3px solid $theme-dark-grey
Not NIT, just consistency of the design? Same as capitalisation of sentences etc.

2021-11-13 16:58 UTC, engelhamer commented on src/vue/src/components/analytics/graphs/SubmissionOnHistogram.vue
> +                late: lateValuesArr,
Yes. Do exactly the same as in this gif (toggle the checkbox) and then 'late' appears in the legend, even though it is not in the graph. Hovering on 'late' in the legend shows nothing highlighted, but blurs the blue part.

This is a bit confusing in my opinion.

2021-11-14 21:43 UTC, engelhamer approved these changes
Fixed some styling bugs I encountered during review. Some minor comments still open but fine to merge.

2021-11-16 12:56 UTC, Larspolo commented on src/vue/src/components/columns/TimelineTwoColumns.vue
> +                    xl="4"
[NIT] Would rather keep the 3 columns for the timeline. If this is wide enough for the other pages, I dont see why it wouldnt be wide enough here. Also it keeps the consistency between the analytics and other timeline pages

2021-11-17 14:44 UTC, engelhamer commented on src/vue/src/components/columns/TimelineTwoColumns.vue
> +                    xl="4"
The graphs can take up a lot of horizontal space. In this case there is also no panel in the right hand column, so why not use the available space that would otherwise be left blank?

2021-11-17 16:33 UTC, Larspolo commented on src/vue/src/components/columns/TimelineTwoColumns.vue
> +                    xl="4"
For consistency

2021-11-25 10:15 UTC, merged