Improved the UX for editing entries with slow internet
eJourn-al/eJournal pull request #1232
Opened 2021-10-02 20:58 UTC by Larspolo

## Description
When users would take a long time to send their changes to the server, it could lead to data being set back. This wont happen now, and it will automatically send the newer data to the server when a (slow) request has finished
EJ-1047 #close
https://ejournal.atlassian.net/browse/EJ-1047

2021-10-05 09:53 UTC, mjvkeulen requested changes
Good addition, clean flow with a single promise chain. 

Just some questions

2021-10-05 09:53 UTC, mjvkeulen commented on src/django/VLE/utils/entry_utils.py
> -            raise VLEBadRequest('Your teacher has updated the template for this entry, please reload and try again.')
Q) How is this case now resolved? This scenario still holds: the front-end data can be stale after the teacher made an update but the student fetched the nodes before the update.

2021-10-05 09:53 UTC, mjvkeulen commented on src/django/VLE/utils/entry_utils.py
> -            raise VLEBadRequest('Provided template is not used by the deadline, please reload and try again.')
Q) How is this case now resolved?

2021-10-05 09:53 UTC, mjvkeulen commented on src/django/VLE/views/entry.py
> +            # Only unlimited nodes provide template ids
[D] Is this quirky good, or should we simply add an explicit flag (unlimited: True) to the API?

2021-10-05 09:53 UTC, mjvkeulen commented on src/django/VLE/factory.py
> +def make_entry(template, author, node):
Since this now only creates a blank draft entry (does not set title, or custom categories etc), which I think is good and much more befitting of our frontend flow, should we just rename this to make_entry_draft? I initially had to rethink why all the checks could be omitted, this would make it clear at a glance to me.

2021-10-05 09:53 UTC, mjvkeulen commented on src/vue/src/components/timeline/TimelineNodeCircle.vue
> +            NEW_ENTRY_ID: -1,
Q) What does this represent exactly?

2021-10-05 09:54 UTC, mjvkeulen commented on src/vue/src/components/timeline/TimelineNodeCircle.vue
> +            NEW_ENTRY_ID: -1,
I think it simply means not yet created?

2021-10-06 13:36 UTC, Larspolo commented on src/django/VLE/utils/entry_utils.py
> -            raise VLEBadRequest('Your teacher has updated the template for this entry, please reload and try again.')
We dont pass the template anymore. If the user creates an entry, it will be linked to the template that is then the current template. This should no longer be a problem backend. Although frontend, the template wont be reloaded, will need to fix that

2021-10-06 13:37 UTC, Larspolo commented on src/django/VLE/utils/entry_utils.py
> -            raise VLEBadRequest('Provided template is not used by the deadline, please reload and try again.')
We dont pass the template anymore. If the user creates an entry, it will be linked to the template that is then the current template. This should no longer be a problem backend. Although frontend, the template wont be reloaded, will need to fix that

2021-10-06 13:40 UTC, Larspolo commented on src/vue/src/components/timeline/TimelineNodeCircle.vue
> +            NEW_ENTRY_ID: -1,
Yes

2021-11-14 22:05 UTC, engelhamer commented on src/vue/src/components/entry/Entry.vue
> +        saveChanges () {
This field count also includes description-only fields, which may be confusing to the user.

E.g. 
![image](https://user-images.githubusercontent.com/39912581/141700429-e5bb65e4-a58f-4686-bdac-912a612ed811.png)

2021-11-14 22:07 UTC, engelhamer approved these changes
Required field error msg could be improved for descriptions, but otherwise alright.

2021-11-15 10:54 UTC, merged