Changed permission system
eJourn-al/eJournal pull request #1245
Opened 2021-10-20 14:19 UTC by Larspolo

Changed permission system

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ejourn-al/ejournal/1245)

2021-11-20 08:19 UTC, mjvkeulen requested changes

2021-11-20 08:19 UTC, mjvkeulen commented on src/django/VLE/views/participation.py
> +        # QUESTION: whats up with the mix between User and participation serializers here and in members?
Did you check how the return values are used? Might be possible to unify the serializer choice?

2021-11-20 08:19 UTC, mjvkeulen commented on src/django/VLE/views/participation.py
> +            request.query_params, (int, 'user_id'))
Absolutely littered with such diffs..

2021-11-20 08:19 UTC, mjvkeulen commented on src/django/VLE/views/rubric.py
> +        source_rubric.viewable_by(request.user, raise_error=True)
This would allow a TA to import a rubric from a course where they are a student (and the rubric is visible to them). 

Should this not also be creatable/editable?

Minor issue

2021-11-20 08:19 UTC, mjvkeulen commented on src/vue/src/components/entry/EntryNonStudent.vue
> +                        published: this.$hasPermission('can_publish_grades') ? option === 'p' : undefined,
Tagging

2021-11-20 08:19 UTC, mjvkeulen commented on src/django/test/test_assessment.py
> +            can_view_mock.assert_called()
What forced the move off `assert_called_with`?

2021-11-20 12:53 UTC, Larspolo commented on requirements/base.txt
> +StrEnum==0.4.6 # Utils
Wanted to make use of the `auto()` property that automatically converts it to lowercase, didnt do it yet though

2021-11-20 12:54 UTC, Larspolo commented on src/django/VLE/models/assessment.py
> +    class PERMISSION_FIELDS(LowercaseStrEnum):
That you can use constants iso strings `PERMISSION_FIELDS.FEEDBACK in fields`. Also useful for the editor. Typing `PERMISSION_FIELDS.` will autofill with the available fields. Set wouldnt

2021-11-20 12:54 UTC, Larspolo commented on src/django/VLE/models/assessment.py
> +    def viewable_by(self, user, raise_error: bool = False):
Forgot

2021-11-20 12:57 UTC, Larspolo commented on src/django/VLE/models/assessment.py
> +            user.check_permission('can_grade', context.assignment)
Added a comment here, you need to tag the other places as well though, I'm not sure when something is "non-trivial". I added comments  on places where I found it complicated myself

2021-11-20 12:57 UTC, Larspolo commented on src/django/VLE/models/assessment.py
> +        raise_error: bool = False,
Function name does not represent something that would raise on default

2021-11-20 12:59 UTC, Larspolo commented on src/django/VLE/models/assessment_model.py
> +            fields=[VLE.models.Assignment.PERMISSION_FIELDS.ASSESSMENT_MODEL],
Not sure what you are asking. What would you suggest doing instead?

2021-11-20 13:02 UTC, Larspolo commented on src/django/VLE/models/assignment.py
> +        context.viewable_by(user, raise_error=True)
This is a result of how we use this system. Good thing for @engelhamer to also note:

The permission wrap does the following:
1. run the function
2. if it raises an error and `raise_error` is false, catch the error and return false
3. if it doesnt an error and `raise_error` is false, return true

This way everything inside the permission function needs to have the `raise_error` set to `True`. Else the permission wrap won't catch the problem anymore

2021-11-20 13:10 UTC, Larspolo commented on src/django/VLE/models/base.py
> +            skip_view_check: bool = kwargs.get('skip_view_check', default_args.get('skip_view_check', True))
This is the case indeed. Its a solution I found best. I would like to make the permission system easy to use. Some functions do need a view check by default, and others dont. How would you like to make this difference? All edit and delete functions require the skip_view_check.

2021-11-20 13:11 UTC, Larspolo commented on src/django/VLE/views/category.py
> +        category: Category = Category.objects.filter(pk=pk).select_related('assignment').get()
It is not required. But I like using typing in my editor. Was busy trying to make the django-stubs work, but I couldnt manage

2021-11-20 13:12 UTC, Larspolo commented on src/django/VLE/models/comment.py
> +            # QUESTION: is this the correct permission to view unpublished comments?
This wasnt the case

2021-11-20 15:03 UTC, Larspolo commented on src/django/VLE/models/comment.py
> +        # QUESTION: we currently have that you don't need can_comment rights to edit
Waiting for @engelhamer 's opinion on this and all other questions before making changes

2021-11-20 15:05 UTC, Larspolo commented on src/django/VLE/models/course.py
> +    # QUESTION: we dont lock based on start / end date. Would we like to?
https://ejournal.atlassian.net/browse/EJ-920

2021-11-20 15:06 UTC, Larspolo commented on src/django/VLE/models/entry.py
> +        journal.is_locked(raise_error=True)
No, changed to suggestion

2021-11-20 15:07 UTC, Larspolo commented on src/django/VLE/models/entry.py
> +    def editable_by(
is_locked checks if node is locked, checks if journal is locked, checks if journal is submitted

2021-11-20 15:13 UTC, Larspolo commented on src/django/VLE/models/grade.py
> +        # QUESTION: should student be able to always see all published grades on their own entry? We currently don't
This is the current case indeed. But why not?

2021-11-20 15:15 UTC, Larspolo commented on src/django/VLE/models/grade.py
> +            user.check_permission('can_publish_grades', context)
Tagging for later me to fix

2021-11-20 15:34 UTC, Larspolo commented on src/django/VLE/models/group.py
> +        user.check_permission('can_view_course_users', context)
Feels like there is a missing permission indeed. But also, do we wish to make a permission for this? Might get too complicated if we start adding more and more permissions

2021-11-20 15:37 UTC, Larspolo commented on src/django/VLE/models/group.py
> +        # If we DO want this, this requires a bit of a workaround or sth as we dont
It also serializes the members. But why limit it furter if you set to only serialize the assigned groups? You already need the `can_view_course_users` permission in both cases

2021-11-20 15:39 UTC, Larspolo commented on src/django/VLE/models/journal.py
> +        exclude=False,
`exclude_viewable_by`?

2021-11-20 15:39 UTC, Larspolo commented on src/django/VLE/models/journal.py
> +        exclude=False,
I feel like in the function call its more clear:
```
        # For all the journals that the user is not able to see
        # We check if it is a participant, because the viewable_by query function only checks for supervisors
        for journal in objects.viewable_by(user, exclude=True):
            if not journal.is_participant(user):
                raise VLEForbiddenError('You are not allowed to view these journals.')
```

2021-11-20 15:40 UTC, Larspolo commented on src/django/VLE/models/journal.py
> +    def get_needs_lti_link(self):
Not introduced in this PR, but I agree

2021-11-20 15:40 UTC, Larspolo commented on src/django/VLE/models/journal.py
> +            sourcedid__isnull=True,
```

    def annotate_needs_lti_link(self):
        """
        Annotates for each journal linked to an lti assignment (active lti id is not None)
        the full name as array of the users who do not have a sourcedid set as `needs_lti_link`
        """
        return self.annotate(needs_lti_link=ArrayAgg(
            'authors__user__full_name',
            filter=Q(authors__sourcedid__isnull=True, assignment__active_lti_id__isnull=False),
            distinct=True,
        ))
```

2021-11-20 15:42 UTC, Larspolo commented on src/django/VLE/models/journal.py
> +        user.check_permission('can_have_journal', self.assignment)
any time `all_objects` is used without the `viewable_by` this may appear

2021-11-20 15:45 UTC, Larspolo commented on src/django/VLE/models/journal.py
> +            groups=VLE.models.Group.objects.filter(participation__user__in=self.authors.values('user')),
I believe it is yes, could be filtered as well already in the first query though, may be more efficient

2021-11-20 15:47 UTC, Larspolo commented on src/django/VLE/models/journal.py
> +                user.check_permission('can_have_journal', self.assignment)
Yup

2021-11-20 15:47 UTC, Larspolo commented on src/django/VLE/models/journal.py
> +            # QUESTION: should this also have a `can_publish_grades` check?
Same, it did not though. @engelhamer

2021-11-20 15:48 UTC, Larspolo commented on src/django/VLE/models/journal.py
> +                raise VLEForbiddenError('You are not allowed to change the journal image.')
Definitely

2021-11-20 15:49 UTC, Larspolo commented on src/django/VLE/models/journal.py
> +        user.check_permission('can_manage_journals', self.assignment)
Hm, appearently. Not sure if I like that though

2021-11-20 15:51 UTC, Larspolo commented on src/django/VLE/models/journal.py
> +    def can_join(self, user, raise_error: bool = False):
Not sure. Permission checks vs bad_request checks. I kept these in the join function itself, but this is an either or for me. @engelhamer

2021-11-20 15:51 UTC, Larspolo commented on src/django/VLE/models/journal_import_request.py
> +        journal_source.is_participant(user, raise_error=True)
I do think so yes

2021-11-20 15:54 UTC, Larspolo commented on src/django/VLE/models/participation.py
> +        user.check_permission('can_add_course_users', context)
Did you not see the difference in `can_add_course_users` and `can_view_course_users`? Or do I missunderstand the question?

2021-11-20 15:56 UTC, Larspolo commented on src/django/VLE/models/preset_node.py
> +            skip_view_check=True,
I think here its wrong, but for the other two it is already checked in the preset_node is viewable, then we dont need to also check if the format is viewable

2021-11-20 15:57 UTC, Larspolo commented on src/django/VLE/models/preset_node.py
> +    def creatable_by(cls, user: 'VLE.models.User', context: 'VLE.models.Format', raise_error: bool = False):
@engelhamer 

I indeed stripped away the `e` in all cases, thought this was how English worked

2021-11-20 15:58 UTC, Larspolo commented on src/django/VLE/models/preset_node.py
> +            raise VLEForbiddenError('Node is locked and can no longer be used.')
Suggestion?

2021-11-20 16:07 UTC, Larspolo commented on requirements/base.txt
>  django-anymail==8.2 # Email client
:shruk: possibly have to revert that

2021-11-20 16:12 UTC, Larspolo commented on src/django/VLE/models/role.py
> +        if not self.role.filter(user=user).exists():
Did you tag the correct line? In the case that a user would like to see its own role (serialize own permissions within a course), it would not need the `can_edit_course_roles` permission

2021-11-20 16:13 UTC, Larspolo commented on src/django/VLE/models/role.py
> +    def bulk_editable_by(
What do you mean?

2021-11-21 07:48 UTC, mjvkeulen commented on src/django/VLE/models/role.py
> +    def bulk_editable_by(
Just the ordering of the functions in a model. So first `viewable_by` and if `bulk_viewable_by` is defined it makes sense if it follows right after.

2021-11-21 07:55 UTC, mjvkeulen commented on src/django/VLE/models/base.py
> +            skip_view_check: bool = kwargs.get('skip_view_check', default_args.get('skip_view_check', True))
To me this touches on sensible defaults: I would prefer that check is always performed unless explicitly skipped. 

Now simply omitting (forgetting) the param skips the check.

2021-11-21 07:59 UTC, mjvkeulen commented on src/django/VLE/models/course.py
> +    # QUESTION: we dont lock based on start / end date. Would we like to?
Remove the question and resolve this thread?

2021-11-21 08:00 UTC, mjvkeulen commented on src/django/VLE/models/grade.py
> +        # QUESTION: should student be able to always see all published grades on their own entry? We currently don't
Sorry, why use `can_view_grade_history`? I figure since we have a dedicated permission for this, let's use it?

2021-11-21 08:03 UTC, mjvkeulen commented on src/django/VLE/models/journal.py
> +        exclude=False,
`exclude_viewable_by` works for me

2021-11-21 08:07 UTC, mjvkeulen commented on src/django/VLE/models/journal.py
> +            sourcedid__isnull=True,
I figured as LTI expert, you could shed some light on whether `sourcedid` and `grade_url` are both equally good indicators for needing an lti link?

2021-11-21 08:10 UTC, mjvkeulen commented on src/django/VLE/models/preset_node.py
> +            raise VLEForbiddenError('Node is locked and can no longer be used.')
I believe I also added suggestions

2021-11-21 12:27 UTC, Larspolo commented on src/django/VLE/models/base.py
> +            skip_view_check: bool = kwargs.get('skip_view_check', default_args.get('skip_view_check', True))
In that case, "viewable_by" or "bulk_viewable_by" would recursively call themself. Or is_locked would needlessly call "viewable_by". I see this as the sensible default

2021-11-21 12:28 UTC, Larspolo commented on src/django/VLE/models/grade.py
> +        # QUESTION: should student be able to always see all published grades on their own entry? We currently don't
Maybe, but `can_view_grade_history` I saw also as the unpublished grades

2021-11-21 12:30 UTC, Larspolo commented on src/django/VLE/models/journal.py
> +        exclude=False,
> Your example

Which currently is also the only use case. I will change it to the "func" param, which by default if filter, and can be changed to `exclude`. However, now that I see that case, I dont find that particularly more verbose that my solution. But best to keep to how we currently do it imo

2021-11-21 12:32 UTC, Larspolo commented on src/django/VLE/models/journal.py
> +            sourcedid__isnull=True,
"LTI expert" ;)

I think we only use one because in any state we should always have both or none set. No need to check for both

2021-11-21 12:33 UTC, Larspolo commented on src/django/VLE/views/participation.py
> +            request.query_params, (int, 'user_id'))
I fixed this in the linter now, I accidentally put the linter to 80 chars iso 120

2021-11-21 12:34 UTC, Larspolo commented on src/django/VLE/views/rubric.py
> +        source_rubric.viewable_by(request.user, raise_error=True)
I would see that as a plus actually. "Oh, in my student time I found that rubric really useful, lets see if I can import it to my assignment now that I am a teacher"

2021-11-21 12:36 UTC, Larspolo commented on src/django/test/test_assessment.py
> +            can_view_mock.assert_called()
Lazyness mostly. But also now its more modular, less to change when function parameters change. I dont like this system where sometimes I now have to change stuff throughout all tests if I change function arguments. There must be a better solution

2021-11-21 12:50 UTC, Larspolo commented on src/django/VLE/models/file_context.py
> +        elif self.assignment:
Added a test, seems to work
```
    def SetUpTestData(cls):
        cls.category = factory.Category(assignment=cls.assignment, name='aaa', n_rt_files=1)


    def test_category_factory(self):
        fc = self.category.filecontext_set.first()
        ...
        assert not fc.viewable_by(factory.Student()), \
            'Files in categories should not be viewable by random unrelated people'
        assert fc.viewable_by(factory.Journal(assignment=self.category.assignment).authors.first().user), \
            'Files in categories should be viewable by students that have a related journal'
```

2021-11-21 12:51 UTC, Larspolo commented on src/django/VLE/models/grade.py
> +        if objects.exclude(pk__in=Entry.objects.filter(node__journal=context).values('grade__pk')).exists():
I don't get it. What do you want to happen?

2021-11-21 12:55 UTC, Larspolo commented on src/django/VLE/models/grade.py
> +            user.check_permission('can_publish_grades', context)
Made it that it requires a journal query set

2021-11-21 13:08 UTC, Larspolo commented on src/django/VLE/models/journal.py
> +                raise VLEForbiddenError('You are not allowed to view these journals.')
Added bulk viewable tests

2021-11-21 13:26 UTC, Larspolo commented on src/django/VLE/models/journal.py
> +            user.check_permission('can_grade', self.assignment)
Seems like there were no tests on bonus points permission checks. Will add them now

2021-11-21 13:28 UTC, Larspolo commented on src/django/VLE/models/node.py
> +        unique_together = ('preset', 'journal')
I dont care about it, but its fine to set the standard, changed it here. if you see any other, tag me, or change it yourself

2021-11-21 13:31 UTC, Larspolo commented on src/django/VLE/models/role.py
> +        # QUESTION: Is this the right permission?
This was the only question that was already there, I was fine with the solution as well, but left the question in

2021-11-21 13:35 UTC, Larspolo commented on src/django/VLE/models/role.py
> +        if not self.role.filter(user=user).exists():
I simply renames this one instead. Seems like something that should be done anyway

2021-11-21 13:39 UTC, Larspolo commented on src/django/VLE/models/role.py
> +    def bulk_editable_by(
Ah okay. My order was first class methods, then non class methods

2021-11-21 13:41 UTC, Larspolo commented on src/django/VLE/models/role.py
> +        if self.name in ['Student', 'TA', 'Teacher']:
No. Was surprised as well
![image](https://user-images.githubusercontent.com/11822478/142764210-96520b85-9c8e-43f5-b0bb-69b5c3dffdab.png)

2021-11-21 13:42 UTC, Larspolo commented on src/django/VLE/models/rubric.py
> +
autolinter, cant wait for black to be pushed through

2021-11-21 13:42 UTC, Larspolo commented on src/django/VLE/models/rubric_submission.py
> +            skip_view_check=True,
yes!

2021-11-21 13:43 UTC, Larspolo commented on src/django/VLE/models/teacher_entry.py
> +            raise_error: bool = False):
Done, please accept the autolinter PR

2021-11-21 13:44 UTC, Larspolo commented on src/django/VLE/models/user.py
> +                pass
Never really, but I felt that if there is no instance, we assume the default -> allow standalone registration

2021-11-21 13:44 UTC, Larspolo commented on src/django/VLE/models/user.py
> +        user: Union['VLE.models.User', None],
LTI launch

2021-11-21 13:48 UTC, Larspolo commented on src/django/VLE/models/user.py
> +            raise VLEForbiddenError('You are not allowed to edit other users.')
Added test

2021-11-21 13:49 UTC, Larspolo commented on src/django/VLE/models/user.py
> +@ receiver(models.signals.post_save, sender=User)
No clue how this came to be

2021-11-21 13:49 UTC, Larspolo commented on src/django/VLE/tasks/beats/notifications.py
> +                course=course, assignment__isnull=False).values_list('assignment', flat=True).distinct():
Yes, although with this change I do agree

2021-11-21 13:51 UTC, Larspolo commented on src/django/VLE/views/assessment.py
> -        feedback, is_draft, is_published = utils.required_typed_params(
User that is unable to publish grades should be able to edit drafts, but not publish assignments. These users should not provide any `is_published` parameter to the backend. This would have triggered the `editable_by` to check if the user is able to change the published status of the assessment

2021-11-21 13:53 UTC, Larspolo commented on src/django/VLE/views/assignment.py
> +        viewable = [assignment for assignment in query if assignment.viewable_by(request.user)]
Not for now necessarily, but someday when someone wants to do stuff to speed things up, they could look for these TODO's

2021-11-21 13:54 UTC, Larspolo commented on src/django/VLE/views/assessment.py
> -        feedback, is_draft, is_published = utils.required_typed_params(
If you check the frontend, you see how I did it. I also make the UI better for these users

2021-11-21 13:56 UTC, Larspolo commented on src/django/VLE/views/comment.py
> +        comment.editable_by(request.user, fields=request.data, raise_error=True)
I find this a great approach, it automatically checks for all the values that are passed in the API, making it less error prone. Not sure on your reasoning here, I probably miss something

2021-11-21 13:58 UTC, Larspolo commented on src/django/VLE/views/entry.py
> -            return response.bad_request('Entry does not allow for a custom title.')
this is checked in the creatable_by function as well:
```
        if cls.PERMISSION_FIELDS.TITLE in fields:
            if not template.chain.allow_custom_title:
                raise VLEForbiddenError('You are not allowed to edit the title of this entry.')
```

But I do think it can be removed indeed

2021-11-21 14:00 UTC, Larspolo commented on src/django/VLE/views/grade.py
> +        # TODO: do not provide published in API if you are not allowed to publish anyway
The permission system does not check for the value, just the key. This does not work great in some cases like this. But I do think its an improvement, users should not be able to pass parameters to the backend that they are not allowed to change

2021-11-21 14:01 UTC, Larspolo commented on src/django/VLE/views/grade.py
> +        )
This comment I suppose?
![image](https://user-images.githubusercontent.com/11822478/142764880-42c2d633-1e8d-4f6e-b2b8-5c935c75c2b9.png)

2021-11-21 14:03 UTC, Larspolo commented on src/django/VLE/views/journal.py
> +        if not journal.editable_by(request.user, fields=[Journal.PERMISSION_FIELDS.MEMBERS]):
Think it would have been save, but I added an else case just in case

2021-11-21 14:05 UTC, Larspolo commented on src/django/VLE/views/member.py
> +        # do we wanna keep it that way?
Nope
![image](https://user-images.githubusercontent.com/11822478/142765008-45626250-0325-4f42-93bf-d5373e60632d.png)

2021-11-21 14:06 UTC, Larspolo commented on src/django/VLE/views/participation.py
> +        # QUESTION: whats up with the mix between User and participation serializers here and in members?
Its not used frontend in either case, but its straving away from REST

2021-11-25 10:25 UTC, mjvkeulen commented on src/django/VLE/models/assessment.py
> +        raise_error: bool = False,
I am not sure if we understand eachother. I meant:

Why motivated setting the parameter `raise_exception` to `False` in most permission functions by default? 

My motivation is that with the default, a permission call function as `has_permission_X` instead of `check_can_X` did in regards to raising an exception or returning a boolean.

I would argue its probably better (by default) to raise an exception (and thus block a permission) when someone forgets, than allow something to happen (as there is no guarantee the return value is used)

2021-11-25 10:27 UTC, mjvkeulen commented on src/django/VLE/models/base.py
> +            skip_view_check: bool = kwargs.get('skip_view_check', default_args.get('skip_view_check', True))
> In that case, "viewable_by" or "bulk_viewable_by" would recursively call themself. Or is_locked would needlessly call "viewable_by". 

Both examples are technicalities of the current implementation and do not motivate opting for a specific default.

> I see this as the sensible default actually

Statement: could you argue why?

2021-11-25 10:29 UTC, mjvkeulen commented on src/django/VLE/models/grade.py
> +        # QUESTION: should student be able to always see all published grades on their own entry? We currently don't
Right so your question is does `can_view_grade_history` govern access to `Acrhived` and/or `Unpublished`?

I would argue for access to `Archived` only, and `Unpublished` can only be seen by someone with the permission to grade.

2021-11-25 10:33 UTC, mjvkeulen commented on src/django/VLE/models/group.py
> +        user.check_permission('can_view_course_users', context)
I am not against adding more permission myself, but this is not something that has to be done in this PR.

Feels like you agree with adding a permission for this, so shall we make an issue?

2021-11-25 10:37 UTC, mjvkeulen commented on src/django/VLE/models/journal.py
> +        user.check_permission('can_manage_journals', self.assignment)
Right so @engelhamer opinion? Move to issue prob

2021-11-25 10:43 UTC, mjvkeulen commented on src/django/VLE/models/role.py
> +        if self.name in ['Student', 'TA', 'Teacher']:
https://ejournal.atlassian.net/browse/EJ-1178

2021-11-25 10:49 UTC, mjvkeulen commented on src/django/VLE/views/assignment.py
> +        viewable = [assignment for assignment in query if assignment.viewable_by(request.user)]
Epic & issue?

2021-11-25 10:52 UTC, mjvkeulen commented on src/django/VLE/views/rubric.py
> +        source_rubric.viewable_by(request.user, raise_error=True)
Would it be serialized though? Prob not doable via normal API, so this is a quirk: not viewable but is importable

2021-11-25 10:53 UTC, mjvkeulen commented on src/django/test/test_assessment.py
> +            can_view_mock.assert_called()
@engelhamer opinion?

2021-11-25 11:15 UTC, Larspolo commented
___
*[src/django/test/test_entry.py, line 625 at r1](https://reviewable.io/reviews/ejourn-al/ejournal/1245#-MpLnSrd0xd78BINI2KN:-MpLnSrd0xd78BINI2KO:b-1o05fz) ([raw file](https://github.com/ejourn-al/ejournal/blob/87404f15c7f22b9f2cb9705827930488aeb03be1/src/django/test/test_entry.py#L625)):*
> ```Python
>         self.assertRaises(
>             VLEForbiddenError,
>             mocked_entry.editable_by,
> ```

Nit this is a test


<!-- Sent from Reviewable.io -->

2021-12-21 16:37 UTC, Larspolo commented on src/django/VLE/models/base.py
> +            skip_view_check: bool = kwargs.get('skip_view_check', default_args.get('skip_view_check', True))
I dont see permissions _by definition_ requiring a `viewable_by` check.

2021-12-21 16:47 UTC, Larspolo commented on src/django/VLE/models/group.py
> +        user.check_permission('can_view_course_users', context)
Sounds good

2021-12-21 16:47 UTC, Larspolo commented on src/django/VLE/models/participation.py
> +        # and NOT the "can_view_course_users" permission? Because that was the case through the members list API call
Could do, I think we already have a related issue on this with premission dependencies being outdated. I highly doubt our platform handling this case nicely

2021-12-22 10:00 UTC, engelhamer commented on src/django/VLE/models/participation.py
> +        # and NOT the "can_view_course_users" permission? Because that was the case through the members list API call
Think it is indeed better to make it required to also have `can_view_course_users`.

2021-12-22 10:00 UTC, engelhamer commented on src/django/VLE/models/rubric.py
> +        # TODO: students need to only be able to see their own rubric
This is not yet fixed? How does this relate to the other rubric visibility PR?

2021-12-22 10:00 UTC, engelhamer commented on src/django/VLE/models/teacher_entry.py
> +        # Cuz now you cant post teacher entries if you dont have can_grade.
Then this should also be enforced in the role editor.

2021-12-22 10:00 UTC, engelhamer commented on src/django/VLE/models/user.py
> +                pass
But an `Instance` is automatically created on get if it does not exist.

2021-12-22 10:00 UTC, engelhamer commented on src/django/VLE/models/user.py
> +        # User is viewing himself
Also themself

2021-12-22 10:00 UTC, engelhamer commented on src/django/VLE/views/assessment.py
> -        feedback, is_draft, is_published = utils.required_typed_params(
`assignments` -> `assessments`? Confused me there.

2021-12-22 10:00 UTC, engelhamer commented on src/django/VLE/models/course.py
> +    def is_participant(self, user: 'VLE.models.User', raise_exception: bool = False):
This name is not consistent with the others

COURSE creatable_by USER -> The course is creatable by te user
COURSE is_participant USER -> The course is participant of the user

Makes no sense.

2021-12-22 12:58 UTC, Larspolo commented on src/django/VLE/models/course.py
> +            raise VLEForbiddenError('You are not a participant of this course.')
Not this function, but in the assignment has_participation, it does have it when addding members. Changed all to "user is not..."

2021-12-22 13:01 UTC, engelhamer commented on src/django/VLE/models/base.py
> +            skip_view_check: bool = kwargs.get('skip_view_check', default_args.get('skip_view_check', True))
The name also does not make sense: if it is the default to **not** perform this check, then it is weird to call it **skip**.

2021-12-22 13:01 UTC, engelhamer commented on src/django/VLE/models/base.py
> +            skip_view_check: bool = kwargs.get('skip_view_check', default_args.get('skip_view_check', True))
So if you want this to be checked, you should explicitly say you **do not want to skip it** 😅

2021-12-22 13:08 UTC, Larspolo commented on src/django/VLE/models/grade.py
> +        context.viewable_by(user, raise_exception=True)
Grading entries outside of your `can_view_journals_of_own_groups` permission

2021-12-22 13:10 UTC, Larspolo commented on src/django/VLE/models/grade.py
> +    class PERMISSION_FIELDS(LowercaseStrEnum):
Single grades are never viewed or edited, no need to implement a function

2021-12-22 13:11 UTC, Larspolo commented on src/django/VLE/models/journal.py
> +            groups=VLE.models.Group.objects.filter(
That is handled inside the `supervisors_only` function. User needs to have
-  `can_view_all_journals` or 
- `can_view_journals_of_own_groups` together with the groups passed in the parameter

2021-12-22 13:20 UTC, Larspolo commented on src/django/VLE/models/entry.py
> +        return not self.is_locked() and not self.is_graded()
Problem is that you do not always have the correct user, kept it like this for now

2021-12-22 13:26 UTC, Larspolo commented on src/django/VLE/models/teacher_entry.py
> +        # Cuz now you cant post teacher entries if you dont have can_grade.
Created an issue

2021-12-22 14:40 UTC, Larspolo commented on src/django/VLE/models/base.py
> +            skip_view_check: bool = kwargs.get('skip_view_check', default_args.get('skip_view_check', True))
If the param is not there -> dont run the viewable by check
If the param is there -> check its value
   if true -> dont run the viewable by check
   if false -> do run the viewable by check

Could be changed to `do_view_check` and default it to false. Would that solve the discussion though?

2021-12-22 14:50 UTC, Larspolo commented on src/django/VLE/views/assessment.py
> -        feedback, is_draft, is_published = utils.required_typed_params(
assessment indeed

2021-12-22 14:54 UTC, Larspolo commented on src/django/VLE/views/assignment.py
> +        viewable = [assignment for assignment in query if assignment.viewable_by(request.user)]
https://ejournal.atlassian.net/browse/EJ-1226

2021-12-22 14:57 UTC, Larspolo commented on src/django/VLE/views/rubric.py
> +        source_rubric.viewable_by(request.user, raise_error=True)
True, fine by me though

2021-12-22 16:16 UTC, engelhamer commented on src/django/VLE/models/grade.py
> +        context.viewable_by(user, raise_exception=True)
That should not be possible indeed.

2021-12-22 16:21 UTC, engelhamer commented on src/django/VLE/models/entry.py
> +        return not self.is_locked() and not self.is_graded()
Why don't you have that?

2021-12-22 16:21 UTC, engelhamer commented on src/django/VLE/models/entry.py
> +        return not self.is_locked() and not self.is_graded()
Issue then resolve is also ok.

2021-12-22 16:23 UTC, engelhamer approved these changes

2021-12-22 20:21 UTC, mjvkeulen commented on src/django/VLE/models/base.py
> +            skip_view_check: bool = kwargs.get('skip_view_check', default_args.get('skip_view_check', True))
Permission default should default to the strictest possible value. Only by explicitly relaxing requirements should a check be omitted.

2021-12-22 21:16 UTC, Larspolo commented on src/django/VLE/models/group.py
> +        #     raise VLEPermissionError(message='You are not allowed to view the user groups of this course.')
> does our UI even work if you can't also see the users in a group?

Highly doubt it works well

>  Does the backend leak any group information in this scenario?

Well, the other permissions are CUD, so it feels cuter-intuitive for me to say that if you could access more information if you had any of those permissions

2021-12-23 08:45 UTC, mjvkeulen commented on src/django/VLE/models/base.py
> +            skip_view_check: bool = kwargs.get('skip_view_check', default_args.get('skip_view_check', True))
@engelhamer could possibly weigh in on this as well?

2021-12-23 10:00 UTC, Larspolo commented on src/django/VLE/models/base.py
> +            skip_view_check: bool = kwargs.get('skip_view_check', default_args.get('skip_view_check', True))
I can default editable_by and deletable_by to have it by default, but it makes no sence for the other permission checks

2021-12-23 10:01 UTC, Larspolo commented on src/django/VLE/models/base.py
> +            skip_view_check: bool = kwargs.get('skip_view_check', default_args.get('skip_view_check', True))
Once the parameter is given, the default is the strictest possible value

2021-12-24 09:52 UTC, Larspolo reviewed
> *[Reviewable](https://reviewable.io/reviews/ejourn-al/ejournal/1245)* status: 0 of 99 files reviewed, 14 unresolved discussions (waiting on @engelhamer and @mjvkeulen)

___
*[src/django/VLE/models/course.py, line 88 at r4](https://reviewable.io/reviews/ejourn-al/ejournal/1245#-MpLl-UcOMXeTurBy14F-r4-88:-MrfpnCJ8gL92tk-LJl7:b-a8xhr0) ([raw file](https://github.com/ejourn-al/ejournal/blob/a7fb7f4ce7f709dd62590794f7eea5e20ae64655/src/django/VLE/models/course.py#L88)):*
<details><summary><i>Previously, engelhamer (Engel Hamer) wrote…</i></summary><blockquote>

This name is not consistent with the others

COURSE creatable_by USER -> The course is creatable by the user
COURSE is_participant USER -> The course is participant of the user

Makes no sense.
</blockquote></details>

renamed to check_participation
___
*[src/django/VLE/models/entry.py, line 429 at r2](https://reviewable.io/reviews/ejourn-al/ejournal/1245#-MpLl-UcOMXeTurBy14G-r2-429:-MrfpsqMCo-Ja9hjguaM:b-896fix) ([raw file](https://github.com/ejourn-al/ejournal/blob/bc25b95dbce5af57245114750cdda22a09bc2f95/src/django/VLE/models/entry.py#L429)):*
<details><summary><i>Previously, engelhamer (Engel Hamer) wrote…</i></summary><blockquote>

Shouldn't this error take precedence over all others?
</blockquote></details>

Done.
___
*[src/django/VLE/models/entry.py, line 432 at r2](https://reviewable.io/reviews/ejourn-al/ejournal/1245#-MpLl-UcOMXeTurBy14G-r2-432:-MrfqEyE6r04l08uNKU-:boywn0s) ([raw file](https://github.com/ejourn-al/ejournal/blob/bc25b95dbce5af57245114750cdda22a09bc2f95/src/django/VLE/models/entry.py#L432)):*
<details><summary><i>Previously, engelhamer (Engel Hamer) wrote…</i></summary><blockquote>

Issue then resolve is also ok.
</blockquote></details>

https://ejournal.atlassian.net/browse/EJ-1229
made an issue
___
*[src/django/VLE/models/grade.py, line 139 at r2](https://reviewable.io/reviews/ejourn-al/ejournal/1245#-MpLl-UcOMXeTurBy14K-r2-139:-MrfqNPy0lTlhc8cifLi:bcfz43l) ([raw file](https://github.com/ejourn-al/ejournal/blob/bc25b95dbce5af57245114750cdda22a09bc2f95/src/django/VLE/models/grade.py#L139)):*
<details><summary><i>Previously, engelhamer (Engel Hamer) wrote…</i></summary><blockquote>

That should not be possible indeed.
</blockquote></details>

Then this check should stay right? Can be resolved?
___
*[src/django/VLE/models/grade.py, line 178 at r2](https://reviewable.io/reviews/ejourn-al/ejournal/1245#-MpLl-UcOMXeTurBy14K-r2-178:-MrfqXgT7l_r5hJo-CcU:b-896fix) ([raw file](https://github.com/ejourn-al/ejournal/blob/bc25b95dbce5af57245114750cdda22a09bc2f95/src/django/VLE/models/grade.py#L178)):*
<details><summary><i>Previously, engelhamer (Engel Hamer) wrote…</i></summary><blockquote>

Leftover
</blockquote></details>

Done.
___
*[src/django/VLE/models/journal.py, line 640 at r2](https://reviewable.io/reviews/ejourn-al/ejournal/1245#-MpLl-UcOMXeTurBy14N-r2-640:-MrfqaeJ8FYYIJOLP9nv:b-896fix) ([raw file](https://github.com/ejourn-al/ejournal/blob/bc25b95dbce5af57245114750cdda22a09bc2f95/src/django/VLE/models/journal.py#L640)):*
<details><summary><i>Previously, engelhamer (Engel Hamer) wrote…</i></summary><blockquote>

Don't we need to check here if `self.assignment.is_group_assignment`?
</blockquote></details>

Done.
___
*[src/django/VLE/models/journal.py, line 724 at r2](https://reviewable.io/reviews/ejourn-al/ejournal/1245#-MpLl-UcOMXeTurBy14N-r2-724:-MrfqdWVAs6xQG_3tSBk:b-896fix) ([raw file](https://github.com/ejourn-al/ejournal/blob/bc25b95dbce5af57245114750cdda22a09bc2f95/src/django/VLE/models/journal.py#L724)):*
<details><summary><i>Previously, engelhamer (Engel Hamer) wrote…</i></summary><blockquote>

```suggestion
                raise VLEForbiddenError('You can only change the members of a journal for group assignments.')
```

Consistent with the error lines below.
</blockquote></details>

Done.
___
*[src/django/VLE/models/rubric.py, line 178 at r4](https://reviewable.io/reviews/ejourn-al/ejournal/1245#-MpLl-UcOMXeTurBy14V-r4-178:-MrfqfLr7-YuTkPAPQt0:b-896fix) ([raw file](https://github.com/ejourn-al/ejournal/blob/a7fb7f4ce7f709dd62590794f7eea5e20ae64655/src/django/VLE/models/rubric.py#L178)):*
<details><summary><i>Previously, engelhamer (Engel Hamer) wrote…</i></summary><blockquote>

This is not yet fixed? How does this relate to the other rubric visibility PR?
</blockquote></details>

Done.
___
*[src/django/VLE/models/user.py, line 191 at r2](https://reviewable.io/reviews/ejourn-al/ejournal/1245#-MpLl-UcOMXeTurBy14Z-r2-191:-Mrfqgd1CtKPkY5PDAT9:b-896fix) ([raw file](https://github.com/ejourn-al/ejournal/blob/bc25b95dbce5af57245114750cdda22a09bc2f95/src/django/VLE/models/user.py#L191)):*
<details><summary><i>Previously, engelhamer (Engel Hamer) wrote…</i></summary><blockquote>

Also themself
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-24 10:29 UTC, mjvkeulen approved these changes

2021-12-24 11:24 UTC, merged