Improved loading speed of assignment API requests
eJourn-al/eJournal pull request #1250
Opened 2021-11-01 22:33 UTC by Larspolo

Including only the serializations that are needed.

Course overview page was about 5 to 10 seconds, which is now 0.5 to 1 second. Other pages also some improvements, but 
![image](https://user-images.githubusercontent.com/11822478/139749045-7f3ca9f5-1799-4d7e-bd91-09bab322e973.png)

Also fixed an issue where badges would not show if it only has unpublished assessments

2021-11-02 08:45 UTC, mjvkeulen requested changes
Just wondering, did you also consider moving the deadlines, journals, and/or stats to their own API?

2021-11-02 08:45 UTC, mjvkeulen commented on src/vue/src/store/modules/assignment.js
> +            return assignmentAPI.get(id, cID, true, true, true, connArgs)
Should these arguments not be passable from the retrieve itself?

I would also argue that these arguments should default to false here as well.

The idea is that the vuex modules incrementally remove the need for api/* files, so I would prefer if we could do away with the import here.

2021-11-02 10:04 UTC, Larspolo commented on src/django/VLE/views/assignment.py
> +                (bool, 'serialize_deadline', False),
deadline is singular, only 1 deadline will be serialized. Is consistent with the `get_deadline` and `get_stats` functions

2021-11-02 10:06 UTC, Larspolo commented on src/vue/src/store/modules/assignment.js
> +            return assignmentAPI.get(id, cID, true, true, true, connArgs)
I imagined that the store would need to have consistent data always, else you will have different values inside the stored assignment, depending on the first time it was accessed

2021-11-02 10:07 UTC, Larspolo commented on src/vue/src/store/modules/assignment.js
> +            return assignmentAPI.get(id, cID, true, true, true, connArgs)
Will change it to an auth again. But waiting for a full review before changing it

2021-11-02 10:20 UTC, mjvkeulen commented on src/vue/src/store/modules/assignment.js
> +            return assignmentAPI.get(id, cID, true, true, true, connArgs)
Yes, this touches on the topic of splitting expensive conditional data to its own API. 

The assignment retrieve is called on **each** page which aID in the route.

2021-11-03 12:59 UTC, Larspolo commented on src/vue/src/store/modules/assignment.js
> +            return assignmentAPI.get(id, cID, true, true, true, connArgs)
Removed the API again

2021-11-05 08:21 UTC, mjvkeulen commented on src/vue/src/store/modules/assignment.js
> +            return assignmentAPI.get(id, cID, true, true, true, connArgs)
Its also cached, but this is complicated by the addition of thee conditional arguments in the API.

2021-11-05 10:12 UTC, Larspolo commented on src/vue/src/store/modules/assignment.js
> +            return assignmentAPI.get(id, cID, true, true, true, connArgs)
Thats why its always true, makes it non-conditional (functioning the same as it does rn). While all other requests can be improved that do not yet have the caching system

2021-11-08 09:00 UTC, mjvkeulen commented on src/django/VLE/serializers.py
> +        if not self.context.get('serialize_deadline', False):
[D] Should we standardize something for this pattern?

Only include fields if a specific key (and/or value) is present?

For example a mixin which allows for:
```
conditional_fields = [
    'deadline',
    'journals',
    'stats',
]
```

Which are then only serialized provided the correct context is set?

2021-11-08 09:02 UTC, mjvkeulen commented on src/django/VLE/views/assignment.py
> +        print(serialize_journals, serialize_stats, serialize_deadline)
Left over

2021-11-13 11:49 UTC, Larspolo commented on src/django/VLE/serializers.py
> +        if not self.context.get('serialize_deadline', False):
Agree, and did it https://github.com/eJourn-al/eJournal/pull/1250/commits/466178e8e9f34bee3dd15d05d92713bd4af97fe8?w=1

2021-11-15 07:50 UTC, engelhamer approved these changes

2021-11-18 10:11 UTC, mjvkeulen approved these changes

2021-11-18 10:12 UTC, merged