Added the ability to publish a saved comment
eJourn-al/eJournal pull request #1252
Opened 2021-11-03 18:53 UTC by Larspolo

![image](https://user-images.githubusercontent.com/11822478/140174370-9149a7fb-20c8-4a29-8e7a-c2ed0ff689b7.png)

2021-11-04 10:02 UTC, mjvkeulen requested changes
1. Create a comment using Send & Publish After Grade
2. Edit comment
3. Options are now Send, and Send & Publish

This is confusing, which options should I use to just edit my comment without sending it directly (as was intended).

The use of `Send` in this scenario is just confusing. When editing a nonpublished comment I would expect to see `Save`.

I propose to rename `Send & Publish After Grade` to `Save & Publish After Grade` so we can use `Save` when editing a non-published comment.

2021-11-05 22:02 UTC, Larspolo commented
The comment is valid, and with it I discovered some [more stuff](https://ejournal.atlassian.net/browse/EJ-1163). Changed the name, also renames "Send & Publish" to just "Publish". Also changed the icon to a save icon

![image](https://user-images.githubusercontent.com/11822478/140582939-292f07c3-77f4-49a7-8b9d-39c3acabc42d.png)

2021-11-06 07:59 UTC, mjvkeulen approved these changes

2021-11-06 07:59 UTC, mjvkeulen commented on src/vue/src/components/entry/CommentCard.vue
> +                published: this.comment.published || this.publishOnUpdate === 'true',
Is this some limitation of the dropdown button? Why can't we work with `true` as a boolean instead of string?

2021-11-06 07:59 UTC, mjvkeulen commented on src/vue/src/components/entry/CommentCard.vue
> +                            text: 'publish',
[NIT] Capitalized anyway but..

2021-11-06 09:08 UTC, Larspolo commented on src/vue/src/components/entry/CommentCard.vue
> +                published: this.comment.published || this.publishOnUpdate === 'true',
limitation of the dropdown button. It is based on the object key

2021-11-06 09:08 UTC, Larspolo commented on src/vue/src/components/entry/CommentCard.vue
> +                            text: 'publish',
Automatically done

2021-11-14 22:19 UTC, engelhamer approved these changes

2021-11-15 10:42 UTC, merged