Added a display for the error messages received from grade passback
eJourn-al/eJournal pull request #1253
Opened 2021-11-05 10:10 UTC by Larspolo

![image](https://user-images.githubusercontent.com/11822478/140494212-ec84f246-f76a-4bef-95d6-4d3f993f7b3c.png)

![image](https://user-images.githubusercontent.com/11822478/140494243-39a5a3de-0c53-41a3-9898-c90d035ce0ef.png)

2021-11-06 08:37 UTC, mjvkeulen requested changes

2021-11-06 08:37 UTC, mjvkeulen commented on src/vue/src/components/assignment/JournalCard.vue
> +                                />
I would move the config of the icon used for this purpose to a component

2021-11-06 08:37 UTC, mjvkeulen commented on src/vue/src/components/assignment/JournalCard.vue
> +                                    v-b-tooltip="`The grade could not be send to the LMS. ${journal.LMS_message}`"
When a teacher reads this, what action should they take?

This is currently missing.

2021-11-06 08:37 UTC, mjvkeulen commented on src/django/VLE/utils/grading.py
> +    if response_teacher is not None and response_teacher['code_mayor'] != 'success':
We basically define what constitutes an unsuccessful LMS response in this check: move this to a function?

2021-11-06 08:37 UTC, mjvkeulen commented on src/django/VLE/utils/grading.py
> +    successful = True
A bit like defensive programming with permissions, should we not start with False (unsuccessful) and only flag successful to true if the response code exactly matched a successful response?

2021-11-06 08:37 UTC, mjvkeulen commented on src/vue/src/components/assignment/JournalCard.vue
> +                                    v-b-tooltip="`The grade could not be send to the LMS. ${journal.LMS_message}`"
I also believe showing the actual error msg is not likely to be helpful? Or is this something they then google (technical already imo)?

2021-11-06 09:10 UTC, Larspolo commented on src/vue/src/components/assignment/JournalCard.vue
> +                                />
It has different classes

2021-11-06 09:14 UTC, Larspolo commented on src/vue/src/components/assignment/JournalCard.vue
> +                                    v-b-tooltip="`The grade could not be send to the LMS. ${journal.LMS_message}`"
> When a teacher reads this, what action should they take?

Passing this back to you, what action should they take? Any suggestions?

> I also believe showing the actual error msg is not likely to be helpful? Or is this something they then google (technical already imo)?

I think it is. The error message indicate if the user left the course, or if the assignment already finished

2021-11-06 09:15 UTC, Larspolo commented on src/django/VLE/utils/grading.py
> +    if response_teacher is not None and response_teacher['code_mayor'] != 'success':
This is not for this PR, but could be. We do a lot of awful stuff. Maybe something to improve in the LTI1.3 PR

2021-11-06 09:17 UTC, Larspolo commented on src/django/VLE/utils/grading.py
> +    successful = True
This is nicer to combine with the LMS_message response, else we would have to do this twice. NIT?

2021-11-06 11:30 UTC, mjvkeulen commented on src/vue/src/components/assignment/JournalCard.vue
> +                                />
Just some positioning classes, works fine if this is set on a component instead.

2021-11-08 08:38 UTC, mjvkeulen commented on src/vue/src/components/assignment/JournalCard.vue
> +                                    v-b-tooltip="`The grade could not be send to the LMS. ${journal.LMS_message}`"
Can we isolate what errors would be due to a more temporary condition (e.g. connectivity)?

If this is too much work, just provide generic advise:

- Try to publish the journal grades and see if the problem persists
- Are you sure the student is still part of the LMS course?
- Contact support if the problem persists and the steps above do not apply.

We can format this nicely, could even be a modal for more space.

2021-11-08 08:40 UTC, mjvkeulen commented on src/django/VLE/utils/grading.py
> +    if response_teacher is not None and response_teacher['code_mayor'] != 'success':
Seems like a simple fix, may as well since we touch the line here?

2021-11-08 08:41 UTC, mjvkeulen commented on src/django/VLE/utils/grading.py
> +    successful = True
How do you perceive a comment about an approach as a NIT?

2021-11-08 08:44 UTC, Larspolo commented on src/vue/src/components/assignment/JournalCard.vue
> +                                    v-b-tooltip="`The grade could not be send to the LMS. ${journal.LMS_message}`"
> Can we isolate what errors would be due to a more temporary condition

Not sure on the full list of errors that are thrown

2021-11-08 08:45 UTC, Larspolo commented on src/django/VLE/utils/grading.py
> +    successful = True
Because it works as is, and "This is nicer to combine with the LMS_message response, else we would have to do this twice".

2021-11-13 10:49 UTC, Larspolo commented on src/vue/src/components/assignment/JournalCard.vue
> +                                    v-b-tooltip="`The grade could not be send to the LMS. ${journal.LMS_message}`"
![image](https://user-images.githubusercontent.com/11822478/141617310-06852565-b219-4780-b912-63fc976f51ea.png)

2021-11-13 10:51 UTC, Larspolo commented on src/django/VLE/utils/grading.py
> +    if response_teacher is not None and response_teacher['code_mayor'] != 'success':
You may add it if you want

2021-11-14 22:28 UTC, engelhamer commented on src/vue/src/components/assignment/JournalCard.vue
> +                                <l-m-s-message
Would prefer import as `LmsMessage` down below to avoid this weird kebab case style.

2021-11-14 22:28 UTC, engelhamer commented on src/vue/src/components/assignment/JournalCard.vue
> +                                <l-m-s-message
Also: maybe move this to next to the grade (above progress bar) instead of next to the student name? Since this error is about the grade not being passed back.

2021-11-14 22:28 UTC, engelhamer commented on src/vue/src/components/journal/LMSMessage.vue
> +            When sending the grade of this journal to the LMS, we received to following error:
```suggestion
            When sending the grade of this journal to the LMS, we encountered the following error:
```

2021-11-14 22:28 UTC, engelhamer commented on src/vue/src/components/journal/LMSMessage.vue
> +            To solve this problem, try the following:
```suggestion
            To resolve this issue, try the following:
```

2021-11-14 22:28 UTC, engelhamer commented on src/vue/src/components/journal/LMSMessage.vue
> +                <li>Check if the student is still in the course</li>
`;` at the end of every but the last line?

2021-11-14 22:28 UTC, engelhamer commented on src/vue/src/components/journal/LMSMessage.vue
> +                <li>Check if the enrollment of the student is not concluded</li>
The standard spelling of `enrolment` in British English only has one L.

2021-11-14 22:28 UTC, engelhamer commented on src/vue/src/components/journal/LMSMessage.vue
> +                >Contact support</a> if the problem persists</li>
```suggestion
                >Contact support</a> if the issue persists.</li>
```

2021-11-15 10:59 UTC, Larspolo commented on src/vue/src/components/journal/LMSMessage.vue
> +                <li>Check if the enrollment of the student is not concluded</li>
Good thing you say. We use "color" in the category edit

![image](https://user-images.githubusercontent.com/11822478/141770369-d3199147-5b04-4e0b-a2e8-a80dcc1e2f47.png)

2021-11-15 11:05 UTC, Larspolo commented on src/vue/src/components/assignment/JournalCard.vue
> +                                <l-m-s-message
I think next to the name is more prominent, which this should be. The badges that are about grading are also not on the progress bar

2021-11-17 14:51 UTC, engelhamer commented on src/vue/src/components/assignment/JournalCard.vue
> +                                <l-m-s-message
But why do you put it in the assessment card on the journal page then? I think this should be consistent.

Badges can also be moved, no problem for me.

2021-11-17 14:58 UTC, engelhamer commented on src/vue/src/components/journal/LmsMessage.vue
> +                v-b-tooltip="`The grade could not be send to the LMS. Click to view more.`"
```suggestion
                v-b-tooltip="`The grade could not be sent to the LMS. Click to learn more.`"
```

2021-11-18 09:59 UTC, mjvkeulen requested changes

2021-11-18 09:59 UTC, mjvkeulen commented on src/django/VLE/models/journal.py
> +        null=True,
For text fields we are better of with null=False, blank=True, and default='' in situations where we do not use `null` differently than `''`.

2021-11-18 09:59 UTC, mjvkeulen commented on src/vue/src/components/journal/JournalAssessmentCard.vue
> +            <lms-message
Would you mind adding one of these to the preset DB?

2021-11-18 09:59 UTC, mjvkeulen commented on src/vue/src/components/journal/LmsMessage.vue
> +    <span class="d-inline">
This component should only be visible to users that can grade

2021-11-18 09:59 UTC, mjvkeulen commented on src/vue/src/components/journal/LmsMessage.vue
> +                class="ml-1 text-orange"
![image](https://user-images.githubusercontent.com/39912610/142392082-6cd6e38c-75bb-4c57-a1a5-7ce9fecf5841.png)

Add `shift-up-3` to fix the icon alignment issue.

2021-11-18 09:59 UTC, mjvkeulen commented on src/vue/src/components/journal/LmsMessage.vue
> +            <b-alert
I would expect similar spacing before as after the alert:

![image](https://user-images.githubusercontent.com/39912610/142392446-d59dffc6-7d60-4781-a663-c0a56c3f0a51.png)

2021-11-18 09:59 UTC, mjvkeulen commented on src/vue/src/components/journal/LmsMessage.vue
> +                    href="mailto:support@ejournal.app"
I would expect this to open our support modal, which should be doable with a simple root emit.

Nice to have would be some prefilled content and the help tab preselected.

2021-11-18 09:59 UTC, mjvkeulen commented on src/vue/src/components/journal/LmsMessage.vue
> +                    href="mailto:support@ejournal.app"
[NIT] I would also formulate this as a button (`variant="link"`) at the bottom of the modal (so separate from the list of steps the user can do on their own, as this is really (hopefully) the last resort).

2021-11-18 09:59 UTC, mjvkeulen commented on src/vue/src/components/journal/LmsMessage.vue
> +                class=" alert-dark"
Should we phrase an error not at least as a warning? (So atleast background yellow)

2021-11-18 11:22 UTC, Larspolo commented on src/vue/src/components/assignment/JournalCard.vue
> +                                <l-m-s-message
Moved it to the journal details card then

2021-11-18 11:23 UTC, Larspolo commented on src/django/VLE/models/journal.py
> +        null=True,
`None` is no message, `''` is more of a mistake that should not happen imo

2021-11-18 11:24 UTC, Larspolo commented on src/vue/src/components/journal/JournalAssessmentCard.vue
> +            <lms-message
Added in logboek and for user `student`

2021-11-18 11:25 UTC, Larspolo commented on src/vue/src/components/journal/LmsMessage.vue
> +    <span class="d-inline">
Should it? Maybe useful for the student to see as well, and I dont mind others seeing it too

2021-11-18 11:27 UTC, Larspolo commented on src/vue/src/components/journal/LmsMessage.vue
> +            <b-alert
Like this?
![image](https://user-images.githubusercontent.com/11822478/142406962-e4d6bd16-ad0a-41b8-8d54-ac843ad0f309.png)

This is not the default bootstrap css then

2021-11-18 11:38 UTC, Larspolo commented on src/vue/src/components/journal/LmsMessage.vue
> +                class=" alert-dark"
See https://github.com/eJourn-al/eJournal/pull/1253?w=1#discussion_r752150731

2021-11-18 11:39 UTC, Larspolo commented on src/vue/src/components/journal/LmsMessage.vue
> +                    href="mailto:support@ejournal.app"
![image](https://user-images.githubusercontent.com/11822478/142408608-6e66da40-2186-46fb-a69c-294613d8d24d.png)

2021-11-18 11:45 UTC, Larspolo commented on src/vue/src/components/journal/JournalAssessmentCard.vue
> +            <lms-message
https://github.com/eJourn-al/eJournal-commands/pull/12

2021-11-18 11:47 UTC, Larspolo commented on src/vue/src/components/journal/LmsMessage.vue
> +                    href="mailto:support@ejournal.app"
> Nice to have would be some prefilled content and the help tab preselected.

Don't know how to do this nicely. Furthermore, not auto-filling content also increases the barrier to contact support ;)

2021-11-20 08:47 UTC, mjvkeulen commented on src/vue/src/components/journal/LmsMessage.vue
> +    <span class="d-inline">
Much of the advice does not apply to non-teaching staff right?

2021-11-20 09:20 UTC, mjvkeulen approved these changes
I still disagree with:

- field=models.TextField(default=None, null=**True**)

On the fence about showing the message to students as well

2021-11-25 20:52 UTC, engelhamer commented on src/vue/src/components/assignment/JournalCard.vue
> +                                <l-m-s-message
So then for consistency, also show it next to the grade (which this whole thing is about, not the name of the student) in the journal card?

2021-11-25 20:53 UTC, engelhamer commented on src/vue/src/components/journal/LmsMessage.vue
> +    <span class="d-inline">
I think teacher-only is fine. The errors originate from their actions (grading) after all.

2021-11-25 20:56 UTC, engelhamer approved these changes

2021-11-25 21:42 UTC, merged