Added a wysiwyg template editor
eJourn-al/eJournal pull request #1254
Opened 2021-11-06 12:40 UTC by Larspolo

## Description
Was inspired by Jira, let's see what you think of something like this. Would be nice to show at SURF, but Idk how much time we have

![image](https://user-images.githubusercontent.com/11822478/140609903-2d714ccb-9e38-4124-9f72-840680fe1282.png)

2021-11-06 14:35 UTC, mjvkeulen commented on src/vue/src/sass/partials/text.sass
> +    text-align: left
Would these work?

https://getbootstrap.com/docs/4.0/utilities/text/

2021-11-06 14:51 UTC, mjvkeulen requested changes
Feels much more intuitive already!

2021-11-06 14:51 UTC, mjvkeulen commented on src/vue/src/components/template/TemplateEdit.vue
> +        <b-tabs
I really like the tabs, happy we can split settings mess from field set.

2021-11-06 14:51 UTC, mjvkeulen commented on src/vue/src/components/template/TemplateEdit.vue
> +                </template>
This now varies from all other preview buttons in the editor (I would like to keep this consistent).

Would using the old button (not as tab) work?

2021-11-06 14:51 UTC, mjvkeulen commented on src/vue/src/components/entry/EntryFieldDisplay.vue
> -            }"
[Q] How come this could be removed?

2021-11-06 14:51 UTC, mjvkeulen commented on src/vue/src/components/template/TemplateEdit.vue
> +                    Preview
Preview is missing from create new template (can preview when editing a template?)

2021-11-06 14:51 UTC, mjvkeulen commented on src/vue/src/components/template/TemplateEdit.vue
> +        >
How about adding a delete icon to the custom title field? Clicking this would turn the setting off (and remove that "field"). 

This is more important now since the setting is found on a different tab.

2021-11-06 15:34 UTC, Larspolo commented on src/vue/src/components/template/TemplateEdit.vue
> +                    Preview
Was thinking of removing the preview fully. What are your thoughts on that?

2021-11-06 15:35 UTC, Larspolo commented on src/vue/src/components/template/TemplateEdit.vue
> +        >
Might cause confusion

2021-11-06 15:54 UTC, Larspolo commented on src/vue/src/components/entry/EntryFieldDisplay.vue
> -            }"
Not surenot sure. Might have been some debugging

2021-11-07 12:59 UTC, Larspolo commented on src/vue/src/components/template/TemplateEdit.vue
> +        >
I removed custom title field as setting, and put it inside the field editor. No confusion of one tab influencing the other

2021-11-07 13:00 UTC, Larspolo commented on src/vue/src/components/template/TemplateEdit.vue
> +                </template>
Tabs do now work nicely with buttons, would require more styling work than you might expect.

Also, with now your other suggestion on moving the title, I am more lenient to fully removing the preview.

2021-11-07 19:20 UTC, mjvkeulen commented on src/vue/src/components/template/TemplateEdit.vue
> +                </template>
We have outstanding issues to improve the display of the assignment start & end (preview) card.

I am not in favor of removing the preview, as the WYSIWYG editor is not that close to the final look.

2021-11-07 19:21 UTC, mjvkeulen commented on src/vue/src/components/entry/EntryFieldDisplay.vue
> -            }"
Yours? Someones elses? This hits like 5-6 components afaik

2021-11-07 21:47 UTC, Larspolo commented on src/vue/src/components/entry/EntryFieldDisplay.vue
> -            }"
My debugging yes

2021-11-07 22:49 UTC, Larspolo commented on src/vue/src/components/template/TemplateEdit.vue
> +                </template>
That is the goal though, so I made it even closer together by stripping away the cards:
![image](https://user-images.githubusercontent.com/11822478/140664722-963bf935-dc7b-41d5-b264-1a6ce671b006.png)

2021-11-07 22:50 UTC, Larspolo commented on src/vue/src/components/entry/EntryFieldDisplay.vue
> -            }"
Added it back

2021-11-08 08:22 UTC, mjvkeulen commented on src/vue/src/sass/partials/text.sass
> +    text-align: left
@Larspolo

2021-11-08 08:23 UTC, mjvkeulen commented on src/vue/src/components/template/TemplateEditFields.vue
> +
![image](https://user-images.githubusercontent.com/39912610/140707834-206c3d7e-f1ab-447f-8fd0-683d3e5d8af9.png)

- The title field has no placeholder when empty?
- I am unable to edit the description?

2021-11-08 08:26 UTC, mjvkeulen commented on src/vue/src/components/template/TemplateEditFields.vue
> +    .handle:hover .move-icon
I favor always showing the move and delete icons, a user won't be looking for these and moving their mouse to find them

2021-11-08 08:30 UTC, mjvkeulen commented on src/vue/src/components/template/TemplateEdit.vue
> +                </template>
Whilst closer, we are still too far away from removing the preview functionality. 

A big issue is spacing between fields, something that is currently achieved by adding new lines to descriptions (e.g. BKO centraal), you are no longer able to view what the end result would be.

2021-11-08 08:35 UTC, mjvkeulen commented on src/vue/src/components/template/TemplateEdit.vue
> +                </template>
> Tabs do now work nicely with buttons, would require more styling work than you might expect.

I propose:

- Move the settings and fields tabs inside the card. 
- Restore the preview and edit buttons

This is more preference I think, but I prefer the card wrappers to cleanly separate each field (as you had it in the previous review?). Especially to also separate the move/delete icons.

2021-11-08 09:00 UTC, Larspolo commented on src/vue/src/components/template/TemplateEditFields.vue
> +
>The title field has no placeholder when empty?

Added "title" as placeholder

>I am unable to edit the description?

On Firefox you could, I now fixed it for Chrome as well

2021-11-08 09:01 UTC, Larspolo commented on src/vue/src/components/template/TemplateEditFields.vue
> +    .handle:hover .move-icon
Sure, but I would also like to move to a view where no preview-mode is needed. If this wont get in the way, then I'll add them back in

2021-11-08 09:03 UTC, Larspolo commented on src/vue/src/sass/partials/text.sass
> +    text-align: left
Was wondering why I couldnt find any yet

2021-11-08 09:08 UTC, Larspolo commented on src/vue/src/components/template/TemplateEdit.vue
> +                </template>
> I prefer the card wrappers to cleanly separate each field 

I don't, the more it looks like the real thing, the better the teacher understands what they are doing. @engelhamer an opinion?

https://user-images.githubusercontent.com/11822478/140609903-2d714ccb-9e38-4124-9f72-840680fe1282.png

With borders for reference (dont look at the title field)

2021-11-20 10:38 UTC, mjvkeulen requested changes

2021-11-20 10:38 UTC, mjvkeulen commented on src/vue/src/components/template/TemplateEdit.vue
> -                </b-button>
Delete is missing

2021-11-20 10:38 UTC, mjvkeulen commented on src/vue/src/components/template/TemplateEditSettings.vue
> +                Max uses
I dislike how the text wraps

![image](https://user-images.githubusercontent.com/39912610/142722376-5c82e373-c448-430e-99db-e35fab36a87d.png)

2021-11-20 10:38 UTC, mjvkeulen commented on src/vue/src/components/assignment_editor/timeline_controlled/assignment/AssessmentModelEdit.vue
> -            class="mt-3"
I feel this is a visual downgrade.

![image](https://user-images.githubusercontent.com/39912610/142722411-11aa354d-eea2-4310-b953-e99d5d681f44.png)

![image](https://user-images.githubusercontent.com/39912610/142722428-7adc6994-0d85-44b7-8cf4-74d1f57a7c7c.png)

2021-11-20 10:38 UTC, mjvkeulen commented on src/vue/src/components/template/TemplateEdit.vue
> +                    v-if="showSettings"
Show settings now persists between switching templates. 

1. Create new template & display settings
2. Navigate to other template

Previously step 2 would go straight into "view" mode for that template (unless it had pending changes).
Now the settings are still expanded. This feels not as intuitive to me.

2021-11-20 10:38 UTC, mjvkeulen commented on src/vue/src/components/template/TemplateEditField.vue
> +                    class="move-icon"
No hover

2021-11-20 10:38 UTC, mjvkeulen commented on src/vue/src/components/template/TemplateEditFields.vue
> +            <template v-else-if="template.title_description">
Some margin issues:

Left hand side outline & on hover:
![Screenshot from 2021-11-20 10-47-30](https://user-images.githubusercontent.com/39912610/142722743-23c67a02-f9c2-4f38-be1b-a3bac80f25cd.png)
![Screenshot from 2021-11-20 10-39-52](https://user-images.githubusercontent.com/39912610/142722712-cb3d1557-c080-4858-bf12-2a24a3e3780d.png)
![Screenshot from 2021-11-20 10-46-02](https://user-images.githubusercontent.com/39912610/142722738-0db0df0c-b72b-4f81-95b6-e5303ea86b79.png)

2021-11-20 10:38 UTC, mjvkeulen commented on src/vue/src/components/template/TemplateEditFields.vue
>  <template>
No auto close on field blur? (title, description, RT default content, etc)

2021-11-20 10:38 UTC, mjvkeulen commented on src/vue/src/components/template/TemplateEditFields.vue
> +    </b-card-body>
Too much margin between end of last field in card body and start of footer?
![Screenshot from 2021-11-20 10-42-12](https://user-images.githubusercontent.com/39912610/142722874-e5f77887-3e96-46fe-8df1-65b75e7b02e2.png)

2021-11-20 10:38 UTC, mjvkeulen commented on src/vue/src/components/template/TemplateEditFields.vue
>  </template>
Similarly, too much margin between the last row of add field buttons and footer end?

![Screenshot from 2021-11-20 10-43-20](https://user-images.githubusercontent.com/39912610/142722902-8a203b3a-9ea3-4ff0-a963-2210df3e8cd0.png)

2021-11-20 10:38 UTC, mjvkeulen commented on src/vue/src/components/template/TemplateEdit.vue
> -                {{ (create) ? 'Preview' : 'Cancel' }}
Actual preview is missing.

For example, there is no way to see the actual display of consecutive fields. We always display `No Field` or no `No Description`. Despite the great improvement to the editing UX, this makes it hard to imagine what the final template will actually look like.

Take this example of a BKO template:

![image](https://user-images.githubusercontent.com/39912610/142723066-1be4f96c-7d40-40d6-9809-831c314118fb.png)

The 1 [a, b] structure is hard to imagine with all the No X stubs.

We can still add a `Student view` button with little effort. This would prevent the need for teachers to launch from Canvas and inspect everything as a student to see the actual final looks.

2021-11-20 10:38 UTC, mjvkeulen commented on src/vue/src/components/template/TemplateEdit.vue
> +                />
It took Joos a bit longer than I hoped to find this button (she initially gave up and only managed to add a category to a template from the respective category). 

Possibly stick with `Settings` [cog] as that might help?

2021-11-20 10:38 UTC, mjvkeulen commented on src/vue/src/components/template/TemplateEditField.vue
> +                v-else-if="field.type === 'v'"
The done button has too much spacing for the video field:

![image](https://user-images.githubusercontent.com/39912610/142723192-aa7b9150-80b7-43fc-9e05-f1374ca82aa0.png)

2021-11-20 10:38 UTC, mjvkeulen commented on src/vue/src/components/template/TemplateEditField.vue
> +                Done
Too little spacing in some scenario's:

![image](https://user-images.githubusercontent.com/39912610/142723219-a3ecd6d9-cf8f-4abf-871f-352f9a1217dd.png)

2021-11-22 12:50 UTC, Larspolo commented on src/vue/src/components/template/TemplateEdit.vue
> -                {{ (create) ? 'Preview' : 'Cancel' }}
![image](https://user-images.githubusercontent.com/11822478/142864640-787f9e26-fd56-49c2-a8e4-a33676230db6.png)
Is it really though? I think this is fine. You also clrealy see that it is required in this example, which maybe would actually be useful to add to the student view

2021-11-22 12:51 UTC, Larspolo commented on src/vue/src/components/template/TemplateEditFields.vue
>  </template>
Changed to mb-2
![image](https://user-images.githubusercontent.com/11822478/142864974-a1a2fe9a-10de-47db-9e3a-71cd764f0230.png)

2021-11-22 12:54 UTC, Larspolo commented on src/vue/src/components/template/TemplateEditField.vue
> +                    class="move-icon"
![image](https://user-images.githubusercontent.com/11822478/142865180-4c41a692-478d-470d-8ace-c0d51a200836.png)
Might this be your cursor not supporting the grab cursor?

2021-11-23 11:03 UTC, Larspolo commented on src/vue/src/components/template/TemplateEdit.vue
> -                </b-button>
![image](https://user-images.githubusercontent.com/11822478/143013119-ead8f7d6-f255-4d21-9310-98d66117e944.png)
Took Nina no looking around to delete the template

2021-11-23 11:16 UTC, Larspolo commented on src/vue/src/components/template/TemplateEditSettings.vue
> +                Max uses
Added a bar as well, imo its good enough now. Else @engelhamer may have something more to add

2021-11-23 11:16 UTC, Larspolo commented on src/vue/src/components/template/TemplateEditSettings.vue
> +                Max uses
![image](https://user-images.githubusercontent.com/11822478/143014854-866d88b3-dafc-49f4-a73b-caa5ad321122.png)

2021-11-23 11:16 UTC, Larspolo commented on src/vue/src/components/template/TemplateEditFields.vue
>  <template>
See DMs

2021-11-23 11:17 UTC, Larspolo commented on src/vue/src/components/template/TemplateEditFields.vue
> +    </b-card-body>
Fine by me, you may change it to what you prefer

2021-11-23 11:17 UTC, Larspolo commented on src/vue/src/components/template/TemplateEditField.vue
> +                Done
Think this should all be fixed now

2021-11-25 07:15 UTC, mjvkeulen commented on src/vue/src/components/template/TemplateEdit.vue
> -                </b-button>
Delete is still missing from the main view (all other components do have this)

2021-11-25 07:17 UTC, mjvkeulen commented on src/vue/src/components/template/TemplateEditField.vue
> +                    class="move-icon"
Not fixed for me sadl
![Peek 2021-11-25 08-16](https://user-images.githubusercontent.com/39912610/143396562-b7b76421-2593-422a-be6e-95355ee392c8.gif)
y?

2021-11-25 07:21 UTC, mjvkeulen commented on src/vue/src/components/template/TemplateEditFields.vue
> +    </b-card-body>
Margin between end of card and the last component is now fixed, but the final field margin issue is still there:

![image](https://user-images.githubusercontent.com/39912610/143396758-89371c51-bc59-4db3-a4b6-fd3a17f22e4b.png)

(Double margin between categories and last field)

2021-11-25 07:24 UTC, mjvkeulen commented on src/vue/src/components/template/TemplateEditField.vue
> +                Done
![Peek 2021-11-25 08-23](https://user-images.githubusercontent.com/39912610/143397473-3ddf53ce-4343-462c-9f47-c99ea37bcc6d.gif)

Margin between description and field differs based on field type

2021-11-25 07:28 UTC, mjvkeulen commented on src/vue/src/components/template/TemplateEditFields.vue
> +            <template v-else-if="template.title_description">
Save button is pushed too far down by the Update existing entries text 
![Peek 2021-11-25 08-27](https://user-images.githubusercontent.com/39912610/143397944-c5fad1c3-e211-4572-a43e-2979528ddc6f.gif)

Not sure if I should have posted it in this PR (figured it doesn't matter)

2021-11-25 07:31 UTC, mjvkeulen commented on src/vue/src/components/template/TemplateEdit.vue
>                  <icon name="save"/>
Save button is pushed too far down by the Update existing entries text 
![Peek 2021-11-25 08-27](https://user-images.githubusercontent.com/39912610/143397944-c5fad1c3-e211-4572-a43e-2979528ddc6f.gif)

Not sure if I should have posted it in this PR (figured it doesn't matter)

2021-11-25 07:43 UTC, mjvkeulen commented on src/vue/src/components/template/TemplateEditSettings.vue
> +                Max uses
![image](https://user-images.githubusercontent.com/39912610/143399882-2650f86b-2a57-4e0f-b59f-8aadbfe9a161.png)

vs old:

![image](https://user-images.githubusercontent.com/39912610/143399932-54af27a6-0d41-40ee-b059-ea35cda826f8.png)

2021-11-25 07:43 UTC, mjvkeulen commented on src/vue/src/components/assignment_editor/timeline_controlled/assignment/AssessmentModelEdit.vue
> -            class="mt-3"
Resolving to focus discussion in one thread

2021-11-25 07:47 UTC, mjvkeulen commented on src/vue/src/components/template/TemplateEditFields.vue
>  <template>
At least it's consistent now. 

However, simply not having any blur revert the input back to read mode is not the ideal UX. 

What was the primary issue? Before we did have some of these blurs working properly. 

Can't we rely on:

- Blur for the title?
- Blur for the description?

Which field(s) were giving us trouble?

2021-11-25 08:34 UTC, mjvkeulen commented on src/vue/src/components/template/TemplateEditFields.vue
> +    </b-card-body>
I fixed the margin issue and took the liberty of changing the "Allow custom categories" setting to something more inline with the WYSIWYG editor style.

![Peek 2021-11-25 09-32](https://user-images.githubusercontent.com/39912610/143406837-b14ef7ec-c901-4a42-8e0a-83d959c42f14.gif)

2021-11-25 08:39 UTC, mjvkeulen commented on src/vue/src/components/category/TemplateCategories.vue
> +        <icon
I took the liberty of changing the "Allow custom categories" setting to something more inline with the WYSIWYG editor style.

![Peek 2021-11-25 09-32](https://user-images.githubusercontent.com/39912610/143406837-b14ef7ec-c901-4a42-8e0a-83d959c42f14.gif)

2021-11-25 09:36 UTC, mjvkeulen commented on src/vue/src/components/template/TemplateEdit.vue
> -                {{ (create) ? 'Preview' : 'Cancel' }}
My ideal would be to provide a student view to the template editor.

This allows the teacher to try the different fields as a student, as well see the exact outcome of the template as a student would.

I made a start on this, but had to add quite a few flags to prevent file uploads and did not want to conflict with the outstanding entry/journal rewrite. 

Do we agree this would be of added value? And if so let's shift this to an issue?

2021-11-25 09:56 UTC, Larspolo commented on src/vue/src/components/template/TemplateEdit.vue
>                  <icon name="save"/>
Imo intended behaviour

2021-11-25 09:58 UTC, Larspolo commented on src/vue/src/components/template/TemplateEditFields.vue
>  <template>
Blur for description. Blur for title could be added though, but then it might seem inconsistent?

2021-11-25 10:13 UTC, Larspolo commented on src/vue/src/components/template/TemplateEdit.vue
> -                </b-button>
This is good enough for me though. You could add it if you want

2021-11-25 10:13 UTC, Larspolo commented on src/vue/src/components/template/TemplateEditSettings.vue
> +                Max uses
@engelhamer

2021-11-25 10:16 UTC, Larspolo commented on src/vue/src/components/template/TemplateEditField.vue
> +                    class="move-icon"
Also works on Chrome for me.  Might this be your cursor theme on Ubuntu not supporting the grab cursor? (note: this is not the pointer cursor)

2021-11-25 10:18 UTC, Larspolo commented on src/vue/src/components/template/TemplateEdit.vue
> -                {{ (create) ? 'Preview' : 'Cancel' }}
https://ejournal.atlassian.net/browse/EJ-1149
Definitly

2021-11-25 10:42 UTC, Larspolo commented on src/vue/src/components/template/TemplateEditField.vue
> +                Done
Think this was only between the title field and the others, this is also fixed now

2021-11-25 10:43 UTC, Larspolo commented on src/vue/src/components/template/TemplateEditFields.vue
> +            <template v-else-if="template.title_description">
Think this was discussed in voice

2021-11-25 14:45 UTC, mjvkeulen commented on src/vue/src/components/template/TemplateEdit.vue
> +                    Preview
Resolving to consolidate thread in one discussion

2021-11-25 14:46 UTC, mjvkeulen commented on src/vue/src/components/template/TemplateEditField.vue
> +                    class="move-icon"
You are right, doesn't work for me before either. Resolving

2021-11-25 14:47 UTC, mjvkeulen commented on src/vue/src/components/template/TemplateEditFields.vue
> +            <template v-else-if="template.title_description">
To me that was just the left hand side padding. Not the bottom spacing, which causes overlap and directly connects to other rows so to speak.

2021-11-25 14:48 UTC, mjvkeulen commented on src/vue/src/components/template/TemplateEditFields.vue
>  <template>
Ok, and what specifically was causing issues for the description blur? I could take a look at it

2021-11-25 15:33 UTC, Larspolo commented on src/vue/src/components/template/TemplateEditFields.vue
>  <template>
Blur is triggered on mouse_down event. While clicks are on mouse_up. When mouse_down happens on the RT fields, the content on the WYSIWYG editor changes, this may lead the mouse_up registering on the wrong element

2021-11-27 11:59 UTC, engelhamer commented on src/vue/src/components/template/TemplateEditFields.vue
> +    .handle:hover .move-icon
Leave the situation as-is? I like the hover.

2021-11-27 12:01 UTC, engelhamer commented on src/vue/src/components/template/TemplateEditSettings.vue
> +                Max uses
I do not want the border around the original setting: there is no reason to have it initially display any different than the other settings. If you really like it, we could add a border around the 'advanced' settings instead of just the line on the left.

2021-11-27 12:06 UTC, engelhamer commented on src/vue/src/components/template/TemplateEditFields.vue
> +            <template v-else-if="template.title_description">
The only overlap is an outline which is an accessibility settting. I would not like to add extra margins everywhere since that makes it larger and thus harder to read?

2021-11-27 12:07 UTC, engelhamer commented on src/vue/src/components/template/TemplateEditFields.vue
>  <template>
In my opinion not needed (not worth the time) to hack a custom solution.

2021-11-27 12:07 UTC, engelhamer commented on src/vue/src/components/template/TemplateEdit.vue
>                  <icon name="save"/>
yes

2021-11-27 12:09 UTC, engelhamer reviewed
The only thing I don't like is that changes can delete content now.

2021-11-27 15:31 UTC, Larspolo commented
> The only thing I don't like is that changes can delete content now.

Sounds like a new issue

2021-11-27 15:34 UTC, engelhamer commented
> > The only thing I don't like is that changes can delete content now.
> 
> Sounds like a new issue

What? This is introduced in this PR.

2021-11-28 10:29 UTC, mjvkeulen commented on src/vue/src/components/template/TemplateEditSettings.vue
> +                Max uses
That would work for me, no border until the settings group is unlocked

2021-11-28 10:30 UTC, mjvkeulen commented on src/vue/src/components/template/TemplateEditFields.vue
> +            <template v-else-if="template.title_description">
The background of the highlighted button also directly borders the next row without any spacing

2021-11-28 10:35 UTC, mjvkeulen commented on src/django/VLE/utils/template.py
> +    # TODO: only update entries is updating is asked for
Seems relevant

2021-11-28 13:00 UTC, Larspolo commented on src/django/VLE/utils/template.py
> +    # TODO: only update entries is updating is asked for
Done

2021-11-28 13:03 UTC, Larspolo commented on src/vue/src/components/template/TemplateEditSettings.vue
> +                Max uses
Im unsure what should be done. Would be nice if either of you fix this

2021-11-29 08:45 UTC, mjvkeulen commented on src/vue/src/components/template/TemplateEditField.vue
> +                Done
Seems not fixed?

![image](https://user-images.githubusercontent.com/39912610/143835578-ced7b910-326a-4fd2-b295-99a6d8d82a1a.png)

Done is hugging the next field

2021-11-29 09:01 UTC, mjvkeulen approved these changes

2021-11-29 12:32 UTC, Larspolo commented on src/vue/src/components/template/TemplateEditField.vue
> +                Done
Now it is, think I didnt push it or sth

2021-12-01 15:48 UTC, engelhamer approved these changes

2021-12-01 16:16 UTC, merged