Improved the template copy and import experience
eJourn-al/eJournal pull request #1258
Opened 2021-11-16 09:14 UTC by mjvkeulen

EJ-1161 #done

![template_copy](https://user-images.githubusercontent.com/39912610/141956503-e3bf100b-c281-4274-ab2e-d3a29f09da8d.gif)

![import_template](https://user-images.githubusercontent.com/39912610/141956516-5100959b-2980-4e62-8312-2c7086d21c87.gif)

2021-11-16 09:30 UTC, Larspolo requested changes

2021-11-16 09:30 UTC, Larspolo commented on src/vue/src/components/template/TemplateMenuItem.vue
> +            class="edit-icon ml-1 float-right"
[D] Not part of this PR, but edit icon blue / orange on hover? @engelhamer

2021-11-16 09:30 UTC, Larspolo commented on src/vue/src/components/template/TemplateMenuItem.vue
> +            copy.name = `Copy of ${copy.name}`
[NIT] Would prefer a `${copy.name} (x)` system to copy a single template twice. Now you get "Please provide a unique template name."

2021-11-16 09:30 UTC, Larspolo commented on src/vue/src/components/template/TemplateImport.vue
> +                newName = `Copy of ${newName}`
Great change!

Copy of ${name} may cause confusion, as it is not necessarily a copy. Would suggest having the default name as `${template.name} from ${template.assignment.name}` or `Imported ${template.name}`

2021-11-16 09:30 UTC, Larspolo commented on src/vue/src/components/template/TemplateMenuItem.vue
> +        />
![image](https://user-images.githubusercontent.com/11822478/141957807-19b64fa2-30eb-4609-b856-b20af1d1f2f7.png)
![image](https://user-images.githubusercontent.com/11822478/141957881-ff6b4e62-fab2-4c23-94f4-1c62c5fa528e.png)

When the right side is too long, it breaks to another row. Check these changes to see how to fix it:

https://github.com/eJourn-al/eJournal/pull/1219/files?w=1#diff-8299bbbde931bf818955d8e2173cfb7a9873c77aa0bc03b432b8785254983763L247
(styling in src/vue/src/views/AssignmentEditor.vue)

2021-11-16 09:32 UTC, Larspolo commented on src/django/VLE/models/template.py
> -            if not template_import:
[Q] How come this is changed and no tests are changed / added?

2021-11-16 10:26 UTC, mjvkeulen commented on src/django/VLE/models/template.py
> -            if not template_import:
Validation of whether the categories are part of the assignment already takes place (and is tested). 

This was just an arbitrary (imo) constraint

2021-11-16 10:26 UTC, mjvkeulen commented on src/vue/src/components/template/TemplateMenuItem.vue
> +            class="edit-icon ml-1 float-right"
Since it adds a template to assignment I would expect green if we want something particular

2021-11-16 11:21 UTC, Larspolo commented on src/vue/src/components/template/TemplateMenuItem.vue
> +            class="edit-icon ml-1 float-right"
This I would suggest making use of the `add-icon` class

2021-11-16 11:57 UTC, mjvkeulen commented on src/vue/src/components/template/TemplateMenuItem.vue
> +        />
For 993 width (lowest val still `md`)

![image](https://user-images.githubusercontent.com/39912610/141981074-faf34233-9a9d-43da-a499-99b5fdc7493f.png)

2021-11-17 09:20 UTC, mjvkeulen commented on src/vue/src/components/template/TemplateImport.vue
> +                newName = `Copy of ${newName}`
It's true that the import is not an exact copy, as the categories are not copied over. However, I am not fond of the proposed names.

I went with `Imported` as to me it's the best out of the options.

2021-11-17 09:59 UTC, Larspolo approved these changes

2021-11-25 21:11 UTC, engelhamer requested changes

2021-11-25 21:11 UTC, engelhamer commented on src/vue/src/components/template/TemplateMenuItem.vue
> +            class="edit-icon ml-1 float-right"
I think green indeed.

2021-11-25 21:11 UTC, engelhamer commented on src/vue/src/components/template/TemplateMenuItem.vue
> +        copyTemplate () {
I would like the copied template to be selected automatically. If someone copies a template from within the same assignment they are 100% sure going to do _something_ with it, else the original template would have sufficed.

2021-11-27 16:50 UTC, engelhamer approved these changes

2021-11-28 11:10 UTC, merged