Node structure rework
eJourn-al/eJournal pull request #1269
Opened 2021-11-25 19:39 UTC by Larspolo

![image](https://user-images.githubusercontent.com/11822478/143491493-396af962-21f4-4448-9459-3359bc59fb35.png)

https://app.diagrams.net/#G1OdsvNHczPM_u3RrxivONUoGg92x6HGEB

2021-11-27 15:13 UTC, engelhamer commented on src/django/VLE/models/journal_content/entry.py
>      def is_editable(self):
I think it would be nice if this also checks for editable by. That makes it easier to handle front-end too (i.e. does not require checks for _if_ the viewer is part of the journal to which the entry belongs. Furthermore this would make it so that the grade status (whether or not the entry is graded) is not leaked.

2021-11-27 15:13 UTC, engelhamer commented on src/django/VLE/models/template.py
> +    def creatable_by(cls, user: 'VLE.models.User', context: 'VLE.models.fAssignment', raise_exception: bool = False):
```suggestion
    def creatable_by(cls, user: 'VLE.models.User', context: 'VLE.models.Assignment', raise_exception: bool = False):
```

2021-11-27 15:13 UTC, engelhamer commented on src/django/VLE/timeline.py
> +        'type': 'add',
Maybe this is a good moment to not add this in the backend anymore?

2021-11-27 15:13 UTC, engelhamer commented on src/django/test/test_preset_node.py
> +            print(deadline_data)
Don't forget.

2021-11-28 13:32 UTC, Larspolo commented on src/django/VLE/models/journal_content/base.py
> +def convert_to_journal_entry_node():
Then I think its best to convert it to a `preset_group_node` -> not serialized for all the journals, only for the onces that have a connection to it

2021-11-28 13:33 UTC, Larspolo commented on src/django/VLE/models/journal_content/base.py
> +        on_delete=convert_to_journal_entry_node
The link to the preset_entry_node should be updated to the new node

2021-11-28 13:37 UTC, Larspolo commented on src/django/VLE/models/journal_content/base.py
> +    def journal(self) -> 'VLE.models.Journal':
Not just easier, indexing could be faster as well (removes a join in the query). Downside is that we then get duplicate data (e.g. having to update journal on both all journal content, and the node if it ever changes)

2021-11-28 13:38 UTC, engelhamer commented on src/django/VLE/models/journal_content/base.py
> +def convert_to_journal_entry_node():
But why convert at all?

2021-11-28 13:38 UTC, engelhamer commented on src/django/VLE/models/journal_content/base.py
> +def convert_to_journal_entry_node():
We can choose not to serialize if no entry exists too right?

2021-11-28 13:38 UTC, Larspolo commented on src/django/VLE/models/journal_content/base.py
> +            return context[1]
Journal context is either a journal, or a node and a journal

2021-11-28 13:39 UTC, engelhamer commented on src/django/VLE/models/journal_content/base.py
> +        on_delete=convert_to_journal_entry_node
Yes, but does the function trigger multiple times? You do not want to perform the node conversion multiple times obviously. How do we keep track of the mapping between the old node and the new one?

2021-11-28 13:40 UTC, engelhamer commented on src/django/VLE/models/journal_content/base.py
> +    def journal(self) -> 'VLE.models.Journal':
So then did the downside outweigh the benefit in your opinion? How do we decide on this?

2021-11-28 13:40 UTC, Larspolo commented on src/django/VLE/models/journal_content/base.py
> +    # QUESTION DB: what is a good name for this function?
When creating an entry, you do not have the object already to check if the user could see the entry if it were to be created (which is a requirement for creating it)

2021-11-28 13:40 UTC, Larspolo commented on src/django/VLE/models/journal_content/base.py
> +    # QUESTION DB: what is a good name for this function?
Then this function is run

2021-11-28 13:41 UTC, Larspolo commented on src/django/VLE/migrations/0104_auto_20211126_1140.py
> +            name='entry',
Didnt do any of the migrations yet

2021-11-28 13:41 UTC, engelhamer commented on src/django/VLE/models/journal_content/base.py
> +            return context[1]
Better

2021-11-28 13:43 UTC, Larspolo commented on src/django/VLE/models/nodes/group_nodes/__init__.py
> +class GroupNode(BaseModel, models.Model):
True, do you have a better name? It is for a single node that relates to only a subgroup of all the journals in the assignment

2021-11-28 13:43 UTC, Larspolo commented on src/django/VLE/models/nodes/group_nodes/teacher_entry_node.py
> +class TeacherEntryNode(Entry, EntryNode):
It should! `Entry` and `GroupNode`

2021-11-28 13:44 UTC, engelhamer commented on src/django/VLE/models/journal_content/base.py
> +    # QUESTION DB: what is a good name for this function?
But why is the can view check necessary in that case? Should we not just check if the user is a journal author?

2021-11-28 13:45 UTC, Larspolo commented on src/django/VLE/models/nodes/group_nodes/teacher_entry_node.py
> +    # QUESTION DB: why was this not included as well?
The TeacherEntryNode is not imported I hope? Only the entry of the student should be

2021-11-28 13:47 UTC, Larspolo commented on src/django/VLE/models/nodes/journal_nodes/base.py
> +    journal = models.ForeignKey(
Unfortuonatly we cannot. If both EntryNode and JournalNode inherit from BaseModel, and then JournalEntryNode inherits from EntryNode and JournalNode,  it will cause a duplicate attribute error (both having a creation date). So JournalEntryNode has to inherit from all three...

2021-11-28 13:47 UTC, Larspolo commented on src/django/VLE/models/nodes/journal_nodes/base.py
> +    journal = models.ForeignKey(
If you have a better solution for this problem, you can suggest it

2021-11-28 13:48 UTC, Larspolo commented on src/django/VLE/models/nodes/journal_nodes/base.py
> +class JournalNode(models.Model):
Just answered it in the comment thread above (Should this not have the creation date as well?)

2021-11-28 13:49 UTC, Larspolo commented on src/django/VLE/models/nodes/node_types/entry_node.py
> +        # Templates should not be deletable when they are in use
I agree, so then we can use  models.PROTECT to make sure of this on DB level

2021-11-28 13:52 UTC, Larspolo commented on src/django/VLE/models/nodes/preset_nodes/base.py
> +        # QUESTION DB: why was this only checked for PresetEntryNodes and not PresetProgressGoalNodes
Makes sense then. But I could see them useful as well. Targets only showing when the deadline of the previous target has passed. Or again with a "LATE" tag, but still reached before the lock date. Stuff like that. Not as useful as the EntryNode, but also not awful to include

2021-11-28 13:55 UTC, Larspolo commented on src/django/VLE/models/journal_content/entry.py
>      def is_editable(self):
Good addition to the permissions PR

2021-11-28 13:56 UTC, Larspolo commented on src/django/VLE/timeline.py
> +        'type': 'add',
Yes! Defenitly up for this. Think this whole file will dissapear

2021-11-28 13:58 UTC, Larspolo commented on src/django/VLE/models/journal_content/base.py
> +    # QUESTION DB: what is a good name for this function?
For EntryNodes: yes. For JournalContent in general: no. Comments should be postable by anyone that can view it

2021-11-28 15:34 UTC, Larspolo commented on src/django/VLE/models/journal_content/base.py
> +    def journal(self) -> 'VLE.models.Journal':
After a bit of reworking the existing codebase, I do see it being a lot easier if we simply always set the journal.
Example:
`Grade.objects.filter(entry__journal=x)`
Does not work in the current setup, becuase journal is not annotated, nor a property

@mjvkeulen if you are fine by this, then I will change it to always have `entry.journal`

2021-11-28 15:34 UTC, Larspolo commented on src/django/VLE/models/journal_content/base.py
> +            return context[1]
Always settings the journal, also fixes this "problem"

2021-11-28 19:05 UTC, engelhamer commented on src/django/VLE/models/journal_content/base.py
> +    # QUESTION DB: what is a good name for this function?
View the entry, that is. Checking whether whatever you're _going to_ create is 'going to be visible' sounds a bit weird.

Comment: `can_comment` and the `Node` should be visible
Entry: journal authos and the `Node` should be visible

2021-11-28 19:06 UTC, engelhamer commented on src/django/VLE/models/nodes/group_nodes/__init__.py
> +class GroupNode(BaseModel, models.Model):
`SharedNode`?

Also extendable to group activities in individual journals in the future 😉

2021-11-28 19:16 UTC, engelhamer commented on src/django/VLE/models/nodes/group_nodes/teacher_entry_node.py
> +    # QUESTION DB: why was this not included as well?
Then what is the question about? The jir down below right?

2021-11-28 19:17 UTC, engelhamer commented on src/django/VLE/models/nodes/group_nodes/teacher_entry_node.py
> +    # QUESTION DB: why was this not included as well?
If it is not included in the import then it should not be needed to have it>

2021-11-28 20:18 UTC, engelhamer commented on src/django/VLE/models/nodes/journal_nodes/base.py
> +    journal = models.ForeignKey(
Ok, but how does `JournalEntryNode` inherit `BaseNode` and `EntryNode` while `EntryNode` itself also inherits `BaseNode` then?

2021-11-28 20:21 UTC, engelhamer commented on src/django/VLE/models/nodes/preset_nodes/base.py
> +        # QUESTION DB: why was this only checked for PresetEntryNodes and not PresetProgressGoalNodes
Hm, but unlock does not mean it appears in the timeline at that moment. It means that you can submit it from that moment. Achieving a point goal does not work that way.

2021-11-28 20:22 UTC, engelhamer commented on src/django/VLE/models/journal_content/entry.py
>      def is_editable(self):
Will comment it there then.

2021-12-21 18:31 UTC, Larspolo commented on src/django/VLE/models/journal_content/base.py
> +def convert_to_journal_entry_node():
This is when an preset entry node is deleted where students have submitted entries. If we dont attach it to another node, it will be node-less -> entries wont be serialized anymore

2021-12-21 18:31 UTC, Larspolo commented on src/django/VLE/models/journal_content/base.py
> +        on_delete=convert_to_journal_entry_node
Good one, this would trigger creating multiple indeed

2021-12-21 18:46 UTC, Larspolo commented on src/django/VLE/models/nodes/journal_nodes/base.py
> +    journal = models.ForeignKey(
Moved everything inside BaseNode, should no longer be inconsisntent

2021-12-21 18:48 UTC, Larspolo commented on src/django/VLE/models/nodes/journal_nodes/base.py
> +    journal = models.ForeignKey(
Might be because it is direct inheritance in that case? Not sure, if you can improve it, be my guest:

```
VLE.JournalEntryNode.creation_date: (models.E006) The field 'creation_date' clashes with the field 'creation_date' from model 'VLE.journalentrynode'.
VLE.JournalEntryNode.update_date: (models.E006) The field 'update_date' clashes with the field 'update_date' from model 'VLE.journalentrynode'.
```

2021-12-21 18:49 UTC, Larspolo commented on src/django/VLE/models/nodes/preset_nodes/base.py
> +        # QUESTION DB: why was this only checked for PresetEntryNodes and not PresetProgressGoalNodes
Ah okay, is that something we might want to change? I see teachers only wanting users to see something after its unlocked, same is how assignment unlock date work

2021-12-21 18:50 UTC, Larspolo commented on src/django/VLE/timeline.py
> +        'type': 'add',
Was a bit more hassle than I would have liked, kept it in for now, but at least its now a serializer

2021-12-22 16:57 UTC, engelhamer commented on src/django/VLE/models/journal_content/base.py
> +def convert_to_journal_entry_node():
That is why I say: instead of deleting the preset, archive it (see first comment).

2021-12-22 17:00 UTC, engelhamer commented on src/django/VLE/models/nodes/journal_nodes/base.py
> +    journal = models.ForeignKey(
Then make it so that `EntryNode` does not inherit `BaseNode` either, right? Only `JournalEntryNode` should inherit it.

If a simultaneous inheritance is not possible, at least it would be good to have it consistent.

2021-12-22 17:01 UTC, engelhamer commented on src/django/VLE/models/nodes/preset_nodes/base.py
> +        # QUESTION DB: why was this only checked for PresetEntryNodes and not PresetProgressGoalNodes
Maybe make an issue for that. But this is not relevant or needed for the structural rework.

2021-12-22 17:10 UTC, engelhamer commented on src/django/VLE/timeline.py
> +        'type': 'add',
Add it to the issue about re-using assignment nodes

2021-12-23 20:58 UTC, Larspolo commented on src/django/VLE/models/journal_content/base.py
> +def convert_to_journal_entry_node():
https://github.com/eJourn-al/eJournal/pull/1269/commits/17e8018d447c6ab19ec06a723db4dae61887a017?w=1
https://github.com/eJourn-al/eJournal/pull/1269/commits/155aa2ebb1bb4974cdef838f18a3810bb1823ec3?w=1

Not sure if all cases are well covered though, but tried to look for problems and added some tests as well

2021-12-23 20:59 UTC, Larspolo commented on src/django/VLE/models/journal_content/base.py
> +    # QUESTION DB: what is a good name for this function?
changed to `check_context_viewable_by`, sounds better?

2021-12-23 20:59 UTC, Larspolo commented on src/django/VLE/models/nodes/preset_nodes/base.py
> +        # QUESTION DB: why was this only checked for PresetEntryNodes and not PresetProgressGoalNodes
I hid the (un)lock dates for now and made an issue for it to improve it in the future

2021-12-23 21:01 UTC, Larspolo commented on src/django/VLE/timeline.py
> +        'type': 'add',
https://ejournal.atlassian.net/browse/EJ-961

Its already its own issue

2021-12-23 21:06 UTC, Larspolo commented on src/django/VLE/models/nodes/journal_nodes/base.py
> +    journal = models.ForeignKey(
Changed the class to `AbstractBaseNodeType`, then we can use it for a base functionallity that is used for all nodetype's

2021-12-27 16:31 UTC, Larspolo reviewed
> *[Reviewable](https://reviewable.io/reviews/ejourn-al/ejournal/1269)* status: 0 of 175 files reviewed, 17 unresolved discussions (waiting on @engelhamer and @mjvkeulen)

___
*[src/django/test/test_preset_node.py, line 124 at r1](https://reviewable.io/reviews/ejourn-al/ejournal/1269#-MpR25fUcmFAh1EVdFxf-r1-124:-Mrwiejb7YyQL-Ajv0Vu:b-z0h2y6) ([raw file](https://github.com/ejourn-al/ejournal/blob/0507f8bacf229367c3c795fe2030476ed5ae5fb3/src/django/test/test_preset_node.py#L124)):*
<details><summary><i>Previously, engelhamer (Engel Hamer) wrote…</i></summary><blockquote>

Don't forget.
</blockquote></details>

Dont forget what? maybe outdated comment?
___
*[src/django/VLE/models/template.py, line 278 at r1](https://reviewable.io/reviews/ejourn-al/ejournal/1269#-MpR25fUcmFAh1EVdFxe-r1-278:-MrwiX-e96N8NmUkU8Hm:b-896fix) ([raw file](https://github.com/ejourn-al/ejournal/blob/0507f8bacf229367c3c795fe2030476ed5ae5fb3/src/django/VLE/models/template.py#L278)):*
<details><summary><i>Previously, engelhamer (Engel Hamer) wrote…</i></summary><blockquote>

```suggestion
    def creatable_by(cls, user: 'VLE.models.User', context: 'VLE.models.Assignment', raise_exception: bool = False):
```
</blockquote></details>

Done.
___
*[src/django/VLE/models/journal_content/base.py, line 28 at r1](https://reviewable.io/reviews/ejourn-al/ejournal/1269#-MpNb1TZW-PaRN0TwNlX-r1-28:-MrwimKn2LvhXu1vpO0M:bolt5y9) ([raw file](https://github.com/ejourn-al/ejournal/blob/0507f8bacf229367c3c795fe2030476ed5ae5fb3/src/django/VLE/models/journal_content/base.py#L28)):*
<details><summary><i>Previously, engelhamer (Engel Hamer) wrote…</i></summary><blockquote>

This is a bit of an unfortunate name, but I guess it is (should be) consistent with the rest of the db.
</blockquote></details>

So, good enough?
___
*[src/django/VLE/models/nodes/group_nodes/__init__.py, line 6 at r1](https://reviewable.io/reviews/ejourn-al/ejournal/1269#-MpNb1TZW-PaRN0TwNla-r1-6:-MrwiKZUApgz7a_Ms0GT:b-896fix) ([raw file](https://github.com/ejourn-al/ejournal/blob/0507f8bacf229367c3c795fe2030476ed5ae5fb3/src/django/VLE/models/nodes/group_nodes/__init__.py#L6)):*
<details><summary><i>Previously, engelhamer (Engel Hamer) wrote…</i></summary><blockquote>

`SharedNode`?

Also extendable to group activities in individual journals in the future 😉 
</blockquote></details>

Done.
___
*[src/django/VLE/models/nodes/group_nodes/teacher_entry_node.py, line 30 at r1](https://reviewable.io/reviews/ejourn-al/ejournal/1269#-MpNb1TZW-PaRN0TwNlc-r1-30:-MrwidW80oju9YyBD8l0:b-896fix) ([raw file](https://github.com/ejourn-al/ejournal/blob/0507f8bacf229367c3c795fe2030476ed5ae5fb3/src/django/VLE/models/nodes/group_nodes/teacher_entry_node.py#L30)):*
<details><summary><i>Previously, engelhamer (Engel Hamer) wrote…</i></summary><blockquote>

If it is not included in the import then it should not be needed to have that field.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-28 12:00 UTC, mjvkeulen requested changes
> Reviewed 7 of 40 files at r1, 142 of 168 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ejourn-al/ejournal/1269)* status: 149 of 175 files reviewed, 51 unresolved discussions (waiting on @engelhamer, @Larspolo, and @mjvkeulen)

___
*[src/django/VLE/serializers.py, line 574 at r2](https://reviewable.io/reviews/ejourn-al/ejournal/1269#-Ms-563F9HzxG_tQRrPo:-Ms-563F9HzxG_tQRrPp:bq20nbf) ([raw file](https://github.com/ejourn-al/ejournal/blob/c1be347ad500ebb0707a47d6297dedf95122830e/src/django/VLE/serializers.py#L574)):*
> ```Python
>         'last_submitted_by',
>         'grade',
>         'journal',  # used in permission check can grade and locked check
> ```

Afaik `journal__assignment__assessment_model` fetches all nested relations as well (so both `journal`, `assignment`, and `assessment_model`).



_Code quote:_
```Python
journal__assignment__assessment_model
```
___
*[src/django/VLE/migrations/0038_file_rework.py, line 20 at r2](https://reviewable.io/reviews/ejourn-al/ejournal/1269#-Ms-83Kg8RoDVAmCB1NI:-Ms-83Kg8RoDVAmCB1NJ:b-5wnr0e) ([raw file](https://github.com/ejourn-al/ejournal/blob/c1be347ad500ebb0707a47d6297dedf95122830e/src/django/VLE/migrations/0038_file_rework.py#L20)):*
> ```Python
> 
> 
> class Node(models.Model):
> ```

Was there a reason why Node is defined specifically in this migration?
___
*[src/django/VLE/migrations/0106_node_structure_rework.py, line 30 at r2](https://reviewable.io/reviews/ejourn-al/ejournal/1269#-Ms-8oic68vbsZSwlrd_:-Ms-8oic68vbsZSwlrda:b-mn0l5s) ([raw file](https://github.com/ejourn-al/ejournal/blob/c1be347ad500ebb0707a47d6297dedf95122830e/src/django/VLE/migrations/0106_node_structure_rework.py#L30)):*
> ```Python
>         template.assignment = template.format.assignment
>         template.save()
>     for template in TemplateChain.objects.filter(format__assignment__isnull=False):
> ```

for chain in
___
*[src/django/VLE/migrations/0106_node_structure_rework.py, line 38 at r2](https://reviewable.io/reviews/ejourn-al/ejournal/1269#-Ms-9nsc27FS-eNioYQC:-Ms-9nsc27FS-eNioYQD:bd8f2f6) ([raw file](https://github.com/ejourn-al/ejournal/blob/c1be347ad500ebb0707a47d6297dedf95122830e/src/django/VLE/migrations/0106_node_structure_rework.py#L38)):*
> ```Python
> 
>     for teacher_entry in TeacherEntry.objects.all():
>         new_teacher_entry_node = TeacherEntryNode.objects.create(
> ```

When creating new objects, should we restore the old creation/update dates?
___
*[src/django/VLE/migrations/0106_node_structure_rework.py, line 63 at r2](https://reviewable.io/reviews/ejourn-al/ejournal/1269#-Ms-Agrx4B7d4x5TX7uS:-Ms-Agrx4B7d4x5TX7uT:b8gbkmr) ([raw file](https://github.com/ejourn-al/ejournal/blob/c1be347ad500ebb0707a47d6297dedf95122830e/src/django/VLE/migrations/0106_node_structure_rework.py#L63)):*
> ```Python
>                 fc.save()
> 
>     for preset_node in PresetNode.objects.filter(type='p', format__assignment__isnull=False):
> ```

We can omit this filter `format__assignment__isnull=False` since we deleted all these earlier?



_Code quote:_
```Python
format__assignment__isnull=False
```
___
*[src/django/VLE/migrations/0106_node_structure_rework.py, line 65 at r2](https://reviewable.io/reviews/ejourn-al/ejournal/1269#-Ms-B4PF4BRHMS8zcWm0:-Ms-B4PF4BRHMS8zcWm1:bwighw3) ([raw file](https://github.com/ejourn-al/ejournal/blob/c1be347ad500ebb0707a47d6297dedf95122830e/src/django/VLE/migrations/0106_node_structure_rework.py#L65)):*
> ```Python
>     for preset_node in PresetNode.objects.filter(type='p', format__assignment__isnull=False):
>         new_preset_node = PresetProgressGoalNode.objects.create(
>             assignment=Assignment.objects.get(format_id=preset_node.format.pk),
> ```

[Q] So is preset_node.format.assignment not available here?
___
*[src/django/VLE/migrations/0106_node_structure_rework.py, line 74 at r2](https://reviewable.io/reviews/ejourn-al/ejournal/1269#-Ms-BnzWBDVGPJ94VsTg:-Ms-BnzWBDVGPJ94VsTh:b39byhz) ([raw file](https://github.com/ejourn-al/ejournal/blob/c1be347ad500ebb0707a47d6297dedf95122830e/src/django/VLE/migrations/0106_node_structure_rework.py#L74)):*
> ```Python
>         )
>         new_preset_node.attached_files.set(preset_node.attached_files.all())
>         new_preset_node.save()
> ```

[NIT] Doesn't .set() do the bulk update right away?
___
*[src/django/VLE/migrations/0106_node_structure_rework.py, line 76 at r2](https://reviewable.io/reviews/ejourn-al/ejournal/1269#-Ms-Cm6MAy3Q2gVAbQNq:-Ms-Cm6MAy3Q2gVAbQNr:b4ilk58) ([raw file](https://github.com/ejourn-al/ejournal/blob/c1be347ad500ebb0707a47d6297dedf95122830e/src/django/VLE/migrations/0106_node_structure_rework.py#L76)):*
> ```Python
>         new_preset_node.save()
>         preset_node_mapping[preset_node.pk] = new_preset_node
>         for fc in FileContext.objects.filter(presetnode=preset_node):
> ```

Is the block here not accomplished by .set() operation and the removal of the old `PresetNode` table?
___
*[src/django/VLE/migrations/0106_node_structure_rework.py, line 128 at r2](https://reviewable.io/reviews/ejourn-al/ejournal/1269#-Ms-DmRrDr0DxId4Nwh-:-Ms-DmRrDr0DxId4Nwh0:b-ur53u8) ([raw file](https://github.com/ejourn-al/ejournal/blob/c1be347ad500ebb0707a47d6297dedf95122830e/src/django/VLE/migrations/0106_node_structure_rework.py#L128)):*
> ```Python
>         teacher_entry_node_id__isnull=True,
>     )
>     print('Missing node:')
> ```

Do we want to remove these prints before we merge?
___
*[src/django/VLE/models/category.py, line 165 at r2](https://reviewable.io/reviews/ejourn-al/ejournal/1269#-Ms-FiO43PrnCstKleTh:-Ms-FiO63ta53-HZ4vkm:b-oc0ukh) ([raw file](https://github.com/ejourn-al/ejournal/blob/c1be347ad500ebb0707a47d6297dedf95122830e/src/django/VLE/models/category.py#L165)):*
> ```Python
> 
> class TeacherEntryCategoryLink(AbstractBaseModel):
>     """Explicit M2M table, linking Entries to Categories."""
> ```

Not Entries but
___
*[src/django/VLE/models/journal.py, line 501 at r2](https://reviewable.io/reviews/ejourn-al/ejournal/1269#-Ms-HeG3-PV12DBYjQOh:-Ms-HeG52W9ukAD3aoKq:b-8bpyib) ([raw file](https://github.com/ejourn-al/ejournal/blob/c1be347ad500ebb0707a47d6297dedf95122830e/src/django/VLE/models/journal.py#L501)):*
> ```Python
>         ).values_list('user__full_name', flat=True).distinct('user__full_name')
> 
>     @ property
> ```

`@ propery`?
___
*[src/django/VLE/models/journal.py, line 502 at r2](https://reviewable.io/reviews/ejourn-al/ejournal/1269#-Ms-HyWe8Cvjd8xHQcBs:-Ms-HyWhDmRRakeZ4SVn:bsicond) ([raw file](https://github.com/ejourn-al/ejournal/blob/c1be347ad500ebb0707a47d6297dedf95122830e/src/django/VLE/models/journal.py#L502)):*
> ```Python
> 
>     @ property
>     def require_teacher_action_entries(self) -> 'VLE.models.EntryQuerySet':
> ```

Do you remember why this is a property instead of an Entry queryset func?
___
*[src/django/VLE/models/notification.py, line 194 at r2](https://reviewable.io/reviews/ejourn-al/ejournal/1269#-Ms-IPX932cK08TC0Vix:-Ms-IPX932cK08TC0Viy:bhdwwq5) ([raw file](https://github.com/ejourn-al/ejournal/blob/c1be347ad500ebb0707a47d6297dedf95122830e/src/django/VLE/models/notification.py#L194)):*
> ```Python
>         attribute_name = VLE.models.Notification.BATCHED_TYPES[self.type]
> 
>         if attribute_name == 'node' and self.node:
> ```

attribute_name == VLE.models.Notification.BATCHED_TYPES['comment'] or is this not the relation you intend to convey?
___
*[src/django/VLE/models/notification.py, line 221 at r2](https://reviewable.io/reviews/ejourn-al/ejournal/1269#-Ms-IjxwCtGXpyyyaJwZ:-Ms-IjxwCtGXpyyyaJw_:bgyzui8) ([raw file](https://github.com/ejourn-al/ejournal/blob/c1be347ad500ebb0707a47d6297dedf95122830e/src/django/VLE/models/notification.py#L221)):*
> ```Python
>         node_deadline = None
>         if isinstance(self.node, VLE.models.AbstractPresetNode) and journal:
>             # QUESTION DB: this leaks (and leaked) the journal grade to the email, do we want that?
> ```

Did we settle on a setting for this? (TODO -> i [...]

2021-12-28 12:10 UTC, Larspolo commented on src/django/VLE/models/journal_content/base.py
> +        # We currently do not have journal progress goals, so this can simply be deleted
Was outdated, we now actually support archived preset nodes, so I set it to PROTECT.
1. teacher created progress goal
2. student posts comment under progress goal
3. teacher deleted goal
4. progress goal still available in the specific journal where the comment is posted, others it wont show

2021-12-28 12:54 UTC, Larspolo reviewed
> Reviewed 7 of 40 files at r1, 168 of 168 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ejourn-al/ejournal/1269)* status: all files reviewed, 51 unresolved discussions (waiting on @engelhamer, @Larspolo, and @mjvkeulen)

___
*[src/django/VLE/serializers.py, line 574 at r2](https://reviewable.io/reviews/ejourn-al/ejournal/1269#-Ms-563F9HzxG_tQRrPo:-Ms-xECjAzzXjRx_mOW0:brm2rdf) ([raw file](https://github.com/ejourn-al/ejournal/blob/c1be347ad500ebb0707a47d6297dedf95122830e/src/django/VLE/serializers.py#L574)):*
<details><summary><i>Previously, mjvkeulen (Maarten van Keulen) wrote…</i></summary><blockquote>

Afaik `journal__assignment__assessment_model` fetches all nested relations as well (so both `journal`, `assignment`, and `assessment_model`).
</blockquote></details>

This already existed previously



_Code quote:_
```Python
        'journal',  # used in permission check can grade and locked check
```
___
*[src/django/VLE/migrations/0038_file_rework.py, line 20 at r2](https://reviewable.io/reviews/ejourn-al/ejournal/1269#-Ms-83Kg8RoDVAmCB1NI:-Ms-xP8U-sX1B_BZY0zm:b-c67t4h) ([raw file](https://github.com/ejourn-al/ejournal/blob/c1be347ad500ebb0707a47d6297dedf95122830e/src/django/VLE/migrations/0038_file_rework.py#L20)):*
<details><summary><i>Previously, mjvkeulen (Maarten van Keulen) wrote…</i></summary><blockquote>

Was there a reason why Node is defined specifically in this migration?
</blockquote></details>

We dont have a Node model anymore, but the migration still requires a node model
___
*[src/django/VLE/migrations/0106_node_structure_rework.py, line 30 at r2](https://reviewable.io/reviews/ejourn-al/ejournal/1269#-Ms-8oic68vbsZSwlrd_:-Ms-xe5mE1zfQrjdq4Nu:b-896fix) ([raw file](https://github.com/ejourn-al/ejournal/blob/c1be347ad500ebb0707a47d6297dedf95122830e/src/django/VLE/migrations/0106_node_structure_rework.py#L30)):*
<details><summary><i>Previously, mjvkeulen (Maarten van Keulen) wrote…</i></summary><blockquote>

for chain in
</blockquote></details>

Done.
___
*[src/django/VLE/migrations/0106_node_structure_rework.py, line 63 at r2](https://reviewable.io/reviews/ejourn-al/ejournal/1269#-Ms-Agrx4B7d4x5TX7uS:-Ms-y4LeCwMQrpfOLPGx:b-896fix) ([raw file](https://github.com/ejourn-al/ejournal/blob/c1be347ad500ebb0707a47d6297dedf95122830e/src/django/VLE/migrations/0106_node_structure_rework.py#L63)):*
<details><summary><i>Previously, mjvkeulen (Maarten van Keulen) wrote…</i></summary><blockquote>

We can omit this filter `format__assignment__isnull=False` since we deleted all these earlier?
</blockquote></details>

Done.



_Code quote:_
```Python
PresetNode.objects.filter(type='p', format__assignment__isnull=False):
```
___
*[src/django/VLE/migrations/0106_node_structure_rework.py, line 65 at r2](https://reviewable.io/reviews/ejourn-al/ejournal/1269#-Ms-B4PF4BRHMS8zcWm0:-Ms-y7K160KfMZ3SDQsy:b-ncy0tq) ([raw file](https://github.com/ejourn-al/ejournal/blob/c1be347ad500ebb0707a47d6297dedf95122830e/src/django/VLE/migrations/0106_node_structure_rework.py#L65)):*
<details><summary><i>Previously, mjvkeulen (Maarten van Keulen) wrote…</i></summary><blockquote>

[Q] So is preset_node.format.assignment not available here?
</blockquote></details>

Some formats do not have an assignment (idk how), but all assignments have a format
___
*[src/django/VLE/migrations/0106_node_structure_rework.py, line 74 at r2](https://reviewable.io/reviews/ejourn-al/ejournal/1269#-Ms-BnzWBDVGPJ94VsTg:-Ms-yJWn6NQZHEjf-hdL:bmljajq) ([raw file](https://github.com/ejourn-al/ejournal/blob/c1be347ad500ebb0707a47d6297dedf95122830e/src/django/VLE/migrations/0106_node_structure_rework.py#L74)):*
<details><summary><i>Previously, mjvkeulen (Maarten van Keulen) wrote…</i></summary><blockquote>

[NIT] Doesn't .set() do the bulk update right away?
</blockquote></details>

Dont know actually
___
*[src/django/VLE/migrations/0106_node_structure_rework.py, line 128 at r2](https://reviewable.io/reviews/ejourn-al/ejournal/1269#-Ms-DmRrDr0DxId4Nwh-:-Ms-yZHg1ahOWxW8QaY_:b-dimqvl) ([raw file](https://github.com/ejourn-al/ejournal/blob/c1be347ad500ebb0707a47d6297dedf95122830e/src/django/VLE/migrations/0106_node_structure_rework.py#L128)):*
<details><summary><i>Previously, mjvkeulen (Maarten van Keulen) wrote…</i></summary><blockquote>

Do we want to remove these prints before we merge?
</blockquote></details>

Think so
___
*[src/django/VLE/models/category.py, line 165 at r2](https://reviewable.io/reviews/ejourn-al/ejournal/1269#-Ms-FiO43PrnCstKleTh:-Ms-yeDuD3_zgDB-mV22:b-896fix) ([raw file](https://github.com/ejourn-al/ejournal/blob/c1be347ad500ebb0707a47d6297dedf95122830e/src/django/VLE/models/category.py#L165)):*
<details><summary><i>Previously, mjvkeulen (Maarten van Keulen) wrote…</i></summary><blockquote>

Not Entries but
</blockquote></details>

Done.



_Code quote:_
```Python
xplicit M2M table, linking Entries to Categories."
```
___
*[src/django/VLE/models/journal.py, line 501 at r2](https://reviewable.io/reviews/ejourn-al/ejournal/1269#-Ms-HeG3-PV12DBYjQOh:-Ms-yhsN1aHhkgOSgiYd:b-896fix) ([raw file](https://github.com/ejourn-al/ejournal/blob/c1be347ad500ebb0707a47d6297dedf95122830e/src/django/VLE/models/journal.py#L501)):*
<details><summary><i>Previously, mjvkeulen (Maarten van Keulen) wrote…</i></summary><blockquote>

`@ propery`?
</blockquote></details>

Done.



_Code quote:_
```Python
@ property
```
___
*[src/django/VLE/models/journal.py, line 502 at r2](https://reviewable.io/reviews/ejourn-al/ejournal/1269#-Ms-HyWe8Cvjd8xHQcBs:-Ms-ymZyB5MOWtAqI0vq:b-wor9ot) ([raw file](https://github.com/ejourn-al/ejournal/blob/c1be347ad500ebb0707a47d6297dedf95122830e/src/django/VLE/models/journal.py#L502)):*
<details><summary><i>Previously, mjvkeulen (Maarten van Keulen) wrote…</i></summary><blockquote>

Do you remember why this is a property instead of an Entry queryset func?
</blockquote></details>

No, but before it also was like this, just for nodes iso entries
___
*[src/django/VLE/models/notification.py, line 194 at r2](https://reviewable.io/reviews/ejourn-al/ejournal/1269#-Ms-IPX932cK08TC0Vix:-Ms-z5WECwbpb8kevMDU:b45tkfy) ([raw file](https://github.com/ejourn-al/ejournal/blob/c1be347ad500ebb0707a47d6297dedf95122830e/src/django/VLE/models/notification.py#L194)):*
<details><summary><i>Previously, mjvkeulen (Maarten van Keulen) wrote…</i></summary><blockquote>

attribute_name == VLE.models.Notification.BATCHED_TYPES['comment'] or is this not the relation you intend to convey?
</blockquote></details>

It is ment for all batch types that are batched by node
___
*[src/django/VLE/models/notification.py, line 221 at r2](https://reviewable.io/reviews/ejourn-al/ejournal/1269#-Ms-IjxwCtGXpyyyaJwZ:-Ms0-34A-qFoHbAxmYWQ:b-ml3ruv) ([raw file](https://github.com/ejourn-al/ejournal/blob/c1be347ad500ebb0707a47d6297dedf95122830e/src/django/VLE/models/notification.py#L221)):*
<details><summary><i>Previously, mjvkeulen (Maarten van Keulen) wrote…</i></summary><blockquote>

Did we settle on a setting for this? (TODO -> issue) 
</blockquote></details>

https://ejournal.atlassian.net/browse/EJ-1235

Disabled the grade & created issue with low prio
___
*[src/django/VLE/models/notification.py, line 223 at r2](https://reviewable.io/reviews/ejourn-al/ejournal/1269#-Ms-IvpFDddDtQbDfqAU:-Ms-zK67C9golzw9z4YO:bfmhj9p) ([raw file](https://github.com/ejourn-al/ejournal/blob/c1be347ad500ebb0707a47d6297dedf95122830e/src/django/VLE/models/notification.py#L223)):*
<details><summary><i>Previously, mjvkeulen (Maarten van Keulen) wrote…</i></summary><blockquote>

Is this our `email` time format or smth? Should we extract this?
</blockquote></details>

You may, but its not introduced in this PR



_Code quote:_
```Python
this leaks (and leaked) the journal grade to the email,
```
___
*[src/django/VLE/models/journal_content/base.py, line 33 at r2](https://reviewable.io/reviews/ejourn-al/ejournal/1269#-Ms-L6bHCJwMBow5TK3Z:-Ms0-LqS66M5-4fyfNMm:b-896fix) ([raw file](https://github.com/ejourn-al/ejournal/blo [...]

2021-12-28 13:35 UTC, Larspolo reviewed
> Reviewed 20 of 20 files at r3.
> *[Reviewable](https://reviewable.io/reviews/ejourn-al/ejournal/1269)* status: 170 of 176 files reviewed, 51 unresolved discussions (waiting on @engelhamer, @Larspolo, and @mjvkeulen)

___
*[src/django/VLE/migrations/0106_node_structure_rework.py, line 38 at r2](https://reviewable.io/reviews/ejourn-al/ejournal/1269#-Ms-9nsc27FS-eNioYQC:-Ms0ExIx51LB7LZ4ZK6h:b-896fix) ([raw file](https://github.com/ejourn-al/ejournal/blob/c1be347ad500ebb0707a47d6297dedf95122830e/src/django/VLE/migrations/0106_node_structure_rework.py#L38)):*
<details><summary><i>Previously, mjvkeulen (Maarten van Keulen) wrote…</i></summary><blockquote>

When creating new objects, should we restore the old creation/update dates?
</blockquote></details>

Done.
___
*[src/django/VLE/migrations/0106_node_structure_rework.py, line 76 at r2](https://reviewable.io/reviews/ejourn-al/ejournal/1269#-Ms-Cm6MAy3Q2gVAbQNq:-Ms0FEMu6IGPLTrDFl-D:b-896fix) ([raw file](https://github.com/ejourn-al/ejournal/blob/c1be347ad500ebb0707a47d6297dedf95122830e/src/django/VLE/migrations/0106_node_structure_rework.py#L76)):*
<details><summary><i>Previously, mjvkeulen (Maarten van Keulen) wrote…</i></summary><blockquote>

Is the block here not accomplished by .set() operation and the removal of the old `PresetNode` table?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-28 13:36 UTC, Larspolo reviewed
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ejourn-al/ejournal/1269)* status: all files reviewed, 51 unresolved discussions (waiting on @engelhamer and @mjvkeulen)



<!-- Sent from Reviewable.io -->

2021-12-29 09:54 UTC, mjvkeulen reviewed
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ejourn-al/ejournal/1269)* status: all files reviewed, 29 unresolved discussions (waiting on @engelhamer and @Larspolo)

___
*[src/django/VLE/serializers.py, line 574 at r2](https://reviewable.io/reviews/ejourn-al/ejournal/1269#-Ms-563F9HzxG_tQRrPo:-Ms4ZCvF7AJHJUdtOllH:bs9j5bs) ([raw file](https://github.com/ejourn-al/ejournal/blob/c1be347ad500ebb0707a47d6297dedf95122830e/src/django/VLE/serializers.py#L574)):*
<details><summary><i>Previously, Larspolo (Lars) wrote…</i></summary><blockquote>

This already existed previously
</blockquote></details>

Yes loads of this exist already, just an FYI as some parts you did also introduce this.
___
*[src/django/VLE/migrations/0038_file_rework.py, line 20 at r2](https://reviewable.io/reviews/ejourn-al/ejournal/1269#-Ms-83Kg8RoDVAmCB1NI:-Ms4ZNFXEtvN65qtbwgG:bj601k2) ([raw file](https://github.com/ejourn-al/ejournal/blob/c1be347ad500ebb0707a47d6297dedf95122830e/src/django/VLE/migrations/0038_file_rework.py#L20)):*
<details><summary><i>Previously, Larspolo (Lars) wrote…</i></summary><blockquote>

We dont have a Node model anymore, but the migration still requires a node model
</blockquote></details>

So we define Node at the first occurrence in code (not model definition?)
___
*[src/django/VLE/migrations/0106_node_structure_rework.py, line 37 at r5](https://reviewable.io/reviews/ejourn-al/ejournal/1269#-Ms4SiTG4Nj4mtIlOdmq:-Ms4SiTG4Nj4mtIlOdmr:b-xkkob4) ([raw file](https://github.com/ejourn-al/ejournal/blob/10695b40c5c20edc3cc0c6f1d73ff91313eb6dc4/src/django/VLE/migrations/0106_node_structure_rework.py#L37)):*
> ```Python
>     TemplateChain.objects.filter(format__assignment__isnull=True).delete()
> 
>     # TODO NSR: keep old creation / update dates
> ```

Tagging
___
*[src/django/VLE/migrations/0106_node_structure_rework.py, line 48 at r5](https://reviewable.io/reviews/ejourn-al/ejournal/1269#-Ms4SP5--_FERqMvfZmU:-Ms4SP5--_FERqMvfZmV:bib7rkx) ([raw file](https://github.com/ejourn-al/ejournal/blob/10695b40c5c20edc3cc0c6f1d73ff91313eb6dc4/src/django/VLE/migrations/0106_node_structure_rework.py#L48)):*
> ```Python
>         new_teacher_entry_node.creation_date = teacher_entry.creation_date
>         new_teacher_entry_node.update_date = teacher_entry.update_date
>         new_teacher_entry_node.save(update_fields=['creation_date', 'update_date'])
> ```

Just tagging to check if a test is present. I remember the auto add fields ignored some .save operations (they still follow direct sql instructions of course)
___
*[src/django/VLE/models/journal_content/base.py, line 137 at r1](https://reviewable.io/reviews/ejourn-al/ejournal/1269#-MpNb1TZW-PaRN0TwNlX-r1-137:-Ms4Zfe80r5rq2_1Gc62:b32wtd) ([raw file](https://github.com/ejourn-al/ejournal/blob/0507f8bacf229367c3c795fe2030476ed5ae5fb3/src/django/VLE/models/journal_content/base.py#L137)):*
<details><summary><i>Previously, Larspolo (Lars) wrote…</i></summary><blockquote>

After a bit of reworking the existing codebase, I do see it being a lot easier if we simply always set the journal.
Example:
`Grade.objects.filter(entry__journal=x)`
Does not work in the current setup, becuase journal is not annotated, nor a property

@mjvkeulen if you are fine by this, then I will change it to always have `entry.journal`
</blockquote></details>

ok
___
*[src/django/VLE/models/nodes/journal_nodes/base.py, line 7 at r2](https://reviewable.io/reviews/ejourn-al/ejournal/1269#-Ms-STgNEWCh25vq2WRG:-Ms4Ypek-gVtTIInr97t:bw5ucsn) ([raw file](https://github.com/ejourn-al/ejournal/blob/c1be347ad500ebb0707a47d6297dedf95122830e/src/django/VLE/models/nodes/journal_nodes/base.py#L7)):*
<details><summary><i>Previously, Larspolo (Lars) wrote…</i></summary><blockquote>

Its not abstract though. This will be used if its not overwritten
</blockquote></details>

`JournalNode` does not exist tho right?
___
*[src/django/VLE/models/nodes/preset_nodes/preset_progress_goal_node.py, line 48 at r2](https://reviewable.io/reviews/ejourn-al/ejournal/1269#-Ms4_bvEEbaGVBpy2aXC:-Ms4_bvEEbaGVBpy2aXD:baokyeo) ([raw file](https://github.com/ejourn-al/ejournal/blob/c1be347ad500ebb0707a47d6297dedf95122830e/src/django/VLE/models/nodes/preset_nodes/preset_progress_goal_node.py#L48)):*
> ```Python
>         target, due_date = generic_utils.required_typed_params(new_data, (int, 'target'), (datetime, 'due_date'))
> 
>         if target < 0:
> ```

Should we also add this check as a CheckConstraint to the table (`AbstractProgressGoalNode`)?
___
*[src/django/VLE/views/preset_node.py, line 34 at r2](https://reviewable.io/reviews/ejourn-al/ejournal/1269#-Ms-mO47CZet68ff_IEK:-Ms4aICP5g2m1V2FlEFX:bfk5qkl) ([raw file](https://github.com/ejourn-al/ejournal/blob/c1be347ad500ebb0707a47d6297dedf95122830e/src/django/VLE/views/preset_node.py#L34)):*
<details><summary><i>Previously, Larspolo (Lars) wrote…</i></summary><blockquote>

No clue what the difference is. I rewrote the whole file
</blockquote></details>

`viewsets.ViewSet` -> `viewsets.ModelViewSet`
___
*[src/vue/src/api/journal.js, line 62 at r2](https://reviewable.io/reviews/ejourn-al/ejournal/1269#-Ms-p_5HCGtp2Jd90g0F:-Ms4ajBb58duS9szHbgE:bmjikwz) ([raw file](https://github.com/ejourn-al/ejournal/blob/c1be347ad500ebb0707a47d6297dedf95122830e/src/vue/src/api/journal.js#L62)):*
<details><summary><i>Previously, Larspolo (Lars) wrote…</i></summary><blockquote>

AFAIK we dont have a standard on asynch function names
</blockquote></details>

https://ejournal.atlassian.net/browse/EJ-1238
___
*[src/vue/src/components/assignment/ManageTeacherEntriesModal.vue, line 298 at r2](https://reviewable.io/reviews/ejourn-al/ejournal/1269#-Ms-qGDP8WQRTbuZBueU:-Ms4anl38iJiov4ZlUT-:b-uf1wgb) ([raw file](https://github.com/ejourn-al/ejournal/blob/c1be347ad500ebb0707a47d6297dedf95122830e/src/vue/src/components/assignment/ManageTeacherEntriesModal.vue#L298)):*
<details><summary><i>Previously, Larspolo (Lars) wrote…</i></summary><blockquote>

Not really
</blockquote></details>

Should we then stick to title in user facing communcation since it is more clear?
___
*[src/vue/src/components/entry/Comments.vue, line 62 at r2](https://reviewable.io/reviews/ejourn-al/ejournal/1269#-Ms-r4QA1UtEDHfs9Nu1:-Ms4azKC7n_OyFmQ6PX7:b-559lii) ([raw file](https://github.com/ejourn-al/ejournal/blob/c1be347ad500ebb0707a47d6297dedf95122830e/src/vue/src/components/entry/Comments.vue#L62)):*
<details><summary><i>Previously, Larspolo (Lars) wrote…</i></summary><blockquote>

It didnt so far
</blockquote></details>

Good enough for me so far ;) Will be an issue but only once those comments are actually introduced
___
*[src/django/VLE/models/journal_content/comment.py, line 90 at r2](https://reviewable.io/reviews/ejourn-al/ejournal/1269#-Ms-MhX11EWY2ORxj_Oq:-Ms4Tb782uT__OwPL5-_:b-u7zi1s) ([raw file](https://github.com/ejourn-al/ejournal/blob/c1be347ad500ebb0707a47d6297dedf95122830e/src/django/VLE/models/journal_content/comment.py#L90)):*
<details><summary><i>Previously, Larspolo (Lars) wrote…</i></summary><blockquote>

I didnt. I thought we settled on creating an issue for that and having three statusses a comment can be is:
- hidden for everybody
- hidden for other groups (e.g. only visible for supervisors)
- visible

Not something I want to touch on in this PR, as it was already like this anyway

https://ejournal.atlassian.net/browse/EJ-1222
</blockquote></details>

I am not sure I agree with the status quo but an issue is fine
___
*[src/django/VLE/models/journal_content/entry.py, line 383 at r2](https://reviewable.io/reviews/ejourn-al/ejournal/1269#-Ms-P7yQ1Ytsc38koG4j:-Ms4TmQ4BSOBzH9JP9eo:bv9m2bn) ([raw file](https://github.com/ejourn-al/ejournal/blob/c1be347ad500ebb0707a47d6297dedf95122830e/src/django/VLE/models/journal_content/entry.py#L383)):*
<details><summary><i>Previously, Larspolo (Lars) wrote…</i></summary><blockquote>

Can a student that does not have a valid LTI link still post comments? Currently its only checked for editing  [...]

2021-12-29 10:52 UTC, Larspolo reviewed
> Reviewed 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/ejourn-al/ejournal/1269)* status: 169 of 176 files reviewed, 29 unresolved discussions (waiting on @engelhamer, @Larspolo, and @mjvkeulen)

___
*[src/django/VLE/serializers.py, line 574 at r2](https://reviewable.io/reviews/ejourn-al/ejournal/1269#-Ms-563F9HzxG_tQRrPo:-Ms4fQ634f8mwtGaqdzJ:b335ck3) ([raw file](https://github.com/ejourn-al/ejournal/blob/c1be347ad500ebb0707a47d6297dedf95122830e/src/django/VLE/serializers.py#L574)):*
<details><summary><i>Previously, mjvkeulen (Maarten van Keulen) wrote…</i></summary><blockquote>

Yes loads of this exist already, just an FYI as some parts you did also introduce this.
</blockquote></details>

Removed it now, lets see if tests start to complain. But I feel like this should have been a NIT
___
*[src/django/VLE/migrations/0038_file_rework.py, line 20 at r2](https://reviewable.io/reviews/ejourn-al/ejournal/1269#-Ms-83Kg8RoDVAmCB1NI:-Ms4fwAx6S0s05cu5IO4:b-ycioqp) ([raw file](https://github.com/ejourn-al/ejournal/blob/c1be347ad500ebb0707a47d6297dedf95122830e/src/django/VLE/migrations/0038_file_rework.py#L20)):*
<details><summary><i>Previously, mjvkeulen (Maarten van Keulen) wrote…</i></summary><blockquote>

So we define Node at the first occurrence in code (not model definition?)
</blockquote></details>

Feels a bit weird to keep it in de models file just because an old migration depended on it. This has also eben done before. See below the class "UserFile"
___
*[src/django/VLE/migrations/0106_node_structure_rework.py, line 37 at r5](https://reviewable.io/reviews/ejourn-al/ejournal/1269#-Ms4SiTG4Nj4mtIlOdmq:-Ms4gAdwEaFuLSShs95d:b-896fix) ([raw file](https://github.com/ejourn-al/ejournal/blob/10695b40c5c20edc3cc0c6f1d73ff91313eb6dc4/src/django/VLE/migrations/0106_node_structure_rework.py#L37)):*
<details><summary><i>Previously, mjvkeulen (Maarten van Keulen) wrote…</i></summary><blockquote>

Tagging
</blockquote></details>

Done.
___
*[src/django/VLE/migrations/0106_node_structure_rework.py, line 48 at r5](https://reviewable.io/reviews/ejourn-al/ejournal/1269#-Ms4SP5--_FERqMvfZmU:-Ms4gBod4F8b9dSdBeIN:bnj5hgd) ([raw file](https://github.com/ejourn-al/ejournal/blob/10695b40c5c20edc3cc0c6f1d73ff91313eb6dc4/src/django/VLE/migrations/0106_node_structure_rework.py#L48)):*
<details><summary><i>Previously, mjvkeulen (Maarten van Keulen) wrote…</i></summary><blockquote>

Just tagging to check if a test is present. I remember the auto add fields ignored some .save operations (they still follow direct sql instructions of course)
</blockquote></details>

Tested manually
___
*[src/django/VLE/models/journal_content/base.py, line 96 at r1](https://reviewable.io/reviews/ejourn-al/ejournal/1269#-MpNb1TZW-PaRN0TwNlX-r1-96:-Ms4nz7_5NWbAfXOhKst:b-896fix) ([raw file](https://github.com/ejourn-al/ejournal/blob/0507f8bacf229367c3c795fe2030476ed5ae5fb3/src/django/VLE/models/journal_content/base.py#L96)):*
<details><summary><i>Previously, Larspolo (Lars) wrote…</i></summary><blockquote>

Good one, this would trigger creating multiple indeed. An issue that needs resolving
</blockquote></details>

Done.
___
*[src/django/VLE/models/journal_content/base.py, line 137 at r1](https://reviewable.io/reviews/ejourn-al/ejournal/1269#-MpNb1TZW-PaRN0TwNlX-r1-137:-Ms4gIMqAlUPUp3lZrMm:b-896fix) ([raw file](https://github.com/ejourn-al/ejournal/blob/0507f8bacf229367c3c795fe2030476ed5ae5fb3/src/django/VLE/models/journal_content/base.py#L137)):*
<details><summary><i>Previously, mjvkeulen (Maarten van Keulen) wrote…</i></summary><blockquote>

ok
</blockquote></details>

Done.
___
*[src/django/VLE/models/nodes/journal_nodes/base.py, line 7 at r2](https://reviewable.io/reviews/ejourn-al/ejournal/1269#-Ms-STgNEWCh25vq2WRG:-Ms4hrKUD7Q8dAw67dcf:bw7d7bm) ([raw file](https://github.com/ejourn-al/ejournal/blob/c1be347ad500ebb0707a47d6297dedf95122830e/src/django/VLE/models/nodes/journal_nodes/base.py#L7)):*
<details><summary><i>Previously, mjvkeulen (Maarten van Keulen) wrote…</i></summary><blockquote>

`JournalNode` does not exist tho right?
</blockquote></details>

But this is a queryset available for all journal nodes. There is no need to overwrite it, while there is a need to overwrite the model
___
*[src/django/VLE/models/nodes/preset_nodes/preset_progress_goal_node.py, line 48 at r2](https://reviewable.io/reviews/ejourn-al/ejournal/1269#-Ms4_bvEEbaGVBpy2aXC:-Ms4iCzx6KS87Stbi7Qv:boo8yrg) ([raw file](https://github.com/ejourn-al/ejournal/blob/c1be347ad500ebb0707a47d6297dedf95122830e/src/django/VLE/models/nodes/preset_nodes/preset_progress_goal_node.py#L48)):*
<details><summary><i>Previously, mjvkeulen (Maarten van Keulen) wrote…</i></summary><blockquote>

Should we also add this check as a CheckConstraint to the table (`AbstractProgressGoalNode`)?
</blockquote></details>

That it needs to be bigger than points possible? You may. But I would NIT this
___
*[src/django/VLE/views/preset_node.py, line 34 at r2](https://reviewable.io/reviews/ejourn-al/ejournal/1269#-Ms-mO47CZet68ff_IEK:-Ms4iLTL9TSZQklFMXZ6:b-ecauaf) ([raw file](https://github.com/ejourn-al/ejournal/blob/c1be347ad500ebb0707a47d6297dedf95122830e/src/django/VLE/views/preset_node.py#L34)):*
<details><summary><i>Previously, mjvkeulen (Maarten van Keulen) wrote…</i></summary><blockquote>

`viewsets.ViewSet` -> `viewsets.ModelViewSet`
</blockquote></details>

Changed it back, also changes `views/node.py` to `viewset`
___
*[src/vue/src/api/journal.js, line 62 at r2](https://reviewable.io/reviews/ejourn-al/ejournal/1269#-Ms-p_5HCGtp2Jd90g0F:-Ms4ibrjAeZFu3NNiE9G:b-896fix) ([raw file](https://github.com/ejourn-al/ejournal/blob/c1be347ad500ebb0707a47d6297dedf95122830e/src/vue/src/api/journal.js#L62)):*
<details><summary><i>Previously, mjvkeulen (Maarten van Keulen) wrote…</i></summary><blockquote>

https://ejournal.atlassian.net/browse/EJ-1238
</blockquote></details>

Done.
___
*[src/vue/src/components/assignment/ManageTeacherEntriesModal.vue, line 298 at r2](https://reviewable.io/reviews/ejourn-al/ejournal/1269#-Ms-qGDP8WQRTbuZBueU:-Ms4ifoP6V9BxDhOWob4:b4l8tlk) ([raw file](https://github.com/ejourn-al/ejournal/blob/c1be347ad500ebb0707a47d6297dedf95122830e/src/vue/src/components/assignment/ManageTeacherEntriesModal.vue#L298)):*
<details><summary><i>Previously, mjvkeulen (Maarten van Keulen) wrote…</i></summary><blockquote>

Should we then stick to title in user facing communcation since it is more clear?
</blockquote></details>

Oh wait, I meant to say, I find name as clear as title. I think its not useful for us to make it inconsistent between back & frontend.
___
*[src/vue/src/components/entry/Comments.vue, line 62 at r2](https://reviewable.io/reviews/ejourn-al/ejournal/1269#-Ms-r4QA1UtEDHfs9Nu1:-Ms4iz9V8uN6caGpn_bl:b-1nqz65) ([raw file](https://github.com/ejourn-al/ejournal/blob/c1be347ad500ebb0707a47d6297dedf95122830e/src/vue/src/components/entry/Comments.vue#L62)):*
<details><summary><i>Previously, mjvkeulen (Maarten van Keulen) wrote…</i></summary><blockquote>

Good enough for me so far ;) Will be an issue but only once those comments are actually introduced
</blockquote></details>

Well, you already have preset entry nodes without entries, and sometimes entries but without grades. I dont see that being a big difference
___
*[src/django/VLE/migrations/0104_auto_20211126_1140.py, line 92 at r1](https://reviewable.io/reviews/ejourn-al/ejournal/1269#-MpR25fUcmFAh1EVdFxg-r1-92:-Ms4oHT9-EOEsBe0oezV:b-896fix) ([raw file](https://github.com/ejourn-al/ejournal/blob/0507f8bacf229367c3c795fe2030476ed5ae5fb3/src/django/VLE/migrations/0104_auto_20211126_1140.py#L92)):*
<details><summary><i>Previously, Larspolo (Lars) wrote…</i></summary><blockquote>

Didnt do any of the migrations yet, but thats true indeed. Also left default values to "1", which should be updated as well
</blockquote></details>

Done.
___
*[src/django/VLE/models/journal_content/comment.py, line 90 at r2](https://reviewable.io/reviews/ejourn-al/ejournal/1269#-Ms-MhX11EWY2ORx [...]

2021-12-30 14:40 UTC, Larspolo reviewed
> Reviewed 1 of 1 files at r6, 6 of 6 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ejourn-al/ejournal/1269)* status: all files reviewed, 29 unresolved discussions (waiting on @engelhamer and @mjvkeulen)



<!-- Sent from Reviewable.io -->

2021-12-30 15:16 UTC, mjvkeulen reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ejourn-al/ejournal/1269)* status: all files reviewed, 19 unresolved discussions (waiting on @engelhamer and @Larspolo)

___
*[src/django/VLE/migrations/0038_file_rework.py, line 20 at r2](https://reviewable.io/reviews/ejourn-al/ejournal/1269#-Ms-83Kg8RoDVAmCB1NI:-MsAqXBu1uV7e7-w-HVZ:bet3gqy) ([raw file](https://github.com/ejourn-al/ejournal/blob/c1be347ad500ebb0707a47d6297dedf95122830e/src/django/VLE/migrations/0038_file_rework.py#L20)):*
<details><summary><i>Previously, Larspolo (Lars) wrote…</i></summary><blockquote>

Feels a bit weird to keep it in de models file just because an old migration depended on it. This has also eben done before. See below the class "UserFile"
</blockquote></details>

Ok, I was just wondering this is fine with me
___
*[src/django/VLE/models/nodes/preset_nodes/preset_progress_goal_node.py, line 48 at r2](https://reviewable.io/reviews/ejourn-al/ejournal/1269#-Ms4_bvEEbaGVBpy2aXC:-MsAtuv2DrwFVYXOaRz4:bvsw2wn) ([raw file](https://github.com/ejourn-al/ejournal/blob/c1be347ad500ebb0707a47d6297dedf95122830e/src/django/VLE/models/nodes/preset_nodes/preset_progress_goal_node.py#L48)):*
<details><summary><i>Previously, Larspolo (Lars) wrote…</i></summary><blockquote>

That it needs to be bigger than points possible? You may. But I would NIT this
</blockquote></details>

I thought this would be like 2 minutes fix but its not.

How should we handle inheritance from multiple Classes with meta defined?

Adding 

```
        constraints = [
            CheckConstraint(check=Q(target__gte=0.0), name='%(app_label)s__%(class)s__positive_target'),
        ]
```

to `AbstractProgressGoalNode` is not inherited because `PresetProgressGoalNode(AbstractPresetNode, AbstractProgressGoalNode)` inherits `AbstractPresetNode` first: which resolves the Meta inheritence entirely adding  only the meta defined in `AbstractPresetNode`?
___
*[src/vue/src/components/assignment/ManageTeacherEntriesModal.vue, line 298 at r2](https://reviewable.io/reviews/ejourn-al/ejournal/1269#-Ms-qGDP8WQRTbuZBueU:-MsArH2R9rPM0HnFCtEB:b-kl68on) ([raw file](https://github.com/ejourn-al/ejournal/blob/c1be347ad500ebb0707a47d6297dedf95122830e/src/vue/src/components/assignment/ManageTeacherEntriesModal.vue#L298)):*
<details><summary><i>Previously, Larspolo (Lars) wrote…</i></summary><blockquote>

Oh wait, I meant to say, I find name as clear as title. I think its not useful for us to make it inconsistent between back & frontend.
</blockquote></details>

@engelhamer 


<!-- Sent from Reviewable.io -->

2021-12-30 15:35 UTC, mjvkeulen reviewed
Manage teacher entry:

> Reviewed 1 of 168 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ejourn-al/ejournal/1269#-:-MsAygVP3o3rRoYD2Kgi:b5tbu58)* status: all files reviewed, 19 unresolved discussions (waiting on @engelhamer and @Larspolo)



<!-- Sent from Reviewable.io -->

2021-12-30 15:40 UTC, mjvkeulen reviewed
> Reviewed 1 of 6 files at r7.
> *[Reviewable](https://reviewable.io/reviews/ejourn-al/ejournal/1269)* status: all files reviewed, 21 unresolved discussions (waiting on @engelhamer and @Larspolo)

___
*[src/django/VLE/migrations/0106_node_structure_rework.py, line 36 at r7](https://reviewable.io/reviews/ejourn-al/ejournal/1269#-MsAzmcHAPVGjLnO3lPE:-MsAzmcI7QhIb3JYCgjh:b-8z2ocv) ([raw file](https://github.com/ejourn-al/ejournal/blob/17c8dc88ed649a397a73b1f356626c360be50291/src/django/VLE/migrations/0106_node_structure_rework.py#L36)):*
> ```Python
>     Template.objects.filter(format__assignment__isnull=True).delete()
>     TemplateChain.objects.filter(format__assignment__isnull=True).delete()
> ```

I would prefer we didnt duplicate the migration names. 

All prefixed with node_structure_rework
1. _create_models
2. _migrate_models
3. _remove_models

or smth
___
*[src/django/VLE/migrations/0106_node_structure_rework.py, line 36 at r7](https://reviewable.io/reviews/ejourn-al/ejournal/1269#-MsB--Fu40fpuw-4gFIA:-MsB--Fu40fpuw-4gFIB:bt2qr0o) ([raw file](https://github.com/ejourn-al/ejournal/blob/17c8dc88ed649a397a73b1f356626c360be50291/src/django/VLE/migrations/0106_node_structure_rework.py#L36)):*
> ```Python
>     Template.objects.filter(format__assignment__isnull=True).delete()
>     TemplateChain.objects.filter(format__assignment__isnull=True).delete()
> ```

I encountered this whislt managing a teacher entry

![image.png](https://files.reviewableusercontent.io/images/reviewable/39912610/3vpCGt4BOtElh5uAZxGwOurf/image.png)


<!-- Sent from Reviewable.io -->

2021-12-31 11:50 UTC, Larspolo reviewed
Missing context

> *[Reviewable](https://reviewable.io/reviews/ejourn-al/ejournal/1269#-:-MsFHSnv0DQ4MaDaKbT8:b-wwdbdc)* status: all files reviewed, 21 unresolved discussions (waiting on @engelhamer and @mjvkeulen)

___
*[src/django/VLE/migrations/0106_node_structure_rework.py, line 36 at r7](https://reviewable.io/reviews/ejourn-al/ejournal/1269#-MsAzmcHAPVGjLnO3lPE:-MsFHqnmBlX4a0xSGRY5:b-896fix) ([raw file](https://github.com/ejourn-al/ejournal/blob/17c8dc88ed649a397a73b1f356626c360be50291/src/django/VLE/migrations/0106_node_structure_rework.py#L36)):*
<details><summary><i>Previously, mjvkeulen (Maarten van Keulen) wrote…</i></summary><blockquote>

I would prefer we didnt duplicate the migration names. 

All prefixed with node_structure_rework
1. _create_models
2. _migrate_models
3. _remove_models

or smth
</blockquote></details>

Done.
___
*[src/django/VLE/migrations/0106_node_structure_rework.py, line 36 at r7](https://reviewable.io/reviews/ejourn-al/ejournal/1269#-MsB--Fu40fpuw-4gFIA:-MsFIwhzBzzr9wBj_hhZ:b-896fix) ([raw file](https://github.com/ejourn-al/ejournal/blob/17c8dc88ed649a397a73b1f356626c360be50291/src/django/VLE/migrations/0106_node_structure_rework.py#L36)):*
<details><summary><i>Previously, mjvkeulen (Maarten van Keulen) wrote…</i></summary><blockquote>

I encountered this whislt managing a teacher entry

![image.png](https://files.reviewableusercontent.io/images/reviewable/39912610/3vpCGt4BOtElh5uAZxGwOurf/image.png)

</blockquote></details>

Done.
___
*[src/django/VLE/models/nodes/preset_nodes/preset_progress_goal_node.py, line 48 at r2](https://reviewable.io/reviews/ejourn-al/ejournal/1269#-Ms4_bvEEbaGVBpy2aXC:-MsFJPqP8Oq7OdC0RyFO:b-f0m42g) ([raw file](https://github.com/ejourn-al/ejournal/blob/c1be347ad500ebb0707a47d6297dedf95122830e/src/django/VLE/models/nodes/preset_nodes/preset_progress_goal_node.py#L48)):*
<details><summary><i>Previously, mjvkeulen (Maarten van Keulen) wrote…</i></summary><blockquote>

I thought this would be like 2 minutes fix but its not.

How should we handle inheritance from multiple Classes with meta defined?

Adding 

```
        constraints = [
            CheckConstraint(check=Q(target__gte=0.0), name='%(app_label)s__%(class)s__positive_target'),
        ]
```

to `AbstractProgressGoalNode` is not inherited because `PresetProgressGoalNode(AbstractPresetNode, AbstractProgressGoalNode)` inherits `AbstractPresetNode` first: which resolves the Meta inheritence entirely adding  only the meta defined in `AbstractPresetNode`?
</blockquote></details>

`constraints = AbstractProgressGoalNode.Meta.constraints + AbstractPresetNode.Meta.constraints`
Could might work. Thats how I do it in the serialization
___
*[src/vue/src/components/assignment/ManageTeacherEntriesModal.vue, line 298 at r2](https://reviewable.io/reviews/ejourn-al/ejournal/1269#-Ms-qGDP8WQRTbuZBueU:-MsFJoM772GKJ1YF_CTO:bd9ljax) ([raw file](https://github.com/ejourn-al/ejournal/blob/c1be347ad500ebb0707a47d6297dedf95122830e/src/vue/src/components/assignment/ManageTeacherEntriesModal.vue#L298)):*
<details><summary><i>Previously, mjvkeulen (Maarten van Keulen) wrote…</i></summary><blockquote>

@engelhamer 
</blockquote></details>

I feel like this is mostly because you were used to "title". A name for a teacher entry node is not weird


<!-- Sent from Reviewable.io -->

2022-01-02 15:16 UTC, Larspolo reviewed
> Reviewed 5 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ejourn-al/ejournal/1269)* status: all files reviewed, 21 unresolved discussions (waiting on @engelhamer and @mjvkeulen)



<!-- Sent from Reviewable.io -->

2022-01-03 07:40 UTC, mjvkeulen reviewed
> Reviewed 3 of 4 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ejourn-al/ejournal/1269)* status: 175 of 176 files reviewed, 18 unresolved discussions (waiting on @engelhamer, @Larspolo, and @mjvkeulen)



<!-- Sent from Reviewable.io -->

2022-01-10 20:28 UTC, mjvkeulen requested changes

2022-01-10 20:28 UTC, mjvkeulen commented on src/vue/src/components/entry/CommentCard.vue
> +                    : undefined,
Q) Was there any significance in using `undefined` specifically?

2022-01-10 20:28 UTC, mjvkeulen commented on src/vue/src/components/entry/CommentCard.vue
> +            return JSON.stringify(this.comment.text) === JSON.stringify(this.editedComment.text)
This seems like a weird change?

2022-01-10 20:28 UTC, mjvkeulen commented on src/vue/src/store/modules/presetNode.js
> -                    context.commit('SET_ASSIGNMENT_PRESET_NODES', { aID, presetNodes: response.data.presets })
To me it wasn't clear that `nodesToList` also updates the store ('SET_ASSIGNMENT_PRESET_NODES'). Since this is the only place `nodeUtils.nodesToList` is called with `presetNodesOnly` set to `true`, I would prefer if this list action call the mutation to update the store (and just remove that block from nodeUtils).

2022-01-10 20:28 UTC, mjvkeulen commented on src/vue/src/store/modules/timeline.js
> +    checkNodeNavigationGuards: (state) => () => state.nodeNavigationGuards.every((guard) => guard()),
Can be removed, merge issue or smth?

2022-01-10 20:28 UTC, mjvkeulen commented on src/vue/src/utils/node_utils.js
> +                )
[NIT] One line?

2022-01-10 20:28 UTC, mjvkeulen commented on src/vue/src/utils/node_utils.js
> +                }
See other comment

2022-01-10 20:28 UTC, mjvkeulen commented on src/vue/src/views/Journal.vue
> +                />
Was this block lost somehow? What happenend?

2022-01-10 20:28 UTC, mjvkeulen commented on src/vue/src/views/Journal.vue
> +/* eslint-disable */
Left over?

2022-01-10 20:28 UTC, mjvkeulen commented on src/vue/src/views/Journal.vue
> +                    journalAPI.getNodes(this.jID, this.assignment.id)
What forced this extra list over using local state?

2022-01-10 21:53 UTC, Larspolo commented on src/vue/src/components/entry/CommentCard.vue
> +                    : undefined,
not passed back to the backend

2022-01-10 21:54 UTC, Larspolo commented on src/vue/src/components/entry/CommentCard.vue
> +            return JSON.stringify(this.comment.text) === JSON.stringify(this.editedComment.text)
:shrug: found it in a merge

2022-01-10 21:59 UTC, Larspolo commented on src/vue/src/views/Journal.vue
> +                    journalAPI.getNodes(this.jID, this.assignment.id)
Dunno

2022-01-10 22:05 UTC, Larspolo commented on src/vue/src/views/Journal.vue
> +                />
Moved to journal card, think merge mistake, removed it again

2022-01-10 22:07 UTC, Larspolo commented on src/vue/src/components/entry/CommentCard.vue
> +            return JSON.stringify(this.comment.text) === JSON.stringify(this.editedComment.text)
https://github.com/eJourn-al/eJournal/commit/66150542d39f885aab2c622d7e2148b6b4eb85ee#diff-639580dad65414c81662bae4de2af2a38d1875ace590693421a16325e0dca838R265

2022-01-11 06:50 UTC, mjvkeulen approved these changes

2022-01-11 09:00 UTC, engelhamer approved these changes

2022-01-11 09:00 UTC, merged