Added the ability for students to preview the assessment model
eJourn-al/eJournal pull request #1271
Opened 2021-11-26 08:02 UTC by mjvkeulen

2021-11-27 12:45 UTC, engelhamer commented on src/vue/src/components/assessment/AssessmentGrades.vue
> +        <rubric-automatic-criterion-display
I prefer to keep such a small (and infrequently used) element within this file. Having to navigate to so many layers that are at the same level in the file tree is annoying.

2021-11-27 12:45 UTC, engelhamer commented on src/django/VLE/migrations/0103_rubric_visibility.py
> +            field=models.CharField(choices=[('v', 'Visible to students'), ('hu', 'Hidden from students until used in an assessment')], default='v', max_length=2),
Why `hu` and not just `h`?

2021-11-27 12:45 UTC, engelhamer commented on src/vue/src/components/journal/JournalEndCard.vue
> +            <template v-if="!loading">
Since `loading` is already passed to the `load-wrapper`, any content in this slot is conditional to this variable already. This layer can be removed?

2021-11-27 12:45 UTC, engelhamer commented on src/vue/src/components/journal/JournalEndCard.vue
> +            class="mr-2"
```suggestion
            class="mr-2 mt-2"
```

The gap between the rubric and this line is too small.

2021-11-27 12:45 UTC, engelhamer commented on src/vue/src/components/journal/JournalEndCard.vue
> +                    <theme-select
Missing some indication which is the default rubric (or: that there is no default). Now students can click around but are unaware about what rubric is active.

2021-11-27 12:45 UTC, engelhamer commented on src/vue/src/components/journal/JournalStartCard.vue
> +        <hr/>
Can be omitted? We do not use `hr` elements for card footers anymore (see e.g. progress node).

2021-11-27 16:09 UTC, mjvkeulen commented on src/django/VLE/migrations/0103_rubric_visibility.py
> +            field=models.CharField(choices=[('v', 'Visible to students'), ('hu', 'Hidden from students until used in an assessment')], default='v', max_length=2),
**H**idden **U**ntill, `h` can be used for just plain hidden at some point.

2021-11-27 16:10 UTC, mjvkeulen commented on src/vue/src/components/journal/JournalEndCard.vue
> +            <template v-if="!loading">
Loading does not prevent its content from being added to the dom (unless changed recently)

2021-11-27 16:10 UTC, mjvkeulen commented on src/vue/src/components/journal/JournalEndCard.vue
> +                    <theme-select
Default is preselected

2021-11-27 16:11 UTC, mjvkeulen commented on src/vue/src/components/journal/JournalStartCard.vue
> +        <hr/>
Hr creates a clean break between the description and additional actions

2021-11-27 16:46 UTC, engelhamer commented on src/vue/src/components/journal/JournalStartCard.vue
> +        <hr/>
But it is not consistent with the other cards in the timeline, where there is no such distinction. Also in the panel on the right (progress bar and buttons) there is none.

2021-11-27 16:46 UTC, engelhamer commented on src/vue/src/components/journal/JournalEndCard.vue
> +                    <theme-select
Yes but that is not stated anywhere. Also
> (or: that there is no default).

2021-11-27 16:47 UTC, engelhamer commented on src/vue/src/components/journal/JournalEndCard.vue
> +            <template v-if="!loading">
![image](https://user-images.githubusercontent.com/39912581/143689821-0d60ab98-5b8c-466d-9b0c-0e0e3257b145.png)

How does that happen?

2021-11-27 16:48 UTC, engelhamer commented on src/django/VLE/migrations/0103_rubric_visibility.py
> +            field=models.CharField(choices=[('v', 'Visible to students'), ('hu', 'Hidden from students until used in an assessment')], default='v', max_length=2),
Which would be hidden, even if it is used?

2021-11-27 16:48 UTC, engelhamer commented on src/django/VLE/migrations/0103_rubric_visibility.py
> +            field=models.CharField(choices=[('v', 'Visible to students'), ('hu', 'Hidden from students until used in an assessment')], default='v', max_length=2),
So that would be a secret rubric?

2021-11-28 10:41 UTC, mjvkeulen commented on src/django/VLE/migrations/0103_rubric_visibility.py
> +            field=models.CharField(choices=[('v', 'Visible to students'), ('hu', 'Hidden from students until used in an assessment')], default='v', max_length=2),
A rubric which is used to formulate a grade, but the rubric is never shared with the students, just the grade.

2021-11-28 10:43 UTC, mjvkeulen commented on src/vue/src/components/journal/JournalStartCard.vue
> +        <hr/>
None of these other examples have user-generated RT followed by actions

2021-11-28 11:06 UTC, mjvkeulen commented on src/vue/src/components/journal/JournalEndCard.vue
> +                    <theme-select
Added (default) to the rubric select label

2021-11-28 11:07 UTC, mjvkeulen commented on src/vue/src/components/journal/JournalEndCard.vue
> +            <template v-if="!loading">
Glad this is the case, removed the extra template. 

Quite a few places have this duplicate guard in place, was this changed after the load wrapper's introduction?

2021-11-28 12:07 UTC, engelhamer commented on src/vue/src/components/journal/JournalStartCard.vue
> +        <hr/>
Progress goal has user-generated content with the deadline info underneath, no line
![image](https://user-images.githubusercontent.com/39912581/143766771-507e5c17-7263-4a5b-81e8-f8cc362fa39d.png)

Then because there are actions here, the deadline info ends up underneath a line
![image](https://user-images.githubusercontent.com/39912581/143766798-eb4c4893-080b-4e37-ab26-af5d3b499d1d.png)

Would prefer to just omit it
![image](https://user-images.githubusercontent.com/39912581/143766810-a1d6ac9a-d562-4c2a-9479-52aeea752a39.png)

Or maybe in the footer?
![image](https://user-images.githubusercontent.com/39912581/143767015-4bf9857c-9574-40ec-b30f-313b4617471e.png)

Just because the line is not used much and can lead to inconsistency.

2021-11-28 12:37 UTC, engelhamer commented on src/vue/src/components/journal/JournalEndCard.vue
> +            <template v-if="!loading">
Yes, this has been the case for 2 years 😄 

Created #1273 to fix these occurrences, there were not that many.

2021-11-28 13:29 UTC, Larspolo requested changes

2021-11-28 13:29 UTC, Larspolo commented on src/vue/src/components/rubric/edit/RubricEdit.vue
> +                    :customLabel="rubricVisibilityLabel"
Feels like this should be a toggle setting, not a dropdown

2021-11-28 13:29 UTC, Larspolo commented on src/vue/src/components/rubric/edit/RubricEdit.vue
> +            <b-form-group
When is this description used? Feels like sth we all overlooked and is never actually used

2021-11-28 13:29 UTC, Larspolo commented on src/vue/src/components/journal/JournalEndCard.vue
> +                    :customLabel="(rubric) => rubric === defaultRubric ? `${rubric.name} (default)` : rubric.name"
Where can I see this? I dont see it in the assignment editor in de "assessment model" node it is not shown in the dropdown. Also for students I don't see it, but Im not sure why

2021-11-28 13:29 UTC, Larspolo commented on src/vue/src/components/journal/JournalEndCard.vue
> +                {{ title }}
This not said "assessment model", but in the edit mode it says "assessment". Feels like it should be consistent between the two
![image](https://user-images.githubusercontent.com/11822478/143769616-cf4688fc-6ef1-4700-b013-a735139f27af.png)
![image](https://user-images.githubusercontent.com/11822478/143769621-be7d28f5-c372-4dc6-bb63-da3e2b125743.png)

2021-11-28 13:29 UTC, Larspolo commented on src/django/VLE/views/rubric.py
> +            context={'user': request.user, 'annotated_is_in_use': can_grade},
[NIT] Could be moved to a `conditional_field`

2021-11-28 13:29 UTC, Larspolo commented on src/vue/src/components/assessment/AssessmentGrades.vue
> +            :description="'Sum of all points obtained through journal entries.'"
```suggestion
            label="Entry points"
            description="Sum of all points obtained through journal entries."
```

2021-11-28 13:29 UTC, Larspolo commented on src/vue/src/components/assessment/AssessmentGrades.vue
> +            :description="'Bonus points given to this journal.'"
```suggestion
            label="Bonus points"
            description="Bonus points given to this journal."
```

2021-11-28 13:29 UTC, Larspolo commented on src/vue/src/components/journal/JournalEndCard.vue
> +                            :description="'Sum of all points obtained through journal entries.'"
```suggestion
                            label="Entry points"
                            description="Sum of all points obtained through journal entries."
```

2021-11-28 13:29 UTC, Larspolo commented on src/vue/src/components/journal/JournalEndCard.vue
> +                            :description="'Bonus points given to this journal.'"
```suggestion
                            label="Bonus points"
                            description="Bonus points given to this journal."
```

2021-11-28 13:29 UTC, Larspolo commented on src/vue/src/components/journal/JournalStartCard.vue
> +        <hr/>
I dont mind any of the proposals

2021-11-29 09:05 UTC, mjvkeulen commented on src/vue/src/components/rubric/edit/RubricEdit.vue
> +                    :customLabel="rubricVisibilityLabel"
I don't mind either way, but expect this to become more than 2 options

2021-11-29 09:05 UTC, mjvkeulen commented on src/vue/src/components/rubric/edit/RubricEdit.vue
> +            <b-form-group
Description is used within the assignment editor. So only for teachers managing the rubrics (atm)

2021-11-29 09:07 UTC, mjvkeulen commented on src/vue/src/components/journal/JournalEndCard.vue
> +                    :customLabel="(rubric) => rubric === defaultRubric ? `${rubric.name} (default)` : rubric.name"
![image](https://user-images.githubusercontent.com/39912610/143838858-4fb72787-eb3c-4baf-a5a8-c61771baa998.png)

It should be shown in the assessment model node, provide a default assessment rubric is set?

2021-11-29 09:18 UTC, mjvkeulen commented on src/vue/src/components/journal/JournalStartCard.vue
> +        <hr/>
Moved to footer

2021-11-29 12:07 UTC, Larspolo commented on src/vue/src/components/rubric/edit/RubricEdit.vue
> +                    :customLabel="rubricVisibilityLabel"
Then its better, but as of now its only 2. When would you expect to add more? Changed it to a NIT

2021-11-29 12:08 UTC, Larspolo commented on src/vue/src/components/rubric/edit/RubricEdit.vue
> +            <b-form-group
Not this PR, but feels like this needs a description then, I would expect it to be shown somewhere else as well

2021-11-29 12:12 UTC, Larspolo commented on src/vue/src/components/journal/JournalEndCard.vue
> +                    :customLabel="(rubric) => rubric === defaultRubric ? `${rubric.name} (default)` : rubric.name"
I swear I did, thats why I was so confused of it not working. Checking it out now, it seems all fine

2021-11-29 12:15 UTC, Larspolo approved these changes

2021-11-29 12:15 UTC, Larspolo commented on src/django/VLE/views/rubric.py
> +            context={'user': request.user, 'annotated_is_in_use': can_grade},
[Q] Previously then was a string? Think that was just wrong, right? Seems like 'True' was truthy, which made it work

2021-12-01 15:46 UTC, engelhamer approved these changes

2021-12-01 15:49 UTC, merged