Added the ability to add rubrics to entries
eJourn-al/eJournal pull request #1328
Opened 2022-02-16 08:50 UTC by Larspolo

2022-02-17 07:58 UTC, mjvkeulen requested changes
> Reviewed 18 of 88 files at r1, 5 of 15 files at r2, 13 of 22 files at r3, 1 of 1 files at r5, 1 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ejourn-al/ejournal/1328)* status: 38 of 92 files reviewed, 20 unresolved discussions (waiting on @engelhamer, @Larspolo, and @mjvkeulen)

___
*[src/django/test/test_assignment.py, line 256 at r5](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-Mw5V5ql-0W_A-D5aCo3:-Mw5V5qm939XLNpo7WyJ:bx5kgxn) ([raw file](https://github.com/ejourn-al/ejournal/blob/7d6d0977e3ce8cd53efe2a47554b74a11b615c69/src/django/test/test_assignment.py#L256)):*
> ```Python
>             for i in range(n_graded_entries):
>                 entry = factory.JournalNodeEntry(
>                     journal=journal, grade__grade=5, grade__published=False, grade__author=self.teacher)
> ```

[D] Do you care for the old deep syntax? (Factory.entry(grade__grade=x)
___
*[src/django/test/test_category.py, line 304 at r5](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-Mw5Vp5kABvuhqCjaxTK:-Mw5Vp5kABvuhqCjaxTL:bf0c587) ([raw file](https://github.com/ejourn-al/ejournal/blob/d99b2767bb6a54b50fd47c5f908b129cd1fd8df0/src/django/test/test_category.py#L304)):*
> ```Python
>             assert not entry.categories.filter(pk=self.category.pk).exists(), 'Category has been succesfully removed'
> 
>             # A student cannot edit an entry's categories if the entry has an empty feedback form
> ```

Once a teacher starts assessment (still draft) a student should be able to continue editing the entry (otherwise it's confusing, after all the student has no assessment indication yet).
___
*[src/django/test/test_grade.py, line 25 at r5](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-Mw5XlpqDDDO7MjW9VgH:-Mw5XlpqDDDO7MjW9VgI:b-l4nj6m) ([raw file](https://github.com/ejourn-al/ejournal/blob/d99b2767bb6a54b50fd47c5f908b129cd1fd8df0/src/django/test/test_grade.py#L25)):*
> ```Python
>             self,
>             'assessment_feedback_forms',
>             params={
> ```

Qualifies wonderfully for assessment feedback form creation params (which like `CommentCreationParamsFactory` could chain with JournalContentBaseParamsFactory)
___
*[src/django/test/test_gradepassback.py, line 173 at r5](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-Mw5YOKWCrd7NFfggnlk:-Mw5YOKWCrd7NFfggnll:b-3pacbt) ([raw file](https://github.com/ejourn-al/ejournal/blob/d99b2767bb6a54b50fd47c5f908b129cd1fd8df0/src/django/test/test_gradepassback.py#L173)):*
> ```Python
>     def test_check_if_need_VLE_publish_journals(self):
>         """Hopefully doesnt crash."""
>         factory.JournalNodeEntry(journal=self.lti_journal, vle_coupling=Entry.NEEDS_SENDING)
> ```

Entry.NEEDS_SENDING seems unrelated to grade passback?
___
*[src/django/test/test_journal.py, line 1226 at r5](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-Mw5Z9cQ06Kh1F7UMGWO:-Mw5Z9cQ06Kh1F7UMGWP:b-uvtpeg) ([raw file](https://github.com/ejourn-al/ejournal/blob/d99b2767bb6a54b50fd47c5f908b129cd1fd8df0/src/django/test/test_journal.py#L1226)):*
> ```Python
>         correct_grade = 2.51
> 
>         def grade(journal):
> ```

Should prob just ditch this block
___
*[src/django/test/test_journal_import_request.py, line 413 at r5](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-Mw5_16B6BwMI8Fl3GHl:-Mw5_16B6BwMI8Fl3GHm:b-xkkob4) ([raw file](https://github.com/ejourn-al/ejournal/blob/d99b2767bb6a54b50fd47c5f908b129cd1fd8df0/src/django/test/test_journal_import_request.py#L413)):*
> ```Python
>             assignment=jir.target.assignment).count()
>         target_journal = Journal.objects.annotate_stats().get(pk=target_journal.pk)
>         # pre_import_needs_marking = target_journal.needs_marking
> ```

Tagging
___
*[src/django/test/test_journal_import_request.py, line 531 at r5](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-Mw5Zl_FALTJrPZGkuYi:-Mw5Zl_FALTJrPZGkuYj:b11xyof) ([raw file](https://github.com/ejourn-al/ejournal/blob/d99b2767bb6a54b50fd47c5f908b129cd1fd8df0/src/django/test/test_journal_import_request.py#L531)):*
> ```Python
>             assignment=jir.target.assignment).count(), \
>             'Post import preset progress goal node count unaffected by the source preset progress goal node count'
>         # TODO: see why this is not working (6 == 5)
> ```

Tagging for now
___
*[src/django/test/test_teacher_entry.py, line 229 at r5](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-Mw5_uwL9CTM8Iebw8S9:-Mw5_uwL9CTM8Iebw8SA:bflmexz) ([raw file](https://github.com/ejourn-al/ejournal/blob/d99b2767bb6a54b50fd47c5f908b129cd1fd8df0/src/django/test/test_teacher_entry.py#L229)):*
> ```Python
> 
>         # Update grade for journal1, create entry to journal2 without grade.
>         pre_update_grade_entry_journal1 = updated_entry_journal1.get_active_assessment_feedback_form()
> ```

I am not sure where to draw the line on this, grade is not the same as an `afbf`. 

Not changing params frontend to match backend

This kind of stuff that will just come back later on
___
*[src/django/test/factory/entry.py, line 32 at r5](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-Mw5aMFV9wuqrxdmvm5L:-Mw5aMFV9wuqrxdmvm5M:b-jtvt1r) ([raw file](https://github.com/ejourn-al/ejournal/blob/7d6d0977e3ce8cd53efe2a47554b74a11b615c69/src/django/test/factory/entry.py#L32)):*
> ```Python
> 
> 
> def _grade(self, create, extracted, **kwargs):
> ```

I prob encountered 30+ instances of grades that were created via this syntax and are now created seperately. Thoughts?
___
*[src/django/test/factory/feedback_form.py, line 8 at r5](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-Mw5abpt2OkN2DUkkDYt:-Mw5abpt2OkN2DUkkDYu:bqob9xl) ([raw file](https://github.com/ejourn-al/ejournal/blob/d99b2767bb6a54b50fd47c5f908b129cd1fd8df0/src/django/test/factory/feedback_form.py#L8)):*
> ```Python
> 
> 
> class FeedbackFormFactory(factory.django.DjangoModelFactory):
> ```

AbstractFeedbackForm

abstract = True

Just match the backend (quick change)
___
*[src/django/VLE/serializers.py, line 774 at r5](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-Mw5aqJv0LzlIlNcWEVR:-Mw5aqJv0LzlIlNcWEVS:b-jenmf1) ([raw file](https://github.com/ejourn-al/ejournal/blob/d99b2767bb6a54b50fd47c5f908b129cd1fd8df0/src/django/VLE/serializers.py#L774)):*
> ```Python
>             return None
> 
>         aff = entry.get_active_assessment_feedback_form()
> ```

Let's stick to one abbreviation for the same model (you may decide whether its aff or afbf)
___
*[src/django/VLE/serializers.py, line 1170 at r5](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-Mw5b7Su4ZQDP4AOqqQA:-Mw5b7Su4ZQDP4AOqqQB:b-xkkob4) ([raw file](https://github.com/ejourn-al/ejournal/blob/d99b2767bb6a54b50fd47c5f908b129cd1fd8df0/src/django/VLE/serializers.py#L1170)):*
> ```Python
> 
>         all_j_stats = all_j.aggregate(
>             # TODO: this value is not used anywhere, for now this reduces computation time
> ```

Tagging
___
*[src/django/VLE/serializers.py, line 1939 at r5](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-Mw5bNSv5ilJFl6xhUfi:-Mw5bNSv5ilJFl6xhUfj:b27fede) ([raw file](https://github.com/ejourn-al/ejournal/blob/d99b2767bb6a54b50fd47c5f908b129cd1fd8df0/src/django/VLE/serializers.py#L1939)):*
> ```Python
> 
> 
> class FeedbackFormSerializer(ExtendedModelSerializer):
> ```

AbstractFeedbackFormSerializer
___
*[src/django/VLE/serializers.py, line 1996 at r5](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-Mw5brTY4Dpykn_AxjHg:-Mw5brTY4Dpykn_AxjHh:bqups90) ([raw file](https://github.com/ejourn-al/ejournal/blob/d99b2767bb6a54b50fd47c5f908b129cd1fd8df0/src/django/VLE/serializers.py#L1996)):*
> ```Python
>             'preset_peer_feedback_node_id',
>             'comment_count',
>             'reviewer_journal',
> ```

TODO select related (annotate grade as well)
Some performance tests for the serializers
___
*[src/django/VLE/serializers.py, line 2046 at r5](https://reviewable.io/reviews/ejourn-al/ejourna [...]

2022-02-17 09:16 UTC, Larspolo reviewed
> *[Reviewable](https://reviewable.io/reviews/ejourn-al/ejournal/1328)* status: 38 of 92 files reviewed, 20 unresolved discussions (waiting on @engelhamer, @Larspolo, and @mjvkeulen)

___
*[src/django/test/test_assignment.py, line 256 at r5](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-Mw5V5ql-0W_A-D5aCo3:-Mw5ukOI0v7xNg9HqUW5:b-lbw68r) ([raw file](https://github.com/ejourn-al/ejournal/blob/7d6d0977e3ce8cd53efe2a47554b74a11b615c69/src/django/test/test_assignment.py#L256)):*
<details><summary><i>Previously, mjvkeulen (Maarten van Keulen) wrote…</i></summary><blockquote>

[D] Do you care for the old deep syntax? (Factory.entry(grade__grade=x)
</blockquote></details>

Feel indifferent. Downside of the syntax is that its no longer accurate as its not attached to the entry
___
*[src/django/test/test_category.py, line 304 at r5](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-Mw5Vp5kABvuhqCjaxTK:-Mw5vKvo7DB7Ui_HzhKR:b-1xutps) ([raw file](https://github.com/ejourn-al/ejournal/blob/d99b2767bb6a54b50fd47c5f908b129cd1fd8df0/src/django/test/test_category.py#L304)):*
<details><summary><i>Previously, mjvkeulen (Maarten van Keulen) wrote…</i></summary><blockquote>

Once a teacher starts assessment (still draft) a student should be able to continue editing the entry (otherwise it's confusing, after all the student has no assessment indication yet).
</blockquote></details>

This was already the functionality, fixed the test accordingly
___
*[src/django/test/test_gradepassback.py, line 173 at r5](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-Mw5YOKWCrd7NFfggnlk:-Mw5vT7e15CiMZNIyrkZ:b-9pr0gx) ([raw file](https://github.com/ejourn-al/ejournal/blob/d99b2767bb6a54b50fd47c5f908b129cd1fd8df0/src/django/test/test_gradepassback.py#L173)):*
<details><summary><i>Previously, mjvkeulen (Maarten van Keulen) wrote…</i></summary><blockquote>

Entry.NEEDS_SENDING seems unrelated to grade passback?
</blockquote></details>

More for the TODO that needs to be send to the teacher, but TBH, I think we can fully remove the VLE coupling, which will be the case in the upcoming LTI 1.3 PR
___
*[src/django/test/test_journal.py, line 1226 at r5](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-Mw5Z9cQ06Kh1F7UMGWO:-Mw5vh1gE-LLAIEP7Hmd:bb6un1j) ([raw file](https://github.com/ejourn-al/ejournal/blob/d99b2767bb6a54b50fd47c5f908b129cd1fd8df0/src/django/test/test_journal.py#L1226)):*
<details><summary><i>Previously, mjvkeulen (Maarten van Keulen) wrote…</i></summary><blockquote>

Should prob just ditch this block
</blockquote></details>

Done
___
*[src/django/test/test_teacher_entry.py, line 229 at r5](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-Mw5_uwL9CTM8Iebw8S9:-Mw5vtqz0EBkaZF5v6ow:b95aoqk) ([raw file](https://github.com/ejourn-al/ejournal/blob/d99b2767bb6a54b50fd47c5f908b129cd1fd8df0/src/django/test/test_teacher_entry.py#L229)):*
<details><summary><i>Previously, mjvkeulen (Maarten van Keulen) wrote…</i></summary><blockquote>

I am not sure where to draw the line on this, grade is not the same as an `afbf`. 

Not changing params frontend to match backend

This kind of stuff that will just come back later on
</blockquote></details>

Feel free to change it, I try to do as much as possible in the short time that is given. Shortcuts are needed because of that
___
*[src/django/test/factory/entry.py, line 32 at r5](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-Mw5aMFV9wuqrxdmvm5L:-Mw5w4Dt1HidU9UQjHw-:b-3z8e6n) ([raw file](https://github.com/ejourn-al/ejournal/blob/7d6d0977e3ce8cd53efe2a47554b74a11b615c69/src/django/test/factory/entry.py#L32)):*
<details><summary><i>Previously, mjvkeulen (Maarten van Keulen) wrote…</i></summary><blockquote>

I prob encountered 30+ instances of grades that were created via this syntax and are now created seperately. Thoughts?
</blockquote></details>

See other thread where (I think) you asked the same question
___
*[src/django/test/factory/feedback_form.py, line 8 at r5](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-Mw5abpt2OkN2DUkkDYt:-Mw5wUre3az7tiSBTRtk:b-896fix) ([raw file](https://github.com/ejourn-al/ejournal/blob/d99b2767bb6a54b50fd47c5f908b129cd1fd8df0/src/django/test/factory/feedback_form.py#L8)):*
<details><summary><i>Previously, mjvkeulen (Maarten van Keulen) wrote…</i></summary><blockquote>

AbstractFeedbackForm

abstract = True

Just match the backend (quick change)
</blockquote></details>

Done.
___
*[src/django/VLE/serializers.py, line 774 at r5](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-Mw5aqJv0LzlIlNcWEVR:-Mw5wnS1CvlSFAxdqQJ9:bsn5n13) ([raw file](https://github.com/ejourn-al/ejournal/blob/d99b2767bb6a54b50fd47c5f908b129cd1fd8df0/src/django/VLE/serializers.py#L774)):*
<details><summary><i>Previously, mjvkeulen (Maarten van Keulen) wrote…</i></summary><blockquote>

Let's stick to one abbreviation for the same model (you may decide whether its aff or afbf)
</blockquote></details>

Removed both abbrevs
___
*[src/django/VLE/serializers.py, line 1170 at r5](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-Mw5b7Su4ZQDP4AOqqQA:-Mw5wsDO-7H5CGkvyCHk:bnq0324) ([raw file](https://github.com/ejourn-al/ejournal/blob/d99b2767bb6a54b50fd47c5f908b129cd1fd8df0/src/django/VLE/serializers.py#L1170)):*
<details><summary><i>Previously, mjvkeulen (Maarten van Keulen) wrote…</i></summary><blockquote>

Tagging
</blockquote></details>

Made an issue https://ejournal.atlassian.net/jira/software/projects/EJ/boards/1?selectedIssue=EJ-1470
___
*[src/django/VLE/serializers.py, line 1939 at r5](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-Mw5bNSv5ilJFl6xhUfi:-Mw5x7WH36MBFsbUhXqh:b-896fix) ([raw file](https://github.com/ejourn-al/ejournal/blob/d99b2767bb6a54b50fd47c5f908b129cd1fd8df0/src/django/VLE/serializers.py#L1939)):*
<details><summary><i>Previously, mjvkeulen (Maarten van Keulen) wrote…</i></summary><blockquote>

AbstractFeedbackFormSerializer
</blockquote></details>

Done.
___
*[src/django/VLE/serializers.py, line 1996 at r5](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-Mw5brTY4Dpykn_AxjHg:-Mw5x9Sn5nr0BTOvOSI7:b-jrk4k) ([raw file](https://github.com/ejourn-al/ejournal/blob/d99b2767bb6a54b50fd47c5f908b129cd1fd8df0/src/django/VLE/serializers.py#L1996)):*
<details><summary><i>Previously, mjvkeulen (Maarten van Keulen) wrote…</i></summary><blockquote>

TODO select related (annotate grade as well)
Some performance tests for the serializers
</blockquote></details>

If you can do this, that would be great
___
*[src/django/VLE/serializers.py, line 2046 at r5](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-Mw5c0UlB_GVXhz9Z6i6:-Mw5xBxw7-rxxk83sdOw:b-89a4l7) ([raw file](https://github.com/ejourn-al/ejournal/blob/d99b2767bb6a54b50fd47c5f908b129cd1fd8df0/src/django/VLE/serializers.py#L2046)):*
<details><summary><i>Previously, mjvkeulen (Maarten van Keulen) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Ditto
___
*[src/django/VLE/models/journal.py, line 183 at r6](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-Mw5dM8F82GzNGvzq-n6:-Mw5xKOx3b0pPaU2JHQk:b-5lvpyl) ([raw file](https://github.com/ejourn-al/ejournal/blob/a0b852102a242ab386307c979de7caae3d66384c/src/django/VLE/models/journal.py#L183)):*
<details><summary><i>Previously, mjvkeulen (Maarten van Keulen) wrote…</i></summary><blockquote>

This should be a float field right? (Prob needs a test as well then)
</blockquote></details>

Changed to floatfield and added TODO to add test
___
*[src/django/VLE/models/rubric_submission.py, line 53 at r6](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-Mw5eDBqDZSvDbcG3Uw4:-Mw5xWod0xDkeeKA7tiJ:b-896fix) ([raw file](https://github.com/ejourn-al/ejournal/blob/a0b852102a242ab386307c979de7caae3d66384c/src/django/VLE/models/rubric_submission.py#L53)):*
<details><summary><i>Previously, mjvkeulen (Maarten van Keulen) wrote…</i></summary><blockquote>

Can't points be null? (None + Float = TypeError)
</blockquote></details>

Done.
___
*[src/django/VLE/models/journal_conten [...]

2022-02-17 16:50 UTC, mjvkeulen requested changes
> Reviewed 24 of 88 files at r1, 2 of 22 files at r3, 2 of 3 files at r6, 1 of 16 files at r7, 3 of 10 files at r8, 5 of 5 files at r9, 5 of 6 files at r10, 2 of 5 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ejourn-al/ejournal/1328)* status: 86 of 100 files reviewed, 55 unresolved discussions (waiting on @engelhamer, @Larspolo, and @mjvkeulen)

___
*[src/django/VLE/views/feedback_form.py, line 192 at r10](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-Mw7UF8AA54dViS4E98y:-Mw7UF8AA54dViS4E98z:b-6erd5n) ([raw file](https://github.com/ejourn-al/ejournal/blob/ca7e061d7eccc0678f0ec610392d82e9ce111319/src/django/VLE/views/feedback_form.py#L192)):*
> ```Python
> 
> 
> class AssessmentFeedbackFormView(viewsets.ViewSet):
> ```

Similarly, thoughts on keeping view sets in their own file? @engelhamer  @larspolo 
___
*[src/django/VLE/views/feedback_form.py, line 225 at r10](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-Mw7WVPlDcPbTWHYLg1u:-Mw7WVPlDcPbTWHYLg1v:b2nhp3p) ([raw file](https://github.com/ejourn-al/ejournal/blob/ca7e061d7eccc0678f0ec610392d82e9ce111319/src/django/VLE/views/feedback_form.py#L225)):*
> ```Python
> 
>     def retrieve(self, request, pk):
>         # TODO: add test for this function
> ```

Tag
___
*[src/django/VLE/views/feedback_form.py, line 264 at r10](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-Mw7WsHw1YZ4rxOUH1D_:-Mw7WsHw1YZ4rxOUH1Da:b2nhp3p) ([raw file](https://github.com/ejourn-al/ejournal/blob/ca7e061d7eccc0678f0ec610392d82e9ce111319/src/django/VLE/views/feedback_form.py#L264)):*
> ```Python
> 
>         rubric_submission: Union[RubricSubmission, None] = None
>         # TODO: add test with rubric
> ```

Tag
___
*[src/django/VLE/views/feedback_form.py, line 268 at r10](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-Mw7Wt7ND3nMmgSQRum5:-Mw7Wt7ND3nMmgSQRum6:b2nhp3p) ([raw file](https://github.com/ejourn-al/ejournal/blob/ca7e061d7eccc0678f0ec610392d82e9ce111319/src/django/VLE/views/feedback_form.py#L268)):*
> ```Python
>             rubric_submission = RubricSubmission.objects.get(pk=rubric_submission_id)
> 
>         # TODO: add test < 0 points
> ```

Tag
___
*[src/django/VLE/views/feedback_form.py, line 269 at r10](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-Mw7WwkKD9aUQSt8EeG1:-Mw7WwkKD9aUQSt8EeG2:bc79su8) ([raw file](https://github.com/ejourn-al/ejournal/blob/ca7e061d7eccc0678f0ec610392d82e9ce111319/src/django/VLE/views/feedback_form.py#L269)):*
> ```Python
> 
>         # TODO: add test < 0 points
>         if points is not None and points < 0:
> ```

Is this not part of AssessmentFeedbackForm.validate?
___
*[src/django/VLE/views/feedback_form.py, line 272 at r10](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-Mw7XUcU2LV4TpXFqSQy:-Mw7XUcU2LV4TpXFqSQz:b-t63kjz) ([raw file](https://github.com/ejourn-al/ejournal/blob/ca7e061d7eccc0678f0ec610392d82e9ce111319/src/django/VLE/views/feedback_form.py#L272)):*
> ```Python
>             return response.bad_request('Grade must be greater than or equal to zero.')
> 
>         new_feedback_form = AssessmentFeedbackForm.objects.create(
> ```

Block should be atomic with import rubric submission
___
*[src/django/VLE/views/feedback_form.py, line 296 at r10](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-Mw7XYJ-60Ct8z_Twg2L:-Mw7XYJ-60Ct8z_Twg2M:b2nhp3p) ([raw file](https://github.com/ejourn-al/ejournal/blob/ca7e061d7eccc0678f0ec610392d82e9ce111319/src/django/VLE/views/feedback_form.py#L296)):*
> ```Python
> 
>     def partial_update(self, request, pk):
>         # TODO: add test for this function, also make sure only feedback & rubric can be updated
> ```

Tag
___
*[src/django/VLE/views/feedback_form.py, line 300 at r10](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-Mw7Xc0cAQt8bTbv46aW:-Mw7Xc0cAQt8bTbv46aX:blgsl8l) ([raw file](https://github.com/ejourn-al/ejournal/blob/ca7e061d7eccc0678f0ec610392d82e9ce111319/src/django/VLE/views/feedback_form.py#L300)):*
> ```Python
> 
>         feedback_form.check_editable_by(request.user, fields=request.data)
> ```

Missing .validate
___
*[src/django/VLE/views/rubric_submission.py, line 64 at r10](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-Mw7Y2S23U9WmIG7MPhb:-Mw7Y2S35vtsgT2ll3sZ:b2nhp3p) ([raw file](https://github.com/ejourn-al/ejournal/blob/ca7e061d7eccc0678f0ec610392d82e9ce111319/src/django/VLE/views/rubric_submission.py#L64)):*
> ```Python
>             if not rubric:
>                 raise VLEBadRequest('This feedback form does not allow for a rubric submission.')
>         # TODO: test this
> ```

Tag
___
*[src/django/VLE/views/rubric_submission.py, line 69 at r10](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-Mw7Yj0n4lJugwdZyQED:-Mw7Yj0n4lJugwdZyQEE:b-c17k4u) ([raw file](https://github.com/ejourn-al/ejournal/blob/ca7e061d7eccc0678f0ec610392d82e9ce111319/src/django/VLE/views/rubric_submission.py#L69)):*
> ```Python
>             rubric = context.journal.assignment.rubrics.select_related(
>                 'assignment').get(pk=rubric_id)
>             if not rubric:
> ```

Can remove this block
___
*[src/django/VLE/views/teacher_entry.py, line 227 at r10](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-Mw7YteJ6Mml4xoYLHOs:-Mw7YteJ6Mml4xoYLHOt:b2nhp3p) ([raw file](https://github.com/ejourn-al/ejournal/blob/ca7e061d7eccc0678f0ec610392d82e9ce111319/src/django/VLE/views/teacher_entry.py#L227)):*
> ```Python
> 
>         # TODO: check if this is outdated, what about last_submission / first_submission?
>         # Last edited is set on creation, even when specified during initialization.
> ```

Tag
___
*[src/vue/src/api/auth.js, line 11 at r10](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-Mw7Z1iM5lwyRl05YL22:-Mw7Z1iM5lwyRl05YL23:b-vseld1) ([raw file](https://github.com/ejourn-al/ejournal/blob/ca7e061d7eccc0678f0ec610392d82e9ce111319/src/vue/src/api/auth.js#L11)):*
> ```JavaScript
> const ERRORS_TO_REDIRECT = new Set([
>     // statuses.FORBIDDEN,
>     // statuses.NOT_FOUND,
> ```

Q) What triggered these changes?
___
*[src/vue/src/store/modules/analytics.js, line 7 at r10](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-Mw7_Fll8CjrwjFlxK_8:-Mw7_Fll8CjrwjFlxK_9:b2nhp3p) ([raw file](https://github.com/ejourn-al/ejournal/blob/ca7e061d7eccc0678f0ec610392d82e9ce111319/src/vue/src/store/modules/analytics.js#L7)):*
> ```JavaScript
>         return auth.get('entry_analytics', { assignment_id: aID }, connArgs)
>             .then((response) => {
>                 // TODO: this currently does not contain the grades of non-entry submissions
> ```

Tag
___
*[src/vue/src/store/modules/assessmentFeedbackForm.js, line 127 at r10](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-Mw7_M0V5m7Wd0nmcNKY:-Mw7_M0V5m7Wd0nmcNKZ:b2nhp3p) ([raw file](https://github.com/ejourn-al/ejournal/blob/ca7e061d7eccc0678f0ec610392d82e9ce111319/src/vue/src/store/modules/assessmentFeedbackForm.js#L127)):*
> ```JavaScript
>         const { node, journal } = getCurrentNodeAndJournal(context.rootGetters)
>         const fbfID = node.entry.assessment_feedback_form_id
>         // const feedbackForm = getAllFeedbackForms(context.state, { node, journal })
> ```

Tag
___
*[src/vue/src/store/modules/assessmentFeedbackForm.js, line 198 at r10](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-Mw7_OPM6FslReU9JERB:-Mw7_OPM6FslReU9JERC:b2nhp3p) ([raw file](https://github.com/ejourn-al/ejournal/blob/ca7e061d7eccc0678f0ec610392d82e9ce111319/src/vue/src/store/modules/assessmentFeedbackForm.js#L198)):*
> ```JavaScript
>     },
>     publishAllAssignmentGrades (context, { aID, connArgs = auth.DEFAULT_CONN_ARGS }) {
>         // TODO: empty the store
> ```

Tag
___
*[src/vue/src/views/Analytics.vue, line 442 at r10](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-Mw7_cF6A26ebNABeYTK:-Mw7_cF6A26ebNABeYTL:bc074iy) ([raw file](https://github.com/ejourn-al/ejournal/blob/ca7e061d7eccc0678f0ec610392d82e9ce111319/src/vue/src/views/Analytics.vue#L442)):*
> [...]

2022-02-17 17:39 UTC, Larspolo reviewed
> *[Reviewable](https://reviewable.io/reviews/ejourn-al/ejournal/1328)* status: 86 of 100 files reviewed, 55 unresolved discussions (waiting on @engelhamer, @Larspolo, and @mjvkeulen)

___
*[src/django/VLE/serializers.py, line 1170 at r5](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-Mw5b7Su4ZQDP4AOqqQA:-Mw7fWIB-5feWjTYHBbn:b-pegb7j) ([raw file](https://github.com/ejourn-al/ejournal/blob/d99b2767bb6a54b50fd47c5f908b129cd1fd8df0/src/django/VLE/serializers.py#L1170)):*
> EJ-1470
Tagged with label
___
*[src/django/VLE/models/journal.py, line 175 at r10](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-Mw6rK1TAz6w95ZGMFPQ:-Mw7ffbw9Rw8mP1ySC2c:b-sraom4) ([raw file](https://github.com/ejourn-al/ejournal/blob/ca7e061d7eccc0678f0ec610392d82e9ce111319/src/django/VLE/models/journal.py#L175)):*
<details><summary><i>Previously, mjvkeulen (Maarten van Keulen) wrote…</i></summary><blockquote>

Tag
</blockquote></details>

What are you tagging (blocking)?
___
*[src/django/VLE/models/journal.py, line 184 at r10](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-Mw6rMF_5iF4IAsopaNR:-Mw7fihaAQV9RIY1fz2h:b-sraom4) ([raw file](https://github.com/ejourn-al/ejournal/blob/ca7e061d7eccc0678f0ec610392d82e9ce111319/src/django/VLE/models/journal.py#L184)):*
<details><summary><i>Previously, mjvkeulen (Maarten van Keulen) wrote…</i></summary><blockquote>

Tag
</blockquote></details>

What are you tagging (blocking)?
___
*[src/django/VLE/models/journal_content/feedback_form.py, line 418 at r10](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-Mw6sImDBlyZkpF39XxA:-Mw7fpJ2Cy3pDSZRKNlh:bmha136) ([raw file](https://github.com/ejourn-al/ejournal/blob/ca7e061d7eccc0678f0ec610392d82e9ce111319/src/django/VLE/models/journal_content/feedback_form.py#L418)):*
<details><summary><i>Previously, mjvkeulen (Maarten van Keulen) wrote…</i></summary><blockquote>

I would like to split the models in this file into their respective files, I spent enough time failing to find the models via file search already
</blockquote></details>

Within a folder again?
___
*[src/django/VLE/models/journal_content/feedback_form.py, line 419 at r10](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-Mw6s7p97z2wLZS7s-FE:-Mw7fuPmB4qDgdAK2O1n:b20kbmx) ([raw file](https://github.com/ejourn-al/ejournal/blob/ca7e061d7eccc0678f0ec610392d82e9ce111319/src/django/VLE/models/journal_content/feedback_form.py#L419)):*
<details><summary><i>Previously, mjvkeulen (Maarten van Keulen) wrote…</i></summary><blockquote>

I guess issue to rename to NodeFeedbackForm and overall assessment to JournalFeedbackForm?
</blockquote></details>

Yeah, not satisfied with the naming schema yet, but @engelhamer had another take on this, as its still an open discussion, I would like to move this to a later PR. You have a confenient "renameModel" function in the migrations
___
*[src/django/VLE/models/journal_content/feedback_form.py, line 444 at r10](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-Mw6t0f09jhmgO8j2iHa:-Mw7gS2P1mPLur9kYoEi:bmjimhm) ([raw file](https://github.com/ejourn-al/ejournal/blob/ca7e061d7eccc0678f0ec610392d82e9ce111319/src/django/VLE/models/journal_content/feedback_form.py#L444)):*
<details><summary><i>Previously, mjvkeulen (Maarten van Keulen) wrote…</i></summary><blockquote>

So technical debt issue to sync backend and frontend properties?
</blockquote></details>

https://ejournal.atlassian.net/browse/EJ-1471
___
*[src/django/VLE/models/journal_content/feedback_form.py, line 445 at r10](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-Mw6suM55XHQLY0VM_Dm:-Mw7gVB-2BGcB0wlH929:b-8luy6m) ([raw file](https://github.com/ejourn-al/ejournal/blob/ca7e061d7eccc0678f0ec610392d82e9ce111319/src/django/VLE/models/journal_content/feedback_form.py#L445)):*
<details><summary><i>Previously, mjvkeulen (Maarten van Keulen) wrote…</i></summary><blockquote>

I always wondered if using F('reviewer_id') would make any difference
</blockquote></details>

no clue either
___
*[src/django/VLE/models/journal_content/feedback_form.py, line 479 at r10](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-Mw6tax24EJYHVIuxfnP:-Mw7g_oACKNwGKXutadj:bfc6d8c) ([raw file](https://github.com/ejourn-al/ejournal/blob/ca7e061d7eccc0678f0ec610392d82e9ce111319/src/django/VLE/models/journal_content/feedback_form.py#L479)):*
<details><summary><i>Previously, mjvkeulen (Maarten van Keulen) wrote…</i></summary><blockquote>

You often use filter_on_x (e.g. filter_on_journal). Why from_x now? Would this not be `filter_on_journals`?
</blockquote></details>

Yeah, this was imported form the GradeQuerySet, but it was never used anyway, so its removed now
___
*[src/django/VLE/models/journal_content/feedback_form.py, line 485 at r10](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-Mw6tyNl4fJXKeKCk1Zi:-Mw7gw-9B_2qfM0JUWKl:b32w12) ([raw file](https://github.com/ejourn-al/ejournal/blob/ca7e061d7eccc0678f0ec610392d82e9ce111319/src/django/VLE/models/journal_content/feedback_form.py#L485)):*
<details><summary><i>Previously, mjvkeulen (Maarten van Keulen) wrote…</i></summary><blockquote>

Is this tested for multiple criterion submissions? E.g. A rubric where only the last criterion submission has received points.
</blockquote></details>

No
___
*[src/django/VLE/models/journal_content/feedback_form.py, line 486 at r10](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-Mw6uAUY2m2ax_DHzOOY:-Mw7h6Ra1N9pL-4lGxNj:bqoxcgs) ([raw file](https://github.com/ejourn-al/ejournal/blob/ca7e061d7eccc0678f0ec610392d82e9ce111319/src/django/VLE/models/journal_content/feedback_form.py#L486)):*
<details><summary><i>Previously, mjvkeulen (Maarten van Keulen) wrote…</i></summary><blockquote>

Why can feedback be null? Especially since this query shows that `''` and `null` both work as no feedback
</blockquote></details>

If you want to change that, you may go ahead
___
*[src/django/VLE/models/journal_content/feedback_form.py, line 490 at r10](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-Mw6zNJCBPNlcu4dH9tR:-Mw7hGCk72-NzIe7ow0E:b89ur87) ([raw file](https://github.com/ejourn-al/ejournal/blob/ca7e061d7eccc0678f0ec610392d82e9ce111319/src/django/VLE/models/journal_content/feedback_form.py#L490)):*
<details><summary><i>Previously, mjvkeulen (Maarten van Keulen) wrote…</i></summary><blockquote>

It confused me that this makes use of self as an argument but does NOT affect the self queryset. 

Does it not make sense to move this to function on the model? Which takes the queryset of which to deactivate older feedback forms as an argument?
</blockquote></details>

Same goes for `.activate` and `.publish`. I think it makes sense to have it in the queryset. Like `bulk_update`, which doesnt return a queryset either. I get that you are confused because its a new thing, but once you are used to it, it makes more sense to have it inside the queryset as it is specifically for a queryset. Modal would then be a static function taking the queryset as an argument
___
*[src/django/VLE/models/journal_content/feedback_form.py, line 507 at r10](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-Mw6xOs82GI3awqxyncT:-Mw7hbQD0YkNo5-lF3V1:b-6y7i5d) ([raw file](https://github.com/ejourn-al/ejournal/blob/ca7e061d7eccc0678f0ec610392d82e9ce111319/src/django/VLE/models/journal_content/feedback_form.py#L507)):*
<details><summary><i>Previously, mjvkeulen (Maarten van Keulen) wrote…</i></summary><blockquote>

Tag
</blockquote></details>

Not sure what you are tagging here
___
*[src/django/VLE/models/journal_content/feedback_form.py, line 535 at r10](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-Mw6zuEsCTTN-XSfwwpJ:-Mw7hsEN4lQAOuguSIzA:bga8ess) ([raw file](https://github.com/ejourn-al/ejournal/blob/ca7e061d7eccc0678f0ec610392d82e9ce111319/src/django/VLE/models/journal_content/feedback_form.py#L535)):*
<details><summary><i>Previously, mjvkeulen (Maarten van Keulen) wrote…</i></summary><blockquote>

AssessmentFeedbackForm.deactivate_older(new_qry=self) (or something among [...]

2022-02-17 22:35 UTC, engelhamer reviewed
> *[Reviewable](https://reviewable.io/reviews/ejourn-al/ejournal/1328)* status: 77 of 105 files reviewed, 55 unresolved discussions (waiting on @engelhamer, @Larspolo, and @mjvkeulen)

___
*[src/django/VLE/models/journal_content/feedback_form.py, line 419 at r10](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-Mw6s7p97z2wLZS7s-FE:-Mw8ogtb0Ra71BfL92oL:b-fk9z7t) ([raw file](https://github.com/ejourn-al/ejournal/blob/ca7e061d7eccc0678f0ec610392d82e9ce111319/src/django/VLE/models/journal_content/feedback_form.py#L419)):*
<details><summary><i>Previously, Larspolo (Lars) wrote…</i></summary><blockquote>

Yeah, not satisfied with the naming schema yet, but @engelhamer had another take on this, as its still an open discussion, I would like to move this to a later PR. You have a confenient "renameModel" function in the migrations
</blockquote></details>

Especially the feedback form / assessment / journal naming is confusing in code, but at least not for the users,
Make issue for coming up with sound, distinguishable names.
___
*[src/django/VLE/utils/import_utils.py, line 42 at r10](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-Mw7IybP3nWfim2OTaJV:-Mw8oYzL8gNEn8xOtSgK:b-pxoob4) ([raw file](https://github.com/ejourn-al/ejournal/blob/ca7e061d7eccc0678f0ec610392d82e9ce111319/src/django/VLE/utils/import_utils.py#L42)):*
<details><summary><i>Previously, mjvkeulen (Maarten van Keulen) wrote…</i></summary><blockquote>

Frustrating, so if the action includes the grade, we effectively exclude context on copy. This is definitely an issue. @engelhamer opinion?
</blockquote></details>

Issue for later, not a problem in the short term
___
*[src/django/VLE/views/feedback_form.py, line 192 at r10](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-Mw7UF8AA54dViS4E98y:-Mw8obbdCAskQdIetQn6:b4yv052) ([raw file](https://github.com/ejourn-al/ejournal/blob/ca7e061d7eccc0678f0ec610392d82e9ce111319/src/django/VLE/views/feedback_form.py#L192)):*
<details><summary><i>Previously, mjvkeulen (Maarten van Keulen) wrote…</i></summary><blockquote>

Similarly, thoughts on keeping view sets in their own file? @engelhamer  @larspolo 
</blockquote></details>

Not strictly needed in my opinion


<!-- Sent from Reviewable.io -->

2022-02-18 16:17 UTC, mjvkeulen reviewed
> Reviewed 1 of 7 files at r26, 2 of 10 files at r31.
> *[Reviewable](https://reviewable.io/reviews/ejourn-al/ejournal/1328)* status: 69 of 112 files reviewed, 39 unresolved discussions (waiting on @engelhamer, @Larspolo, and @mjvkeulen)

___
*[src/django/test/test_feedback_form.py, line 672 at r3](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-MwC_T8H46gHFuO0bBo8:-MwC_T8I-UrXOo3GjtF5:b-gsz1ni) ([raw file](https://github.com/ejourn-al/ejournal/blob/300d7656907686485952423c5b6bbf4120d9ec20/src/django/test/test_feedback_form.py#L672)):*
> ```Python
>         )
> 
>         user_serializer_mock.assert_called_with(
> ```

What changed?
___
*[src/django/test/test_grade.py, line 25 at r5](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-Mw5XlpqDDDO7MjW9VgH:-MwCbpPcEN2zfn_eebHc:budy9ju) ([raw file](https://github.com/ejourn-al/ejournal/blob/d99b2767bb6a54b50fd47c5f908b129cd1fd8df0/src/django/test/test_grade.py#L25)):*
<details><summary><i>Previously, Larspolo (Lars) wrote…</i></summary><blockquote>

Added the factory, but cant be bothered changing the existing code
</blockquote></details>

Since it makes no sense to add the factory, but not refactor I just did the refactor.


<!-- Sent from Reviewable.io -->

2022-02-18 16:33 UTC, mjvkeulen reviewed
> Reviewed 1 of 9 files at r25, 3 of 10 files at r27, 1 of 12 files at r28, 5 of 15 files at r29, 3 of 10 files at r31.
> *[Reviewable](https://reviewable.io/reviews/ejourn-al/ejournal/1328)* status: 78 of 112 files reviewed, 34 unresolved discussions (waiting on @engelhamer, @Larspolo, and @mjvkeulen)



<!-- Sent from Reviewable.io -->

2022-02-18 16:41 UTC, Larspolo reviewed
> *[Reviewable](https://reviewable.io/reviews/ejourn-al/ejournal/1328)* status: 78 of 112 files reviewed, 34 unresolved discussions (waiting on @engelhamer, @Larspolo, and @mjvkeulen)

___
*[src/django/test/test_feedback_form.py, line 672 at r3](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-MwC_T8H46gHFuO0bBo8:-MwChB9Y05aSQAFUwl7G:b-i3wrrv) ([raw file](https://github.com/ejourn-al/ejournal/blob/300d7656907686485952423c5b6bbf4120d9ec20/src/django/test/test_feedback_form.py#L672)):*
<details><summary><i>Previously, mjvkeulen (Maarten van Keulen) wrote…</i></summary><blockquote>

What changed?
</blockquote></details>

Removed the reviewer from the peer feedback node serializer. Because that only even will be the reviewer_journal
___
*[src/django/VLE/models/notification.py, line 175 at r6](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-Mw5drK-Bi2cDG5S8cIb:-MwBqH9i3IWGzFxDG6uo:b-896fix) ([raw file](https://github.com/ejourn-al/ejournal/blob/a0b852102a242ab386307c979de7caae3d66384c/src/django/VLE/models/notification.py#L175)):*
<details><summary><i>Previously, mjvkeulen (Maarten van Keulen) wrote…</i></summary><blockquote>

Lets not skip this in our migration of the old data
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-18 16:56 UTC, mjvkeulen reviewed
> Reviewed 2 of 9 files at r25, 2 of 5 files at r30.
> *[Reviewable](https://reviewable.io/reviews/ejourn-al/ejournal/1328)* status: 104 of 112 files reviewed, 7 unresolved discussions (waiting on @Larspolo and @mjvkeulen)

___
*[src/vue/src/components/journal/JournalFeedbackForm.vue, line 413 at r31](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-MwCjm8yAipcee2lYFob:-MwCjm8yAipcee2lYFoc:b-ojvcxk) ([raw file](https://github.com/ejourn-al/ejournal/blob/252ce7805f383336a0b2539ec51a88a915982c98/src/vue/src/components/journal/JournalFeedbackForm.vue#L413)):*
> ```Vue
>             return 1
> 
>             // this.createRubricSubmission({
> ```

Left over


<!-- Sent from Reviewable.io -->

2022-02-18 17:59 UTC, Larspolo reviewed
> *[Reviewable](https://reviewable.io/reviews/ejourn-al/ejournal/1328)* status: 111 of 112 files reviewed, 15 unresolved discussions (waiting on @engelhamer, @Larspolo, and @mjvkeulen)

___
*[src/django/test/test_grade.py, line 177 at r30](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-MwCWNOu1QzNwieYuCX2:-MwCyHMw3DBUAML9y316:b-896fix) ([raw file](https://github.com/ejourn-al/ejournal/blob/35eb66c3e8ea27ee22fc07e95996fdc259676c36/src/django/test/test_grade.py#L177)):*
<details><summary><i>Previously, engelhamer (Engel Hamer) wrote…</i></summary><blockquote>

Add another case to this where there is a draft? (should not be included in the journal grade)
</blockquote></details>

Done.
___
*[src/django/test/test_teacher_entry.py, line 229 at r5](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-Mw5_uwL9CTM8Iebw8S9:-MwCyOQq7BXp8-uaQPyW:b-dimqvl) ([raw file](https://github.com/ejourn-al/ejournal/blob/d99b2767bb6a54b50fd47c5f908b129cd1fd8df0/src/django/test/test_teacher_entry.py#L229)):*
<details><summary><i>Previously, engelhamer (Engel Hamer) wrote…</i></summary><blockquote>

So `pre_update_grade` would need to be `pre_update_assessment` or something? Is that what this comment about?
</blockquote></details>

Think so
___
*[src/django/VLE/migrations/0113_replace_grade_with_feedback_form_migrate.py, line 6 at r30](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-MwCeBLuByQQ0yc2cFNm:-MwCyPj034XJllmT2zON:bgvvf2b) ([raw file](https://github.com/ejourn-al/ejournal/blob/35eb66c3e8ea27ee22fc07e95996fdc259676c36/src/django/VLE/migrations/0113_replace_grade_with_feedback_form_migrate.py#L6)):*
<details><summary><i>Previously, engelhamer (Engel Hamer) wrote…</i></summary><blockquote>

What about the `vle_coupling`?
</blockquote></details>

Is removed, no longer needed (already since the introduction of the LMS_grade
___
*[src/django/VLE/models/journal.py, line 166 at r30](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-MwCeez70umzuWZejiwm:-MwCyVAzC3HHLFoBHyPA:b5nvbj6) ([raw file](https://github.com/ejourn-al/ejournal/blob/35eb66c3e8ea27ee22fc07e95996fdc259676c36/src/django/VLE/models/journal.py#L166)):*
<details><summary><i>Previously, engelhamer (Engel Hamer) wrote…</i></summary><blockquote>

What is wrong with `entry_points`? Maybe add `_sum` to that?

Also: is this still only about entries, or also about peer feedback participation scores?
</blockquote></details>

Can be on non entries. Peer feedback scores are included. Not for the marking needed though
___
*[src/django/VLE/models/rubric_submission.py, line 61 at r21](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-MwAicyNDPqQbhNcQwSi:-MwCydjm4jxK9WtVgT1g:b-521fmz) ([raw file](https://github.com/ejourn-al/ejournal/blob/5966dc533c530e8340ccb6b2a8431046cf7243d4/src/django/VLE/models/rubric_submission.py#L61)):*
<details><summary><i>Previously, engelhamer (Engel Hamer) wrote…</i></summary><blockquote>

Why order by is active?
</blockquote></details>

To get the latest is_active feedback form that is attached to the rubric. It should be the same though, but in case it is ever not
___
*[src/vue/src/components/journal/JournalDetails.vue, line 84 at r30](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-MwCrUHDE4v_Q5c2vE9g:-MwCypLr7CDRdlAs4IzK:bsfcaky) ([raw file](https://github.com/ejourn-al/ejournal/blob/35eb66c3e8ea27ee22fc07e95996fdc259676c36/src/vue/src/components/journal/JournalDetails.vue#L84)):*
<details><summary><i>Previously, engelhamer (Engel Hamer) wrote…</i></summary><blockquote>

![image.png](https://files.reviewableusercontent.io/images/reviewable/39912581/5GQhZuT1rkASAo66IlKRzqk2/image.png)

This button is not working very well. Displayed always even if no feedback is there to publish.
</blockquote></details>

Was already the case, see teams
___
*[src/vue/src/store/modules/assessmentFeedbackForm.js, line 136 at r30](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-MwCtZv77PoQN0tMw6Gl:-MwCyuTiBwrw1BwgQy4K:bfs8zjs) ([raw file](https://github.com/ejourn-al/ejournal/blob/35eb66c3e8ea27ee22fc07e95996fdc259676c36/src/vue/src/store/modules/assessmentFeedbackForm.js#L136)):*
<details><summary><i>Previously, engelhamer (Engel Hamer) wrote…</i></summary><blockquote>

Would it not make sense to include an action for 'finalising the feedback form' as is now done in `JournalFeedbackForm`? Then we could also get rid of the `$parent.$parent.$parent.$parent.$ref.$ref.$ref` (no joke..)

Seems like this is a good moment for it, since the store module is introduced just now.
</blockquote></details>

Would be nice, you may add it if you want
___
*[src/vue/src/store/modules/feedbackForm.js, line 99 at r30](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-MwCtyP464QmvP2BmUST:-MwCz-LV5PfXN0NBTsvL:b11o4jj) ([raw file](https://github.com/ejourn-al/ejournal/blob/35eb66c3e8ea27ee22fc07e95996fdc259676c36/src/vue/src/store/modules/feedbackForm.js#L99)):*
<details><summary><i>Previously, engelhamer (Engel Hamer) wrote…</i></summary><blockquote>

Very very confusing that this module is named `feedbackForm (whichhh was done to keep it generic) but now is only used for peer feedback. I get that you did things fast but it could still be cleaner with the names..

At least update the name of the module ten?
</blockquote></details>

Yup, also entry-grade needs to become `grade` of `assessment-feedback-form` or whatever
___
*[src/vue/src/views/Journal.vue, line 455 at r30](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-MwCuqc0Ec2b7AANEenO:-MwCzE8aCf-wW2Yn_4Pl:bj09k2) ([raw file](https://github.com/ejourn-al/ejournal/blob/35eb66c3e8ea27ee22fc07e95996fdc259676c36/src/vue/src/views/Journal.vue#L455)):*
<details><summary><i>Previously, engelhamer (Engel Hamer) wrote…</i></summary><blockquote>

Should be fixed before release. We cannot just omit the feature all together for all users?
</blockquote></details>

With automatically saving grades, it is still the same amount of clicks that is required


<!-- Sent from Reviewable.io -->

2022-02-18 19:25 UTC, engelhamer requested changes
> *[Reviewable](https://reviewable.io/reviews/ejourn-al/ejournal/1328)* status: 111 of 112 files reviewed, 16 unresolved discussions (waiting on @engelhamer, @Larspolo, and @mjvkeulen)

___
*[src/vue/src/components/peer_feedback/PeerFeedbackNode.vue, line 62 at r36](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-MwDHqTxEEkOFBW_nRVE:-MwDHqTxEEkOFBW_nRVF:boop4u7) ([raw file](https://github.com/ejourn-al/ejournal/blob/300d7c8413e32392c06e669bce9c7390af43c64b/src/vue/src/components/peer_feedback/PeerFeedbackNode.vue#L62)):*
> ```Vue
>         </b-tabs>
>         <b-card-footer
>             v-if="assessmentFeedbackForm"
> ```

@larspolo this makes it so that you cannot add a participation score for the pfb activity if it does not already exist (you can only update it). Why is this required?


<!-- Sent from Reviewable.io -->

2022-02-18 19:36 UTC, engelhamer requested changes
> Reviewed 1 of 1 files at r36, 2 of 2 files at r37, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ejourn-al/ejournal/1328)* status: all files reviewed, 13 unresolved discussions (waiting on @Larspolo and @mjvkeulen)

___
*[src/django/test/test_grade.py, line 177 at r30](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-MwCWNOu1QzNwieYuCX2:-MwDJLV16ca6D0SmsTYA:b-s9tqb0) ([raw file](https://github.com/ejourn-al/ejournal/blob/35eb66c3e8ea27ee22fc07e95996fdc259676c36/src/django/test/test_grade.py#L177)):*
<details><summary><i>Previously, Larspolo (Lars) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Do not see a commit changing this file?
___
*[src/django/VLE/migrations/0113_replace_grade_with_feedback_form_migrate.py, line 6 at r30](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-MwCeBLuByQQ0yc2cFNm:-MwDJZ4qDyjs4Wzdxnp0:bwtfvqr) ([raw file](https://github.com/ejourn-al/ejournal/blob/35eb66c3e8ea27ee22fc07e95996fdc259676c36/src/django/VLE/migrations/0113_replace_grade_with_feedback_form_migrate.py#L6)):*
<details><summary><i>Previously, Larspolo (Lars) wrote…</i></summary><blockquote>

Is removed, no longer needed (already since the introduction of the LMS_grade
</blockquote></details>

Ok nice :)
___
*[src/django/VLE/models/rubric_submission.py, line 61 at r21](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-MwAicyNDPqQbhNcQwSi:-MwDJk6555THRCtZC3HO:b-q4f7h0) ([raw file](https://github.com/ejourn-al/ejournal/blob/5966dc533c530e8340ccb6b2a8431046cf7243d4/src/django/VLE/models/rubric_submission.py#L61)):*
<details><summary><i>Previously, Larspolo (Lars) wrote…</i></summary><blockquote>

To get the latest is_active feedback form that is attached to the rubric. It should be the same though, but in case it is ever not
</blockquote></details>

So the 'sort order' for `is_active` is TRUE < FALSE?
___
*[src/vue/src/components/journal/JournalDetails.vue, line 84 at r30](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-MwCrUHDE4v_Q5c2vE9g:-MwDK3ra3yvW6RQ1GfDO:bkl6dc4) ([raw file](https://github.com/ejourn-al/ejournal/blob/35eb66c3e8ea27ee22fc07e95996fdc259676c36/src/vue/src/components/journal/JournalDetails.vue#L84)):*
<details><summary><i>Previously, Larspolo (Lars) wrote…</i></summary><blockquote>

Was already the case, see teams
</blockquote></details>

Renamed to old name.
___
*[src/vue/src/store/modules/assessmentFeedbackForm.js, line 136 at r30](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-MwCtZv77PoQN0tMw6Gl:-MwDI0Up9qikwmWUIeOd:b-ibju1q) ([raw file](https://github.com/ejourn-al/ejournal/blob/35eb66c3e8ea27ee22fc07e95996fdc259676c36/src/vue/src/store/modules/assessmentFeedbackForm.js#L136)):*
<details><summary><i>Previously, Larspolo (Lars) wrote…</i></summary><blockquote>

Would be nice, you may add it if you want
</blockquote></details>

It is a waste of time to have this back and forth conversation. I feel that this response is given a bit too often in this PR :sweat_smile: 

This is your PR: If I wanted to do it myself I would not have commented it.
Either make the change or make an issue.
___
*[src/vue/src/store/modules/feedbackForm.js, line 99 at r30](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-MwCtyP464QmvP2BmUST:-MwDIXb9C6b7oGylD7fr:b-rogdzr) ([raw file](https://github.com/ejourn-al/ejournal/blob/35eb66c3e8ea27ee22fc07e95996fdc259676c36/src/vue/src/store/modules/feedbackForm.js#L99)):*
<details><summary><i>Previously, Larspolo (Lars) wrote…</i></summary><blockquote>

Yup, also entry-grade needs to become `grade` of `assessment-feedback-form` or whatever
</blockquote></details>

Are you going to change this? I feel that you have most feeling for what has to be changed where since you authored the code.
___
*[src/vue/src/views/Journal.vue, line 455 at r30](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-MwCuqc0Ec2b7AANEenO:-MwDIgvD80y7YerDFbFs:b-h4uomh) ([raw file](https://github.com/ejourn-al/ejournal/blob/35eb66c3e8ea27ee22fc07e95996fdc259676c36/src/vue/src/views/Journal.vue#L455)):*
<details><summary><i>Previously, Larspolo (Lars) wrote…</i></summary><blockquote>

With automatically saving grades, it is still the same amount of clicks that is required
</blockquote></details>

Not true: scroll + manual find + click != click.

How about we do proceed if the grade is published? (which is an actual button click).


<!-- Sent from Reviewable.io -->

2022-02-18 23:12 UTC, Larspolo reviewed
> *[Reviewable](https://reviewable.io/reviews/ejourn-al/ejournal/1328)* status: 101 of 115 files reviewed, 13 unresolved discussions (waiting on @engelhamer, @Larspolo, and @mjvkeulen)

___
*[src/django/test/test_grade.py, line 142 at r30](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-MwCVqopA522pU-u0zZd:-MwDwrZP76HyEqFpMb70:b-896fix) ([raw file](https://github.com/ejourn-al/ejournal/blob/35eb66c3e8ea27ee22fc07e95996fdc259676c36/src/django/test/test_grade.py#L142)):*
<details><summary><i>Previously, engelhamer (Engel Hamer) wrote…</i></summary><blockquote>

How about drafts? This should probably be tested as well (they should not be returned to students).
</blockquote></details>

Done.
___
*[src/django/test/test_grade.py, line 177 at r30](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-MwCWNOu1QzNwieYuCX2:-MwDwuAI0SbA3ducisZJ:b52nm6f) ([raw file](https://github.com/ejourn-al/ejournal/blob/35eb66c3e8ea27ee22fc07e95996fdc259676c36/src/django/test/test_grade.py#L177)):*
<details><summary><i>Previously, engelhamer (Engel Hamer) wrote…</i></summary><blockquote>

Do not see a commit changing this file?
</blockquote></details>

Forgot to push
___
*[src/django/VLE/models/rubric_submission.py, line 61 at r21](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-MwAicyNDPqQbhNcQwSi:-MwDwyqHBJ_jop5Qlxjm:b-sbzmud) ([raw file](https://github.com/ejourn-al/ejournal/blob/5966dc533c530e8340ccb6b2a8431046cf7243d4/src/django/VLE/models/rubric_submission.py#L61)):*
<details><summary><i>Previously, engelhamer (Engel Hamer) wrote…</i></summary><blockquote>

So the 'sort order' for `is_active` is TRUE < FALSE?
</blockquote></details>

It takes the last, so I think TRUE > FALSE? It has the following order:
- first, sort by is_active, the active feedback forms last
- sort each is_active type based on their creation date, the latest created last
So the last one is the latest active feedback form
___
*[src/django/VLE/utils/import_utils.py, line 49 at r10](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-Mw7JQsDCkM-skC8ewID:-MwDxRjVERoD7BXoGTpQ:bh9w0ea) ([raw file](https://github.com/ejourn-al/ejournal/blob/ca7e061d7eccc0678f0ec610392d82e9ce111319/src/django/VLE/utils/import_utils.py#L49)):*
<details><summary><i>Previously, Larspolo (Lars) wrote…</i></summary><blockquote>

Might be yeah
</blockquote></details>

Did you fix this @mjvkeulen ?
___
*[src/vue/src/components/peer_feedback/PeerFeedbackNode.vue, line 62 at r36](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-MwDHqTxEEkOFBW_nRVE:-MwDxa8xAsnQPh5Kxy4q:b-21tvqf) ([raw file](https://github.com/ejourn-al/ejournal/blob/300d7c8413e32392c06e669bce9c7390af43c64b/src/vue/src/components/peer_feedback/PeerFeedbackNode.vue#L62)):*
<details><summary><i>Previously, engelhamer (Engel Hamer) wrote…</i></summary><blockquote>

@larspolo this makes it so that you cannot add a participation score for the pfb activity if it does not already exist (you can only update it). Why is this required?
</blockquote></details>

An empty assessment will be created upon visit. So I think you can always fill in a grade as a teacher. The problem was that students should only see this is there is a published grade. They saw this box, without any grade attached (or grade indication)
___
*[src/vue/src/store/modules/assessmentFeedbackForm.js, line 136 at r30](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-MwCtZv77PoQN0tMw6Gl:-MwDyI-19IobvWxVlnqW:baws8jt) ([raw file](https://github.com/ejourn-al/ejournal/blob/35eb66c3e8ea27ee22fc07e95996fdc259676c36/src/vue/src/store/modules/assessmentFeedbackForm.js#L136)):*
https://ejournal.atlassian.net/browse/EJ-1342

The issue already exists, although it is a bit hidden I got to say

> I feel that this response is given a bit too often in this PR

Fair enough, get that it is annoying. This PR is also me trying to do the most in the given time. With such a short deadline, I cannot fix everything fully
___
*[src/vue/src/views/Analytics.vue, line 442 at r10](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-Mw7_cF6A26ebNABeYTK:-MwE-qug7-kvukg7Tprg:bitl9rx) ([raw file](https://github.com/ejourn-al/ejournal/blob/ca7e061d7eccc0678f0ec610392d82e9ce111319/src/vue/src/views/Analytics.vue#L442)):*
> This is not true.

Not sure which part is not true about which statement. But you agree that this statement is useful, as of now the new content will be loaded in the backend anyway?
___
*[src/vue/src/views/Journal.vue, line 455 at r30](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-MwCuqc0Ec2b7AANEenO:-MwE5jGu6FgaEZTe9bNU:byew1m8) ([raw file](https://github.com/ejourn-al/ejournal/blob/35eb66c3e8ea27ee22fc07e95996fdc259676c36/src/vue/src/views/Journal.vue#L455)):*
<details><summary><i>Previously, engelhamer (Engel Hamer) wrote…</i></summary><blockquote>

Not true: scroll + manual find + click != click.

How about we do proceed if the grade is published? (which is an actual button click).
</blockquote></details>

Good idea, did that :) you may check it out and see what you think of it
___
*[src/vue/src/store/modules/feedbackForm.js, line 99 at r30](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-MwCtyP464QmvP2BmUST:-MwE-1KtDB9hBwIOmaSd:bbpkzmr) ([raw file](https://github.com/ejourn-al/ejournal/blob/35eb66c3e8ea27ee22fc07e95996fdc259676c36/src/vue/src/store/modules/feedbackForm.js#L99)):*
<details><summary><i>Previously, engelhamer (Engel Hamer) wrote…</i></summary><blockquote>

Are you going to change this? I feel that you have most feeling for what has to be changed where since you authored the code.
</blockquote></details>

Renames the files, but not all uses


<!-- Sent from Reviewable.io -->

2022-02-19 09:04 UTC, mjvkeulen requested changes
> *[Reviewable](https://reviewable.io/reviews/ejourn-al/ejournal/1328)* status: 95 of 123 files reviewed, 14 unresolved discussions (waiting on @engelhamer, @Larspolo, and @mjvkeulen)

___
*[src/django/VLE/models/template.py, line 55 at r40](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-MwGDOC394nLMwnWrCEs:-MwGDOC394nLMwnWrCEt:b-gou09p) ([raw file](https://github.com/ejourn-al/ejournal/blob/a9d5c5566e92a541b86726aaf38ec9de5e3de971/src/django/VLE/models/template.py#L55)):*
> ```Python
>         null=True,
>     )
>     rubric = models.ForeignKey(
> ```

Does not match with assessment model default_rubric or template default_grade settings


<!-- Sent from Reviewable.io -->

2022-02-19 12:10 UTC, Larspolo reviewed
> *[Reviewable](https://reviewable.io/reviews/ejourn-al/ejournal/1328)* status: 89 of 129 files reviewed, 14 unresolved discussions (waiting on @engelhamer, @Larspolo, and @mjvkeulen)

___
*[src/django/VLE/models/template.py, line 55 at r40](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-MwGDOC394nLMwnWrCEs:-MwGsxuA-8LChPAFapxu:b-896fix) ([raw file](https://github.com/ejourn-al/ejournal/blob/a9d5c5566e92a541b86726aaf38ec9de5e3de971/src/django/VLE/models/template.py#L55)):*
<details><summary><i>Previously, mjvkeulen (Maarten van Keulen) wrote…</i></summary><blockquote>

Does not match with assessment model default_rubric or template default_grade settings
</blockquote></details>

Done.
___
*[src/django/VLE/views/feedback_form.py, line 192 at r10](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-Mw7UF8AA54dViS4E98y:-MwE8AFFCeQmY2EbkGzW:bu0v5cq) ([raw file](https://github.com/ejourn-al/ejournal/blob/ca7e061d7eccc0678f0ec610392d82e9ce111319/src/django/VLE/views/feedback_form.py#L192)):*
<details><summary><i>Previously, engelhamer (Engel Hamer) wrote…</i></summary><blockquote>

Not strictly needed in my opinion
</blockquote></details>

Cannot find the other threat anymore, but I split both


<!-- Sent from Reviewable.io -->

2022-02-19 14:53 UTC, mjvkeulen reviewed
> Reviewed 8 of 14 files at r38, 10 of 12 files at r39, 10 of 11 files at r41, 5 of 7 files at r42, 7 of 7 files at r43, 2 of 2 files at r44, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ejourn-al/ejournal/1328)* status: all files reviewed, 10 unresolved discussions (waiting on @engelhamer, @Larspolo, and @mjvkeulen)

___
*[src/django/VLE/utils/import_utils.py, line 49 at r10](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-Mw7JQsDCkM-skC8ewID:-MwHSppI4tcIdvJ5abFJ:bndj07d) ([raw file](https://github.com/ejourn-al/ejournal/blob/ca7e061d7eccc0678f0ec610392d82e9ce111319/src/django/VLE/utils/import_utils.py#L49)):*
<details><summary><i>Previously, Larspolo (Lars) wrote…</i></summary><blockquote>

Did you fix this @mjvkeulen ?
</blockquote></details>

I fixed it when you give a new grade. For JIR we have this issue https://ejournal.atlassian.net/browse/EJ-1473 


<!-- Sent from Reviewable.io -->

2022-02-19 14:55 UTC, engelhamer requested changes
> *[Reviewable](https://reviewable.io/reviews/ejourn-al/ejournal/1328)* status: all files reviewed, 5 unresolved discussions (waiting on @Larspolo and @mjvkeulen)

___
*[src/django/VLE/models/rubric_submission.py, line 61 at r21](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-MwAicyNDPqQbhNcQwSi:-MwHR5-10lSsEwlBUL-e:b-ws4njo) ([raw file](https://github.com/ejourn-al/ejournal/blob/5966dc533c530e8340ccb6b2a8431046cf7243d4/src/django/VLE/models/rubric_submission.py#L61)):*
<details><summary><i>Previously, Larspolo (Lars) wrote…</i></summary><blockquote>

It takes the last, so I think TRUE > FALSE? It has the following order:
- first, sort by is_active, the active feedback forms last
- sort each is_active type based on their creation date, the latest created last
So the last one is the latest active feedback form
</blockquote></details>

I think the context of this line got lost (I do not see the order line anymore) but would it not make more sense to filter on `is_active`? The sort order is confusing there, since it is not obvious from reading it (as the above thread suggests)
___
*[src/vue/src/components/peer_feedback/PeerFeedbackNode.vue, line 62 at r36](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-MwDHqTxEEkOFBW_nRVE:-MwHSYYGBSxRfmyfV2JD:b77yexo) ([raw file](https://github.com/ejourn-al/ejournal/blob/300d7c8413e32392c06e669bce9c7390af43c64b/src/vue/src/components/peer_feedback/PeerFeedbackNode.vue#L62)):*
<details><summary><i>Previously, Larspolo (Lars) wrote…</i></summary><blockquote>

An empty assessment will be created upon visit. So I think you can always fill in a grade as a teacher. The problem was that students should only see this is there is a published grade. They saw this box, without any grade attached (or grade indication)
</blockquote></details>

But now going there as a teacher does not show it either. I think the automatically created assessment doed not work well for pfb activities?

Reproduce:

1. `make preset-db`
2. Go to http://localhost:8080/Home/Course/1697/Assignment/1/Journal/3 as teacher
3. Select 'Peer feedback'
4. It is not possible to give a performance score
___
*[src/vue/src/views/Analytics.vue, line 442 at r10](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-Mw7_cF6A26ebNABeYTK:-MwHS8Sy36yO0uipHD34:blygtwq) ([raw file](https://github.com/ejourn-al/ejournal/blob/ca7e061d7eccc0678f0ec610392d82e9ce111319/src/vue/src/views/Analytics.vue#L442)):*
<details><summary><i>Previously, Larspolo (Lars) wrote…</i></summary><blockquote>

> This is not true.

Not sure which part is not true about which statement. But you agree that this statement is useful, as of now the new content will be loaded in the backend anyway?
</blockquote></details>

My reply was to @mjvkeulen his comment: that this comes back to not forcing at the router level. The implementations are not equivalent.
I am perfectly fine with the current change! (my status was resolved)
___
*[src/vue/src/views/Journal.vue, line 455 at r30](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-MwCuqc0Ec2b7AANEenO:-MwHTLlK-AKxfTB9KDSH:b-87j110) ([raw file](https://github.com/ejourn-al/ejournal/blob/35eb66c3e8ea27ee22fc07e95996fdc259676c36/src/vue/src/views/Journal.vue#L455)):*
<details><summary><i>Previously, Larspolo (Lars) wrote…</i></summary><blockquote>

Good idea, did that :) you may check it out and see what you think of it
</blockquote></details>

Good.


<!-- Sent from Reviewable.io -->

2022-02-20 00:38 UTC, Larspolo reviewed
> *[Reviewable](https://reviewable.io/reviews/ejourn-al/ejournal/1328)* status: 124 of 130 files reviewed, 4 unresolved discussions (waiting on @engelhamer and @mjvkeulen)

___
*[src/django/VLE/models/rubric_submission.py, line 61 at r21](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-MwAicyNDPqQbhNcQwSi:-MwJTD1I4xw8UosKRd_9:b-ulxipo) ([raw file](https://github.com/ejourn-al/ejournal/blob/5966dc533c530e8340ccb6b2a8431046cf7243d4/src/django/VLE/models/rubric_submission.py#L61)):*
<details><summary><i>Previously, engelhamer (Engel Hamer) wrote…</i></summary><blockquote>

I think the context of this line got lost (I do not see the order line anymore) but would it not make more sense to filter on `is_active`? The sort order is confusing there, since it is not obvious from reading it (as the above thread suggests)
</blockquote></details>

You can have a rubric submission pointing to a non active feedback form though. I will add a comment above
___
*[src/django/VLE/models/journal_content/feedback_form.py, line 616 at r10](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-Mw73eGq0g9GsTLR3HfZ:-MwJYoE_Eh-TYXyFztfx:b-nsvlwl) ([raw file](https://github.com/ejourn-al/ejournal/blob/ca7e061d7eccc0678f0ec610392d82e9ce111319/src/django/VLE/models/journal_content/feedback_form.py#L616)):*
<details><summary><i>Previously, mjvkeulen (Maarten van Keulen) wrote…</i></summary><blockquote>

We have solved this already, see Criterion (location, rubric) unique constraint (when reordering a criterion one could save the new location before updating the old location or vice versa).

Boils down to a transaction and using deferrable
</blockquote></details>

Missed this comment, but I added it, and it was already in a single transition, so it didnt need much extra coding
___
*[src/vue/src/components/peer_feedback/PeerFeedbackNode.vue, line 62 at r36](https://reviewable.io/reviews/ejourn-al/ejournal/1328#-MwDHqTxEEkOFBW_nRVE:-MwJUEcHE0zSoGK6wLUW:b-886gsx) ([raw file](https://github.com/ejourn-al/ejournal/blob/300d7c8413e32392c06e669bce9c7390af43c64b/src/vue/src/components/peer_feedback/PeerFeedbackNode.vue#L62)):*
<details><summary><i>Previously, engelhamer (Engel Hamer) wrote…</i></summary><blockquote>

But now going there as a teacher does not show it either. I think the automatically created assessment doed not work well for pfb activities?

Reproduce:

1. `make preset-db`
2. Go to http://localhost:8080/Home/Course/1697/Assignment/1/Journal/3 as teacher
3. Select 'Peer feedback'
4. It is not possible to give a performance score
</blockquote></details>

Fixed


<!-- Sent from Reviewable.io -->

2022-02-20 11:01 UTC, engelhamer reviewed
> Reviewed 1 of 11 files at r41.
> *[Reviewable](https://reviewable.io/reviews/ejourn-al/ejournal/1328)* status: 124 of 130 files reviewed, 3 unresolved discussions (waiting on @engelhamer and @mjvkeulen)



<!-- Sent from Reviewable.io -->

2022-02-20 11:02 UTC, engelhamer requested changes
LTI tests are not yet complete enough

2022-02-20 11:57 UTC, engelhamer approved these changes

2022-02-20 13:17 UTC, mjvkeulen approved these changes

2022-02-20 13:39 UTC, merged