Fixed a couple small issues with the LTI grade passback system
eJourn-al/eJournal pull request #982
Opened 2020-08-06 10:25 UTC by Larspolo

## Description
Fixed couple LTI grading bugs:
Fixed bug where creating new course wouldnt work
Grade now also gets send back when giving an unpublished grade
Submission date is now correctly set

## Summary of changes
- Fixes Z#1117
- Fixes Z#1085
- Fixes Z#1084

2020-08-10 10:52 UTC, engelhamer commented on src/vue/src/views/LtiLaunch.vue
> +                            && assignment.active_lti_course !== null
If the `typeof` check indeed shows that it is an `assignment.active_lti_course` is an object, then it is never `null`?

2020-08-10 10:59 UTC, engelhamer commented on src/vue/src/views/LtiLaunch.vue
> +                            && assignment.active_lti_course !== null
This check is incorrect: it does not show assignments to link even though they exist (different course, or the same course with no active LTI link yet).

2020-08-10 11:49 UTC, engelhamer commented on src/vue/src/views/LtiLaunch.vue
> +                            && assignment.active_lti_course !== null
```
assignment => !assignment.active_lti_course
|| assignment.active_lti_course.cID !== this.page.cID
```

2020-08-10 12:05 UTC, Larspolo commented on src/vue/src/views/LtiLaunch.vue
> +                            && assignment.active_lti_course !== null
> If the typeof check indeed shows that it is an assignment.active_lti_course is an object, then it is never null?
![image](https://user-images.githubusercontent.com/11822478/89780498-d902fc80-db11-11ea-9bdb-6e48cbed318e.png)
If only JavaScript would make sense.

> This check is incorrect: it does not show assignments to link even though they exist (different course, or the same course with no active LTI link yet).

Will check this now

2020-08-19 18:23 UTC, engelhamer approved these changes

2020-08-20 10:57 UTC, engelhamer requested changes
Would like to see Z#1143 also fixed.

2020-08-24 08:22 UTC, mjvkeulen approved these changes

2020-08-24 08:22 UTC, merged