Import entries
eJourn-al/eJournal pull request #987
Opened 2020-08-25 16:35 UTC by mjvkeulen

## Description
What did you change and why?

## Summary of changes
- Added the ability to create journal import requests (**JIR**s). These can be created in the target journal view, by a student. Once created these requests become visible for the teachers of the relevant assignment with the new permission `can_manage_journal_import_requests`. The teacher can process the request in the target journal, if approved, the source journal and all entries will be copied to the target journal. Any relevant files or comments are also copied. There are 4 options when it comes to processing:
     - Approve including the existing grades, ungraded entries can be edited.
     - Approve excluding the existing grades, all entries can be edited.
     - Approve and lock the entries, all entries will be graded as `0`.
     - Simply decline the request.

    JIRs are kept as a history of earlier import requests and are only deleted when a pending JIR's source journal is deleted. JIR 
    statistics and ToDos show when relevant.
- Testing factories reworked to always present an accurate state of the underlying database model, no more additional or dangling testing instances. Each model can be initiated in isolation. Because each instantiated model will be linked in a sensible way according to our expected DB model, test will execute a lot swifter if instances upwards in the chain are reused. For example, creating entries in a loop without specifying the entry will generate a new journal, assignment, and course instance and users. Do not initiate formats in isolation, initiate a format via an assignment. Addition of tests for the factories themselves.
- Minor changes related to the database layer, the addition of some validation and stricter conditions as preparation for Z#1122
- Extention of the entry content validation rules, the addition of existing file checks.
- Added a script to drop any testing database generated by a Pytest thread in the case of an unsuccessful termination. Expects to be executed by the `postgres` user.
- Addition of helper function `equal_models` to compare dictionaries or model instances, including any nested lists or dictionaries. Makes use of DeepDiff library, can be passed top-level keys, e.g. `id` which will be directly ignored. Or can be passed regex to exclude nested paths from the comparison, e.g. something to catch `root['entry']['content']['<index>']['id']` value.
- Presetdb is reworked to only make use of our testing factories, longterm this should increase the accuracy of our tests. If anything is amiss in our local testing environment we now have to fix the factories to match the desired outcome. Fixes Z#1146
- Removed no longer needed VLE.factories, more can be removed as we move more existing tests to the new factories.
- Addition of a more scalable number badge display component.

![image](https://user-images.githubusercontent.com/39912610/91202164-b4a64300-e701-11ea-9e76-ae5be93efd79.png)

![image](https://user-images.githubusercontent.com/39912610/91202101-9b9d9200-e701-11ea-9435-5d82d9ddecd7.png)

2020-08-25 17:46 UTC, Larspolo requested changes
- Missing visual indication of pending import journal requests for student

- Would prefer using the journal component when getting the preview of the old journal (over the current iframe approach). Preferably with only the stuff that is necessary: timeline, content, grades (so no grading box, next/prev buttons etc)

- This dropdown can be non existing when there are no import requests
![image](https://user-images.githubusercontent.com/11822478/91207569-3b125300-e709-11ea-8643-e7134638ff47.png)

- Would prefer the button to be hidden if there are no open JIR's
![image](https://user-images.githubusercontent.com/11822478/91207800-a0feda80-e709-11ea-954a-ac093be9e502.png)

- Badge keeps indicating TODO on JIR's even after approving all JIR's
![image](https://user-images.githubusercontent.com/11822478/91208417-77927e80-e70a-11ea-885d-8cb55d39f1d0.png)

- You can rerequest importing a journal after reloading the page (only does stuff in frontend though)

- A visual indication on which entries are imported would be nice

2020-08-25 17:50 UTC, engelhamer commented
> - Would prefer using the journal component when getting the preview of the old journal (over the current iframe approach). Preferably with only the stuff that is necessary: timeline, content, grades (so no grading box, next/prev buttons etc)

Maybe just omit the preview alltogether?


> - A visual indication on which entries are imported would be nice

I can add one now.

Also: instead of just the title of the assignment / journal in the teacher dropdown, it would be better to include the course and start/end year as well in the same dropdown line

2020-08-25 18:03 UTC, Larspolo commented on src/django/VLE/models.py
> +    last_edited = models.DateTimeField(auto_now_add=True)
This should not happen. This means that entry will change its last_edited state when the grade is updated (or author or whatever) while we use this field ONLY for checking if a user changed its content

2020-08-25 18:03 UTC, Larspolo commented on src/django/VLE/models.py
> +    jir = models.ForeignKey(
This is unclear to me, what does this field do? Maybe a comment or a different name

2020-08-25 18:03 UTC, Larspolo commented on src/django/VLE/models.py
> -            self.last_edited = timezone.now()
Needs to be added back again

2020-08-25 18:03 UTC, Larspolo commented on src/django/VLE/models.py
> +    ALLOWED_DATETIME_FORMAT = '%Y-%m-%dT%H:%M:%S'
LTI uses a different standard, so will have to be updated then :upside_down_face:

2020-08-25 18:03 UTC, Larspolo commented on src/django/VLE/models.py
> +        if Content.objects.filter(field=self.field, entry=self.entry).count() > 1:
Can this also be done as a unique together? Would like to use that instead if so

2020-08-25 18:43 UTC, engelhamer requested changes
49/88 viewed.

2020-08-25 18:43 UTC, engelhamer commented on src/django/VLE/factory.py
> +# TODO: Remove the chain of not used factories (or only used in tests)
When should this be done?

2020-08-25 18:43 UTC, engelhamer commented on src/django/VLE/management/commands/preset_db.py
> +                'instance': factory.Course(
Mixed single and double quotes (occurs often throughout all files in this PR).

2020-08-25 18:43 UTC, engelhamer commented on src/django/VLE/models.py
> +    # QUESTION: WHy is this an integer field? If one is to debug a Notifaction, we have to look at the integer
Remove question or discuss elsewhere? This is not really the place.

2020-08-25 18:43 UTC, engelhamer commented on src/django/VLE/models.py
> +        # QUESTION: Can a journal belong to a non group assignment with an author limit > 1?
Is the author limit always 1 for non-group journals?

2020-08-25 18:43 UTC, engelhamer commented on src/django/VLE/models.py
> +# TODO JIR: Unique together (journal, preset)
To do left.

2020-08-25 18:43 UTC, engelhamer commented on src/django/VLE/models.py
> +                raise ValidationError('You cannot import a journal into itself.')
`You cannot import a journal from within the same assignment.` would make more sense maybe?

2020-08-25 18:47 UTC, engelhamer commented
I would like fewer journals with import requests in the preset db. This now seems oversampled (5 out of 7 whereas in reality even just 1 would be a rare occurence). Also the button for creating a request is too 'in your face' maybe? Only required once by a select few at most, but every time you visit a journal it's always there for everyone, permanently in sight.

2020-08-25 18:55 UTC, engelhamer commented
Added `IMPORTED` badge (like `LATE` badge) but noticed that even for imported entries `jir` is `null` (so it is not currently displayed)

![image](https://user-images.githubusercontent.com/39912581/91215756-39e72300-e715-11ea-8d08-5eaece987148.png)

2020-08-25 20:23 UTC, mjvkeulen commented
> Added `IMPORTED` badge (like `LATE` badge) but noticed that even for imported entries `jir` is `null` (so it is not currently displayed)
> 
> ![image](https://user-images.githubusercontent.com/39912581/91215756-39e72300-e715-11ea-8d08-5eaece987148.png)

Would we not also expect an indication in the timeline itself? 

The serialization of an entry with corresponding JIR is tested here: `assert target_node['entry']['jir']['source']['assignment']['name'] == source_assignment.name` in `test_jir_import_result_via_serialization`. Are you sure the node data structure might not simply vary front end?

2020-08-25 20:25 UTC, mjvkeulen commented on src/django/test/test_journal_import_request.py
> +        # A jir generates only a single ap for both its source and target
The JIR factory will generate both a source and target journal unless provided, this is a test for the factory after all?

2020-08-25 20:25 UTC, mjvkeulen commented on src/django/test/test_gradepassback.py
> +            ap__grade_url='https://uvadlo-tes.instructure.com/api/lti/v1/tools/267/grade_passback'
Agreed but not something introduced in this PR

2020-08-25 20:27 UTC, mjvkeulen commented on src/django/test/test_entry.py
> +        course_c = Course.objects.count()
You don't think the variable names are quite clear given the structure? I am all for descriptive variable names but this was quite repetitive.

2020-08-25 20:29 UTC, engelhamer commented
> > Added `IMPORTED` badge (like `LATE` badge) but noticed that even for imported entries `jir` is `null` (so it is not currently displayed)
> > 
> > ![image](https://user-images.githubusercontent.com/39912581/91215756-39e72300-e715-11ea-8d08-5eaece987148.png)
> 
> Would we not also expect an indication in the timeline itself? 
> 
> The serialization of an entry with corresponding JIR is tested here: `assert target_node['entry']['jir']['source']['assignment']['name'] == source_assignment.name` in `test_jir_import_result_via_serialization`. Are you sure the node data structure might not simply vary front end?

`jir` was `null` here although the entry was imported. I haven't yet traced why.

There is no need for an indication in the timeline itself in my opinion, maybe in some other PR where progress colours or the timeline in general are also addressed?

2020-08-25 20:29 UTC, mjvkeulen commented on src/django/VLE/migrations/0053_entry_last_edited_auto_now_add.py
> +    ]
I opted for separate as these changes have no connection to journal import requests

2020-08-25 20:32 UTC, mjvkeulen commented
> * Would prefer the button to be hidden if there are no open JIR's

It is currently conditional to `v-if="journal.import_requests"`, guess thats broken then?

2020-08-25 20:33 UTC, mjvkeulen commented
> * Would prefer using the journal component when getting the preview of the old journal (over the current iframe approach). Preferably with only the stuff that is necessary: timeline, content, grades (so no grading box, next/prev buttons etc)
> *
The components you are referring to are not modular

2020-08-25 20:35 UTC, mjvkeulen commented
> * This dropdown can be non existing when there are no import requests

I don't quite follow, the manage import request button should not show if there are no import requests, and the modal auto closes if there are no more import requests to manage?

2020-08-25 20:37 UTC, engelhamer commented
> > * Would prefer the button to be hidden if there are no open JIR's
> 
> It is currently conditional to `v-if="journal.import_requests"`, guess thats broken then?

Empty list is truthy. Check on length larger than 0.

2020-08-25 20:38 UTC, mjvkeulen commented on src/django/VLE/models.py
> +    jir = models.ForeignKey(
It links to the JIR which approved its import. Could be `journal_import_request` but its quite long and `jir` is used quite often as shorthand. I think you will get used to it before you know it?

2020-08-25 20:39 UTC, engelhamer commented
> > * Would prefer using the journal component when getting the preview of the old journal (over the current iframe approach). Preferably with only the stuff that is necessary: timeline, content, grades (so no grading box, next/prev buttons etc)
> > *
> The components you are referring to are not modular

Omit the preview. Teacher can open journal (probably force new tab) by clicking on the card.

2020-08-25 20:39 UTC, mjvkeulen commented on src/django/VLE/models.py
> +    last_edited = models.DateTimeField(auto_now_add=True)
Fair enough, will revert.

2020-08-25 20:41 UTC, mjvkeulen commented on src/django/VLE/management/commands/preset_db.py
> +                'instance': factory.Course(
The double quotes are leftovers from the previous preset_db, I should not be mixing quotes. Please point them out in the PR.

2020-08-25 20:42 UTC, mjvkeulen commented on src/django/VLE/models.py
> +    # QUESTION: WHy is this an integer field? If one is to debug a Notifaction, we have to look at the integer
Since this is not live yet, I propose we change this more in line with the other choice fields.

2020-08-25 20:43 UTC, mjvkeulen commented on src/django/VLE/models.py
> +        # QUESTION: Can a journal belong to a non group assignment with an author limit > 1?
I think so, would be another validation rule. @Larspolo

2020-08-25 20:54 UTC, Larspolo commented on src/django/VLE/models.py
> +    jir = models.ForeignKey(
Cool, that's fair. Keep it then.

2020-08-25 20:55 UTC, mjvkeulen commented
> > > * Would prefer the button to be hidden if there are no open JIR's
> > 
> > 
> > It is currently conditional to `v-if="journal.import_requests"`, guess thats broken then?
> 
> Empty array is truthy. Check on length larger than 0?

I believe the `import_requests` are simply an int, the real JIRs are fetched once the manager is opened to speed up the assignment overview page. Not quite sure why the check wouldn't work, will check properly tomorrow.

2020-08-25 21:00 UTC, mjvkeulen commented on src/vue/src/components/entry/Entry.vue
> +                        v-b-tooltip:hover="'This entry was imported from another journal'"
Would we not expect a bit more info? For example where the import came from?

2020-08-25 22:25 UTC, Larspolo reviewed
17/90 :upside_down_face:

2020-08-25 22:25 UTC, Larspolo commented on src/django/VLE/serializers.py
> +                        f'FILE content {content.pk} refers to unknown file in data: {content.data}', level='error')
Aperantly I started using this notation in the Notification PR as well. However, this is not Python 3.5. This will drop support for that version. Do we want that?

2020-08-25 22:25 UTC, Larspolo commented on src/django/VLE/serializers.py
> +                    'assignment': AssignmentSerializer(entry.jir.source.assignment, context=self.context).data,
`AssignmentSerializer` shouldnt be necessary here. This massively increased the data needed. At least use SmallAssignmentSerializer, or just what is needed

2020-08-25 22:25 UTC, Larspolo commented on src/django/VLE/serializers.py
> +                'processor': UserSerializer(entry.jir.processor, context=self.context).data
Also here, is all of this necessary? Doesnt even seem to be used anywhere

2020-08-25 22:25 UTC, Larspolo commented on src/django/VLE/serializers.py
> +            'assignment': AssignmentSerializer(jir.source.assignment, context=self.context).data,
This is an expensive one, here again Small is preferred. Dont think we need the full one.

2020-08-25 22:25 UTC, Larspolo commented on src/django/VLE/utils/file_handling.py
> +def get_temp_files_from_rich_text(rich_text):
This rename is still needed in `views/entry.py`

2020-08-25 22:25 UTC, Larspolo commented on src/django/VLE/utils/import_utils.py
> +    grade_author = grade_author if grade_author else jir.processor
For jir yes, but maybe not for other uses as well (which we might want later in life).

You did forget a check is jir is None or not. I would personally change this to:

```
if jir and not grade_author:
    grade_author = jir.processor
```

2020-08-25 22:25 UTC, Larspolo commented on src/django/VLE/utils/import_utils.py
> +def copy_entry(entry, node=None, grade=None, vle_coupling=None):
Whats the diff between `copy_*` and `import_*`?

2020-08-26 06:44 UTC, mjvkeulen commented on src/django/VLE/models.py
> +        ['import_request_targets', ['target']],
This is tested here:
```        
jir2.state = JournalImportRequest.DECLINED
jir2.save()
journal.refresh_from_db()
assert journal.import_requests == 0, 'Import requests should update on the state change of a JIR'
```

What went wrong there?

2020-08-26 06:47 UTC, mjvkeulen commented on src/django/VLE/serializers.py
> +                'import_requests': journal_set.aggregate(Sum('import_requests'))['import_requests__sum'] or 0,
This aggregates the computed property: `import_requests`, which already filters based on `PENDING` state.

2020-08-26 06:49 UTC, mjvkeulen commented on src/django/VLE/serializers.py
> +        return JournalImportRequest.objects.filter(target__assignment=assignment).count()
Good catch will update to include the pending filter.

2020-08-26 06:50 UTC, mjvkeulen commented on src/django/VLE/models.py
> +        raise VLEProgrammingError('Content still exists which depends on a template being deleted')
It's quite clear to me, what do you propose?

2020-08-26 06:51 UTC, mjvkeulen commented on src/django/VLE/serializers.py
> +            'assignment': AssignmentSerializer(jir.source.assignment, context=self.context).data,
Agreed

2020-08-26 06:53 UTC, mjvkeulen commented on src/django/VLE/serializers.py
> +                'processor': UserSerializer(entry.jir.processor, context=self.context).data
I believe displaying frontend who approved the import request is desired. Could be stripped into yet another user serializer or custom dict, but I actually don't like those options as it spreads user serialization logic even more.

2020-08-26 06:58 UTC, mjvkeulen commented on src/django/VLE/utils/import_utils.py
> +def copy_entry(entry, node=None, grade=None, vle_coupling=None):
These functions have no side effects besides creating a copy of the passed instance. E.g. the `content_import` also duplicates all nested FCs.

2020-08-26 07:03 UTC, mjvkeulen commented
```
For jir yes, but maybe not for other uses as well (which we might want later in life).

You did forget a check is jir is None or not. I would personally change this to:

if jir and not grade_author:
    grade_author = jir.processor
```

There is quite a big check right above this line?

2020-08-26 07:04 UTC, mjvkeulen commented
> For jir yes, but maybe not for other uses as well (which we might want later in life).
> 
> You did forget a check is jir is None or not. I would personally change this to:

>if jir and not grade_author:
>    grade_author = jir.processor

There is quite a big check right above this line?

2020-08-26 07:19 UTC, mjvkeulen commented on src/django/VLE/models.py
> -            self.last_edited = timezone.now()
This was replaced by `auto_now_add=True` on the `last_edited` field. Which according to the [docs](https://docs.djangoproject.com/en/3.1/ref/models/fields/#django.db.models.DateField.auto_now_add): "_Automatically set the field to now when the object is first created_". How does this line differ?

2020-08-26 07:20 UTC, mjvkeulen commented on src/django/VLE/models.py
> +    ALLOWED_DATETIME_FORMAT = '%Y-%m-%dT%H:%M:%S'
Typical, at least we have a central place now.

2020-08-26 07:29 UTC, mjvkeulen commented on src/django/VLE/models.py
> +        # QUESTION: Could even move the permission checks here, e.g. need to be author of both source and target journal
Exactly, this would provide a (much needed) central place. 

- It would remove duplicate validation logic if the model is used in multiple view/http methods/utility functions etc.
- Enforce the same validation rules for our testing data.
- Some more advantages are outlined in Z#1139.

A problem with the save method is that the model could be saved for the first time, so some fields are not as easily accessed, hence the if statements. But this approach works without an `is_new` check, so the same logic both before and after the first save is called.

I am still looking for an optimal solution, and simply place this comment here to highlight that this approach is different from what we do usually, but it comes with the earlier outlined advantages.

2020-08-26 07:33 UTC, mjvkeulen commented on src/django/VLE/serializers.py
> +                        f'FILE content {content.pk} refers to unknown file in data: {content.data}', level='error')
I would love that, and even propose to move to 3.8 so we get access to the walrus operator (or higher).

2020-08-26 07:41 UTC, mjvkeulen commented on src/django/VLE/validators.py
> +    # QUESTION: Is '' really valid data for all fields?
So if the field is not required, and content is an empty string, we do not raise a validation error for *all* field types. 
So is an empty string truly ok for all field types?

2020-08-26 07:50 UTC, mjvkeulen commented on src/django/VLE/views/journal.py
> +        JournalImportRequest.objects.filter(target=journal, state=JournalImportRequest.PENDING).delete()
Interesting topic, I extended the logic to the journal reset.

If one of your teammates made an import request (does not have to be to a personal journal, could for example be a duo project), would you really expect that import request to disappear when that person leaves the journal?

I would argue that the only non-ambiguous case is the journal reset. What do we think?

2020-08-26 07:52 UTC, mjvkeulen commented on src/django/VLE/views/journal.py
> +        JournalImportRequest.objects.filter(target=journal, state=JournalImportRequest.PENDING).delete()
I also didn't think about the group journal `kick` functionality. Shall I move your proposal there?

2020-08-26 08:18 UTC, Larspolo commented on src/vue/src/store/modules/preferences.js
> +        dismissedJIRs: [],
This is not really a preference. Would keep this in the component itself

2020-08-26 08:18 UTC, Larspolo commented on src/vue/src/components/journal/JournalImportModal.vue
> +                    You can only import journal you own journals, and you cannot import the same journal into itself.
@engelhamer mentioned a better way to say this

2020-08-26 09:11 UTC, Larspolo commented on src/django/VLE/serializers.py
> +                'processor': UserSerializer(entry.jir.processor, context=self.context).data
May be desired, but its currently not used, suggest removal for now?

2020-08-26 09:12 UTC, mjvkeulen commented on src/django/VLE/views/entry.py
> +        # Unlimited entry
Could you make an issue regarding the naming scheme of deadline and unlimited entries?

2020-08-26 09:14 UTC, mjvkeulen commented on src/django/VLE/views/journal_import_request.py
> +    def create(self, request):
I don't know of any missing permission checks, and tests exist? You are confused because the checks you are looking for can be found in the save of the model?

2020-08-26 09:14 UTC, mjvkeulen commented on src/django/test/test_journal_import_request.py
> +    def test_create_jir(self):
I don't know of any missing permission checks, and tests exist? You are confused because the checks you are looking for can be found in the save of the model?

2020-08-26 09:17 UTC, mjvkeulen commented on src/vue/src/store/modules/preferences.js
> +        dismissedJIRs: [],
This is as much a preference as `comment_button_setting` and `grade_button_setting`, I don't quite follow?

2020-08-26 09:55 UTC, Larspolo commented on src/django/VLE/views/journal_import_request.py
> +    def create(self, request):
Figured you needed some `can_view` persmission checks. Now if you cant view an assignment it will respond with a 404 iso the (for me expected) 403.

Also 
```
        # You cannot create a JIR for an unpublished assignment
        target_assignment.is_published = False
        target_assignment.save()
        api.create(self, 'journal_import_request', params=data, user=student, status=400)
        target_assignment.is_published = True
        target_assignment.save()
```
Currently fails.

2020-08-26 09:57 UTC, Larspolo commented on src/django/test/test_journal_import_request.py
> +    def test_create_jir(self):
```
        # You cannot create a JIR for an unpublished assignment
        target_assignment.is_published = False
        target_assignment.save()
        api.create(self, 'journal_import_request', params=data, user=student, status=400)
        target_assignment.is_published = True
        target_assignment.save()
```
`can_view` permission would be nice

2020-08-26 10:34 UTC, mjvkeulen commented on src/django/test/test_journal_import_request.py
> +        # # TODO JIR: Triggers unique constraint of AP (assignment, user) but why..
TODO removed, and unique constraint fixed

2020-08-26 14:11 UTC, engelhamer commented on src/django/VLE/models.py
> +    # QUESTION: WHy is this an integer field? If one is to debug a Notifaction, we have to look at the integer
I propose we leave as is.

2020-08-26 14:22 UTC, engelhamer commented on src/django/VLE/models.py
> +        # QUESTION: Could even move the permission checks here, e.g. need to be author of both source and target journal
Lars advocates **not** implementing it here right?

2020-08-26 14:26 UTC, engelhamer commented on src/django/VLE/views/journal.py
> +        JournalImportRequest.objects.filter(target=journal, state=JournalImportRequest.PENDING).delete()
Well, in the current setup any outstanding request is always deleted once _some_ member leaves the journal right? This is not very logical, instead it would be better to remove one if a _specific_ member (the jir author) left or got kicked indeed.

2020-08-26 14:28 UTC, engelhamer commented on src/django/test/test_entry.py
> +        course_c = Course.objects.count()
Well in some instances I see `a_c` and the like. That's just not very clear (and better of a bit longer but easier to understand).

2020-08-26 14:29 UTC, engelhamer commented on src/vue/src/components/entry/Entry.vue
> +                        v-b-tooltip:hover="'This entry was imported from another journal'"
Not required in my opinion: the content is what's most important?

2020-08-26 14:29 UTC, engelhamer commented on src/vue/src/components/entry/Entry.vue
> +                        v-b-tooltip:hover="'This entry was imported from another journal'"
Could be added later on if needed.

2020-08-26 14:58 UTC, engelhamer requested changes

2020-08-26 14:58 UTC, engelhamer commented on src/django/VLE/validators.py
> +    # QUESTION: Is '' really valid data for all fields?
Are you talking about line 56 or 58?

2020-08-26 14:58 UTC, engelhamer commented on src/django/test/factory/entry.py
> +    '''
Again single quote docstrings.

2020-08-26 14:58 UTC, engelhamer commented on src/django/test/factory/user.py
> +        '''
Again single quote...

2020-08-26 14:58 UTC, engelhamer commented on src/django/test/test_journal.py
> +        # TODO: Enable once fixed?
Still disabled?

2020-08-26 14:58 UTC, engelhamer commented on src/django/test/test_node.py
> +        # TODO: Some meaningful tests on what is returned?
Issue or remove.

2020-08-26 14:58 UTC, engelhamer commented on src/django/test/test_notification.py
> +        # journal = entry.node.journal
Disabled.

2020-08-26 14:58 UTC, engelhamer commented on src/django/test/test_notification.py
> +        # TODO JIR
To do left.

2020-08-26 14:58 UTC, engelhamer commented on src/django/test/utils/generic_utils.py
> +    '''
Again double quote docstrings.

2020-08-26 14:58 UTC, engelhamer commented on src/vue/src/components/assets/DeadlineDeck.vue
> +                        + b.stats.import_requests_own_groups
Why is this included in marking needed sort here?

2020-08-26 14:58 UTC, engelhamer commented on src/vue/src/components/assets/TodoCard.vue
> +import numberBadgesDisplay from '@/components/assets/NumberBadgesDisplay.vue'
Why was the display suffix added?

2020-08-26 14:58 UTC, engelhamer commented on src/vue/src/components/assets/file_handling/BonusFileUploadInput.vue
> +                    this.$emit('bonusPointssuccessfullyUpdated', this.file.name)
Not camelcase anymore.

2020-08-26 14:58 UTC, engelhamer commented on src/vue/src/components/assignment/StatisticsCard.vue
> +            <b>Needs marking</b><number-badges-display
Move to new line.

2020-08-26 14:58 UTC, engelhamer commented on src/vue/src/components/journal/JournalImportModal.vue
> +                approved, the entries of the selected journal will be added to your journal. The reuse of existing
`transfer` of existing grades?

2020-08-26 14:58 UTC, engelhamer commented on src/vue/src/components/journal/JournalImportModal.vue
> +                    You can only import journal your own journals, and you cannot a journal into itself.
`cannot import a journal from within the same assignment` ?

2020-08-26 14:58 UTC, engelhamer commented on src/vue/src/components/journal/JournalImportRequestApprovalModal.vue
> +                    <div
Remove preview alltogether for now.

2020-08-26 14:58 UTC, engelhamer commented on src/vue/src/components/journal/JournalImportRequestApprovalModal.vue
> +                        @click.native="openSelectedJirInNewWindow()"
This is very nice and sufficient info for teacher in my opinion.

2020-08-26 14:58 UTC, engelhamer commented on src/vue/src/components/journal/JournalImportRequestApprovalModal.vue
> +                                icon: 'paper-plane',
`check` instead of `paper-plane` would fit better? Also for those below.

2020-08-26 14:58 UTC, engelhamer commented on src/vue/src/components/journal/JournalImportRequestApprovalModal.vue
> +                                icon: 'ban',
`cross`?

2020-08-26 14:58 UTC, engelhamer commented on src/vue/src/components/journal/JournalImportRequestApprovalModal.vue
> +                        No outstanding journal import requests available.
Either remove `outstanding` or `available`. They mean the same.

2020-08-26 14:58 UTC, engelhamer commented on src/vue/src/components/journal/JournalImportRequestApprovalModal.vue
> +        // How to simply provide jirs as options to the multiselect with a display for jir.source.assignment.name?
Display should also include course and year, e.g.:

`Colloquiumlogboek, Academische Vaardigheden Informatica 1 (2019-2020)`

Otherwise teacher does not know from which edition of a course (or which course at all) the journal is.

2020-08-26 14:58 UTC, engelhamer commented on src/vue/src/components/journal/JournalImportRequestApprovalModal.vue
> +            // TODO JIR: Update timeline without required reload
Reloading nodes is not a problem in my opinion as this rarely occurs. Easier to emit and re-init journal.

2020-08-26 14:58 UTC, engelhamer commented on src/vue/src/components/journal/JournalImportRequestApprovalModal.vue
> +.resp-iframe-container
Remove when removing iframe.

2020-08-26 14:58 UTC, engelhamer commented on src/vue/src/components/journal/JournalNonStudent.vue
> +                        class="bonus-section grade-section mt-1 full-width"
Prefer `mb-2` on all buttons.

2020-08-26 14:58 UTC, engelhamer commented on src/vue/src/components/journal/JournalNonStudent.vue
> +        journalImportRequestApprovalModal,
Capitalize.

2020-08-26 14:58 UTC, engelhamer commented on src/vue/src/components/journal/JournalStudent.vue
> +            <h3 class="theme-h3">
Wrap this whole thing in a `v-if`: there should never be an 'actions' heading when no actions are available.

2020-08-26 14:58 UTC, engelhamer commented on src/vue/src/components/timeline/TimelineNodeCircle.vue
> +        /* TODO JIR: Meaningfull way to display show that the entry was imported */
Not needed in my opinion (or create separate issue).

2020-08-26 14:58 UTC, engelhamer commented on src/vue/src/store/modules/preferences.js
> +        dismissedJIRs: [],
Dismissed requests? How are they preferences?

2020-08-26 14:58 UTC, engelhamer commented on src/vue/src/store/modules/preferences.js
> +        // TODO JIR move to DB preferences
Still needs to be done.

2020-08-26 14:58 UTC, engelhamer commented on src/vue/src/views/Assignment.vue
> +                    <option value="importRequests">
Only provide option _if_ there are any at all

2020-08-26 14:58 UTC, engelhamer commented on src/vue/src/views/Assignment.vue
> +                        @bonusPointssuccessfullyUpdated="hideModal('bonusPointsModal'); init()"
Also inconsistent camelcase here.

2020-08-26 14:58 UTC, engelhamer commented on src/vue/src/views/Assignment.vue
> +                importRequests,
Only include if larger than 0. Not needed to show the whole time.

2020-08-26 19:55 UTC, Larspolo commented on src/django/VLE/models.py
> -            self.last_edited = timezone.now()
Aha missremembered what auto_now_add was

2020-08-26 20:03 UTC, Larspolo commented on src/vue/src/store/modules/preferences.js
> +        dismissedJIRs: [],
comment_button_setting grade_button_setting are both on how you like the buttons to be set

2020-08-27 07:08 UTC, mjvkeulen commented on src/django/VLE/management/commands/preset_db.py
> +                            node__preset=deadline_node.preset, node__journal=j, gen_content__from_file=True)
Turned into an issue, just need consensus on the numbers.

2020-08-27 07:08 UTC, mjvkeulen commented on src/django/VLE/models.py
> +        # Otherwise this would form a reasonable validation rule
Added

2020-08-27 07:08 UTC, mjvkeulen commented on src/django/VLE/models.py
> +    last_edited = models.DateTimeField(auto_now_add=True)
See other comment

2020-08-27 07:18 UTC, mjvkeulen commented on src/django/VLE/models.py
> +        if Content.objects.filter(field=self.field, entry=self.entry).count() > 1:
Added

2020-08-27 07:20 UTC, mjvkeulen commented on src/django/VLE/factory.py
> +# TODO: Remove the chain of not used factories (or only used in tests)
Z#1164

2020-08-27 07:23 UTC, mjvkeulen commented on src/django/VLE/models.py
> +    # QUESTION: WHy is this an integer field? If one is to debug a Notifaction, we have to look at the integer
Since this was not live yet I updated it in place.

2020-08-27 07:24 UTC, mjvkeulen commented on src/django/VLE/models.py
> +        # QUESTION: Can a journal belong to a non group assignment with an author limit > 1?
Added test and validation rule

2020-08-27 07:25 UTC, mjvkeulen commented on src/django/test/test_entry.py
> +        # QUESTION: Now the data which is validated is no longer equal to the data of the actual content.
Likely to be addressed in Z#1122

2020-08-27 07:30 UTC, mjvkeulen commented on src/vue/src/components/entry/Entry.vue
> +                        v-b-tooltip:hover="'This entry was imported from another journal'"
I strongly feel we should present the information on where the journal was imported from

2020-08-27 07:31 UTC, mjvkeulen commented on src/django/VLE/utils/file_handling.py
> +def get_temp_files_from_rich_text(rich_text):
Good catch, double check if correct now

2020-08-27 07:33 UTC, mjvkeulen commented on src/django/VLE/views/journal_import_request.py
> +    def create(self, request):
Added test and check, anything else?

2020-08-27 07:36 UTC, mjvkeulen commented on src/django/test/factory/entry.py
> +    '''
We use single quotes when possible, quite the trap haha

2020-08-27 07:38 UTC, mjvkeulen commented on src/django/test/test_journal.py
> +        # TODO: Enable once fixed?
This is a newly added test revolving around code introduced by #359. Created dedicated issue Z#1150, "Floating entries on journal reset"

2020-08-27 07:41 UTC, mjvkeulen commented on src/django/test/test_node.py
> +        # TODO: Some meaningful tests on what is returned?
Z#1165

2020-08-27 07:46 UTC, mjvkeulen commented on src/vue/src/views/Assignment.vue
> +                        @bonusPointssuccessfullyUpdated="hideModal('bonusPointsModal'); init()"
Good subject, we need to move to kebab case for events anyway.

https://eslint.vuejs.org/rules/custom-event-name-casing.html

Currently, the rule is enforced for my editor by default but not for our env, need to check why there is a mismatch to begin with.

Z#1166

2020-08-27 07:48 UTC, mjvkeulen commented on src/vue/src/views/Assignment.vue
> +                importRequests,
Number badge is not shown if zero, filers should remain visible if zero. Or what do you mean?

2020-08-27 09:10 UTC, Larspolo approved these changes

2020-08-27 11:04 UTC, engelhamer requested changes
Still TODO and QUESTION left.

2020-08-27 11:04 UTC, engelhamer commented on src/vue/src/components/timeline/TimelineNodeCircle.vue
> +        /* TODO JIR: Meaningfull way to display show that the entry was imported */
Remove.

2020-08-27 11:04 UTC, engelhamer commented on src/vue/src/store/modules/preferences.js
> +        // TODO JIR move to DB preferences
Remove.

2020-08-27 11:04 UTC, engelhamer commented on src/django/VLE/models.py
> +            # TODO JIR Create notifications depending on state
Remove.

2020-08-27 11:04 UTC, engelhamer commented on src/django/test/factory/__init__.py
> +        # TODO Handle size more cleanly
Remove.

2020-08-27 11:04 UTC, engelhamer commented on src/django/test/factory/content.py
> +                    # TODO deep syntax could be made available by using a dedicated class with its own related
Remove.

2020-08-27 11:04 UTC, engelhamer commented on src/django/VLE/validators.py
> +    # QUESTION: Is '' really valid data for all fields?
Remove question

2020-08-27 11:09 UTC, engelhamer commented on src/vue/src/components/journal/JournalImportRequestApprovalModal.vue
> +                    <div
Still not removed

2020-08-27 12:09 UTC, mjvkeulen commented
JIR approval modal now does not select the correct assignment by default

2020-08-27 17:19 UTC, mjvkeulen commented on src/django/VLE/utils/import_utils.py
> +    if action == JournalImportRequest.APPROVED_INC_GRADES:
Updated and tested

2020-08-27 17:21 UTC, mjvkeulen commented on src/django/VLE/utils/import_utils.py
> +    grade_author = grade_author if grade_author else jir.processor
If the grade author is specifically specified I would prefer to use that instead.

2020-08-27 17:26 UTC, mjvkeulen commented on src/django/VLE/views/journal_import_request.py
> +        for source_entry in source_entries:
Just a way to skip the copy loop

2020-08-27 17:27 UTC, mjvkeulen commented on src/django/VLE/serializers.py
> +                'processor': UserSerializer(entry.jir.processor, context=self.context).data
Resolving as it's now used to display in the imported badge

2020-08-27 17:34 UTC, mjvkeulen commented on src/django/test/test_import_utils.py
> +            ignore_keys=['last_edited', 'update_date', 'id', 'creation_date', 'journal', 'entry']
Removed and test held

2020-08-27 17:48 UTC, mjvkeulen commented on src/django/test/test_import_utils.py
> +            source_entry, copied_entry_instance, ignore_keys=['last_edited', 'update_date', 'id', 'creation_date'])
Fixed for both comment and entry

2020-08-27 17:49 UTC, mjvkeulen commented on src/django/test/test_content.py
> +            VLE.validators.validate_entry_content(c.data, c.field)
Was added in this PR, see `test_validate_entry_content`

2020-08-27 17:52 UTC, mjvkeulen commented on src/django/VLE/serializers.py
> +        for content in entry.content_set.all().order_by('field__location'):
If the order is handled front end leave it there, removed.

2020-08-27 17:54 UTC, mjvkeulen commented on src/django/test/factory/content.py
> +                raise VLEProgrammingError('Content should never be generated for a no submission field')
@engelhamer ?

2020-08-27 17:54 UTC, mjvkeulen commented on src/django/test/factory/content.py
> +                raise VLEProgrammingError('Content should never be generated for a no submission field')
Engel confirmed that there should never be content for a no submission field

2020-08-27 17:57 UTC, mjvkeulen commented on src/django/test/test_course.py
> +        c_c = Course.objects.count()
I find the variables quite clear given the structure, I believe if the variable-length would be increased the code would become more unclear due to single line statements spanning multiple lines. `c_c` course count, `a_c` assignment count. These are also used in very obvious asserts with text.

2020-08-27 18:06 UTC, mjvkeulen commented on src/vue/src/views/Assignment.vue
> +                    <option value="importRequests">
This conflicts with our policy of not hiding filters when the result would be zero.

2020-08-27 18:07 UTC, mjvkeulen commented on src/vue/src/store/modules/preferences.js
> +        dismissedJIRs: [],
And the dismissed requests determines whether the modal should auto open on journal show. If any jirs exists which were not processed yet, but the modal was closed by the user. Unless there are new jirs, the modal will not auto open again.

2020-08-28 08:30 UTC, mjvkeulen commented on src/vue/src/components/assets/TodoCard.vue
> +import numberBadgesDisplay from '@/components/assets/NumberBadgesDisplay.vue'
As it is a display component not single (theme styled) number badge

2020-08-28 08:31 UTC, mjvkeulen commented on src/vue/src/components/assets/file_handling/BonusFileUploadInput.vue
> +                    this.$emit('bonusPointssuccessfullyUpdated', this.file.name)
See other comment, camelcase events are dangerous

2020-08-28 08:33 UTC, mjvkeulen commented on src/vue/src/components/assignment/StatisticsCard.vue
> +            <b>Needs marking</b><number-badges-display
It still (like the old line) an inline display

2020-08-28 08:37 UTC, mjvkeulen commented on src/vue/src/components/journal/JournalImportRequestApprovalModal.vue
> +                        No outstanding journal import requests available.
I referred to outstanding as pending JIRs, for the user the result is the same so I will remove it

2020-08-28 08:38 UTC, mjvkeulen commented on src/vue/src/components/journal/JournalImportRequestApprovalModal.vue
> +        // How to simply provide jirs as options to the multiselect with a display for jir.source.assignment.name?
Fixed by Lars

2020-08-28 09:56 UTC, engelhamer approved these changes

2020-08-28 10:13 UTC, merged