Improved the captured context in the case of possible errors
eJourn-al/eJournal pull request #999
Opened 2020-09-01 19:01 UTC by mjvkeulen

- Sentry event users should now be linked to the same user for both front and backend.
- Sentry will now always capture additional user context when not dealing with an anonymous user.
- During the build process of Vue, a release is created on the sentry environment (appropriate to the build context, e.g. stage/production). Afterwards, the source maps are automatically and linked to the release allowing for better debugging of our frontend live environments.
- Fixes Z#1001

I had to touch additional python files in order to fix circular imports.

2020-09-04 08:18 UTC, Larspolo requested changes

2020-09-04 08:18 UTC, Larspolo commented on config/roles/release/tasks/git_tag.yml
> +  when: create_git_tag
@engelhamer so this wasnt necessary anymore?

2020-09-04 08:18 UTC, Larspolo commented on src/django/VLE/utils/error_handling.py
> +                    'id': request.user.pk,
own user serializer also provides the `id` right?

2020-09-04 08:18 UTC, Larspolo commented on src/django/VLE/utils/error_handling.py
> +                    'id': request.user.pk,
Would also like to see the course / assignment information if it is given in the url / request query params / request data:
`if 'course_id' in request.query_params` or `if 'assignment_id' in request.data` or sth with `request.url` and "courses" in it

2020-09-04 08:18 UTC, Larspolo commented on src/django/VLE/utils/statistics.py
> +            - own: Subset of all with which [user] shmares a group.
typo?

2020-09-04 08:18 UTC, Larspolo commented on src/vue/src/views/LtiLaunch.vue
> +                })
This will also have reported an error in the backend already

2020-09-04 08:18 UTC, Larspolo commented on src/django/VLE/views/lti.py
> +        capture_exception(e)
Here the request url / query params would be really valuable to also have

2020-09-04 08:18 UTC, Larspolo commented on src/django/VLE/views/lti.py
> +        capture_exception(err)
Here the request url / query params would be really valuable to also have

2020-09-04 08:32 UTC, mjvkeulen commented on .travis.yml
> +    - RELEASE_VERSION="1.0.0"
Travis is just a dummy version since we do not deploy from travis, only use it as our test runner.

2020-09-04 08:33 UTC, mjvkeulen commented on Makefile
> +		pip install -r requirements/$(requirements_file) --use-feature=2020-resolver && \
Yes, no issues running the app but of course I did not run the full checklist. This will force us to deal with any issues ahead of time.

2020-09-04 08:34 UTC, mjvkeulen commented on config/roles/release/tasks/git_tag.yml
> +  when: create_git_tag
This is off by default (release/defaults)

2020-09-04 08:35 UTC, mjvkeulen commented on src/vue/src/views/LtiLaunch.vue
> +                })
Yes but the rest of the context frontend might differ, I rather capture some overlap twice.

2020-09-04 08:36 UTC, mjvkeulen commented on src/django/VLE/views/lti.py
> +        capture_exception(e)
Makes sense, we should be able to capture this globally in error handling.

2020-09-04 08:43 UTC, mjvkeulen commented on config/env_vars/base.yml
> +sentry_auth_token: !vault |
Sentry auth tokens are scoped on a per-user and organization basis. We only run a single organization.

Users are scoped based on their team and project affiliation, feel free to create a team/member/token combo to scope these tokens per environment (which we organized as projects on the Sentry side).

2020-09-04 08:46 UTC, mjvkeulen commented on src/django/VLE/utils/error_handling.py
> +                    'id': request.user.pk,
Feel free to add w/e you like, we can also just dictionary dump the request always.

2020-09-04 08:52 UTC, mjvkeulen commented on src/django/VLE/views/lti.py
> +        capture_exception(e)
On further inspection the request and request body are captured by default

2020-09-04 09:07 UTC, mjvkeulen commented on src/django/VLE/views/lti.py
> +        capture_exception(err)
So see other response

2020-09-04 09:08 UTC, mjvkeulen commented on Makefile
> +	@if ! [ $(shell which 'sentry-cli' > /dev/null 2>&1; echo $$?) -eq 0 ]; then \
Only runs if not exist yet, I don't quite follow why this is not the correct position for the check?

2020-09-04 09:45 UTC, Larspolo commented on config/env_vars/base.yml
> +sentry_auth_token: !vault |
local doesnt need these vars right?

2020-09-04 09:46 UTC, Larspolo commented on Makefile
> +	@if ! [ $(shell which 'sentry-cli' > /dev/null 2>&1; echo $$?) -eq 0 ]; then \
I ment *comment

2020-09-04 11:04 UTC, mjvkeulen commented on config/env_vars/base.yml
> +sentry_auth_token: !vault |
Fair enough will move the token to the relevant envs

2020-09-05 11:44 UTC, Larspolo commented on src/django/VLE/utils/error_handling.py
> +                    'id': request.user.pk,
Will do in another PR

2020-09-05 11:44 UTC, Larspolo approved these changes

2020-09-05 13:10 UTC, Larspolo commented on config/roles/release/tasks/prompts.yml
> +    new_release: "{{ prompt.user_input | bool }}"
This prompt can also be changed to a variable set by either running `make run-ansible-new-release` (which runs the deploy, only thing changed is this release variable) or sth

2020-09-06 15:17 UTC, engelhamer commented on config/roles/release/tasks/git_tag.yml
> +  when: create_git_tag
Since we only want actual releases from master I don't see why this would be needed indeed.

2020-09-06 15:27 UTC, engelhamer requested changes
Creating a release via the CLI is not really to my liking. I would only want releases from the master branch, made and verified through github.

2020-09-06 15:27 UTC, engelhamer commented on src/django/VLE/factory.py
> -from VLE.models import (Assignment, Comment, Content, Course, Entry, Field, Format, Grade, Group, Node, Participation,
Why this change? Circular imports?

2020-09-06 15:27 UTC, engelhamer commented on src/django/VLE/models.py
>  import VLE.utils.file_handling as file_handling
Why change for permissions but not for file handling?

2020-09-06 15:27 UTC, engelhamer commented on src/django/VLE/permissions.py
> -from VLE.utils.error_handling import VLEProgrammingError
This was more specific: why import the whole of error handling?

2020-09-06 15:27 UTC, engelhamer commented on src/vue/vue.config.js
> +                release: process.env.RELEASE_VERSION,
I would suggest retrieving the version from the `package.json` when building (like the version number frontend stuff).

2020-09-06 15:51 UTC, mjvkeulen commented on src/django/VLE/models.py
>  import VLE.utils.file_handling as file_handling
One was needed, other was not?

2020-09-06 15:52 UTC, mjvkeulen commented on src/vue/vue.config.js
> +                release: process.env.RELEASE_VERSION,
The env variable is needed for the client anyway, best to phase this out of the package.json as the source of truth. For example, the backend needs to know the version number anyway.

2020-09-06 15:53 UTC, mjvkeulen commented on src/django/VLE/factory.py
> -from VLE.models import (Assignment, Comment, Content, Course, Entry, Field, Format, Grade, Group, Node, Participation,
Yes as stated in the PR description

2020-09-06 15:57 UTC, engelhamer commented on src/vue/vue.config.js
> +                release: process.env.RELEASE_VERSION,
For which client?

2020-09-06 16:15 UTC, engelhamer requested changes

2020-09-06 16:15 UTC, engelhamer commented on config/roles/release/tasks/git_tag.yml
> +- name: Prompt for release git tag message "This update brings X, Y, Z. (but keep it short, otherwise the alert will get too large)"
There is not even an alert anymore.

2020-09-06 16:15 UTC, engelhamer commented on config/roles/release/tasks/git_tag.yml
> +- name: Create a new tag on the master branch
This does not necessarily create the tag on the master branch.

2020-09-06 16:15 UTC, mjvkeulen commented on src/vue/vue.config.js
> +                release: process.env.RELEASE_VERSION,
Front, back and sentry all need the release version to keep releases synced.

2020-09-06 16:16 UTC, mjvkeulen commented on config/roles/release/tasks/git_tag.yml
> +- name: Create a new tag on the master branch
True, the current branch, will update.

2020-09-06 16:19 UTC, mjvkeulen commented on config/roles/release/tasks/git_tag.yml
> +- name: Prompt for release git tag message "This update brings X, Y, Z. (but keep it short, otherwise the alert will get too large)"
As we talked about earlier, and was stated earlier, this is (by your request) off by default?

2020-09-06 16:46 UTC, engelhamer commented on config/roles/release/tasks/git_tag.yml
> +- name: Prompt for release git tag message "This update brings X, Y, Z. (but keep it short, otherwise the alert will get too large)"
Yes but then still the text is incorrect?

2020-09-06 16:46 UTC, engelhamer commented on config/roles/release/tasks/git_tag.yml
> +- name: Prompt for release git tag message "This update brings X, Y, Z. (but keep it short, otherwise the alert will get too large)"
Since this does not appear anywhere

2020-09-06 17:14 UTC, mjvkeulen commented on config/roles/release/tasks/git_tag.yml
> +- name: Prompt for release git tag message "This update brings X, Y, Z. (but keep it short, otherwise the alert will get too large)"
The text is correct, the running of the file is conditional?

2020-09-06 17:17 UTC, mjvkeulen commented on config/env_vars/base.yml
> +sentry_auth_token: !vault |
Local also needs this token to make change via the `sentry-cli`

2020-09-06 18:12 UTC, engelhamer commented on config/roles/release/tasks/git_tag.yml
> +- name: Prompt for release git tag message "This update brings X, Y, Z. (but keep it short, otherwise the alert will get too large)"
> (but keep it short, otherwise the alert wille be too large)

This is just not correct since there never is an alert so it could never be too large, despite not always running this.

2020-09-06 18:31 UTC, engelhamer approved these changes
Ok if Travis is fixed.

2020-09-06 19:15 UTC, mjvkeulen commented on config/roles/release/tasks/git_tag.yml
> +- name: Prompt for release git tag message "This update brings X, Y, Z. (but keep it short, otherwise the alert will get too large)"
Ah right will update

2020-09-06 20:09 UTC, merged